### ISSUE TITLE
Mail can't have more than 1024 characters

### ISSUE THREAD

**Issue by HakShak** [ccpgames/esi-issues#1]
https://esi.tech.ccp.is/latest/#!/Mail/post_characters_character_id_mail

This will be fixed with a new major version.

**Comment by gitAskur** [comment]
Still an issue in the code that needs pushing out before we can hook the live endpoint to v2. Hopefully we can push it out with Tuesdays deployment.

**Comment by gitAskur** [comment]
The v2 CSPA charge = 0 issue has been fixed Tim so we can hook the public endpoint to it and send all the spam we want forever!

**Comment by tsuthers-ccpgames** [comment]
frontend fix has been deployed. closing ticket.
