### ISSUE TITLE
Corporation Roles In Swagger UI Seems Wrong

### ISSUE THREAD

**Issue by rottjr** [ccpgames/esi-issues#101]
Just wanted to bring a small issue (I think) to attention. Currently the Swagger client at https://esi.tech.ccp.is/dev/ and https://esi.tech.ccp.is/latest/ show "GET /corporations/{corporation_id}/roles/ | Get Corporation Members" when I assume the part after the vertical pipe is supposed to read "Get Corporation Roles". 

On that same entry the SSO scope says "esi-corporations.read_corporation_membership.v1" where I expect it is supposed to read "esi-corporations.read_corporation_roles.v1". Hope this helps!

![corp_roles_error](https://cloud.githubusercontent.com/assets/20824145/20423919/f524a4de-ad27-11e6-8949-0b1f2453227b.png)

**Comment by tsuthers-ccpgames** [comment]
My copypasting ways have finally caught up with me! Fixed, thanks!
