### ISSUE TITLE
Chat channel data and text (and motd?) endpoints.

### ISSUE THREAD

**Issue by Ligraph** [ccpgames/esi-issues#103]
It would be nice to get an endpoint to read chat channel data, and text.  I assume you would only be able to read channels that the character who's auth you are using has access to.  This way I don't have to read chatlogs.

An endpoint to set the MOTD (and maybe other settings) would also be great (if you have the roles for the channel ofc).

**Comment by rottjr** [comment]
This seems like it would be relatively simple, in XML or CREST (can't remember which at this moment) you were able to collect the channels that users were in, seems it would be simple to just associate the channel ID from that request with a request to a 'channel' API to get all the information you requested above, and maybe more? Would be nice to get a channels user list (obviously only those visible).

Great idea, hope it gets accepted!

**Comment by polarina** [comment]
@rottjr for clarification, the XML API shows only channels you own or are an operator of.

**Comment by rottjr** [comment]
@polarina thanks for the clarification. Would it not be possible to include all active chat channels? Then attach a character ID to an owner field so the developer knows if they would have access to a chat owner endpoint IE: /chat/{channel ID}/owner/ using the bearer auth as security? I could be off point, but this seems like a logical path. Then if they aren't the owner pull public data like the MOTD and currently visible users through the /chat/{Channel ID}/. This could pose an opportunity (if implemented) to collect active channels through this endpoint IE: /chat/channels/{character ID}/ and maybe even join channels from out of game apps via a post or put IE: /chat/channels/{character ID} with the channel ID as the post content or put content.

Just ideas.

**Comment by ddouglas493** [comment]
Could this be used to pull in Local and therefore get a list of current
users in Local? What would the cache timer on an endpoint like this be?

**Comment by NathenSample** [comment]
@ddouglas493 Local would either have such a cache time that it would be useful for everything or be abused as a new pseudo logserver.

Neither are good.

**Comment by Arthien** [comment]
I think it would be best to mirror the XML api's method were you could only pull custom channels the user has access to. This includes a list of ops, members, and the MOTD.

**Comment by SpeedProg** [comment]
would be nice to be able to set MOTDs for channels you have operator.

**Comment by DaneelTrevize** [comment]
Hello, could we get clarity on what Staging means for this issue atm, I don't see anything for channels in https://esi.tech.ccp.is/latest/?datasource=singularity but know that Spectre Fleet would be hugely positively impacted by a writable channel MOTD endpoint. It could revolutionise our fleet scheduling & consistent communication with our community, and help remove the need to give newer junior FC Operator access.

**Comment by Robbilie** [comment]
With possible changes to the chat system coming I don't see them investing time into writing endpoints for a soon to be replaced system, unless they have it done already I don't see it being released before the new chat system :)

**Comment by aquarhead** [comment]
We've added https://esi.tech.ccp.is/latest/#!/Character/get_characters_character_id_chat_channels for parity with XML api. If you have problem using it or new feature request please open new issues.

**Comment by DaneelTrevize** [comment]
Can I just ask why this didn't appear in /dev or for the sisi datasource prior to being live for TQ? Is that out of the ordinary?

**Comment by a-tal** [comment]
that's normal. the versions of the endpoints are for spec changes. when a new endpoint is introduced, it will have versions `v1`, `latest`, `legacy` and `dev`. then if/when a breaking change to that endpoint is introduced, it will come in as `v2` and `dev`, with a migration to `latest` at some announced point in time.
