### ISSUE TITLE
Header dates in ISO 8601 / RFC 3339

### ISSUE THREAD

**Issue by Kyria** [ccpgames/esi-issues#104]
Currently, dates in the header are written in a local format (yours I believe) : `Sat, 19 Nov 2016 11:49:42 GMT` 

Could you switch this format to use the ISO DateTime format : `YYYY-MM-DDThh:mm:ssTZD`, just like you do in the different endpoints (like calendar events : `"event_date": "2016-12-01T21:34:37Z"`) so we can parse it, without having to wonder about the datetime format. 

This is especially true for the "Expire" header we want to be able to read in our apps. 

Thanks !

**Comment by polarina** [comment]
The HTTP headers containing dates are required to follow the format specified in RFC 7231. https://tools.ietf.org/html/rfc7231#section-7.1.1.1

The format can not be changed.

**Comment by Kyria** [comment]
My bad, I was searching for something like that, but I didn't find that one.. :(  Thanks for the link !  
I'm closing that issue.
