### ISSUE TITLE
Character Bookmarks scope issue

### ISSUE THREAD

**Issue by rottjr** [ccpgames/esi-issues#105]
While requesting an SSO code I had **all scopes below incorporated**:
esi-calendar.read_calendar_events.v1
%20esi-calendar.respond_calendar_events.v1
%20esi-clones.read_clones.v1
%20esi-characters.read_contacts.v1
%20esi-killmails.read_killmails.v1
%20esi-bookmarks.read_character_bookmarks.v1
%20esi-characters.read_contacts.v1
%20esi-skills.read_skillqueue.v1
%20esi-skills.read_skills.v1
%20esi-wallet.read_character_wallet.v1

at this point I was **receiving the error below**:
{"error":"invalid_scope","error_description":"The requested scopes either don't exist, or are not valid for this client"}

after removing the esi-bookmarks.read_character_bookmarks.v1 scope I was properly redirected to my websites SSO accept page.

**Troubleshooting Steps**

- Checked application on developers.eveonline.com for scopes, esi-bookmarks.read_character_bookmarks.v1 was selected.
- Tried SSO request with ONLY esi-bookmarks.read_character_bookmarks.v1 and receive the same error

o7 Hope it helps
--- Pizza Thief

**Comment by a-tal** [comment]
cannot reproduce. please ensure your application has requested the ability to use the `esi-bookmarks.read_character_bookmarks.v1` scope
