### ISSUE TITLE
Deduplicate responses where possible

### ISSUE THREAD

**Issue by burberius** [ccpgames/esi-issues#106]
It would be nice if the titles would be named better, as Swagger Codegen otherwise creates ugly class names like _GetCorporationsCorporationIdWalletsWalletIdTransactionsInternalServerError_ in Java.

For example:
get_characters_names_200_ok -> character_names_response
get_characters_character_id_corporationhistory_200_ok -> character_corporation_history_response

Also when the error schema titles would be named the same (they seam to have always the same structure), there would probably only one class generated, not one for every error response:
```
$ ls src/main/java/net/troja/eve/esi/model/*InternalServerError.java | wc -l
37
$ ls src/main/java/net/troja/eve/esi/model/*Forbidden.java | wc -l
21
```

**Comment by a-tal** [comment]
initially we had the same names for all error responses, what happens then is most clients add auto incrementing numbers to the end of the name. the current naming scheme guarantees unique names per response.

I'm not totally opposed to this though, but we have to keep in mind keeping everything unique (it's possible for an endpoint to define an error with a different schema than the auto-generated one). also see issue #107 re using models/refs.

current structure of response titles is:

```<http_method>_<route>_<status_msg>```

where `<status_msg>` is the output from `http.HTTPStatus(int(status_code)).name`

and the models inside the response:

```<http_method>_<route>_<status_code>_<status_msg>```

we could change the `<status_msg>` to a hardcoded string of `response` like suggested, but we have to include at least the http method, and could only use `response` for the 2xx level object. not sure if worth

**Comment by burberius** [comment]
My current solution is to replace the names with a sed script:
https://github.com/burberius/eve-esi/blob/master/replace.sed

But that leads to some of the responses to get numbered, like the NotFoundResponse*: https://github.com/burberius/eve-esi/tree/16-11-29-16bdd84a37/src/main/java/net/troja/eve/esi/model

Perhaps the swagger file can be manipulated to solve that and #107 before creating the code...

**Comment by a-tal** [comment]
oof, DatCamelCase, agree to disagree there ;)

could take a look at deduplicating the error responses with models tho, I doubt any of the 2xx responses will be able to (other than 204s)

**Comment by burberius** [comment]
I use CamelCase there, as I create Java classes from it, there the names don't change and I can distinguish easily what I already changed! ;-)

I started on manipulating the swagger file yesterday and it works really nice! Saves me many classes.
Script can be found here: https://github.com/burberius/eve-esi/blob/master/transformation.sh
But it's not finished yet.

**Comment by antihax** [comment]
+1 for deduping. Every additional endpoint proliferates more duplicate models with long names.
`delete_characters_character_id_fittings_fitting_id_internal_server_error`

**Comment by a-tal** [comment]
this is in staging atm, part of `ESI 0.5.1`.

any endpoint defined responses that are codes only will be deduped, along with 403 (if applicable) and 500

**Comment by a-tal** [comment]
`ESI 0.5.1` is now in production
