### ISSUE TITLE
inline schema usage

### ISSUE THREAD

**Issue by casualjim** [ccpgames/esi-issues#107]
When trying to generate clients from the specs here, I run into issues on go-swagger due to the heavy usage of inline schemas for array items.
This has exposed a structural design issue in go-swagger and it will take quite some time to fix that problem.
The easy solution that gets you to generate go code from swagger specs would be to use `$ref:"/definitions/arrayItem"` and use named definitions instead of inline schemas.
As an aside you'll probably get a cleaner and shorter spec out of it too.

**Comment by a-tal** [comment]
this is a design decision, each endpoint is self-contained inside their operation object. if we used refs and models we'd quickly end up in dependency hell.

**Comment by burberius** [comment]
@casualjim You can manipulate the swagger.json before generating the code. I currently do that for my Java project: https://github.com/burberius/eve-esi

You can see the script here:
https://github.com/burberius/eve-esi/blob/master/transformation.sh

I hope that helps you.
