### ISSUE TITLE
Sort tags alphabetically

### ISSUE THREAD

**Issue by polarina** [ccpgames/esi-issues#109]
The tags listing on the front page of https://esi.tech.ccp.is/ are not in alphabetical order. Can they be sorted, please?

**Comment by a-tal** [comment]
this is live now, thanks!

**Comment by CarbonAlabel** [comment]
I feel like keeping the `Live` tag at the top of the list and the `Dummy` tag at the bottom of the list would have been nice.

**Comment by polarina** [comment]
Those tags shouldn't really exist.

**Comment by a-tal** [comment]
^ don't rely on the `Live` tag, once there are no more `Dummy` tagged endpoints `Live` will be deleted
