### ISSUE TITLE
esi-mail: review pagination stratagy

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#11]
https://trello.com/c/25iHGAni/41-esi-mail-review-pagination-stratagy

**Comment by Regner** [comment]
May I ask what came of this review? Any changes happening?

**Comment by tsuthers-ccpgames** [comment]
It's not actually done yet, I'm fighting with the progress bot -_-

**Comment by aquarhead** [comment]
@tsuthers-ccpgames you basically only use the board (Project) for managing progress tags. And once an issue is closed, you need to move it first on the board then immediately re-open it, otherwise the bot will pick up closed issues on other columns and move them to "Done"

**Comment by tsuthers-ccpgames** [comment]
We're happy with the current pagination strategy for mail, so closing this.
