### ISSUE TITLE
/characters/{character_id}/skillqueue/ showing completed trained skills

### ISSUE THREAD

**Issue by ctg1** [ccpgames/esi-issues#113]
while testing /characters/{character_id}/skillqueue/, had noticed on an alpha character, esi still showed skills in the endpoint data, despite them being done several days ago, character hadn't logged in since they were completed, logged in, and the data refreshed, queue empty, i tested again on a different alpha clone character, initial esi data showed 2 skills in queue,as expected, data is shown below, its 18:30 now, XML api shows nothing in skillqueue, so they are done, but the data is still showing up in the esi queue endpoint.

tested with https://esi.tech.ccp.is/latest/#!/Skills/get_characters_character_id_skillqueue
and my personal clientID app, both showed data still in endpoint.

how ever, when i tested with the "eve portal" app on ios, it returned the correct skillqueue (nothing), then i log the character on, then regrabed the data, the endpoint finally returns nothing(as expected), since the skills have completed. 

i only mention alpha characters, since i dont have any small/quick skills to test with on a omega account

[
  {
    "level_start_sp": 0,
    "finished_level": 1,
    "start_date": "2016-11-27T17:21:42Z",
    "queue_position": 0,
    "finish_date": "2016-11-27T17:40:51Z",
    "level_end_sp": 500,
    "training_start_sp": 251,
    "skill_id": 3312
  },
  {
    "level_start_sp": 0,
    "finished_level": 1,
    "start_date": "2016-11-27T17:40:51Z",
    "queue_position": 1,
    "finish_date": "2016-11-27T17:55:46Z",
    "level_end_sp": 500,
    "training_start_sp": 306,
    "skill_id": 3310
  }
]

**Comment by polarina** [comment]
Internally, skills and skillqueues are not updated in the EVE database until the character has next logged in. You need to apply the needed computation yourself to determine which skills have finished and which have not.

The EVE Portal application does these computations itself.

**Comment by ctg1** [comment]
Thanks, figured eve portal was doing that, figured I would mention that anyway, just in case.
