### ISSUE TITLE
Market orders for a type

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#114]
Currently, the market orders endpoint requires a region ID to be provided, with an optional type ID parameter. A new endpoint which would only require a type ID and return orders for that type across all regions in the universe would be very useful, as retrieving all orders for a single type is something I could see myself doing quite often, but cannot be done at the moment without either making a large number of separate requests or using a third-party API which aggregates and caches the data.

**Comment by aquarhead** [comment]
Closing to the same reason as #74
