### ISSUE TITLE
GET /characters/{character_id}/corporationhistory/ vs GET /corporations/{corporation_id}/alliancehistory/ consistency

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#115]
```
  {
    "corporation_id": 90000001,
    "is_deleted": false,
    "record_id": 500,
    "start_date": "2016-06-26T20:00:00Z"
  }
```
vs
```
  {
    "alliance": {
      "alliance_id": 99000006,
      "is_deleted": false
    },
    "record_id": 23,
    "start_date": "2016-10-25T14:46:00Z"
  }
```

**Comment by Mumbleskates** [comment]
While this is inconsistent, it was designed this way for a reason. Alliance membership records may indicate the lack of an alliance, as when a corporation becomes independent, while a character must always be part of some corporation; the absence of a single key makes a little more sense for that use case.

I wouldn't rank this as very important, considering.

**Comment by Robbilie** [comment]
Considering that you have about the Same Attributes you Can surely Just group the id and deleted of Corporation unser a Corporation object to have more consistency.

**Comment by a-tal** [comment]
patch submitted to create v2 of `GET /corporations/{corporation_id}/alliancehistory/`

**Comment by a-tal** [comment]
https://esi.tech.ccp.is/dev/?datasource=tranquility#!/Corporation/get_corporations_corporation_id_alliancehistory
