### ISSUE TITLE
Dead alliances sometimes throwing errors

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#116]
```{"error": "uncaught exception: TypeError(\\"int() argument must be a string, a bytes-like object or a number, not \'NoneType\'\\",)"}```

appeared for:
https://esi.tech.ccp.is/latest/alliances/715562507/
https://esi.tech.ccp.is/latest/alliances/145667443/

**Comment by Mumbleskates** [comment]
https://forums.eveonline.com/default.aspx?g=posts&m=6182937

**Comment by a-tal** [comment]
fixed, executor_corp is now optional
