### ISSUE TITLE
Broken Character

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#117]
https://esi.tech.ccp.is/latest/characters/2100086311/
https://esi.tech.ccp.is/latest/characters/2100333839/
https://esi.tech.ccp.is/latest/characters/2108838724/
https://esi.tech.ccp.is/latest/characters/2100335449/

```
{"error": "Action failed"}
```

**Comment by Mumbleskates** [comment]
Character IDs starting from 2.1 billion were reserved for DUST characters. You can safely assume that any character with an id in `range(2100000000, 2200000000)` is a DUST toon and therefore largely irrelevant for current applications, though the fact that these IDs are still traversable means it would be nice to have access to that data.

**Comment by Robbilie** [comment]
CCP confirmed These to be dust chars, the Problem is that when going through All existing endpoints starting with the alliances list you will reach those, thats how i did, thats why the ancestry_id will be Made optional, a fix for this will be deployed soon.
