### ISSUE TITLE
esi-bookmarks: delete and rearrange bookmarks

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#12]
https://trello.com/c/78EyFXa2/42-esi-bookmarks-delete-and-rearrange-bookmarks

**Comment by ccpStuart** [comment]
reviewed

**Comment by ccpStuart** [comment]
Duplicate of https://github.com/ccpgames/esi-issues/issues/69

**Comment by gitAskur** [comment]
You crawl further and further down the dark recesses of the cavern, but soon reach a dead end. When you turn around to go back the way you came you realize that what now lies behind you is not the cavern you just passed through but something entirely different.

Go to #69 to continue on your journey!
