### ISSUE TITLE
GET /universe/structures/ - 'public' definition

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#120]
what is the definition of 'public'?

does this include all structures with docking ACL having the "public-flag" set

or

does this include all structures with docking ACL having the "public-flag" set AND no entity set to BLOCKED

former would mean that a public citadel is public for some characters/corporations/alliances but not all…

**Comment by tsuthers-ccpgames** [comment]
So it originally was the former, but following the dates in this blog, it will become the latter: https://developers.eveonline.com/blog/article/changes-to-public-citadel-endpoint
