### ISSUE TITLE
Member count in /alliances/{alliance_id}/

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#122]
No member count is returned for alliances, as currently found on the related XML API endpoint: https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/eve/eve_alliancelist.html

**Comment by aquarhead** [comment]
You can use [this](https://esi.tech.ccp.is/latest/#!/Alliance/get_alliances_alliance_id_corporations) to fetch all member corporations of an alliance, then do a simple count. There's no need to duplicate the information which might also possibly mismatch because of cache.
