### ISSUE TITLE
Corporations not reported as dead by /characters/{character_id}/corporationhistory/

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#123]
All corporations seem to be reported as alive, regardless of their actual status (`is_deleted` is always set to `false`)

Example IDs exhibiting this behaviour, plucked from Amarr local:

- `235695799` with corporation IDs `98346399`, `98178546`, `1020763245`
- `429350544` with corporation IDs `98451069`. `98445063`
- `91808044` with corporation IDs `98120759`, `98072060`

**Comment by Mumbleskates** [comment]
+1

**Comment by a-tal** [comment]
patch submitted

**Comment by a-tal** [comment]
this is resolved. you may have to wait out the cache timer if you're still getting all `false`
