### ISSUE TITLE
Include packaged volume on type information if available.

### ISSUE THREAD

**Issue by RemyArmstro** [ccpgames/esi-issues#125]
You were able to get volume from CREST (although it was not packaged volumes).  Please include volumes in ESI for types, and preferrably, also include packaged volumes.

**Comment by Regner** [comment]
This information is hard coded on I believe the inventory group level. :( Not that it cannot be added, just a bit of a pain.

**Comment by RemyArmstro** [comment]
Alternatively, can we expose the inventory group levels via a different ESI endpoint, and then just expose the inventory group identifier on the type if that makes it simpler?

**Comment by RemyArmstro** [comment]
I would suggest closing this issue and instead implementing #156 which contains the volume data (packaged and normal).  This will solve this issue, as well as solve the issue of a missing market group endpoing which was available in CREST.

**Comment by Claudweb** [comment]
The market group 

Ships / Industrial Ships / Industrial Command Ships / ORE / 

contains Porpoise(50000 packaged) and Orca (500000 packaged), so this can't be done via market groups.
