### ISSUE TITLE
HTML error pages

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#132]
If I request an invalid API route (for example, include decimal places in my character ID: https://esi.tech.ccp.is/latest/characters/93265215.00/ ), the resulting 404 error page will be an HTML document.

I would suggest that those error pages be replaced with JSON error pages, like the ones returned by the endpoints themselves when producing an error, as this may make debugging route related errors a bit easier.

**Comment by a-tal** [comment]
some of this is possible, can take a look into flask to ensure we're not generating any 400 level html errors there. sometimes this won't be possible though, there's not a way currently to change the errors generated on google's L7 LB for instance.

code interacting with ESI should attempt to parse errors as JSON, with a fallback to text/html.

**Comment by a-tal** [comment]
ESI uses JSON for 404 errors now.

**Comment by Robbilie** [comment]
sexyyyy
