### ISSUE TITLE
Returning ISK amounts as decimal numbers vs integers

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#134]
Old title: **Result of /characters/{character_id}/cspa/ returned in ISK hundredths**

The cost attribute of the response is said to be returned in ISK hundredths, which I consider to be highly unusual as there aren't any other CCP released APIs or resources (at least not any I've encountered) which express ISK amounts in such a way.

This also doesn't make much sense by itself, as it is not possible to set a character's CSPA charge to a non-integer value.

**Comment by polarina** [comment]
The [wallet endpoint](https://esi.tech.ccp.is/latest/#!/Wallet/get_characters_character_id_wallets) also returns ISK amounts in hundredths.

I argue that returning monetary amount in hundredths is the way to go: you avoid all the associated issues with floating point precision errors, comparisons, and equality checks.

**Comment by CarbonAlabel** [comment]
Thanks for pointing that out, I didn't notice that endpoint.

I completely agree that monetary amounts are best handled as integers and don't have anything against them being returned as such if the practice will be followed consistently.

However, this is already not the case. The prices in market endpoints and the insurance endpoint are returned as decimal numbers, just as they were in CREST. I would say that a decision should be made on which format to use, and all endpoints converted to it, while ESI is still young.
