### ISSUE TITLE
/characters/{character_id}/cspa/ times out for large amount of characters

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#137]
If I request the CSPA charge for a large amount of characters (111 characters in one case I was testing) the request fails after ~10 seconds:

```json
{
  "error": "No reply within 10 seconds. Error ID: 75a6391d-40be-4a23-a03e-1884aa01a132"
}
```

However, requesting the CSPA charge for exactly 110 characters returned a result almost instantly.

In other cases, the breaking point occurred at different amount of IDs, but always sometime soon after the length of the JSON array containing the IDs exceeded 1000 characters.

This behaviour fascinates me.

**Comment by aquarhead** [comment]
@tsuthers-ccpgames 
This is due to using message attributes for sending content with arbitary length.

Maybe we should also limit the length of the list ( `maxItems` )

**Comment by tsuthers-ccpgames** [comment]
If it's still using attributes it should just be ported to using body like all the modern endpoints.

**Comment by CarbonAlabel** [comment]
The characters array has a limit of 100 items now (could even be further reduced to 50 as that's the maximum number of recipients a mail can have), so this should probably be closed, unless you think the issues mentioned above are something that still needs addressing.

**Comment by polarina** [comment]
@CarbonAlabel can't quite put the limit at 50. The limit is 50 characters, not recipients. You can send a corp mail + 50 other character recipients, for example.

**Comment by CarbonAlabel** [comment]
@polarina true, but I don't believe CSPAs apply to entities other than characters.

**Comment by polarina** [comment]
@CarbonAlabel oh derp, thought this was about the send mail endpoint. My bad. :)

**Comment by CarbonAlabel** [comment]
It's cool :)

That said, the send mail endpoint does have a 50 item limit on its recipients array.
Increasing that to 51 wouldn't really work (what if someone tries to send a mail to 51 characters), and the alternative would be to adopt the (IMO) more complicated format used by the UI new mail endpoint.
Time for a new inconsistency issue, I guess.

**Comment by ccp-zoetrope** [comment]
As was said above this is being closed because the maxItems on the characters array is 100 for [/v4/characters/{character_id}/cspa/](https://esi.tech.ccp.is/ui/#/Character/post_characters_character_id_cspa).
