### ISSUE TITLE
[Future Request] Endpoint for character combat logs 

### ISSUE THREAD

**Issue by Shegox** [ccpgames/esi-issues#139]
It would be very handy to have a endpoint which returns the combat logs with a short cache timer (seconds to minutes) which returns the last hour (or more though paging?) of all combat logs (including, but not limited to Mining Amount, Bounty, scramble attempts, damage applied and all what pop up in UI). This can be used to do tracking of mining ops without manually parsing fleet logs (my use case) as well as real time tracking of damage application for FCs.

Handy would be a unique identifier for each entry as well as time stamp and the message as string or even better as some kind of attribute list (message_type, amount, type).

Suggested route:`/character/{character_id}/logs/combat`

Example Response (sorted descending after log_id):
```
{
  "application/json": [
    {
      "log_date": "2016-06-26T20:00:10Z", // date of the log and time
      "log_id": 1235, // unique all time id
      "message_type": "Mining", // Message type, realized as string or integer
      "amount": 150, // For Mining: Amount of mined Ore
      "type_id": 1230 // For Mining; What was mined?
    },
    {
      "log_date": "2016-06-26T20:00:05Z", // date of the log and time
      "log_id": 1234, // unique all time id
      "message_type": "Combat", // Message type, realized as string or integer
      "amount": 12000, // For Combat: Damage done
      "type_id": 3146, // For Combat: Type what done damage f.e. Heavy Neutron Blaster II
      "target_id": 92439100 // For Combat: Person who received damage (for NPCs NPC id?)
    }
  ]
}
```

**Comment by burberius** [comment]
Also nice would be, remote shield/armor and also ECM stuff.

I miss stats like in WoW for healers! ;-)

**Comment by JacksonWages** [comment]
+1 to this, especially if it can include mining logs! Would love to have a proper mining fleet app.

**Comment by Mumbleskates** [comment]
-1, this sounds incredibly hard and not very useful. If you need your own data, there are already logs sent locally; otherwise, the volume of this kind of granular information would thoroughly overwhelm every other data source in the API.

**Comment by Regner** [comment]
Writing an application that captures the already existing logs from the client and pipes them to a server should be super easy.

**Comment by Shegox** [comment]
The problem, especially with mining logs/amounts is, that these are not captured in the log files aswell the ingame log viewer. The same is with Bounty Payout Messages.

**Comment by Regner** [comment]
Mining might not be in the logs, but you can probably ask for that to be added separately to the client logs if they reject this.

**Comment by CarbonAlabel** [comment]
You still need to get people to install an application to do so, and you can't really verify the logs' validity.

Getting this implemented from CCP's side might not be such an easy task, either. Personally, I'd close this and put it in the "maybe someday" category.

**Comment by Shegox** [comment]
Sure, will just let it open and wait for a response. Maybe it is easy to implement, maybe not. Was just intended as a idea. Will look into piping the logs to our server and how I can secure that.

**Comment by tsuthers-ccpgames** [comment]
The mining logs are going to be arriving as part of the "mining ledger" system that team 5-0 is working on as part of the moon mining revamp, and we will be creating an authed endpoint for both personal and corporation mining logs. So yes, that's happening :)

The combat logs are, in aggregate, a /lot/ of data. The infrastructure required to support that endpoint doesn't justify it's utility, I'm afraid.
