### ISSUE TITLE
Authorization/Authentication?

### ISSUE THREAD

**Issue by xingped** [ccpgames/esi-issues#141]
Can anyone share a short run-down or a link to one on how to implement the OAuth2 authorization/authentication scheme for ESI? Also where do we register apps to get the client id, secret, etc.?

**Comment by Robbilie** [comment]
https://developers.eveonline.com/
https://eveonline-third-party-documentation.readthedocs.org/en/latest/

**Comment by snitchashor** [comment]
Basically you need to obtain an accessToken either by using the one time code you get from the login or a refreshToken you obtained and stored earlier from the oauth. Depending on what programming language you intend to use, there are libraries which simplify this. When querying an esi end point you pass this accesToken as an authorization header (bearer). Again when using a library e.g. the ones created by swagger-codegen, there is gonna be some sort of setAccessToken functionality and the requests use it when needed.
Btw. the whole authentication part is no different from crest.

**Comment by xingped** [comment]
Thanks for the links and help! Couple questions...

I assume it's a bad idea to have the secret key stored client-side? How would I (or is there a way I can) store the secret and use it for authentication if I'm building a web page or desktop app that communicates with my own server?

If the access token is not yet expired, but I refresh it, will the old access token become invalid?

I think the answer is no, but I'll ask anyway - Is corporation information about member roster and their roles publicly accessible or do I have to use the access token of a member/privileged member of that corporation?

**Comment by a-tal** [comment]
come chat with us in #esi on tweetfleet slack if you have any outstanding sso questions
