### ISSUE TITLE
need mail notifications (attack poses\citadels, fuel etc)

### ISSUE THREAD

**Issue by crysalis** [ccpgames/esi-issues#143]
Please add this notifications in esi 

now they are only in xml api

**Comment by evrial** [comment]
+1. Any progress with that?

**Comment by aquarhead** [comment]
Are you talking about [this](http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/character/char_notifications.html) and [this](http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/character/char_notificationtexts.html) ?

**Comment by crysalis** [comment]
@aquarhead exactly

**Comment by Kupuyc** [comment]
+1 for that feature. Very important thing.
