### ISSUE TITLE
Add founding character / corp to alliance info endpoint

### ISSUE THREAD

**Issue by mumbleskates** [ccpgames/esi-issues#146]
**Description**, **URL**, and **current faction** (facwar alignment) information is missing for ~~both corporations and~~ alliances, as is **tax rate** information for corporations. This is the kind of quality info I'm sure we would love to have, is with strong precedent, and is ideal to provide here.

**Comment by Robbilie** [comment]
description (at least for corporations) has been requested in another issue already, same goes for the faction

**Comment by Robbilie** [comment]
any news on this end, would be really cool to have at least description for the 2 endpoints, prolly not that much effort required :3

**Comment by aquarhead** [comment]
not yet, working on static data in esi-universe now

**Comment by Robbilie** [comment]
looks like some cool progress has been made on the esi-corporations endpoint v3, tax_rate, url, founder, founding date and description included

although i would suggest renaming corporation_description to description aswell as corporation_name to name

no change on the esi-alliances endpoint though

**Comment by Robbilie** [comment]
in addition to the name and description, it would make a lot more sense to have the faction field be an ID as the pk for the factions endpoint is the id and not the name…

**Comment by antihax** [comment]
also missing HQ station and shares which are available via XML.

**Comment by mumbleskates** [comment]
Additional information that is missing:

alliance -> founding character / corp
corporation -> founding character

**Comment by Robbilie** [comment]
corporation has the field creator_id

**Comment by a-tal** [comment]
https://esi.tech.ccp.is/ui/?version=dev#/Alliance/get_alliances_alliance_id
