### ISSUE TITLE
validation issue

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#158]
http://editor.swagger.io/#/

https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility

```
✖ Swagger Error
Missing required property definition: content_id
Jump to line 3572
Details
 Object
code:  "OBJECT_MISSING_REQUIRED_PROPERTY_DEFINITION"
message:  "Missing required property definition: content_id"
 path: Array [12]
level: 900
type:  "Swagger Error"
description:  "Missing required property definition: content_id"
lineNumber: 3572
```

**Comment by a-tal** [comment]
looked at this briefly. the attribute this is erroring on (`pins.content`) is optional, and currently has no code path to actually be generated atm.

the `content` param will likely change to match the required name `content_id`. @tsuthers-ccpgames to confirm tho, change is in staging atm

**Comment by tsuthers-ccpgames** [comment]
Yep, the fix for this looks sensible, I've pushed it out. This part of the spec was never rigged up to code so I'm comfortable deleting it even though it looks a bit like a breaking change, since nothing functional could never have been rigged up to it.
