### ISSUE TITLE
esi-bookmarks: Get corporation's bookmarks

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#16]
https://trello.com/c/MZK5j82F/27-esi-bookmarks-get-corporation-s-bookmarks

**Comment by gitAskur** [comment]
Monolith action get_corporation_bookmarks-v1 created for support.

**Comment by gitAskur** [comment]
@a-tal @aquarhead @tsuthers-ccpgames What should I be doing with these sort of feature requests so they do not get lost? Assign them to some people or just tag your names like I am doing now?

Clearly I'm gonna start by moving this into "In Progress", as this monolith action is out on Fractal and TQ and such but has no ESI endpoint. Unless it does, then some people on Slack might wanna know about it :p

**Comment by Slivo-fr** [comment]
Well, why not closing this and going for https://github.com/ccpgames/esi-issues/issues/69 ?

Once roles and stuff are sorted, getting a DELETE action should't be much more, isn't it ?

**Comment by gitAskur** [comment]
Less work, no politics involved and would not be wasted work if we ever get to #12

**Comment by Slivo-fr** [comment]
Sounds goods too, hope we won't wait #12 too long once this is done :)

**Comment by Slivo-fr** [comment]
![image](https://user-images.githubusercontent.com/10325988/31391405-b81cde16-add6-11e7-9d22-37072db14dae.png)

**Comment by ccp-zoetrope** [comment]
@Slivo-fr done 😄
