### ISSUE TITLE
Moons

### ISSUE THREAD

**Issue by shibdib** [ccpgames/esi-issues#160]
No way currently to convert a moon ID to anything

**Comment by Robbilie** [comment]
The /universe/names/ endpoint doesnt do that?

**Comment by shibdib** [comment]
Supported ID's for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types.

Moon id gets "error": "Invalid body JSON type"

**Comment by Robbilie** [comment]
the error is actually "no valid IDs found" but seems like you found a different error

**Comment by a-tal** [comment]
https://esi.tech.ccp.is/latest/#!/Universe/get_universe_moons_moon_id exists now
