### ISSUE TITLE
swagger ui post_universe_names broken

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#162]
https://esi.tech.ccp.is/latest/#!/Universe/post_universe_names

entering ids will make a request with the value in the ids field as whole body

Example:

putting 0 into the ids field will make a request with the POST body:
```
0
```
instead of:
```
{ "ids": [0] }
```

**Comment by a-tal** [comment]
this is intended behaviour. if you click on the example it should populate itself in the free form JSON box.

(this is actually more of an issue with basic arrays, that swagger-ui doesn't display the example, see https://esi-test.tech.ccp.is/dev/#!/Universe/post_universe_names)

would need a fix from upstream -> https://github.com/swagger-api/swagger-ui/
