### ISSUE TITLE
Request: Add more details to /universe/systems/{system_id}/

### ISSUE THREAD

**Issue by shibdib** [ccpgames/esi-issues#163]
Jumps per 24h... etc... stuff that can be see using the ingame map

**Comment by Regner** [comment]
Might be better to have a stats endpoint that lists the stats for all solar systems

**Comment by shibdib** [comment]
This would also work

**Comment by Robbilie** [comment]
@shibdib would you mind changing the feature request to creating a dedicated stats endpoint?
maybe per system, maybe global (like the jumps/kills api in xml)
pilots in space would be a nice stat to add here aswell

**Comment by Robbilie** [comment]
this here is actually a duplicate of andis request:
https://github.com/ccpgames/esi-issues/issues/86

**Comment by aquarhead** [comment]
Closing in favor of #86 which is in staging now
