### ISSUE TITLE
Character and corporation industry jobs endpoints

### ISSUE THREAD

**Issue by jamesremuscat** [ccpgames/esi-issues#165]
Analogous to the XML API's `/char/IndustryJobs.xml.aspx` and `/corp/IndustryJobs.xml.aspx`, listing current industry jobs for character and corp.

**Comment by aquarhead** [comment]
The character one is already up at https://esi.tech.ccp.is/latest/#!/Industry/get_characters_character_id_industry_jobs

The corporation one will be tracked with #387
