### ISSUE TITLE
Inaccurate parameter name in POST /ui/autopilot/waypoint/

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#168]
The endpoint seems to have inherited the behaviour of the CREST endpoint wherein the destination system ID can actually be set to a system, station or structure ID. The parameter `solar_system_id` should be renamed in order to better communicate this.

**Comment by polarina** [comment]
May I suggest calling it `location_id`?

**Comment by aquarhead** [comment]
Yeah, some internal naming and miss reading some code made me think it only accepts solar system. Will change to `destination_id`
