### ISSUE TITLE
Lack of authentication opens for Spreadsheets

### ISSUE THREAD

**Issue by whinis** [ccpgames/esi-issues#169]
While I know the response to this is going to be oh well, there is currently a large section of eve players currently using the xml api and insecure api keys either in google sheets or straight excel. They use it to pull market values and their asset apis for build calculators or mining sheets or any number of other items. Currently there is no equivalent for it in ESI using SSO logins as you can't SSO login via a spreadsheet and at best as has been discussed in slack the technically literate are making proxies that either only accept local host request or use a static api key. The ones less computer savy will either turn to public or private proxy services without any knowledge of what the key does or quit depending on how trusted or accepted the proxy services are.

So is there the possibility of adding in static keys for these people ?

**Comment by Regner** [comment]
A possible solution would be for someone to develop a service that acts as a form of proxy. There used to be a similar service for the XML API. I think it was called EVE Kit or something. It used to keep a history of all the APIs you gave it access to but also convert the XML API to JSON.

Someone could to a similar thing with ESI. Let you log into the site and then give you an authorization token. Using said token it would then just proxy all the requests as is essentially.

**Comment by whinis** [comment]
I thought about that and would have no problem developing such a service, however I was not sure it was within the developer rules with the whole agreement and application registration requirements. It would also almost render SSO login security useless

**Comment by Regner** [comment]
Yes and no. Just as before how good the security of the service, and therefor how secure the permissions you're giving away are, comes down to the developer you're trusting with your credentials. You can still revoke your credentials at any time from the EVE site.

**Comment by deadlybulb** [comment]
Still alive and well: https://evekit.orbital.enterprises/
Source code for all the modules is here: https://github.com/OrbitalEnterprises

EveKit has an XML API-like key and hashcode system.  Been pondering how to start pulling data from the ESI for EveKit.  Looks like I'll have to just ask users to login at least once then renew the creds as long as I can.

Note that I also wrote a very simple proxy for XML to JSON (without all the history retention, etc).  That's here if you're interested: https://github.com/OrbitalEnterprises/orbital-eve-xml-api-proxy

It wouldn't be hard to modify that code to handle authentication, then proxy everything else.

This all assumes you're cool with Java, which may not be the case these days.

**Comment by Regner** [comment]
:D Oh hey, so it is!

**Comment by tsuthers-ccpgames** [comment]
>I thought about that and would have no problem developing such a service, however I was not sure it was within the developer rules with the whole agreement and application registration requirements.

That's totally within the developer rules. When developing this service, you can either develop it as a service developers should deploy themselves and use with their own client credentials, or as a hosted service that proxies everyone's requests using your client credentials.

Either is fine, but be aware that if you opt for the latter, you will be responsible for ensuring that downstream use by your customers is in compliance with the developer agreement, because you're the one who will show up in the logs as the point of contact if someone starts doing silly things.

**Comment by Blacksmoke16** [comment]
Relevant:
https://github.com/Blacksmoke16/GESI

Steve also made a post about his script for it:
https://www.fuzzwork.co.uk/2017/03/14/using-esi-google-sheets/

**Comment by aquarhead** [comment]
Can this issue be closed now? or are there more things to discuss?
