### ISSUE TITLE
400 error when posting citadell IDs

### ISSUE THREAD

**Issue by Dran-Arcana** [ccpgames/esi-issues#172]
/universe/names/ endpoint returns a 400 error "failed to coerce value '<citadel_id>' into type integer (format: int32)" when posting citadel IDs.

Sample data: { "ids": [1021425637189] }

CCP SnowedIn suggested the spec needed to be fixed.

**Comment by tsuthers-ccpgames** [comment]
Converting a citadel ID into a name requires an ACL check to see if you're allowed to know about the citadel, which requires a character ID verified by the SSO. Thus, it is not supported through the public /universe/names endpoint. You should use the /universe/structures/{structure_id}/ authed endpoint for this.
