### ISSUE TITLE
Formatting of contact label IDs

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#174]
Contact label IDs are actually bitfields, not IDs, which isn't specified anywhere in the spec, and might cause problems for developers using it for the first time.

I would suggest either making that fact more obvious, by changing the property names and/or descriptions, or abstracting it away by specifying contract labels as arrays.

**Comment by aquarhead** [comment]
I don't really see a need of this..

**Comment by CarbonAlabel** [comment]
Here is what it looks like in the XML API: https://developers.eveonline.com/blog/article/contact-labels

Renaming the `label_id` property to `label_mask` would be a nice start. If people try to match the `label_id` of a contact with multiple labels to an ID from the label list, they're probably gonna be unpleasantly surprised.

**Comment by polarina** [comment]
Labels in ESI are exposed as an array of label IDs. The IDs happen to be power of twos, but that is considered an implementation detail. This could change one day without prior notice and should not be relied on.

**Comment by CarbonAlabel** [comment]
@polarina no, they aren't. They are specified as a single integer.
![image](https://cloud.githubusercontent.com/assets/17382986/22185449/0ca403d8-e0e6-11e6-8d14-7a612b946330.png)
Specifying them as an array of individual label IDs was one of my initial suggestions.

**Comment by polarina** [comment]
@CarbonAlabel that's indeed a bug then. It should most definitely be an array.

**Comment by a-tal** [comment]
- [ ] PUT /characters/{character_id}/contacts/ - change int `label_id` query param to array `label_ids`
- [ ] POST /characters/{character_id}/contacts/ - change int `label_id` query param to array `label_ids`
- [ ] GET /characters/{character_id}/contacts/ - change int `label_id` output parameter to array `label_ids`

we need to bump versions of these routes, under the assumption there's existing code that can already deal with these undocumented bitmasks.

we should also update the existing params documentation to reflect the fact that they are bitmasks.
