### ISSUE TITLE
Request: kitchen sink scope

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#178]
It would be nice to have batches of scopes or and entire kitchen sink scope so we don't have to collect new keys from users as features are implemented.

I.e. I currently have 160 tokens with CREST contact read/write access, which now needs to be moved to ESI resulting in:
1. Updating the SSO permissions at https://developers.eveonline.com/applications
2. Adding the scope to the request.
3. Requesting 160 characters delete old and create new tokens.

Would this be possible or break the intent of the scopes?

**Comment by ddouglas493** [comment]
It would break the intent of the whole system. They authorized you to
access certain information on crest. Not ESI. You'll have to do it the hard
way.

**Comment by Blacksmoke16** [comment]
I store the scopes that a user has when they login.  If they login and the scopes they logged in with does not match the scopes stored in my user table then replace the scopes, get a new refresh token and get a new token.  

This way no matter what new scopes i add, i only have to update them on the dev site and specify what ones are used when they click login.

**Comment by antihax** [comment]
My application is a little different. There is a login similar to as you describe, but under that login, tokens for each character are stored with the real scopes to allow things such as  pulling journals, updating contacts, etc. In my own personal case, to update to the new scopes I have to log in 12 times to update all 12 characters.

**Comment by Blacksmoke16** [comment]
Ah yea.  Having something to help with logging in with like many different accounts to auth each char would be nice.  But ccp stated they won't be doing account auth so don't know if there is much they can/will do.

**Comment by smclenithan** [comment]
If this can't be a thing, then what about an identifier that represents a set of long list of scopes. We continue to have the issue where the server returns a 404 when requesting many scopes at once. This is extremely frustrating.

**Comment by aquarhead** [comment]
When we reach parity with XML and ESI, we'll be at a much more stable state - so we won't be putting out new scopes every week etc..

We might take another look at all the scopes and maybe make them more concise when parity work is done. But we are definitely not going to support a "kitchen sink" scope.

I'll merge this issue to #267 for you to track the 404 errors caused by requesting too many scopes.
