### ISSUE TITLE
GET /characters/{character_id}/wallets returns unknown wallet id with 0 balance

### ISSUE THREAD

**Issue by ddouglas493** [ccpgames/esi-issues#179]
[
  {
    "wallet_id": 1000,
    "balance": xxxxxxx
  },
  {
    "wallet_id": 1200,
    "balance": 0
  }
]

The second account does not exist in game. 

XML API Output: http://i.imgur.com/Rj2hbtu.png

**Comment by polarina** [comment]
If I recall correctly, wallet 1200 used to be Aurum balance before they were migrated to the VGS.

**Comment by ddouglas493** [comment]
Ahhh, I was unaware of this. No offense, but can anybody else confirm?
