### ISSUE TITLE
esi-corporations: add corporation description to corporation info

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#18]
https://trello.com/c/cXOenxXG/29-esi-corporations-add-corporation-description-to-corporation-info

**Comment by gitAskur** [comment]
Added to minor version 1

**Comment by tsuthers-ccpgames** [comment]
Now in the dev version of the corporation endpoints. Should be promoted through in a few days once we've messaged the removal of v1, which no one should be using anyway because it gives back hard-coded fractal results.
