### ISSUE TITLE
/characters/{character_id}/wallets/ balance doesn't include decimal for cents

### ISSUE THREAD

**Issue by Blacksmoke16** [ccpgames/esi-issues#182]
The response balance from the ESI char wallets endpoint does not include a decimal to separate the cents.

```
[
  {
    "wallet_id": 1000,
    "balance": 3025276141073
  },
  {
    "wallet_id": 2000,
    "balance": 0
  },
  {
    "wallet_id": 3000,
    "balance": 0
  },
  {
    "wallet_id": 4000,
    "balance": 0
  },
  {
    "wallet_id": 1200,
    "balance": 0
  },
  {
    "wallet_id": 10000,
    "balance": 0
  }
]
```

the balance should show up as 30,252,761,410.73 however without the decimal it reads as a bit over 3 trillion.  Which is obviously not accurate :)

**Comment by polarina** [comment]
The description for the `balance` field specifies that the value is in ISK hundredths.

**Comment by Blacksmoke16** [comment]
Is that for any particular reason?  Would it not be better to just return the actual balance?

**Comment by polarina** [comment]
It was done so to avoid issues inherent with representing fixed-precision decimal values in floating point. Floating point values can not represent decimal fractions exactly.

**Comment by Blacksmoke16** [comment]
Fair enough.  Thanks!
