### ISSUE TITLE
Incorrect validation keywords in spec?

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#184]
It appears that the incorrect validation steps are taken by some of the endpoints. For example. on character_ids of contacts, maxLength is used when it should be maxItems. Can this be verified?

> 5.6. maxLength
>The value of this keyword MUST be a non-negative integer.
The value of this keyword MUST be an integer. This integer MUST be greater than, or equal to, 0.
A string instance is valid against this keyword if its length is less than, or equal to, the value of this keyword..

vs.

> 5.10. maxItems
The value of this keyword MUST be an integer. This integer MUST be greater than, or equal to, 0.
An array instance is valid against "maxItems" if its size is less than, or equal to, the value of this keyword.

```
{  
                  "description":"A list of contacts to edit",
                  "in":"body",
                  "name":"contact_ids",
                  "required":true,
                  "schema":{  
                     "description":"contact_ids array",
                     "items":{  
                        "description":"ID of the contact to edit",
                        "format":"int32",
                        "title":"delete_characters_character_id_contacts_contact_id",
                        "type":"integer"
                     },
                     "maxLength":20,
                     "minLength":1,
                     "title":"delete_characters_character_id_contacts_contact_ids",
                     "type":"array"
                  }
               },
```

**Comment by aquarhead** [comment]
Must be before I'm aware of the `maxItems` thing... will fix

**Comment by aquarhead** [comment]
For some reason, `minLength` and `maxLength` works, but `minItems` and `maxItems` doesn't..........

**Comment by aquarhead** [comment]
Need to change how esi-lib validates these.

**Comment by aquarhead** [comment]
This is fixed in esi-lib now, would fix this endpoint and review other existing endpoints as well.

**Comment by antihax** [comment]
Awesome, i will see if i can start adding validation to the Go codegen tonight.
