### ISSUE TITLE
UniverseNames parameter PostUniverseNamesIds is inconvenient.

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#186]
UniverseNames parameter PostUniverseNamesIds results in the requirement of a struct initialization in Go for a simple []int32 parameter; making it awkward to use.

Compare this to PostCharactersCharacterIdContacts which accepts `contactIds []int32` directly.

Should this not be more like PostCharactersCharacterIdContacts?

In the model compare:

```
post_universe_names_ids {
   ids (Array[integer]): ids array
}
```
with
```
contact_ids Array[integer]
```

**Comment by aquarhead** [comment]
Actually there's already a `v2` / `dev` version of this endpoint: https://esi.tech.ccp.is/dev/?datasource=tranquility#!/Universe/post_universe_names

@tsuthers-ccpgames any reason we didn't move `latest` to `v2`?

**Comment by Robbilie** [comment]
maybe because even that endpoint is broken…
body ```{ "ids": [0] }``` still yields ```{ "error": "Invalid body JSON type" }``` on v2

**Comment by a-tal** [comment]
v2 isn't broken. that's an expected error when you send an object where an array should be.

```
$ curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[0]' 'https://esi.tech.ccp.is/dev/universe/names/?datasource=tranquility'
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 22 Jan 2017 20:12:22 GMT
Content-Type: application/json
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,POST,DELETE,PUT,PATCH,OPTIONS
Access-Control-Allow-Headers: Content-Type,Authorization
Access-Control-Expose-Headers: Content-Type,Authorization
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=31536000
Content-Encoding: gzip
Via: 1.1 google
Alt-Svc: clear
Transfer-Encoding: chunked

[{"id": 0, "name": "#System", "category": "inventory_type"}]
```

**Comment by aquarhead** [comment]
`v2` solves this, and `latest` will be moved next week.

https://github.com/ccpgames/esi-issues/projects/2#card-1466218
