### ISSUE TITLE
Cache-Control for authenticated routes is inconsistent

### ISSUE THREAD

**Issue by earwig** [ccpgames/esi-issues#187]
When I make a authenticated request to a restricted endpoint twice with the same token, the first one (correctly) indicates `"Cache-Control: private"`, but the second one responds with `"Cache-Control: public"`. This is a security issue as an upstream server might publicly cache sensitive data.

Example:

![issue](https://cloud.githubusercontent.com/assets/637235/21470466/bafba886-ca58-11e6-8c9f-3fda73d8658a.png)

**Comment by a-tal** [comment]
thanks for the report. this is building atm, will be in prod soon
