### ISSUE TITLE
put /fleets/{fleet_id}/ doesn't update the fleet even though it says so

### ISSUE THREAD

**Issue by snitchashor** [ccpgames/esi-issues#188]
I get a 204 response when trying to set the motd or free move but the fleet never gets updated. Reproduced using the codegen php client or the webinterface at https://esi.tech.ccp.is/latest/#!/Fleets/put_fleets_fleet_id

**Comment by snitchashor** [comment]
Hmm actually setting the motd does work just changing is_free_move doesnt.

**Comment by aquarhead** [comment]
will take a look

**Comment by snitchashor** [comment]
If that helps, setting free move works but no matter if you set true or false it always enables free move.
