### ISSUE TITLE
Unauthed endpoint to get structure/station names.

### ISSUE THREAD

**Issue by Ligraph** [ccpgames/esi-issues#191]
This would be useful for display purposes (I could display the structure ID, but it looks much nicer to display the name), and wouldn't expose any sensitive data.  It might be easier to add structures to /universe/names/.

**Comment by Robbilie** [comment]
https://github.com/ccpgames/esi-issues/issues/65

**Comment by Ligraph** [comment]
This would not just be for freeports, but for any structure, and would only expose the name.  Its purpose is for display only.

**Comment by CarbonAlabel** [comment]
The name of a structure is sensitive data, as it contains the structure's location.

**Comment by Robbilie** [comment]
aka same endpoint yielding different results for the same field when authed or unauthed? sounds like a good idea :P

**Comment by zweizeichen** [comment]
3rd party API workaround: https://stop.hammerti.me.uk/api/

**Comment by ccp-zoetrope** [comment]
We do not intend to allow you to see a structure's name if you are not on the ACL as it does contain sensitive data (such as it's location). Look at [this comment](https://github.com/ccpgames/esi-issues/issues/450#issuecomment-378909031) for a better explanation of why.
