### ISSUE TITLE
/markets/{region_id}/history could have a longer cache time

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#193]
GET /markets/{region_id}/history appears to only change at midnight and could benefit from having a cache timer expire just after midnight.

**Comment by polarina** [comment]
CREST used to compute the exact needed cache expiry time for the market history endpoint such that it would always expire just after midnight.

This caused a race conditions where the market node had not yet computed yesterday's market history data when CREST requested it just after midnight, resulting in the unfortunate scenario where people now had to wait additional 24-hours for the day-before-yesterday's data.

**Comment by antihax** [comment]
Could it be possible to return a shorter expiration until the endpoint sees the latest data?

**Comment by aquarhead** [comment]
Not for now I think... esi-lib only supports fixed cache time for now

How about pushing it to 1 hour? (CREST is 30 min if I'm reading correctly)

**Comment by polarina** [comment]
It would be preferred not to. Caching in ESI is implemented in a context-insensitive manner and for simplicity it's probably best if all endpoints employ the same caching strategy.

What benefit does an expires-at-midnight cache timer provide for this endpoint?

**Comment by antihax** [comment]
The data does not change for ~24 hours, so it could be cached preventing
repetitive queries to the endpoints backend.

**Comment by zweizeichen** [comment]
Please reconsider, this could greatly reduce some overhead on your end when we're scraping during unusual times when the entries are not in cache. Also we could go a lot faster when scraping as we'd hit the CDN.
