### ISSUE TITLE
SSO not possible from modern Browsers

### ISSUE THREAD

**Issue by EdJoPaTo** [ccpgames/esi-issues#197]
In order to [obtain the characterID](https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/obtaincharacterid.html) from access token you have to POST `https://login.eveonline.com/oauth/verify` with an Authorization Header. To ensure you are allowed to do this, the browser will precheck the POST target uri for the CORS headers with an OPTIONS request. This OPTIONS request is currently not implemented in your backend so the browser will cancel the POST request before even sending it.

There is a great blog post describing this behavior: [Understanding and using CORS](http://restlet.com/blog/2015/12/15/understanding-and-using-cors/).
Where I found it: [StackOverflow Answer](https://stackoverflow.com/questions/39408413/angular2-http-post-how-to-send-authorization-header/39411480#39411480).

So basically I'm currently not able to use any authenticated ESI (and CREST) routes that will require the own character ID from modern browsers.

---

The failing OPTIONS request:

```http
OPTIONS /oauth/verify HTTP/1.1
Host: login.eveonline.com
(...)
Origin: http://localhost:4200
Access-Control-Request-Method: POST
Access-Control-Request-Headers: authorization
```

Current response:

```http
HTTP/1.1 404 Not Found
Cache-Control: private
Content-Type: application/json; charset=utf-8
X-Powered-By: ASP.NET
Date: Wed, 04 Jan 2017 16:01:38 GMT
Connection: close
Content-Length: 31
```

Hoping for a response like that:

```http
HTTP/1.1 200 OK
(...)
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Headers: content-type,authorization
Access-Control-Max-Age: 1728000
```

Edit: Changed from `/oauth/token` to `/oauth/verify` because [the token is not needed for browser applications](https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/implicitflow.html#client-side-applications).

**Comment by polarina** [comment]
Mind if I ask why the authorization token is being verified in the browser as opposed to on your backend?

**Comment by EdJoPaTo** [comment]
@polarina because i want to create services without a backend. Why should there exist a backend if everything can be handled just within the browser?

**Comment by EdJoPaTo** [comment]
https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/implicitflow.html#client-side-applications

I missed that point where you can use the SSO without the auth code and use the token directly.

**Comment by EdJoPaTo** [comment]
In order to [obtain the characterID](https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/obtaincharacterid.html) you have to use the `/oauth/verify` route which have the missing response headers too.
