### ISSUE TITLE
mail POST to mailing list fails

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#2]
using `recipient_type` `mailing_list` does not send to the mailing list id, and results in a timeout

https://sentry.tech.ccp.is/ccpgames/esi-mail/issues/129447/events/4723621/

**Comment by a-tal** [comment]
It also happens with corporation and alliance

**Comment by gitAskur** [comment]
Taking a look on the monolith side. Figure it might be exception class UserError being raised by the mail service and not going anywhere because the actions probably do not really handle user errors as exceptions.

**Comment by GunfighterJ** [comment]
Sent a mail to a valid mailing list, it appeared in my sent box; however, the "To" list was empty.
http://i.imgur.com/IIK9sdy.png

Here was the request:
`{"body": "Test", "subject": "Testing", "recipients": [{"recipient_id": 145174015, "recipient_type": "mailing_list"}]}`

And here was the response headers:
`{
  "date": "Thu, 24 Nov 2016 18:50:24 GMT",
  "via": "1.1 google",
  "alt-svc": "clear",
  "server": "nginx",
  "access-control-allow-origin": "*",
  "strict-transport-security": "max-age=31536000",
  "access-control-allow-methods": "GET,POST,DELETE,PUT,PATCH,OPTIONS",
  "content-type": "application/json",
  "status": "201",
  "access-control-expose-headers": "Content-Type,Authorization",
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Content-Type,Authorization",
  "content-length": "9"
}`

**Comment by gitAskur** [comment]
The fix to this should be going out tomorrow. It's exactly the issue that @GunfighterJ is describing so i'm hopeful.

**Comment by tsuthers-ccpgames** [comment]
Looks like everyone forgot about this but some quick testing suggests that the fix went out and was successful, so I'm closing this ticket. If this is not the case just reopen it and let me know.
