### ISSUE TITLE
esi-wallet: Wallet Transactions

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#20]
https://trello.com/c/eou7INVg/4-esi-wallet-wallet-transactions

**Comment by gitAskur** [comment]
What is this and how does it differ from https://github.com/ccpgames/esi-issues/issues/493 ?

**Comment by gitAskur** [comment]
According to https://github.com/ccpgames/esi-issues/issues/389 this should have been merged into 493. Closing.
