### ISSUE TITLE
Random 500 http code errors for killmails endpoint

### ISSUE THREAD

**Issue by cvweiss** [ccpgames/esi-issues#200]
Randomly receiving this error for roughly 1% of calls for the ```https://esi.tech.ccp.is/v1/characters/<characterID>/killmails/recent/``` endpoint:

    {"error": "Endpoint error: ConnectionError(ProtocolError('Connection aborted.', BadStatusLine(\"''\",)),)"}

**Comment by a-tal** [comment]
this should be fixed now.
