### ISSUE TITLE
Make NPC Corporation killmails available via endpoint

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#202]
If and when the corporation killmail endpoint is under development, can consideration be made to procure killmails from NPC corporations publicly?

Right now, if one was so inclined, they could open each killmail and copy the URL for the kill and post to zkill, so they are by no means private.

See: http://puu.sh/tdTTZ/3eff39313f.jpg

**Comment by Robbilie** [comment]
the amount of npc losses should fill the missing killmail_id gap :D

+1 here

**Comment by aquarhead** [comment]
Game designs denied
