### ISSUE TITLE
Improved Structure information

### ISSUE THREAD

**Issue by jowrjowr** [ccpgames/esi-issues#203]
Currently the structure API information is very minimal. This makes management "difficult".

The following features which are not in the ESI API would be godsends:

* Fuel. Everything Fuel. Consumption, ETA until empty (in epoch time?), how much fuel in the bay. 
* Security. Full exposure of vulnerability windows, ACL and profile information. Anchor status too, in case something is being ninja-unanchored. Especially current status, reinforced (and how long until it is out, in case it is, and what level of reinforcement). 
* Fittings. "Nice to have." Would be nice to check these things remotely.
* Services. What services does the structure have for an authorized user? 
* Industry/service information. This would be tricksy but it would be very nice if we could know industry tax, ore refine yields, market tax, industry tax, industry rig bonusing, etc. Everything of that nature.

**Comment by wtfrank** [comment]
It would be sensible to put industry/service information in-game on the services tab when you click show info on a structure

**Comment by ErikKalkoken** [comment]
I am currently mostly working with public structure and the info that I would regard as most important to add to the endpoint is:
1. Corporation ID
2. Services

Both should be obtainable for public structures.

**Comment by jowrjowr** [comment]
THE NEW ENDPOINT IS CLOSE ENOUGH.
