### ISSUE TITLE
Request: Get Route between two points

### ISSUE THREAD

**Issue by SciFi-Bob** [ccpgames/esi-issues#205]
Would be great to have an endpoint that allows for route planning using the same logic as the client does allowing you to request the path from A > B.

Something like the below (just as a very sloppy example)

/v1/universe/getRoute?startSolarSystemID=12345&endSolarSystemID=67890&routeType=safest

Returns:

{
  "application/json": {
    "total_jumps": 19,
    "route": {

2342312,
1234552,
1231233,
etc}
  }
}

**Comment by a-tal** [comment]
there's something in the works for this

**Comment by polarina** [comment]
> there's something in the works for this

Just click the "Make Open-Source" button. People can at least get some code. :)

**Comment by fuzzysteve** [comment]
https://gist.github.com/fuzzysteve/f16bff3ca331d5e03ac801e631bb2fe7

;)

**Comment by Regner** [comment]
Looking forward to seeing that project go get more love.

**Comment by a-tal** [comment]
this is live -> https://esi.tech.ccp.is/latest/#!/Routes/get_route_origin_destination
