### ISSUE TITLE
ESI sometimes returning gzipped responses even if different encoding specified

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#207]
when no accept-encoding is specified or even if "identity" is set, ESI sometimes returns gzipped content (although with the correct response header set telling you that it is gzipped) and sometimes plain text like requested.

http clients that cannot or do not want to use gzip fail on those.

**Comment by Robbilie** [comment]
when setting the accept-encoding to gzip it sometimes returns plain text, looks like the accept-encoding header is stripped somewhere and then randomly chosen what to respond :D

**Comment by a-tal** [comment]
thanks for opening this. a fix has been deployed, building now

**Comment by a-tal** [comment]
this is resolved now (for new results)
