### ISSUE TITLE
Google's CDN does not consider the Accept-Language header

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#209]
For routes without authentication, you may receive the wrong language if it's a cached result.

Currently, the only routes affected by this are 

- `GET /insurance/prices/`
- `GET /fleets/{fleet_id}/members/`
- `GET /fleets/{fleet_id}/wings/`

We have opened a case with Google support to add support for language headers to their CDN, will keep this issue updated with progress.

**Comment by a-tal** [comment]
case 11817531

**Comment by a-tal** [comment]
It doesn't look like Google's going to admit fault here.

"Working as intended" :-1:

ESI will likely change all language header support to qsparams because of this 😞

**Comment by Regner** [comment]
They don't even support the Vary header for Accept-Language :( The is fucking balls.

**Comment by a-tal** [comment]
`esi 0.3.7` is being built atm. with it the endpoint wrap kwarg `translated` changes from the header `Accept-Language` to the query string parameter `language`

**Comment by a-tal** [comment]
this is live now. relevant change: https://github.com/xxpizzaxx/esi-archive/commit/46394554cb814a2ee9d6a5c596b17d81c563ca05
