### ISSUE TITLE
ui/openwindow endpoints don't have cors enabled?

### ISSUE THREAD

**Issue by Blacksmoke16** [ccpgames/esi-issues#212]
When making a request to open a contract window in my app i get stuck with the CORs error.

`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://eve.tools' is therefore not allowed access.`

It used to work and I am pretty sure i didn't change anything on my end.  

When requesting from postman it works fine.

**Comment by a-tal** [comment]
there is an `access-control-allow-origin: "*"` header added to all ESI requests.

I can't repro this:

```
$ curl -i --compressed -d '' -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer <some token>' 'https://esi.tech.ccp.is/latest/ui/openwindow/contract/?contract_id=1234567890&datasource=tranquility'
HTTP/1.1 204 NO CONTENT
Server: nginx
Date: Mon, 16 Jan 2017 22:56:31 GMT
Content-Type: application/json
Content-Length: 0
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,POST,DELETE,PUT,PATCH,OPTIONS
Access-Control-Allow-Headers: Content-Type,Authorization
Access-Control-Expose-Headers: Content-Type,Authorization
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=31536000
Via: 1.1 google
Alt-Svc: clear
```

**Comment by CarbonAlabel** [comment]
@a-tal the problem isn't in the POST request, the problem is in the preflight (OPTIONS) request that every browser will make before even trying to make the POST request.

```http
~# curl -i -X OPTIONS https://esi.tech.ccp.is/latest/ui/openwindow/contract/
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 17 Jan 2017 02:25:56 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Allow: POST, OPTIONS
Strict-Transport-Security: max-age=31536000
Via: 1.1 google
Alt-Svc: clear
```

This problem seems to occur with **ALL** ESI endpoints, and it's a pretty big one, making it impossible to make anything but unauthenticated GET requests from browsers.

**Comment by a-tal** [comment]
yeah ok. thanks for being explicit. a fix is building currently
