### ISSUE TITLE
Show Container and ship names in assets list

### ISSUE THREAD

**Issue by whinis** [ccpgames/esi-issues#213]
Currently there is a way in the XML API to get the name of a container or ship via the char/Locations API however there does not appear to be an equivalent for ESI. This would be useful for asset management programs as well as industry or other applications so that they only look in locations with certain names

**Comment by GoldenGnu** [comment]
I like the solution in issue #498 better than a direct copy of the XML API

**Comment by aquarhead** [comment]
2 options that I can see now:

1. Have a separate endpoint for querying asset names, similiar to [this](https://esi.tech.ccp.is/latest/#!/Universe/post_universe_names)
2. Have the name be an optional field in asset list response

**Comment by gitAskur** [comment]
Do we need an issue for XML API Parity? Thinking we should maybe just close this one since this is already on our todo list so we do not need it.

**Comment by aquarhead** [comment]
@gitAskur I think it's fine to keep existing ones, so ppl can track progress, just don't make new ones that only talks about XML parity.

**Comment by aquarhead** [comment]
[This](https://esi.tech.ccp.is/latest/#!/Assets/post_characters_character_id_assets_names) and [this](https://esi.tech.ccp.is/latest/#!/Assets/post_characters_character_id_assets_locations) have been deployed.
