### ISSUE TITLE
Date in example for /markets/{id}/history/ do not match actual output

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#214]
The date in the example does not follow what is returned by ESI.
This is causing an issue with a mock server used for testing.

Example: ```
[ {
  "average" : 5.25,
  "date" : "2015-05-01",
  "highest" : 5.27,
  "lowest" : 5.11,
  "order_count" : 2267,
  "volume" : 16276782035
} ]
```

Actual: ```
[{"date": "2016-09-13T00:00:00Z", "order_count": 21, "volume": 21, "highest": 34500000.0, "average": 26180136.32, "lowest": 12122122.12}]
```

**Comment by aquarhead** [comment]
Definitely something wrong in the actual response, will take a look tomorrow. It's also weird ESI doesn't complain it's a type mismatch.

**Comment by antihax** [comment]
My dilemma is the reverse. I cannot parse`"date" : "2015-05-01",` with Go, but i can decode `"2016-09-13T00:00:00Z"`

**Comment by aquarhead** [comment]
Can't everyone just follow the spec? http://swagger.io/specification/
