### ISSUE TITLE
esi-killmails: Support reading corporation killmails

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#22]
http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/corporation/corp_killmails.html

**Comment by cvweiss** [comment]
I'm bummed to see this request in the backlog. Very bummed.

**Comment by goowikns** [comment]
Good to see it's in progress !

Just out of curiosity, as it's not a change but a new uri, will this just be added to the v1 & latest? Or is this going to be in v2?

**Comment by aquarhead** [comment]
When a new endpoint comes out it will always to on `v1`, `legacy`, `latest` and `dev`. Then `dev` would upgrade to some new versions followed up by `latest`, `legacy` endpoints not aliased to `latest` would eventually be removed and things move on.

When using an endpoint in production, always use **versioned** ones, as in `v1`, `v2` etc..

**Comment by aquarhead** [comment]
This endpoint needs some extra care, but it will come out very soon.

**Comment by aquarhead** [comment]
We found the issue and will push out fix soon
