### ISSUE TITLE
Request: PI - Invalidate planet endpoint cache

### ISSUE THREAD

**Issue by DavidEdwards** [ccpgames/esi-issues#220]
Problem
===

The cache remains holding invalid data after a user has applied changes to their planet. Example, reactivating their extractors.

Solution
===

When a planet is changed by the user, the cache for the planet should be invalidated so that apps can pull the most accurate data from the ESI.

The trigger for cache clearing could be when the user clicks on the apply button.

**Comment by tsuthers-ccpgames** [comment]
Could you provide a use case where simply waiting up to 600 seconds for the cache to clear would not be acceptable?

**Comment by DavidEdwards** [comment]
It causes confusion for the user when interacting with the third party app.

Take [my App](https://play.google.com/store/apps/details?id=dae.evepi) for example.

1. My app reports that an extractor has expired. The user needs to interact with PI in-game.
2. The user switches their extractors back on in-game.
3. The user refreshes their data in the App manually. The extractors report as being expired still.
4. User is confused.

**Comment by tsuthers-ccpgames** [comment]
I'm not convinced this case is strong enough to warrant cache invalidation. Usually this would be solved with a UI element that informs the user when fresh data will be available.
