### ISSUE TITLE
Adding citadel market orders to /market/region_id/orders/

### ISSUE THREAD

**Issue by flashspys** [ccpgames/esi-issues#227]
First, thank you for adding the /market/structures/structure_id endpoint to esi. It's really helpful!

Unfortunately the current state is to fetch every single site of this page (small reminder to #90) to get all orders for the type_id I'm looking for. It would be very nice to make enhance the /market/region_id/orders/ endpoint by an optional Authentication Header. In case the Header is transmitted the orders in citadels that are accessible by the authenticated person will be shown next to the station orders.

**Comment by tsuthers-ccpgames** [comment]
Unfortunately, adding an authentication mechanism breaks our caching strategy for the market/region_id/orders endpoint. Caching is global for non-authed endpoints or per-auth-token for authed routes. 

The /market/region_id/orders endpoint is the endpoint we can least afford cache misses on, and we cannot open up the ability to bypass the public cache on this endpoint by using different auth headers, as it would have a severe performance impact on the market.
