### ISSUE TITLE
esi-wars: Reverse ID Order to remove caching issue

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#228]
When the wars endpoint would be sorted ascending like CREST instead of descending the issue of cache related id gaps between pages would be resolved

**Comment by polarina** [comment]
What gaps? New IDs show up on the first page shifting the oldest ID of that page on to the next. If you fetch the pages sequentially you may get duplicates but never gaps.

**Comment by Robbilie** [comment]
Last time I checked I had a 50 I'd hap between page 263 and 262

**Comment by aquarhead** [comment]
This will become irrelevant after deployment tomorrow.

**Comment by Regner** [comment]
Why? What changes?

**Comment by Robbilie** [comment]
```max_war_id```
i am not happy

**Comment by Regner** [comment]
O_o Why the route of busting more caches and complicating things instead of simply reversing the order?

**Comment by Robbilie** [comment]
^ 527986 possible cached pages instead of 263, thanks
