### ISSUE TITLE
/universe/names/ & /search/ naming consistency

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#230]
/search/ -> inventorytype, solarsystem
/universe/names/ -> inventory_type, solar_system

**Comment by a-tal** [comment]
this is fixed in v2/dev of /search/, thanks

**Comment by Robbilie** [comment]
nope its not :3

**Comment by Robbilie** [comment]
GET /characters/{character_id}/search/ still needs the fix

**Comment by Robbilie** [comment]
i also wouldnt mind inventory_type -> type, solar_system -> system :)
