### ISSUE TITLE
Error messages should not contain IDs

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#235]
currently we have (and need to fix):

- [ ] <character_id> is not a character id
- [ ] type <type_id> not found

please report any other error messages containing an ID

**Comment by gitAskur** [comment]
Why do we need to sanitize this out? There are places that straight up report back invalid IDs provided so if this is sensitive information we probably need to address them.

**Comment by gitAskur** [comment]
Otherwise this should be easily addressable on the interface level but I still need to know the prupose so I can make independent decisions :dancer: 

Wow I can't believe I have the dancer here.. :hankey: 

This is great!

**Comment by Robbilie** [comment]
Corp and alli have a different response, maybe just change them to have the all fit into the same scheme

**Comment by gitAskur** [comment]
As a former goth, conformity is anathema to me. I also use words like anathema. Goth is a serious affliction.

Facetiousness aside, I'll put it on my list.

**Comment by CarbonAlabel** [comment]
> Why do we need to sanitize this out?
