### ISSUE TITLE
esi-wars: /wars/ fails

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#236]
{"error": "Action failed"}

**Comment by aquarhead** [comment]
Vulnerable to a single node death, will be fixed

**Comment by Robbilie** [comment]
K8S node or even cluster node? O.o

**Comment by aquarhead** [comment]
EVE Cluster node, not a random node death though. Because of old DB proc's performance concern all calls are directed to a single static node and it somehow dead. New proc don't have that concern so I can distribute it over all nodes.

**Comment by Regner** [comment]
Ha! A K8s node dying and and someone actually noticing :P
