### ISSUE TITLE
Bug: /universe/names/ breaks when http header is not set

### ISSUE THREAD

**Issue by ErikKalkoken** [ccpgames/esi-issues#240]
When sending a POST request to /universe/names/ without having a HTTP header set the server is running for approx. 30 secs and then returns an error message. 

Suggestion: Since the API is running into a timeout this looks like an unhandeled case. The API should either assume a http header (e.g. 'Content-Type: application/json') or return an appropriate error message. 

Here is the response message:
```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

**Comment by tsuthers-ccpgames** [comment]
Hrm, that endpoint is programmed to attempt to json-decode the request regardless of what encoding you specify. Could you provide a curl command that reproduces the issue?

**Comment by CarbonAlabel** [comment]
I know that cURL will set a `Content-Type: application/x-www-form-urlencoded` header for POST requests where a `Content-Type` header isn't specified otherwise, which might be pretty confusing to the server when combined with a JSON request body.

Have you checked if an invalid `Content-Type` header is being added by some of the tools you are using?

**Comment by ErikKalkoken** [comment]
@tsuthers-ccpgames 
Here is an example PHP code with CURL that produces the mentioned error every time. Note that I commented out the line that would set the http header. With that line it works perfectly, even with different content types.

```
<?php

$query = [
	'ids' => [93330670]
];
$body = json_encode ($query);
$url = "https://esi.tech.ccp.is/latest/universe/names/";

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,            $url );
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1 );
curl_setopt($ch, CURLOPT_POST,           1 );
curl_setopt($ch, CURLOPT_POSTFIELDS,     $body ); 
// curl_setopt($ch, CURLOPT_HTTPHEADER,     ['Content-Type: application/json'] ); 

$response = curl_exec ($ch);
var_dump ($response);

?>
```

**Comment by ErikKalkoken** [comment]
@CarbonAlabel 
I am not using any additional tools other than PHP 5.6 on a WAMP stack (my local dev environment).
I can reproduce the same behavior both on my local dev environment and when running this script on the web server hosted by my provider (also PHP 5.6).

**Comment by a-tal** [comment]
for some reason php is automagically including a `Content-Type` header value of `application/x-www-form-urlencoded` in that request.

according to rfc2388 the default if not set is `text/plain`, which I have confirmed does not result in an error, nor does omitting the header entirely.

I've put together a patch for `esi-lib` to handle `Content-Type: application/x-www-form-urlencoded` as JSON anyway. it'll make it's way to prod in the next little while
