### ISSUE TITLE
schema for "ids" argument for Universe.post_universe_names should have type object

### ISSUE THREAD

**Issue by deadlybulb** [ccpgames/esi-issues#241]
Clients picky about Swagger spec (like bravado) complain because the schema for "ids" on Universe.post_universe_names doesn't have "type" : "object".  That is, change:

"parameters":[{"description":"The ids to resolve","in":"body","name":"ids","required":true,"schema":{"description":"ids schema",...

to:

"parameters":[{"type":"object", "description":"The ids to resolve","in":"body","name":"ids","required":true,"schema":{"description":"ids schema",...

Failing to do so will give you errors like this (from bravado):

SwaggerMappingError: No proper type could be found from {'required': ['ids'], 'description': 'ids schema', 'properties': {'ids': {'minItems': 1, 'type': 'array', 'items': {'type': 'integer', 'format': 'int32', 'description': 'id integer', 'title': 'post_universe_names_id'}, 'title': 'post_universe_names_ids', 'description': 'ids array', 'uniqueItems': True}}, 'title': 'post_universe_names_ids'}

**Comment by deadlybulb** [comment]
Forgot to include the forum topic where this was raised.  It's here:
https://forums.eveonline.com/default.aspx?g=posts&m=6811963#post6811963

**Comment by a-tal** [comment]
this is fixed in `/dev/`, the body is an array there instead.

```
>>> from bravado.client import SwaggerClient
>>> esi = SwaggerClient.from_url("https://esi.tech.ccp.is/dev/swagger.json")
>>> esi.Universe.post_universe_names(ids=[1234])
<bravado.http_future.HttpFuture object at 0x000000010a93f718>
```
