### ISSUE TITLE
Invalid body JSON type on /universe/names

### ISSUE THREAD

**Issue by Ionaru** [ccpgames/esi-issues#245]
Since today I get the error "Invalid body JSON type" when attempting to get an item name using the /universe/names resource.

cURL copy from Postman:
```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
  "ids": [
    11186
  ]
}' "https://esi.tech.ccp.is/latest/universe/names/"
```

This call used to work, but suddenly stopped.

EDIT: Seems this resource no longer accepts the "ids" parameter, the array with integers has to be sent without parameter, example:
```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '[
  11186
]' "https://esi.tech.ccp.is/latest/universe/names/"
```

Is this intentional?

**Comment by tsuthers-ccpgames** [comment]
It looks like the answer is yes, it was deliberate, but the breaking change wasn't telegraphed as it should have been before being promoted. 

The previous version has been moved from /latest to /legacy, although best practice is to always use the versioned alt-route to make sure that your app doesn't suddenly break when this sort of thing happens. In this case, you'll find the old version under /v1, as can be seen here: https://esi.tech.ccp.is/legacy/?datasource=tranquility#!/Universe/post_universe_names

I suggest you upgrade to v2 when you have time. If we make a v3 and move that to latest, v1 will be removed completely and v2 will drop down to legacy :)

**Comment by Ionaru** [comment]
Thanks for the quick response.
Is there a place where I can track the changes made to the ESI so a change like this won't take me by surprise easily?

**Comment by a-tal** [comment]
https://github.com/ccpgames/esi-issues/projects/2

**Comment by aquarhead** [comment]
So we set up a timeline to track scheduled and already deployed changes to ESI last week here: https://github.com/ccpgames/esi-issues/projects/2

It was an internal discussion and I kinda forgot to say it loud publicly (on forum/slack channel) we'll see how we can improve the awareness of schedule of deployment.
