### ISSUE TITLE
esi-fleets: Can't update MOTD with long message

### ISSUE THREAD

**Issue by aquarhead** [ccpgames/esi-issues#247]
Will be fixed soon(ish)

**Comment by SpeedProg** [comment]
is there any ETA on this, because it is actually holding me back from updating an app now :(
might just need to write work around code to just use crest for this

**Comment by aquarhead** [comment]
Yes next Thursday

2017/02/17 18:34、SpeedProg <notifications@github.com> のメッセージ:
