### ISSUE TITLE
Request: add an endpoint for Outposts

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#256]
Would be nice to see an endpoint which lists all outposts identical to the ConquerableStationsListXML.

This cannot be included in the static dump as names, and owners can change on these outposts.

**Comment by a-tal** [comment]
this is included as part of https://esi.tech.ccp.is/latest/#!/Sovereignty/get_sovereignty_structures

you could look for `structure_type_id`s that you were interested in, or maybe `solar_system_id`, or `alliance_id` as well, then use those IDs with https://esi.tech.ccp.is/latest/#!/Universe/get_universe_stations_station_id to get detailed info about the station itself
