### ISSUE TITLE
PI: "Invalid 200 response: 0 does not meet minimum of 1"

### ISSUE THREAD

**Issue by tschwery** [ccpgames/esi-issues#257]
I get a 500 return status with the error message "Invalid 200 response: 0 does not meet minimum of 1" in the response of the GET /characters/{character_id}/planets/{planet_id}/ endpoint.

It could be linked to my PI shuffling of this morning where I left an extractor without any head.

I don't know if #222 is the same issue or not as the error messages are different and the extractor has no head instead of idle ones.

**Comment by tsuthers-ccpgames** [comment]
Not sure if it's related, but might as well cover it in the same pass.

**Comment by tsuthers-ccpgames** [comment]
I can't repro this locally. Could you get in contact with me on tweetfleet slack, so I can get some specific details from you and take a closer look at this?

**Comment by tschwery** [comment]
I cannot reproduce this error either since a couple of days. I tried to change things around again but no error.

If I encounter the error again I will reopen this bug and send you everything possible.
