### ISSUE TITLE
Add 'Access-Control-Max-Age' header

### ISSUE THREAD

**Issue by daimian** [ccpgames/esi-issues#258]
Browser based AJAX calls require CORS OPTIONS pre-flight calls before actually requesting data, returning us an Access-Control-Max-Age header will cache the response client-side so it is not made every API call.

**Comment by cvweiss** [comment]
Would you propose 1200 seconds? (the lifetime of an access token)

**Comment by Regner** [comment]
Would suggest a LOT longer. This is about caching the OPTIONS request which is irrelevant of authorization token.

**Comment by daimian** [comment]
Limited research yielded that FireFox allows a max age of 24 hours however it seems Chrome only allows 600 seconds (10min). I have yet to test this and info is sketchy.

I would propose we start between 1-3 hours and monitor - there is no recommended value from my limited research.

**Comment by a-tal** [comment]
thanks for this. implemented at 600 for now
