### ISSUE TITLE
No way to determine if a character is actively training

### ISSUE THREAD

**Issue by whinis** [ccpgames/esi-issues#259]
so currently you can hit /characters/{character_id}/skillqueue/ to get the skill queue or /characters/{character_id}/skills/ to get all current skills but neither one can tell you if the character is actively training. I suggest adding something to /characters/{character_id}/skillqueue/ that says if the current character is actively training.

**Comment by a-tal** [comment]
if the skillqueue result is empty, or all the `finish_date`'s are in the past, your skillqueue is empty

**Comment by rohimma** [comment]
@a-tal  i did not test this but i have some characters that have a skill queue length of a couple off months but i have paused them to train an other character on the same account.

That would mean i have non empty skill queue and i assume the `finish_date` is in the future?

**Comment by a-tal** [comment]
if your skillqueue is paused the `finish_date` key will be absent in the response
