### ISSUE TITLE
esi-assets: list personal and or corporate assets

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#26]
https://trello.com/c/eaMh8y9p/14-esi-assets-list-personal-and-or-corporate-assets

Right now, assets don't show up properly for citadels, on the non-flat list.

**Comment by gitAskur** [comment]
We have nuked the nested list monolith actions and the personal assets including citadels and containers in stations and space can now be accessed through monolith action get_character_assets-v1

Corporate assets monolith action has not been implemented but I should get on that soon so I can remove myself from this task.

**Comment by Ligraph** [comment]
I assume there is a plan for a locations endpoint for container names?  I think it would be nicer to integrate it into the assets endpoint, but I'm not sure what that would entail.

**Comment by a-tal** [comment]
ping @gitAskur waiting on a corp assets action yet

**Comment by gitAskur** [comment]
Oh look another blast from the past I had forgotten!

**Comment by gitAskur** [comment]
Three hours later I am so intimately remembering why I forgot this and dreaming about forgetting this again (but I won't. Promise!)

**Comment by gitAskur** [comment]
Back on this now after GLORIOUS INTERNATIONAL WORKERS DAY!

I'll have to ensrue XML parity, which is terrible because this is very costly. So I'm going to spend yet more time on trying to find better ways of approaching this to protect our precious running simulation.

**Comment by gitAskur** [comment]
Monolith support cannot be released until internal release name EMILY goes LIVE due to refactoring that is happening in the corporation asset management of the inventory modules.

**Comment by gitAskur** [comment]
Developer doing said refactoring is on vacation... soo I guess I won´t be doing anything with this today.

**Comment by JakeChely** [comment]
Any news on this one?
It's been a while since the last update.

**Comment by gitAskur** [comment]
We're in the corporation phase of functional parity, so this is happening. This is however probably the more complex corporation action, and is/was blocked by technical refactoring, I am going on vacation and the priority is on preventing db overload/chatter from scraping.. so to be perfectly honest this one is probably going to be a bit late to the party.

**Comment by rebrowning** [comment]
Any news on this?

**Comment by gitAskur** [comment]
I've been on vacation, so no. But this is totally on the parity todo list.
