### ISSUE TITLE
Combine location/location and location/shipType endpoint

### ISSUE THREAD

**Issue by marekr** [ccpgames/esi-issues#263]
I find myself putting out 2x the requests for maybe 500 characters over a 5 second window because I need both. I don't personally see the reason for shipType to be separate, the original justification for CREST was because a new scope was needed. But most of the time if you are getting the ship type you also want to know where it is and vice versa.  To throw it out there, I use it for wormhole mapping and mass calculation so both are required. (Though I can make some assumptions about the ship type changing to slow it down a little). The other usage I see for ship types is for fleet management by seeing composition but most use cases would want location as well to see where the peons are.

But ESI is new and it should have just been the one....

Alternatively create a combo scope and endpoint.

**Comment by ddouglas493** [comment]
This was brought up somewhere in Tweetfleet at one point. The reason it is separate is because one may not want to reveal where they are but they want to let u know what ship they are flying and vise versa. I think it was during the ESI keynote.

**Comment by a-tal** [comment]
@ddavaham is correct. the same logic also applies to the online endpoint.

if you're tracking a set of characters the fleet endpoints might be better suited to that task. or if you'd like to track a corporation, the `GET /corporations/{corporation_id}/membertracking/` route.

**Comment by marekr** [comment]
@a-tal I run siggy, I have 10k+ characters to track.

Your suggestions don't help in this situation :P
