### ISSUE TITLE
developers.eveonline ESI scope selections

### ISSUE THREAD

**Issue by marekr** [ccpgames/esi-issues#264]
The scope selection box is so tiny and there are so many ESI scopes now.
Please make box moar bigger.

Also if you select ESI scopes, save. The overview page will then flipflop the ESI scopes. If you refresh, the scopes disappear, if you refresh they reappear, refresh again, they disappear, refresh, refresh, flip flop confusion. This same bug happens with the selection box after they were already saved. There seems to be a caching issue on the server.

**Comment by BaldvinTh** [comment]
Box height increased from 200px to 21em
