### ISSUE TITLE
/v2/universe/names specification broken

### ISSUE THREAD

**Issue by Salvoxia** [ccpgames/esi-issues#268]
Hi,

the specification for the /universe/names endpoint says a POST parameter called "ids" is required, and it should be an array of integers.
Since v2 of this endpoint, passing a POST body in this format results in HTTP 400 with the error "Invalid body JSON type":

```
curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"ids": [800263173]}' 'https://esi.tech.ccp.is/latest/universe/names/?datasource=tranquility'
```

returns
```json
{
  "error": "Invalid body JSON type"
}
```

The same request against the legacy version:
```
curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"ids": [800263173]}' 'https://esi.tech.ccp.is/legacy/universe/names/?datasource=tranquility'
```
returns 
```json
[
  {
    "id": 800263173,
    "name": "Salvoxia",
    "category": "character"
  }
]
```

Passing an unnamed integer array works with the latest version, but this breaks any generated library.
So either the specification should be changed, or the endpoint's parsing behavior restored.

Best Regards,
Salvoxia

**Comment by a-tal** [comment]
This is expected behaviour, and follows the spec.

```
$ curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[800263173]' 'https://esi.tech.ccp.is/latest/universe/names/?datasource=tranquility'
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 10 Feb 2017 17:58:11 GMT
Content-Type: application/json
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,X-User-Agent
Access-Control-Allow-Methods: GET,POST,DELETE,PUT,PATCH,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type,Warning
Access-Control-Max-Age: 600
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
Content-Encoding: gzip
Via: 1.1 google
Alt-Svc: clear
Transfer-Encoding: chunked

[{"id": 800263173, "name": "Salvoxia", "category": "character"}]
```

the error you received is because the POST data type was an object instead of an array.

**Comment by snitchashor** [comment]
If its not the spec then where else is the problem? If you generated a php client with v1, Model and documentation are correct, in v2 model and doc are wrong, actually doc didn't change it just doesnt work this way any longer.

**Comment by SpeedProg** [comment]
the spec changed through, that is what you are ignoring.
from
`"parameters": [
          {
            "description": "The ids to resolve",
            "in": "body",
            "name": "ids",
            "required": true,
            "schema": {
              "description": "ids schema",
              "properties": {
                "ids": {
                  "description": "ids array",
                  "items": {
                    "description": "id integer",
                    "format": "int32",
                    "title": "post_universe_names_id",
                    "type": "integer"
                  },
                  "minItems": 1,
                  "title": "post_universe_names_ids",
                  "type": "array",
                  "uniqueItems": true
                }
              },
              "required": [
                "ids"
              ],
              "title": "post_universe_names_ids"
            }
          },
          {
            "default": "tranquility",
            "description": "The server name you would like data from",
            "enum": [
              "tranquility",
              "singularity"
            ],
            "in": "query",
            "name": "datasource",
            "type": "string"
          }
        ]`
to
`"parameters": [
          {
            "description": "The ids to resolve",
            "in": "body",
            "name": "ids",
            "required": true,
            "schema": {
              "description": "ids array",
              "example": [
                95465499,
                30000142
              ],
              "items": {
                "description": "id integer",
                "format": "int32",
                "title": "post_universe_names_id",
                "type": "integer"
              },
              "maxItems": 1000,
              "minItems": 1,
              "title": "post_universe_names_ids",
              "type": "array",
              "uniqueItems": true
            }
          },
          {
            "default": "tranquility",
            "description": "The server name you would like data from",
            "enum": [
              "tranquility",
              "singularity"
            ],
            "in": "query",
            "name": "datasource",
            "type": "string"
          }
        ]`

**Comment by Salvoxia** [comment]
Is it possible that there's some kind of delay after a new version was pushed out for getting the latest spec? I could swear that I checked with a newly generated API library before posting this issue. When I generated another one just now, the example in the docs and model check out to the new spec.
I'm a bit confused.

**Comment by SpeedProg** [comment]
not really since the documentation is generated in your browser from the specs that it loads from the url.

**Comment by antihax** [comment]
CCP are also generating swagger specs locked to a version. 
```
https://esi.tech.ccp.is/v1/swagger.json
https://esi.tech.ccp.is/v2/swagger.json
https://esi.tech.ccp.is/v3/swagger.json
https://esi.tech.ccp.is/v4/swagger.json
```
You can generate clients with these and use fixed versions so things don't break when they push new versions to `/latest`.

**Comment by Salvoxia** [comment]
Please correct me if I'm wrong, but it seems that each of these spec files only contains the endpoints for which that exact version number exists (which kinda makes sense).
But if I wanted to use a generated API client, I'd have to generate multiple clients from each of these versions (starting with the latest one), until all endpoints I need are covered, right?
That seems very impractical to me. Am I missing something there?

**Comment by antihax** [comment]
Yes you could generate one for each version and use a wrapper to combine them into a single client.

**Comment by Salvoxia** [comment]
Is there any chance for CCP to provide a Swagger spec with all endpoints using their latest version, but with a fixed version number in the route? That way, you could generate your library at a given time, develop using that state, and easily upgrade as soon as any endpoint starts throwing deprecation warnings.
In my opinion, that would be the most elegant solution.

**Comment by deadlybulb** [comment]
Just to make sure I understand, you want to request an endpoint like https://esi.tech.ccp.is/latest-versions/swagger.json which will replace all paths with the latest versioned alternates at the latest version.  So /market/prices/ becomes /v1/market/prices/ but /universe/names/ becomes /v2/universe/names/.  Correct?  This is probably something I can serve from my proxy if CCP can't get to this any time soon.  As long as CCP keeps the alternate route info current in the spec, this is a straightforward transformation of swagger.json.  A proxy (or client side code) would just transform the paths before passing to your client generator.

**Comment by Salvoxia** [comment]
Hi,

yes, that's exactly what I meant. I haven't yet taken any closer look at the swagger spec itself, but if you can do that, I'd be most grateful.

Best Regards,
Salvoxia
