### ISSUE TITLE
/universe/structures isn't unique

### ISSUE THREAD

**Issue by fuzzysteve** [ccpgames/esi-issues#269]
There are duplicates for a number of the structure ids in the data.

      2  1021019034868
      2  1021020162189
      2  1021023752413
      2  1021024120599
      2  1021043925343
      2  1021044733397
      2  1021049832391
      2  1021060102812
      2  1021136952292
      2  1021219751496
      2  1021266483175
      2  1021287331870
      2  1021287754376
      2  1021312632464
      2  1021329602794
      2  1021361776294
      2  1021464873953
      2  1021661425270
      2  1021747178693
      2  1022058050069
      2  1022070970637
      2  1022089086689
      2  1022310662352
      2  1022340313503
      2  1022371270826
      2  1022394819498
      2  1022426149653
      2  1022563626310
      2  1022602731496
      2  1022633297269
      2  1022666132124
      2  1022690044676
      2  1022787430021
      2  1022812208117
      2  1022828408129
      2  1022828538287
      2  1022828705606
      2  1022855999665
      2  1022905070205
      2  1022941222333
      2  1022956092748
      2  1022968564754
      2  1022981751916
      2  1023031951534
      2  1023084895096
      2  1023084901702
      2  1023110598854
      2  1023209970971
      2  1023274364281
      2  1023274905624
      2  1023341834060
      2  1023403676974
      2  1023429602726
      2  1023458488941
      3  1022758535954
      3  1022768496566
      3  1023087852781
      3  1023158823741
      5  1021071444008

**Comment by a-tal** [comment]
thanks for pointing this point. fix coming to prod soon

**Comment by a-tal** [comment]
once the caches expire this should be resolved
