### ISSUE TITLE
OAuth2: missing refresh_token in response when scope is empty

### ISSUE THREAD

**Issue by biow0lf** [ccpgames/esi-issues#274]
OAuth2 response from login.eveonline.com missing refresh token when scope is empty.

**Comment by Robbilie** [comment]
Intended behaviour, request public_data if you need a refresh_token for comparing owner_hash or such...

**Comment by cvweiss** [comment]
If there ever will be an FAQ this should be number one. I know it got me when I first started working with the SSO.

**Comment by antihax** [comment]
So what happens when the public_data scope is removed with the rest of the CREST scopes?

Could we keep this one? (I am using it too.)
