### ISSUE TITLE
Datatype inconsistancy

### ISSUE THREAD

**Issue by burberius** [ccpgames/esi-issues#275]
The endpoints
*GET /alliances/names/*
*GET /corporations/names/*
expect a list of *long*.
But the ids in both cases are only *integer*.

**Comment by aquarhead** [comment]
An interesting discovery: you can put both corp id and alliance id in either of the 2 endpoints and they'll always give back you the name.... 😆 

Maybe we should get rid of these and just use https://esi.tech.ccp.is/latest/#!/Universe/post_universe_names

**Comment by aquarhead** [comment]
Deployed `/v2` of these endpoints aliased to `/dev` for this
