### ISSUE TITLE
Request: Precise NPC Standings

### ISSUE THREAD

**Issue by wranders** [ccpgames/esi-issues#277]
**Ask:** Respective character and corporation NPC standings paths that reveal the same high-precision float values used to calculate market and reprocessing taxes in-game at NPC stations.

**Rational:** The current standings information supplied by CREST and the XML API are insufficient as values are rounded to the hundredth. With low value actions, the calculations are close (within 1-10 ISK), but as actions grow in value, the margin of error grows unreliably wide.

**Goal:** Access to the same high-precision float standings the cluster uses to enable third-party applications to accurately calculate market and reprocessing taxes at NPC facilities.

---
Requested data along the lines of:
```json
{
    "faction": [
        {
            "faction_id": 1, 
            "standing": 4.73858573947,
            "derived_standing": 7.65197546
        }, ...
    ], 
    "corporation": [
        {
            "corporation_id": 3487, 
            "standing": -7.82738473468237,
            "derived_standing": -1.4591357493
        }, ...
    ], 
    "agent": [
        {
            "agent_id": 48334, 
            "standing": 4.3234525,
            "derived_standing": 5.4186321
        }, ...
    ]
}
```
Agent standings are not needed in regard to this request, but are included for the sake of completeness.

**Comment by a-tal** [comment]
unless I'm missing something, this info is included in https://esi.tech.ccp.is/latest/#!/Character/get_characters_character_id_standings

**Comment by wranders** [comment]
Oh, that's new. When I suggested this, standings were only to the hundredth. 
Thanks.
