### ISSUE TITLE
esi-bookmarks: Get character's bookmarks

### ISSUE THREAD

**Issue by a-tal** [ccpgames/esi-issues#29]
https://trello.com/c/U8DMxCJH/26-esi-bookmarks-get-character-s-bookmarks

**Comment by aquarhead** [comment]
```
{
  "error": "Action failed"
}
```

**Comment by gitAskur** [comment]
Look at it in a bit

**Comment by gitAskur** [comment]
Macho Object Cache being a turdmuncher. Object cache logic to the call receiver rather than the caller which cannot guarantee any cache existing locally based on a cacheOK response from a remote node.

**Comment by gitAskur** [comment]
Reproed on a multinode local.

**Comment by gitAskur** [comment]
Submitted to branch. Will integrate out to release with other fixes later today. Probably going to TQ on Tuesday the 24th.

@tsuthers-ccpgames There´s a new version of the bookmarks action as well that can be used and will not have silly BlueDate formats. I fixed both actions though.
