### ISSUE TITLE
Ship names returning with escaped values

### ISSUE THREAD

**Issue by w9jds** [ccpgames/esi-issues#293]
I am receiving names like `&lt;` instead of like this `<`, this is specifically visible in the ship endpoint on the name property

**Comment by antihax** [comment]
As you should; the player could create a malicious ship name resulting in unintentional things on a website.

It should be trivial to unescape in most languages if you need to display text values?

**Comment by polarina** [comment]
@antihax it is the responsibility of the presentation layer (i.e. the HTML writer) to escape otherwise harmful tokens. An API should never do any HTML escaping.

**Comment by w9jds** [comment]
Just making sure it is intentional @polarina

**Comment by ccp-zoetrope** [comment]
I am closing this because @polarina is correct and nothing needs to be done further for this issue.
