### ISSUE TITLE
corporations endpoint erroring if given a charid

### ISSUE THREAD

**Issue by jowrjowr** [ccpgames/esi-issues#294]
_No, this is not stupid._ This is used to determine whether an arbitrary ID (char, alliance, corp) is friendly for internal service usage.

If I query /corporations/some_id and it happens to be a charid, I get a 500 status with "{"error": "Unhandled internal error encountered!"}" as the json response.

In comparison, if I hand /characters/some_id a corp id, it simply says 404 as you would expect.

**Comment by aquarhead** [comment]
Or you can use https://esi.tech.ccp.is/latest/#!/Universe/post_universe_names to directly find out what thing it is.

**Comment by jowrjowr** [comment]
Oh, I didn't know about that endpoint. That makes things a lot easier, actually. 

Though my point about the inconsistent with the /corporations endpoint stands!

**Comment by aquarhead** [comment]
Seems fixed
