### ISSUE TITLE
esi-characters: Information missing

### ISSUE THREAD

**Issue by mumbleskates** [ccpgames/esi-issues#298]
Character's **current security status** is not provided in ESI, but is available via XML. This together with #142 are blocking issues for moving from XML to ESI for the characters endpoint.

**Comment by CarbonAlabel** [comment]
[v4](https://esi.tech.ccp.is/v4/characters/93265215/) of the character endpoint provides this information.

**Comment by mumbleskates** [comment]
Oh very cool! This must have been added... since yesterday? I didn't see it then.
