### ISSUE TITLE
Destroyed citadel Id found in public structures list.

### ISSUE THREAD

**Issue by alexoulapour** [ccpgames/esi-issues#3]
The ID of a citadel that was destroyed 4 days prior to this call was found in the structures list and details for the structure can still be retrieved. 
  
Ashab - Pandora was the name of the citadel.
Id: 1021180724262

This was the call. https://esi.tech.ccp.is/latest/universe/structures/1021180724262/?datasource=tranquility
Here is the kill of that citadel. https://zkillboard.com/kill/56957749/

**Comment by gitAskur** [comment]
Fixed internally. Not sure about when we can push this out. Assigning to me while I figure things out.
