### ISSUE TITLE
ESI Send_Mail Proper JSON Error Responses

### ISSUE THREAD

**Issue by Blacksmoke16** [ccpgames/esi-issues#300]
Would it be possible to have proper JSON error responses? 

Example, the following is the 500 error when sending more than 5 mail (which is kinda low but that's another topic).
```
{
  "error": "Could not send mail!\nUser error, msg=MailStopSpamming, dict={'remainingTime': 556738406L}"
}
```

It would be nicer if the response used a more easily JSON parse-able string so that the handling of errors could be easier managed.  Using the example below the msg element could be used to differentiate the type of internal service error.  i.e. if msg = MailStopSpamming do something, vs just assuming all 500 type errors are because of the MailStopSpamming error.

```
{
  "error": {
                    "error":  "Could not send mail! User error",
                    "msg": "MailStopSpamming"
                    "remainingTime": 556738406L
               }
}
```

**Comment by Blacksmoke16** [comment]
Reaching the spam limit now returns a 420 error.  Not sure this is by design or if something else is going on.

**Comment by aquarhead** [comment]
Merge into #504
