### ISSUE TITLE
Feature Request: OAuth vs 3 characters per Eve account

### ISSUE THREAD

**Issue by DaneelTrevize** [ccpgames/esi-issues#303]
Would it be possible for the initial SSO https://login.eveonline.com/oauth/authorize/? GET to also pass an optional character name to CCP, such that if the name is one of those on the account the user logs into, then that character is the one pre-selected in the authorisation dropdown? I.e on this page:
https://spectrefleet.com/media/image/fleets/fleet%20scopes.png

The app invoking SSO need not gain any additional data in the response, there should be zero risk of creating a means to determine which characters are on which accounts, this is simply a way to help sites to help their users not mistakenly try to SSO for the different wrong character name than they intend to & were sent to SSO for, when the redirecting app has a character name to propose (which won't always be the case).

This case often occurs when a generic user has initially logged in to an app using independant credentials, or simple SSO without scopes, and is then required to authenticate again for a token with actual CREST/ESI scope included, because they wish to use role-restricted features such as an FC management tool, for which it would not be right to request every app user grant sufficient scopes for during simple SSO login.

**Comment by Zarquu** [comment]
CharacterID and/or CharacterName, but yes +1.

**Comment by lunedis** [comment]
This sounds like a very good idea.

**Comment by DaneelTrevize** [comment]
Requesting an SSO tag for this issue.

**Comment by aquarhead** [comment]
Please move this to https://github.com/ccpgames/sso-issues
