### ISSUE TITLE
Multiple universe location lookup routes return 500 instead of 404

### ISSUE THREAD

**Issue by paxswill** [ccpgames/esi-issues#307]
When passing a region_id that doesn't exist (0, 10000000, 99999999), instead of the expected 404 status code for a region not found, I am getting a 500 with the error message `"Unhandled internal error encountered!"`. Behavior is consistent across datasources as well.

**Comment by paxswill** [comment]
Further investigation shows that region lookup is not the only route affected:
- `/universe/regions/{region_id}/`
- `/universe/constellations/{constellation_id}/`
- `/universe/stargates/{stargate_id}/`
- `/universe/systems/{system_id}/`

All of these routes respond with a 500 status code and this response body:
```
{
  "error": "Unhandled internal error encountered!"
}
```

The moon and planet responses are more interesting (still responding with a 500 status code):
- `/universe/moons/{moon_id}/` (The example below is with 0 as the moon_id)
  ```
  {
    "error": "Invalid 200 response: failed to coerce value 'None' into type integer (format: int32)",
    "response": {
      "position": {
        "y": 0,
        "x": 0,
        "z": 0
      },
      "moon_id": 0,
      "system_id": null,
      "name": "(none)"
    }
  }
  ```
- `/universe/planets/{planet_id}/` (Again, planet_id is 0)
  ```
  {
    "error": "Invalid 200 response: failed to coerce value 'None' into type integer (format: int32)",
    "response": {
      "position": {
        "y": 0,
        "x": 0,
        "z": 0
      },
      "type_id": 0,
      "system_id": null,
      "name": "(none)",
      "planet_id": 0
    }
  }
  ```

The other routes in the Universe heading seemed to handle invalid IDs correctly.

**Comment by a-tal** [comment]
moons and planets have been fixed. will have to take a look at the rest of these with #369 #370 #371

**Comment by a-tal** [comment]
all linked issues are closed. please open a new issue if any route was missed
