### ISSUE TITLE
[Resolved: User Error] Calendar Scopes Not working

### ISSUE THREAD

**Issue by Zarquu** [ccpgames/esi-issues#310]
characterCalendarRead  does not work.   (neither does requesting the 'esi-calendar.read_calendar_events.v1' scope - which apparently does not exist)

![scopefail](https://cloud.githubusercontent.com/assets/26278745/23764803/bbcbd50a-04f6-11e7-9c7d-90c7c3fbdac6.png)

**Comment by Robbilie** [comment]
uhm…
thats the wrong scope, thats the one for crest, the one for ESI is called esi-calendar.read_calendar_events.v1

**Comment by Zarquu** [comment]
Ah, I didn't have it enabled in the developer.eveonline.com tool.
