### ISSUE TITLE
Searching for types on the market / finding market types

### ISSUE THREAD

**Issue by zweizeichen** [ccpgames/esi-issues#311]
Hey,
I'm building a typeahead feature based on the search endpoint for finding types on the market. At the moment I need to do this in a two-step process:

1. Fetch `typeIDs`from the search endpoint
2. Fetch type information from the types endpoint, then filter unpublished types

Obviously published types still include types not on the market. Now I see two possible solutions for this: Either add another category (e.g. `markettypes`) to the search endpoint and/or add a property to the type information which allows to detect if a type is not tradeable. CREST had the market types endpoint. Walking all the market groups is not really an option due to the time constraints of this use-case.

**Comment by MrNukealizer** [comment]
You can use `/v3/universe/types/{type_id}/` for the type and check if it has a `market_group_id`.

**Comment by zweizeichen** [comment]
Ah tanks a lot, `/v3` is only available in `/dev`not `/latest` - I missed that while browsing the docs. Consider this issue closed, then :)
