### ISSUE TITLE
500 internal on a market group

### ISSUE THREAD

**Issue by vivace-io** [ccpgames/esi-issues#316]
Playing around with ESI to make some cool toys, I was walking `/markets/groups` and noticed a failed job that got a 500 internal server error for group ID `369216`.

Message: `Unhandled internal error encountered!`

Ran over to CREST and noticed that the group does exist ([link](https://crest-tq.eveonline.com/market/groups/369216/)), but doesn't have anything in it. I'm assuming it is unreleased, or something to that nature?

For the record, I'm using ESI's latest release. The offending resource may be [found here.](https://esi.tech.ccp.is/latest/markets/groups/369216/?datasource=tranquility)

Cheers! And thanks for the awesome API as always! 😄

**Comment by aquarhead** [comment]
Note to me: Maybe need to make `description` optional, or give it an empty string at least

**Comment by MrNukealizer** [comment]
#304 is the same thing, with a list of all the offending IDs. It does indeed seem to be the lack of description causing the problem.

**Comment by aquarhead** [comment]
@MrNukealizer good to know, merging this issue to #304 then, will fix soon
