### ISSUE TITLE
Account Characters

### ISSUE THREAD

**Issue by MarcusThatsMe** [ccpgames/esi-issues#317]
I posted a post on the Technology Forum about the "/account/Characters.xml.aspx" end point with the XML API, back in November a dev post said all functionality would be converted over but now I'm being told this isn't which would be a super WIN for every wardec corporation in the game.

How can we know if the character joining a corp is not an alt spy for a wardec corp if we can't see what characters are linked to an account and then have them login with those other characters to review their background.

You can't tell someone to sign in with three characters, because you never know if it's from the same account (which might not have 3 characters setup) or two accounts to hide their main character hiding in the shadows.

"/account/Characters.xml.aspx" needs to be added for the sake of every corporation that cares about security.

**Comment by Robbilie** [comment]
sorry, thats not up for discussion, any account related data will be stripped from the API

**Comment by MarcusThatsMe** [comment]
How can this not be up for discussion?!? Being able to see the characters linked to a given account is fundamental to any recruitment process and is key to finding spies, thieves, and just bad characters in general from trying to enter a corporation. Its asinine.

**Comment by Robbilie** [comment]
ok so i dont know if you knew but…you can just create a new account to spy on people.
also, its not a corporations/alliances right to tell a player what to do with his/her account, you pay CCP to have 3 character slots you can use to do whatever you like in New Eden, a corporation/alliance is not to tell you what to do with those characters.

**Comment by MarcusThatsMe** [comment]
I've been playing since 2008 between myself and other vets we know most if not all the various ways people try to enter a corp to spy on it and that is why the XML API and that functionality specifically is vital to that system.  Using that along with data collected from other sources gives us a pretty good picture of a player.

I sort of understand your point with someone is paying CCP to have 3 seperate accounts and they can do what they want with them.  But its a huge loss for industrial corps and smaller pvp corps, and a HUGE win for wardec corps, thieves and other bad characters in EVE. Congratulations.

**Comment by Robbilie** [comment]
a wardeccer who read your comment said they (6-7 wardec alliances he was in) rarely used spies bc ppl are dumb enough, dunno, nullsec alliances have spies, but they dont get caught using api checks, at least not based on account api data

**Comment by MarcusThatsMe** [comment]
So everyone gets penalized because a few corps don't know how to properly vet players and catch them?  I can tell you we've caught quite a few spies just knowing what characters are linked with an account and being able to dig into that data.  Is it going to work 100% of the time no, but it does work.

**Comment by Robbilie** [comment]
what i meant was that you usually can catch spies based on other data, catching them based on account data is the easiest way but also the dumbest aka if they get caught on acc data basis you will catch them based on other data aswell, most likely.

**Comment by MarcusThatsMe** [comment]
Yes it is the easiest way, its the first line of defense, period.  So we're removing the easiest way to find spies and replacing it with a "most likely" way to find spies.  Doesn't sound smart to me, industrial corps are going to love that explanation.  And sometimes you have to really dig into their data to find good spies, the really really good spies you're not going to find generally, but the good spies hide it well, perhaps in their transaction history or marketing history (getting paid in different ways) or who they are transacting with and cross referencing those with other sources.  There is tons of data which you can correlated to keep attempt to find spies, but it all begins with knowing their characters.

And I said I understood your point with someone paying CCP to have 3 separate accounts, but then I remembered for the past decade or so they've been providing character data for accounts through the XML API, so that can't really agree with that logic, if they didn't do that then I would agree fully, but I just partially agree =)

**Comment by Robbilie** [comment]
subscription status was also in the api yet its not going into ESI, just like characters, with ascension ccp changed their standpoint…

to kinda quote someone, lazyness doesnt qualify as a good reason to include sensitive data

**Comment by MarcusThatsMe** [comment]
I wouldn't call a list of character names and ids as sensitive data.  I can understand stripping out the subscription data, I never understood why that was there. Perhaps a compromise is to allow a player to activate that ability, thus giving the player the option to make it available or not, if a corporation requires it then the player has the option to comply or to find another corp. =)

**Comment by Robbilie** [comment]
you didnt understand why it was there…?
you never ran evemon or such to see when your sub runs out and when you have to PLEX or pay again…?

your identities surely are sensitive, this all is about not even giving corps the choice to disciminate characters based on their sub or use of their other accs, including a scope will only lead to every corp requesting it and therefore to the behaviour you described, which ccp apparently wants to prevent

**Comment by MarcusThatsMe** [comment]
I've used evemon, but my sub auto renewed so I never paid attention =) And no I don't use PLEX.  BUT, now that you mention it I could see how others would like that feature.

LOL, well it's not like we're discriminating a character because they're Caldari and have two different genders.  We might not want them because its an alt character and their main is in a pure pvp corp that is thinking about attacking us.  Or perhaps their main is joining, but their alt has been collecting stolen items from their main, or something along those lines.  It's a virtual game, you don't discriminate you make judgements based on all the available data.  So I'm not going to accept the discrimination label with a virtual game, you can just say CCP doesn't want you rejecting a character because the character is actually an alt and their main character is in a wardec corp.  Or CCP doesn't want you rejecting a character because their alt is receiving payments from a corp that hates your corp and that alt is funneling money to the character joining your corp so they can steal or blow things up, etc.  I don't see a positive to not providing names and ids apart from preventing the above and other scenarios like them.  And if that's the reason, fine, they want to make the game more spicy, I'll buy that over labeling it discrimination. =)

And you're right any smart corp would require such a scope if it were made available, because its a corps first line of defense against bad characters / players. =)  I still think its asinine, but if CCP wants the game more spicy then this will surely do it.

**Comment by jowrjowr** [comment]
SHUT THE HELL UP. WE ARE TIRED OF THE LIVE FEED OF THIS DUMB SHIT.

**Comment by MarcusThatsMe** [comment]
Sorry jowrjowr I'm not too familiar with how github works, I was just told to post the issue here to get some feedback.  You could have however asked nicely, there was no need to shout.
