### ISSUE TITLE
Request: Volume Packaged on GET /universe/types/{type_id}/

### ISSUE THREAD

**Issue by mattbucci** [ccpgames/esi-issues#318]
EDIT: Looks like a duplicate of https://github.com/ccpgames/esi-issues/issues/125

Was browsing through this endpoint and couldn't find a way to get the packaged Volume, It didn't seem to be included in the dogma attributes either. 

TypeID 650 for instance has a packaged Volume of 20,000 only the unpackaged volume of 240,000 is returned.
https://esi.tech.ccp.is/latest/universe/types/650/?datasource=tranquility&language=en-us

**Comment by MrNukealizer** [comment]
+1, I'd love to drop my table of custom volume overrides for ships and capital modules.

**Comment by jrausch12** [comment]
also +1. Packaged volumes can be involved in many use cases and make many of our lives easier :)

**Comment by a-tal** [comment]
closing in favour of #125
