### ISSUE TITLE
PI Extractor qty_per_cycle wrong

### ISSUE THREAD

**Issue by hampld** [ccpgames/esi-issues#321]
esi tells me the qty_per_cycle is 5095, cycle_time is 900 -> 20380/h. ingame it tells me, the avg. hourly output is 15274. the current ingame hourly output is 19901.

I have no idea, where this comes from. Happens across all planets. First I though the esi response would be the first cycle's qty, but that would be in the above stated example 5064/15min = 20256/h. 

please either specify what the qty_per_cycle exactly is, or return the avg. qty_per_cycle as shown ingame in the program output -> per hour field.

**Comment by Regner** [comment]
I wrote up a formula and put it on the old EVElopedia, you will basically need that formula to have these values make any sense.

Hopefully someone has a copy of EVElopedia and can dig that up or someone on EVE dev can dig it up again. Should go in the EVE Third-Party docs.

**Comment by Regner** [comment]
Fuzzysteve was kind enough to provide a web archive link: https://web.archive.org/web/20160228222856/https://wiki.eveonline.com/en/wiki/Equations_Industry#Planetary_Interaction_Program_Chart

Hopefully that helps.

**Comment by hampld** [comment]
using the formula you posted i get avg. rate of 11838. that's unfortunately just as wrong. 

Is there any official documentation on this?

**Comment by Regner** [comment]
That was the official documentation. I doubt the code behind it changed. I know the Android PI timer app (https://play.google.com/store/apps/details?id=com.PITimer.myapp&hl=en) is based on that same code in that link.

I don't have an active PI colony to test. Can you tell me what the API tells you for the `install_time`, `cycle_time`, and `qty_per_cycle`?

**Comment by hampld** [comment]
last_cycle_start: "2017-03-24 09:33:13", product_type_id: 2309, cycle_time: 900, qty_per_cycle: 4589, install_time: "2017-03-24 09:33:13", expiry_time: "2017-03-25 10:18:13"

is the API info. according to the formula provided, that should give me 343433 total units. accoring to ingame stats, it's 332323 units.

**Comment by Regner** [comment]
Agreed it should be. I know a PR to https://github.com/ccpgames/eveonline-third-party-documentation explaining it would be greatly appreciated. :)
