### ISSUE TITLE
GET /characters/{character_id}/ not always returning alliance_id

### ISSUE THREAD

**Issue by stevesonne** [ccpgames/esi-issues#322]
Call to https://esi.tech.ccp.is/latest/characters/95768318/?datasource=tranquility was returning the following: 

```{"corporation_id": 98453261, "birthday": "2015-07-30T03:34:07Z", "name": "Drezzt Hemanseh", "gender": "male", "race_id": 4, "bloodline_id": 5, "description": "", "ancestry_id": 2, "security_status": 0.9069609783825237}```

Character had joined corp earlier in the day but 8+ hours later there was no alliance_id included in the response.

**Comment by ddouglas493** [comment]
Current output of the corporations endpoint shows that the corporations is currently in an alliance.

https://esi.tech.ccp.is/latest/corporations/98453261/?datasource=tranquility

``{"corporation_name": "Apotheosis.", "ticker": "APOHS", "member_count": 126, "ceo_id": 91752204, "corporation_description": "<font size=\"12\" color=\"#bfffffff\">We're a Dota corp now. 2k MMR or greater only. Pudge pickers need not apply. <br><br>All applicants must compose a Haiku featuring the word \"Gnome\" for <i>each character admitted.</i><br><br>Contact:  </font><font size=\"12\" color=\"#ffffa600\"><a href=\"showinfo:1373//91752204\">Kyle Aparthos</a></font><font size=\"12\" color=\"#bfffffff\"> or join </font><font size=\"12\" color=\"#fff7931e\"><a href=\"joinChannel:-76789389//None//None\">APOHS_public</a></font><font size=\"12\" color=\"#bfffffff\"> <br><br><br></font><font size=\"12\" color=\"#ffffa600\"><loc><a href=\"http://i.imgur.com/s2Okcb0.png\">GNOME</loc>S</a><br><br><br></font><font size=\"12\" color=\"#bfffffff\"><i>Deeps of Russian Space,<br>Echoes one cry from blackness<br>Fuck Iceland Fuck Gnomes<br><br>---</font><font size=\"12\" color=\"#ffffa600\"><a href=\"showinfo:1377//95107215\">Pardet Kynes</a></font><font size=\"12\" color=\"#bfffffff\"> </i></font>", "tax_rate": 0.05, "creator_id": 91752204, "url": "http://", "alliance_id": 99006692, "creation_date": "2016-04-08T04:09:51Z"}``

**Comment by cvweiss** [comment]
cache?

**Comment by ddouglas493** [comment]
https://esi.tech.ccp.is/v4/characters/95768318/?datasource=tranquility

``
{
  "corporation_id": 98453261,
  "birthday": "2015-07-30T03:34:07Z",
  "name": "Drezzt Hemanseh",
  "gender": "male",
  "race_id": 4,
  "description": "",
  "bloodline_id": 5,
  "ancestry_id": 2,
  "security_status": 0.90696097838252
}
``

Reflecting the correct results now.

**Comment by cvweiss** [comment]
Yea, it was the cache. You have to expect things like that to happen.

**Comment by Robbilie** [comment]
It was not the cache.

We noticed it 5h after he joined and after the expires of the one we checked when we noticed it showed it still missing even on a fresh version.

It might be the cache as in it's not returning fresh data even though the expires was reached but that's a big then.

**Comment by cvweiss** [comment]
@Robbilie I was talking about @ddouglas493 's posts, not yours.

**Comment by ddouglas493** [comment]
OH i was just paste stuff in to help with the current snapshot portion of the investigation. questions liek well is the corporation the member is a part of in an alliance at the moment. I was saying i have my own issue. Sorry for the confusion.

**Comment by ddouglas493** [comment]
Leaving another example. I had to refactor some code today because our renter corporation switch to a new alliance today and the new alliance is not showing up in the /character/{character_id} endpoints output


```
{#366 ▼
  +"corporation_id": 98492431
  +"birthday": "2015-10-07T04:49:22Z"
  +"name": "David Davaham"
  +"gender": "male"
  +"race_id": 4
  +"bloodline_id": 5
  +"description": "Null Sec Industrialist<br>Corporation Web Developor<br>All around good guy"
  +"ancestry_id": 2
  +"security_status": 0.83034457967212
}
```

[In Game Character Sheet](http://i.imgur.com/c8CHuP6.png)

**Comment by aquarhead** [comment]
We've been fixing character tracking related things recently, is this still a problem?

**Comment by aquarhead** [comment]
Since no one replied ^ I'm closing this.
