### ISSUE TITLE
No way for Corps to track Corp Scope Usage

### ISSUE THREAD

**Issue by whinis** [ccpgames/esi-issues#327]
While prior to CREST and ESI there was no log as well, the API keys were limited to creation by directors and CEOs. Now there are Corp scopes that require you are only part of a corp( such as members) and unlike corp API keys can be requested rather you have the correct roles to access data or not. While its true that the scopes only become active if you have the correct roles unlike the API keys they are not invalidated upon losing the roles (the Token stays valid even if the scopes do not) such as removal of director access or moving corps. The fact that they are not invalidated coupled with the fact that its no longer constrained to directors and no API log for corps means that corp have no realistic way of knowing who has access to corp data. 

I have been told this is a trust issue by some however just accepting someone into the corp means activation of some scopes. I am unsure how the assets API works but I assume giving a user access to communal hangers means that they can query all assets in all communal hangers. This creates a severe breakdown in the intel game of eve as there is no counter play, there is no tracking who has access or has given access or way of finding out.

**Comment by a-tal** [comment]
corps can manage their access via the roles system. just because you have a valid token does not mean the action will succeed. the character still needs the appropriate roles in the corporation to perform the action.
