### ISSUE TITLE
feature request: alliance contacts

### ISSUE THREAD

**Issue by bmstettin** [ccpgames/esi-issues#328]
missing an esi endpoint as replacement for  api.eveonline.com/Corp/ContactList.xml.aspx
i suggest to create endpoints with a feature set similar to the esi-Contacts block  for corp and alliance contacts.
this would make the contact and standing management on corp/alliance/coalition level much easier.

**Comment by Captainthrills** [comment]
I thought I was going crazy looking through all the endpoints and couldn't figure out which to call. This would be much much easier for dynamic contact lookup for when your registration system is public and you just need to check their alliance standing against your current.

**Comment by ErikKalkoken** [comment]
Looking forward to see corporation and alliance contacts / standings in ESI. It would be super awesome to get write access to alliance standings, same as it currently works for character standings. Being able to automate maintenance of alliance standings would make life so much easier.

**Comment by Slazanger** [comment]
I would like to see this also!

**Comment by ddouglas493** [comment]
Any update on this?

**Comment by ErikKalkoken** [comment]
Corporation contacts apparently are now available at this endpoint: 
`/v1/corporations/{corporation_id}/contacts/`
However, no alliance contacts yet as far as I can see.

**Comment by Slazanger** [comment]
any update on when the alliance contacts will be available ?

**Comment by ccp-zoetrope** [comment]
@Slazanger what I'm about to say is the stock answer lately, but this won't be looked at until "after parity is reached with XML API". ☹️

**Comment by CarbonAlabel** [comment]
@ccp-zoetrope but alliance contacts are a part of XML parity.

**Comment by ddouglas493** [comment]
He's right. 

https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/character/char_contactlist.html

The char_contactlist contains Alliance Contacts.

**Comment by aquarhead** [comment]
😱

**Comment by ccp-zoetrope** [comment]
@CarbonAlabel thanks for pointing that out. I guess this issue will be worked on as part of XML parity then.

**Comment by Slazanger** [comment]
@ccp-zoetrope so soon ish ?

**Comment by ccp-zoetrope** [comment]
Yes, soon™ for sure :) @Slazanger

**Comment by ddavaham** [comment]
Ekkkkkkkkkkkkkkkkkk *closes eyes* please work please work please work please no bad cache please no bad cache.

**Comment by Slazanger** [comment]
hang on.. soon™ actually happened!  Thanks!
