### ISSUE TITLE
Waypoints endpoint returns 404

### ISSUE THREAD

**Issue by themightymanuel** [ccpgames/esi-issues#329]
I am trying to set a waypoint. But everytime I try I get a 404 error. If I try to set it from the Swagger UI it works just fine, waypoint shows in game almost instantly, returns 204 as expected. Even using the exact url that it is using I get the same 404 error.

Sample url:

`https://esi.tech.ccp.is/latest/ui/autopilot/waypoint/?add_to_beginning=true&clear_other_waypoints=true&destination_id=60008158`

also tried something like:

`https://esi.tech.ccp.is/latest/ui/autopilot/waypoint/?add_to_beginning=false&clear_other_waypoints=false&datasource=tranquility&destination_id=60008158&token=abcdefghijklmnopqrstuvwxyz`

from google chrome, this returns:

`{"error": "Not found"}`

These are identical to the settings I put into the swagger UI where it worked perfectly well.

**Comment by Robbilie** [comment]
Try making a POST request instead of a GET request

**Comment by tschwery** [comment]
If I understood you correctly, you cannot (always) copy and paste the URL given in ESI into your Chrome URL bar. The method is important in ESI.

The `/autopilot/waypoint/` is only accessible through `POST`. If you use your browser, it will send a `GET` request. You can either use the `curl` command that is given in ESI, use a Chrome extension that will allow you to forge your own REST requests with the correct method or build a page that will make the request with a `POST`.

**Comment by Robbilie** [comment]
You can send post requests from Chrome's JS console or use something handy like postman but yeah, pasting in the URL bar makes a GET request, also, this endpoint requires authentication so you have to set a header or a query parameter with an access token :)

**Comment by themightymanuel** [comment]
Wow didn't even realize it was a POST request (though it does make sense logically as I'm telling the server to do something as opposed to asking for something). I didn't see any content being POSTed so I just assumed GET. Changed that one word in my request and left content blank and it's now working. Might be something worth mentioning in the implementation notes. I assume as I implement any other ui commands or similar they will be POST requests as well?

**Comment by tschwery** [comment]
The method is always written on the left of the URL.

It can also be `DELETE` or `PUT` (see for example the mail ones : https://esi.tech.ccp.is/latest/#/Mail).

**Comment by themightymanuel** [comment]
Wow never noticed that until you mentioned it. I don't know how they are all colorful and stuff.

**Comment by aquarhead** [comment]
Can this be closed now?
