### ISSUE TITLE
Contacts GET/DELETE throwing 500 errors since downtime 3/30.

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#332]
Receiving the following error on 50+ tokens that were working prior to downtime.

```HTTP/2.0 500 Internal Server Error
 {"error": "Unhandled internal error encountered!"}```

ccp_aquarhead had hinted that this may be related to blocked characters, but there is another bug preventing blocked characters from being removed in game through the UI. They clear, but on restarting the client, they are back.

**Comment by aquarhead** [comment]
Didn't see any errors on DELETE'ing contacts from our logging system..

**Comment by antihax** [comment]
So unfortunately I am not dumping response data for this one and since the parameters are in the body, they are not recoverable in the request once fired... But I am seeing 500's on DELETE.

```500 Internal Server Error | **SNIP** | 
DELETE /v1/characters/720601369/contacts/ HTTP/1.1
Host: esi.tech.ccp.is
Accept: application/json
Authorization: Bearer **SNIP**
Content-Type: application/json; charset=utf-8
```

Will see if i can get more information tonight.

**Comment by aquarhead** [comment]
Any update? Fix for GET should be out at least

**Comment by antihax** [comment]
Still seeing errors and failover to CREST. Cannot tell which endpoints ATM.

**Comment by antihax** [comment]
This is the error from the DELETE endpoint.

``` 
HTTP/2.0 500 Internal Server Error
blah... blah...
{"error": "Invalid 200 response: no schema defined", "response": {}}
```

**Comment by a-tal** [comment]
@antihax confirmed a fix for the delete endpoint, should receive a 204 on success now.

@w9jds lets get the delete body debate going in a separate issue, it's more related to conventions in esi-lib than this specific route/issue
