### ISSUE TITLE
GET /characters/{character_id}/portrait/ - Missing size

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#335]
nowhere documented anyways but handy, there is a resolution for 1024x1024 which is missing from this endpoint.
Mising resolutions:
32x32
1024x1024

**Comment by SpeedProg** [comment]
from my own experience old characters don't have a 1024x1024 ( the url actually works but it spits out a 512x512 picture)
So maybe that is why it isn't in there

**Comment by Robbilie** [comment]
i mean the sizes are marked optional in the spec anyways so…

**Comment by CarbonAlabel** [comment]
#131
