### ISSUE TITLE
The hidden Fleet member

### ISSUE THREAD

**Issue by rohimma** [ccpgames/esi-issues#337]
Lets start off with a screenshot of what i mean with 'hidden' fleet member:
![image](https://cloud.githubusercontent.com/assets/2255417/24628067/435ea862-18b6-11e7-8f38-ff475c4d07c1.png)
(notice the 2 indicating that there should be 2 fleet members) 

#### steps to reproduce
1. Get 2 players in a fleet and have them as squad members
![image](https://cloud.githubusercontent.com/assets/2255417/24628550/09aca00a-18b7-11e7-88d1-051f2b671ccb.png)

2. use esi to promote player A (in this case 'Jarno Midumulf') to fleet commander but include the wing_id and squad_id in the body.  
Ingame player A will move to the squad commander position:
![image](https://cloud.githubusercontent.com/assets/2255417/24629102/286fa522-18b8-11e7-9952-e27f49bc2ee3.png)

3. use esi to promote player B (in this case 'Rohan midumulf') to wing commander. 
Ingame player A will disappear from the fleet window:
![image](https://cloud.githubusercontent.com/assets/2255417/24629180/786f3966-18b8-11e7-9f33-8ec9bfb5f4de.png)

I can provide the fleet id, wing id and squad id via slack (@rohimma or 'Jarno midumulf') or via chat ingame

**Comment by aquarhead** [comment]
Added checks in ESI prior to sending the data to the monolith, this should not happen any more

**Comment by rohimma** [comment]
@aquarhead thx for the quick solution, this bug has been resolved.  

But now when i want to promote some one to `squad commander` or `squad member` i get an error that i should provide both `squad_id` and `wing_id`, but i am sending both off them.

Do you want me to make a new report for that or is this fine?
