### ISSUE TITLE
route endpoint - flag parameter has no effect

### ISSUE THREAD

**Issue by Vargsyn** [ccpgames/esi-issues#339]
If i want to get the route between 2 systems the returned list of systems never differ with different values for the flag parameter. In the attached files is the result of a route between 2 Systems. If the flag parameter isn't set or it's set to 'shortest' it takes the expected routes through low sec systems. 
But if i change the flag to 'secure' the same route is returned. Again leading through low sec instead of taking the longer route through high sec. 

For comparison: 

**shortest:** https://esi.tech.ccp.is/latest/route/30000158/30000188/?avoid=30000153&datasource=tranquility&flag=shortest 
**secure:** https://esi.tech.ccp.is/latest/route/30000158/30000188/?avoid=30000153&datasource=tranquility&flag=secure 
**insecure:** https://esi.tech.ccp.is/latest/route/30000158/30000188/?avoid=30000153&datasource=tranquility&flag=insecure

Below are screenshots of the route proposed with the flag parameter set to "secure" and one of the systems with a security status below [0.5]

![esi-bug](https://cloud.githubusercontent.com/assets/15607509/24712059/15b0d8a0-1a22-11e7-880b-ad5e137b0415.jpg)
![esi-bug-system](https://cloud.githubusercontent.com/assets/15607509/24712060/15b83528-1a22-11e7-9b30-67d1223863ea.jpg)

**Comment by a-tal** [comment]
cheers thanks, this is fixed in production now

you might still see some weird results from the cdn as the caches expire
