### ISSUE TITLE
Feature Request: /ui/openwindow/givemoney/

### ISSUE THREAD

**Issue by Conjur0** [ccpgames/esi-issues#343]
BACKGROUND/USAGE:
    Several alliances run SRP/Buyback/misc other payout services; that currently require people to copy/paste names/values/descriptions from a webpage, to the client. Personally, I run a buyback for one of the larger alliances, and have lost quite a bit due to my lack-luster copy/paste skills.

METHOD: POST
PARAMETERS: (preferably in content): character_id, amount, reason
SCOPE: esi-ui.open_window.v1

**Comment by Blacksmoke16** [comment]
Duplicate of #190

**Comment by a-tal** [comment]
closing this in favour of #190
