### ISSUE TITLE
intermittent 502 Bad Gateway errors (~25% of the time)

### ISSUE THREAD

**Issue by Conjur0** [ccpgames/esi-issues#344]
Recently, I have been getting intermittent 502 errors... my current workaround is to just repeat the request until it goes through, but some times that ends up sending 20+ requests, and wasting a significant amount of time and bandwidth.

Confirmed Affected endpoints:
/latest/markets/structures/.../?datasource=tranquility
/latest/markets/.../orders/?datasource=tranquility&order_type=all
/latest/characters/.../assets/?datasource=tranquility
/latest/characters/.../skills/?datasource=tranquility
/latest/corporations/.../members/?datasource=tranquility

It likely effects all ESI endpoints; but these are the only ones I pull regularly, and have seen the error in.

Example of returned header:
```
Array
(
    [0] => HTTP/1.0 502 Bad Gateway
    [1] => Server: nginx
    [2] => Date: Wed, 12 Apr 2017 01:35:11 GMT
    [3] => Content-Type: text/html
    [4] => Content-Length: 166
    [5] => Strict-Transport-Security: max-age=31536000
    [6] => Via: 1.1 google
    [7] => Alt-Svc: clear
)
```

**Comment by a-tal** [comment]
this should be improved now. let us know if you run into issues again and/or hang out in the #esi channel in tweetfleet slack for up to date news/patch info/etc.

**Comment by Kupuyc** [comment]
Still a lot of 502 errors. Not 25% but annoying. Example routes:

- /v1/characters/names/
- /v4/corporations/[corporationID]/

**Comment by Kupuyc** [comment]
Now there are another error

`2018-06-05T19:37:16.835Z - EveEsiApi request error path=/v4/characters/697951723/skills/, Authorization=Bearer, error=Timeout contacting tranquility`

**Comment by cvweiss** [comment]
Setup your code to expect 502s and 504s and retry accordingly. Why? Because shit happens.

**Comment by Kupuyc** [comment]
Ofc I did it. But it is not a reason do not try to fix it.
