### ISSUE TITLE
request: /characters/{character_id}/contracts/ and /corporation/{corporation_id}/contracts

### ISSUE THREAD

**Issue by Conjur0** [ccpgames/esi-issues#345]
Request similar functionality to the current API; but with select changes to reduce bandwidth and unnecessary processing.

METHOD: GET
PARAMETERS:
  (optional)contractID,  return information on a specific contract
  (optional)first_id, return contracts created after, and including, the listed contractID
  (optional)changed_after, return contracts that have changed status after the date/time given (recommend using the "sql interger" format (yyyymmddhhmmss) or seconds since epoch, to avoid formatting/timezone confusion.
  (optional)status, only return contracts with the given status.
SCOPE(s): (new)esi-characters.read_contracts.v1 (new)esi-corporation.read_contracts.v1

METHOD: PATCH (could be PUT, but would prefer that be reserved for future functionality of creating contracts, which would require a significant amount of time to implement properly)
PARAMETERS:
  contractID, selects the contract ID to affect.
  action=accept,accept_corp,reject,delete
SCOPE(s): (new)esi-characters.write_contracts.v1 (new)esi-corporation.write_contracts.v1

It would be nice to be able to mix/match the parameters (IE,  status=Outstanding&changed_after=20170411235748)

**Comment by ddouglas493** [comment]
Duplicate https://github.com/ccpgames/esi-issues/issues/61

**Comment by a-tal** [comment]
closing in favour of #61
