### ISSUE TITLE
alliances/names/ include alliance ticker + maybe option to fetch all alliances at once

### ISSUE THREAD

**Issue by Risingson** [ccpgames/esi-issues#351]
edited for priority:
1 - add alliance ticker. it belongs in the names endpoint
2 - query for all active alliances at once

**Comment by Robbilie** [comment]
what do you mean with "all"?

**Comment by Risingson** [comment]
every active alliance

**Comment by Robbilie** [comment]
and why not all all alliances?
i think ticker is a good idea, all alliances, nah, just query the /alliances/ endoint and pipe in the ids, not that this would work bc the url would be too long but yeah…

**Comment by Risingson** [comment]
hurts!

**Comment by Robbilie** [comment]
what?

**Comment by Risingson** [comment]
splitting the ids into chunks to get all alliance names and hopefully tickers makes me stick to using the xml api...

**Comment by Robbilie** [comment]
bad luck risingson, xml api is going away :D

**Comment by Risingson** [comment]
hence i created an esi issue :p

**Comment by a-tal** [comment]
the alliance ticker (and its name) is available from https://esi.tech.ccp.is/latest/?datasource=tranquility#!/Alliance/get_alliances_alliance_id

all alliances are available as well https://esi.tech.ccp.is/latest/?datasource=tranquility#!/Alliance/get_alliances

**Comment by Risingson** [comment]
_alliances/names_ has the advantage of being able to query multiple alliance_ids at once.
similar request at https://github.com/ccpgames/esi-issues/issues/362

adding the ticker to this endpoint really makes sense imho
