### ISSUE TITLE
esi-killmails: faction_id returned in corporation_id field (CREST does not)

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#354]
my tool just started bugging me that some ids were not valid corp ids, 500001 and 500002 specifically.
those are faction ids, this time i did not mess up, esi-killmails actually return the faction id in the corporation id field while crest does not.

https://crest-tq.eveonline.com/killmails/31733120/60e29400986066c0d35cd52ad495e87bf3fdaa0f/
https://esi.tech.ccp.is/latest/killmails/31733120/60e29400986066c0d35cd52ad495e87bf3fdaa0f/

i got 1221 examples for 500001 being returned as corporation_id

**Comment by gitAskur** [comment]
Monolith action does
add_valid_id(victim_info, 'corporation_id', killmail.victimCorporationID)

I assume this is being persisted to DB wrong, or is correctly persisted as something weird because :decisions:. At any rate I'll take another peek at this tomorrow.

**Comment by gitAskur** [comment]
This is totally in the persisted data. Will take a look at why later and see if I need to assign some defects internally or if this is supposed to make sense like this.

**Comment by gitAskur** [comment]
Scratch that! It's early in the morning and I just read an npc corpID and thought it was clearly on the factionID range. victimCorporationID is clean of any factionIDs. Hooray for correct data!

**Comment by gitAskur** [comment]
CREST return
`		{
			"damageDone": 566,
			"faction": {
				"id_str": "500001",
				"href": "https://crest-tq.eveonline.com/factions/500001/",
				"id": 500001,
				"name": "Caldari State",
				"icon": {
					"href": "http://imageserver.eveonline.com/Alliance/500001_128.png"
				}
			},
			"damageDone_str": "566",
			"shipType": {
				"id_str": "3741",
				"href": "https://crest-tq.eveonline.com/inventory/types/3741/",
				"id": 3741,
				"name": "Caldari Sentry Gun II",
				"icon": {
					"href": "http://imageserver.eveonline.com/Type/3741_128.png"
				}
			},
			"finalBlow": false,
			"securityStatus": 0
		},`

ESI Return
`	{
		"security_status": 0.0, 
		"final_blow": false, 
		"damage_done": 566, 
		"corporation_id": 500001, 
		"ship_type_id": 3741
	}, `

Seems like the monolith killblob parser is not handling NPC participants correctly.

**Comment by gitAskur** [comment]
Wow I am super happy with that code formatting..

**Comment by Robbilie** [comment]
I just hope it's correct in the DB and there's no special snowflake handling in crest

**Comment by gitAskur** [comment]
```
Testing
  Triple
    Backticks
```

**Comment by gitAskur** [comment]
It's all cool in the DB @Robbilie.. except I can only see two attackers in the killblob and not three.. but ESI and CREST agree on it being three so clearly, as so often before, I am the problem here!
