### ISSUE TITLE
Specify prices as double instead of float

### ISSUE THREAD

**Issue by zweizeichen** [ccpgames/esi-issues#356]
Client generators infer a 32 bit float from ESI's Swagger spec. 32 bit floating point values are not enough to represent common price ranges accurately. See: https://play.golang.org/p/oeia298mty
I suggest simply changing the data type to `double`. This does not require any changes to ESI's backend whatsoever and improves the situation immediately. There is no real reason to keep it 32 bits apart from backwards compatibility. In the future, a solution based on integers could be discussed.

**Comment by antihax** [comment]
I would prefer int64 iskCents; but can work with either.

**Comment by zweizeichen** [comment]
Why not both? :tada: :taco:

**Comment by a-tal** [comment]
I've `double`'d your ISK attributes.

in wallets and markets anyway, where they were float previously. if I've missed any let me know w/ a new issue, thanks

**Comment by zweizeichen** [comment]
I knew doubling ISK would work eventually. 💸💸 Thanks a lot! Maybe you could consider adding cents, too as @antihax suggested.
