### ISSUE TITLE
Open Window UI Endpoint is not opening window ingame given 204 response

### ISSUE THREAD

**Issue by ddouglas493** [ccpgames/esi-issues#357]
I am not sure what information I can provide, but I am unable when make an HTTP Post request to the /v1/ui/openwindow/information/ endpoint, I am receiving a 204 HTTP Response Code. When I look at my client though, there is no window open reflect my requests success.

I have tested this on both my site and the ESI Site. Same result. The window is not opening.

Headers from the ESI Site:
{
  "date": "Sat, 22 Apr 2017 05:45:26 GMT",
  "via": "1.1 google",
  "vary": "Accept-Encoding",
  "alt-svc": "clear",
  "server": "nginx",
  "access-control-allow-origin": "*",
  "access-control-max-age": "600",
  "access-control-allow-methods": "GET,POST,DELETE,PUT,PATCH,OPTIONS",
  "content-type": "application/json",
  "status": "204",
  "access-control-expose-headers": "Content-Type,Warning",
  "access-control-allow-credentials": "true",
  "strict-transport-security": "max-age=31536000",
  "access-control-allow-headers": "Content-Type,Authorization,X-User-Agent"
}

**Comment by CarbonAlabel** [comment]
Could it be you are providing the endpoint with an ID which is not that of a character, corporation or alliance?

**Comment by ddouglas493** [comment]
Damnit I could have of sworn that this excepted solar system id's as well. Derp
