### ISSUE TITLE
Location endpoint

### ISSUE THREAD

**Issue by Rubee** [ccpgames/esi-issues#359]
`universe/planets/{planet_id}/` should include asteroid belts and possibly stations (station could possibly have it's own endpoint).
```
{
  "system_id": 30001050,
  "name": "Jamunda",
  "position": {
    "x": -21707538630857810,
    "y": 12158993335236082,
    "z": -144833414682716930
  },
  "security_status": -0.03783249109983444,
  "constellation_id": 20000153,
  "planets": [
    {
      "planet_id": 40066852
    },
    {
      "planet_id": 40066853
    },
    {
      "planet_id": 40066855
    },
    {
      "planet_id": 40066857,
      "moons": [
        40066858
      "belts": [
        ids...
      "stations": [
        ids...
      ]
    },
```

**Comment by ccp-zoetrope** [comment]
While it would make sense, currently `/universe/planets/{planet_id}` does not contain any sub lists of objects associated with it. However, you can see which moons are attached to which planets in the `/universe/system/{system_id}/` route. Asteroid belts should follow the same convention as moons currently do. Please follow this issue now: https://github.com/ccpgames/esi-issues/issues/813
