### ISSUE TITLE
Assets blueprints missing quantity

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#363]
I'm getting the following return from the Assets ESI endpoint:
```
  {
    "type_id": 1153,
    "location_id": 60014818,
    "location_type": "station",
    "item_id": 1665101352,
    "location_flag": "Hangar",
    "is_singleton": true
  },
```
TypeID: 1153 = Antimatter Charge L Blueprint (AKA It's a blueprint)
is_singleton: true = It's unpacked (AKA It can be either a blueprint copy or original)
But, quantity is not returned to identify if it's a copy or original

**Comment by kriberg** [comment]
Quantity is redundant when is_singleton is true, as it will be 1. Saves bytes in response

**Comment by GoldenGnu** [comment]
So if quantity is omitted for a blueprint, is it a blueprint original or a blueprint copy?

**Comment by GoldenGnu** [comment]
So, this issue need a little extra info:
``rawQuantity`` and ``quantity`` from the XML API, was merged in ESI and is now just ``quantity``
Therefor, for blueprints ESI should return -1 (BPO), -2 (BPC), > 1 (BPO)
It should never return 1 or omit quantity, because then you can not figure out if it's a BPO or a BPC.
At the very least, it should be defined if a blueprint is a BPO or a BPC if the ``quantity`` is omited or have the value 1

**Comment by GoldenGnu** [comment]
Adding additional info:
quantity can be 1, but, only if is_singleton is false (because, then it can only be a BPO), if it’s 1 and singleton is true it’s impossible to figure out of it’s a BPO or BPC

**Comment by gitAskur** [comment]
Wouldn't you rather be returned an explicit attribute such as 'is_original':[True, False] or 'type':['original', 'copy'] rather than having to derive that data from our whacky hackjobs?

**Comment by GoldenGnu** [comment]
Yes! ...and if you do this on the assets endpoints, at would be awesome if you did it on that Contract Items endpoints too :)

Relevant contracts issues:
https://github.com/ccpgames/esi-issues/issues/578
https://github.com/ccpgames/esi-issues/issues/407

**Comment by ddavaham** [comment]
Can we get `is_original : [true, false]`?

**Comment by ccp-zoetrope** [comment]
As mentioned in slack this can be closed because quantity is required in the v3 version of this route.
