### ISSUE TITLE
ESI ETag Caching

### ISSUE THREAD

**Issue by itshouldntdothis** [ccpgames/esi-issues#364]
ESI responses that are based on specific eve server builds and will not change during the lifetime of that build should recive a HTTP ETag cache header of that build version. This allows for If-None-Match requests along with 304 Not Modified responses in order to increase cache hit ratio.

An example endpoint would be the `/universe/systems/`.

This is all based on the `/status/`endpoint given its known capabilities an alternative option would be to generate the ETag based on the response allowing this method over most endpoints however not knowing about the backend I can't say if this is warrented.

**Comment by a-tal** [comment]
Etag support added to ESI 0.4.4

need to go through and mark individual endpoints yet

**Comment by a-tal** [comment]
weak etags have been added to esi-universe, based on server version. there's probably more routes yet that etags could be added to, but we can look at that in new issues
