### ISSUE TITLE
Expecting HTTP 404 but getting 500

### ISSUE THREAD

**Issue by vivace-io** [ccpgames/esi-issues#368]
Something I found accidentally and is only really a tiny problem...

When querying `/universe/systems/{system_id}` and placing the ID of a system that doesn't exist, it returns an HTTP 500 error instead of a 404.

[Example URL](https://esi.tech.ccp.is/latest/universe/systems/20000001/?datasource=tranquility&language=en-us) (I may or may not have accidentally used a Constellation's ID instead of the system's...)

**Comment by a-tal** [comment]
can confirm, needs a fix in the monolith.
