### ISSUE TITLE
Region expecting HTTP 404 receive 500

### ISSUE THREAD

**Issue by itshouldntdothis** [ccpgames/esi-issues#369]
URL : `https://esi.tech.ccp.is/latest/universe/regions/1/?datasource=tranquility&language=en-us`
```
{ "error": "Unhandled internal error encountered!" }
```

**Comment by a-tal** [comment]
this occurs with ids inside the regions range. needs a monolith fix

**Comment by aquarhead** [comment]
Merge into #307 since it also mentioned the problem of `/constellations`
