### ISSUE TITLE
Planet expecting HTTP 404 receive 500

### ISSUE THREAD

**Issue by itshouldntdothis** [ccpgames/esi-issues#370]
URL : `https://esi.tech.ccp.is/latest/universe/planets/1/?datasource=tranquility`
```
{
  "error": "Invalid 200 response: failed to coerce value 'None' into type integer (format: int32)",
  "response": {
    "position": {
      "y": 0,
      "x": 0,
      "z": 0
    },
    "type_id": 0,
    "system_id": null,
    "name": "EVE System",
    "planet_id": 1
  }
}
```

**Comment by a-tal** [comment]
i've submitted a patch for this, to find returns with null system_ids.... @aquarhead we might want to look at this in the monolith though, currently this endpoint returns data for celestials, not only planets

**Comment by aquarhead** [comment]
Move to internal issue tracking.
