### ISSUE TITLE
Validation error of Status example

### ISSUE THREAD

**Issue by kwekuadoboli** [ccpgames/esi-issues#372]
Hi,

This is a very minor bug/documentation issue.

While the spec is perfectly fine, there is a small error in the Status example. The value of `server_version` should be a string and not a number.

go-swagger validates the examples and threw me an error.

**Comment by a-tal** [comment]
it is?

`server_version (string): Running version as string`

it will be a number for published builds, but internally these versions can include characters, hence the string type.

**Comment by a-tal** [comment]
muh bad. reading fail. will fix the example

**Comment by a-tal** [comment]
this is fixed now, thanks!
