### ISSUE TITLE
/markets/{region_id}/orders/ endpoint gapping

### ISSUE THREAD

**Issue by deadlybulb** [ccpgames/esi-issues#374]
Snapshots from the orders endpoint, without type_id (don't know if this happens with type_id), occasionally omit orders that appear in later snapshots.  The missing orders often have issue dates several days or more in the past and should therefore appear in earlier snapshots.

This is easy to reproduce:

1. Grab consecutive order book snapshots in a region like 10000002 (separated by at least 5 minutes of course)
2. Look for orders in the second snapshot which did not appear in the first snapshot.
3. Check the issue date for the "new" orders.  If you find a "new" order with an issue date well before the first snapshot then you're seeing the problem.

You may have to repeat these steps a few times, but I've been able to reproduce consistently after collecting around five snapshots or so.

I can provide data and/or simple bash scripts to reproduce the issue as well.

**Comment by jamesremuscat** [comment]
I wonder if this might be related to https://github.com/ccpgames/esi-issues/issues/194 (marked as fixed, but could be a regression)?

**Comment by deadlybulb** [comment]
Not sure, feels slightly different.  To avoid pagination issues, my test code requests all the pages in parallel so I can pull a snapshot rather quickly.  Still not impossible to hit caching issues, but seems less likely.  I also see the problem in the data I archive, although that is through the CREST endpoint (need to update that).  Some samples I made in April show the same problem (still in CREST).

**Comment by a-tal** [comment]
it could be possible that while pulling all pages the underlying cache is refreshed, maybe ping me on slack sometime in the next week or two to chat more about this

**Comment by deadlybulb** [comment]
Will do.  I don't see an "a-tal" on slack, what handle should I ping?

**Comment by deadlybulb** [comment]
nm, a kind soul clued me in.  i'll ping you later (have a nice holiday)

**Comment by a-tal** [comment]
could add page count at the same time as adding cached on/expires in the monolith cache when we go into fix this.

seems a bunch of people would like that

**Comment by aquarhead** [comment]
So we've made that all pages will have a same cache expire time according to when that cache is built on monolith side. This should make it clear whether cache has changed or not, and as long as you're hitting the same cache across all pages you should not see any gap.

**Comment by deadlybulb** [comment]
This is live now?  Also, did you manage to add page count as well?

**Comment by aquarhead** [comment]
cache timer change is live as of now, page count discussion maybe continued here: https://github.com/ccpgames/esi-issues/issues/90 ?

**Comment by deadlybulb** [comment]
Ok, I'll give it a test.

@a-tal relying on you to resurrect #90 which seems to be stalled :)
