### ISSUE TITLE
Corporation endpoints (assets, wallet, industry and etc)

### ISSUE THREAD

**Issue by heggi** [ccpgames/esi-issues#376]
# Feature request

Corporation endpoints (assets, wallet, industry and other)

### Previous XML or CREST route

/corp/AccountBalance
/corp/AssetList
/corp/IndustryJobs
/corp/IndustryJobsHistory
/corp/MarketOrders
/corp/WalletJournal
/corp/WalletTransactions

**Comment by alexoulapour** [comment]
/corp/MemberMedals

**Comment by a-tal** [comment]
this issue is way too broad. pls open an issue per request
