### ISSUE TITLE
Add sun id to systems endpoint

### ISSUE THREAD

**Issue by itshouldntdothis** [ccpgames/esi-issues#384]
# Feature request
Add sun_type_id field
### Route
`/v2/universe/systems/{system_id}/`
### Use case
Allows for access to the sun infomation for a system without requiring the SDE
### Example returns
`/v2/universe/systems/30000003/`
```
{
  "application/json": {
    "sun_type_id": 3799
    "constellation_id": 20000001,
    "name": "Akpivem",
    "planets": [
      {
        "moons": [
          40000042
        ],
        "planet_id": 40000041
      },
      {
        "planet_id": 40000043
      }
    ],
    "position": {
      "x": -91174141133075340,
      "y": 43938227486247170,
      "z": -56482824383339900
    },
    "security_class": "B",
    "security_status": 0.8462923765182495,
    "stargates": [
      50000342
    ],
    "system_id": 30000003
  }
}
```

**Comment by tsuthers-ccpgames** [comment]
Following our standard pattern for celestial objects, I've added the star_id to /universe/systems/{system_id}/ (dev and latest), and once the supporting action is released on tranquility I'll deploy the /universe/stars/{star_id}/ route.
