### ISSUE TITLE
Feature request: faction warfare data

### ISSUE THREAD

**Issue by garemoko** [ccpgames/esi-issues#395]
# Feature request
I recently created a faction warfare dashboard. I then discovered that the xml api is going away in favor of ESI. Please replicate the faction warfare data including owning/occupying faction, victory points and faction kills. 

I would also love to have upgrade level data that is not currently available via the xml api. Ideally level per system rather than overall faction level which can be calculated from system data. I'm currently estimating Minmatar are at level 4 based on the number of systems held, for example, They are actually at level 3. 

### Route
?

### Authentication
Public

### Use case
https://garemoko.github.io/eve-fw-data/

### Example returns
http://games.chruker.dk/eve_online/test_eve_api.php?action=lookup&function=faction_warfare_general_statistics&myeve_key_id=

http://games.chruker.dk/eve_online/test_eve_api.php?action=lookup&function=faction_warfare_occupancy&myeve_key_id=

### Previous XML or CREST route
/eve/FacWarStats.xml.aspx 

/map/FacWarSystems.xml.aspx

**Comment by xtnm501** [comment]
Hi,

I have the same requirements for a corp-specific tool, and would love to see FacWarStats and FacWarSystems, as well as system-level upgrade data into ESI.

Many thanks

**Comment by ccp-zoetrope** [comment]
Half of this has been done, namely the porting of /eve/FacWarStats.xml.aspx. It has been split into two endpoints:
https://esi.tech.ccp.is/latest/fw/wars/
https://esi.tech.ccp.is/latest/fw/stats/

**Comment by ccp-zoetrope** [comment]
/map/FacWarSystems.xml.aspx has now been ported over to ESI:
https://esi.tech.ccp.is/latest/#!/Faction32Warfare/get_fw_systems

**Comment by garemoko** [comment]
Thanks @ccp-zoetrope. I'll work on migrating my app to use the new endpoints later in the month. Any chance of getting system upgrade level added to the data available?

**Comment by ccp-zoetrope** [comment]
Parity with existing XML API functionality is the main focus at this point, but please make a new issue asking for this additional feature so it doesn't get lost and can be added after full parity is reached :)

**Comment by garemoko** [comment]
#531

**Comment by garemoko** [comment]
@ccp-zoetrope evewarfare.com has now been completely migrated away from the xml api

**Comment by ccp-zoetrope** [comment]
🍾 🎊  The words "migrated away from the xml api" always makes me feel warm and fuzzy inside 😄
