### ISSUE TITLE
Request: include group_id in char/corp blueprints

### ISSUE THREAD

**Issue by schertt** [ccpgames/esi-issues#398]
Without group_ids, the process of sorting blueprints into larger groups (Frigate blueprint, Cruiser blueprint, etc.) becomes an exponential-time task. It would be super helpful to just have that information tied to the blueprint.

**Comment by aquarhead** [comment]
We don't repeat information "for convenience". Build your own type_id -> group/category/market group/whatever mapping by caching [these information](https://esi.tech.ccp.is/latest/#/Universe)
