### ISSUE TITLE
category_id in /universe/groups/{group_id} reponse is a float

### ISSUE THREAD

**Issue by mmlinford** [ccpgames/esi-issues#402]
# Inconsistency
### Routes
/universe/groups/{group_id}
### Description
The type of category_id in a /universe/groups/{group_id} is a float (e.g. 18.0 in https://esi.tech.ccp.is/latest/universe/groups/100/ ) whereas category_id (and other id's) are integers elsewhere (e.g., in the /universe/groups/ list)

**Comment by a-tal** [comment]
thanks for the report! this is making its way to prod now
