### ISSUE TITLE
Get current route

### ISSUE THREAD

**Issue by Zyles** [ccpgames/esi-issues#408]
An endpoint to get the current assigned route on your character.

**Comment by a-tal** [comment]
does this exist anywhere currently?

what is the use case?

why didn't you use the template? :(

**Comment by Regner** [comment]
It does not have an existing API and is only stored on the client currently. The AP info is not sent to the server at all. At least last I was around.

**Comment by ddouglas493** [comment]
https://github.com/ccpgames/esi-issues/issues/366

Feature as already been request. Please close

**Comment by a-tal** [comment]
good catch, thanks @ddouglas493
