### ISSUE TITLE
Fitting endpoint expects minimum description length of 1 for "post" of fitting

### ISSUE THREAD

**Issue by wtfrank** [ccpgames/esi-issues#409]
# Bug

In game fittings can have a 0 length description, and the get fitting endpoint is perfectly happy to serve 0 length descriptions. However when I try and create a new fitting with a 0 length description, it fails validation, because there is a minimum length of 1.

Failed validating u'minLength' in schema[u'properties'][u'description']:
    {u'description': u'description string',
     u'maxLength': 500,
     u'minLength': 1,
     u'title': u'post_characters_character_id_fittings_description',
     u'type': u'string'}

**Comment by a-tal** [comment]
thanks for the report, this is being built atm

**Comment by a-tal** [comment]
https://github.com/xxpizzaxx/esi-archive/commit/185b21d6426c31f66f65dcc3c95428a45a166814
