### ISSUE TITLE
Some calls to Universe.get_universe_structures_structure_id() fail with a 500 error

### ISSUE THREAD

**Issue by wtfrank** [ccpgames/esi-issues#41]
When querying some citadel ids via get_universe_structures_structure_id(), a 500 error is returned.

Some examples: 

1021308483995 https://esi.tech.ccp.is/latest/universe/structures/1021308483995/?datasource=tranquility (info about this citadel was recorded externally here https://stop.hammerti.me.uk/api/citadel/1021308483995)

1021088687524 https://esi.tech.ccp.is/latest/universe/structures/1021088687524/?datasource=tranquility

This issue is discussed by ccp bartender here https://tweetfleet.slack.com/archives/esi/p1478709286001509. 

ccp bartender: "ya, that's a bug. We don't remove the ACL's when a structure is destroyed, so you're being allowed to query the structure because you're on the ACL(or it was public), but then the query fails because it isn't actually located anywhere"

**Comment by wtfrank** [comment]
Sample python code that will trigger many examples of this very quickly:

#!/usr/bin/env python 

from bravado.client import SwaggerClient
import bravado.exception

client = SwaggerClient.from_url('https://esi.tech.ccp.is/latest/swagger.json')
strucs = client.Universe.get_universe_structures().result()

auth_token = "PASTE IN AN AUTH TOKEN (bearer token from the swagger docs)"

headers = {
    "Authorization": "Bearer %s" % auth_token,
    "User-Agent" : "issue reproduction",
    }
request_options = {'headers' : headers}

for sid in strucs:
  print(sid)
  try:
    print(client.Universe.get_universe_structures_structure_id(structure_id=sid, _request_options=request_options).result())
  except bravado.exception.HTTPInternalServerError as e:
    print e.response.status_code, e

**Comment by a-tal** [comment]
thanks for the bug report!

this was fixed with https://github.com/ccpgames/esi-universe/commit/5865bcc19fa7df5d5f514371f1be08addf18019e

**Comment by wtfrank** [comment]
Most citadels that previously returned 500 now seem to return 404 which makes more sense.

There are however still a few structures returning 500. e.g. 1021096761041, 1021061295426, 1021406297593
