### ISSUE TITLE
/characters/names/ should be converted to a POST request

### ISSUE THREAD

**Issue by skyride** [ccpgames/esi-issues#414]
# Feature request

### Route
/characters/names/

### Use case
At current, the request length limit on the ESI web servers limit this such that you can only get about 40-50 ids in there. There are a ton totally reasonable situations where you'd want to resolve significantly more IDs to names in greater bulk than that.

Converting this endpoint to a POST request would solve this issue.

**Comment by a-tal** [comment]
use https://esi.tech.ccp.is/latest/#!/Universe/post_universe_names instead

not sure there's any reason for the character names endpoint to still exist
