### ISSUE TITLE
GET /universe/factions/ solar_system_id & corporation_id should be optional instead of returning invalid data (0)

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#420]
# Bug
GET /universe/factions/
solar_system_id & corporation_id should be optional instead of returning invalid data (0)

### Request
make solar_system_id and corporation_id optional

### Response
[{ "faction_id" : 500021, "name" : "Unknown", "description" : "Unknown", "solar_system_id" : 0, "corporation_id" : 0, "size_factor" : 0, "station_count" : 0, "station_system_count" : 0, "is_unique" : false }, ...]

### Expected
[{ "faction_id" : 500021, "name" : "Unknown", "description" : "Unknown", "size_factor" : 0, "station_count" : 0, "station_system_count" : 0, "is_unique" : false }, ...]

**Comment by a-tal** [comment]
released a v2 of /universe/factions/ with optional `solar_system_id` and `corporation_id`
