### ISSUE TITLE
Add "active" to the skills endpoint.

### ISSUE THREAD

**Issue by frankysaken** [ccpgames/esi-issues#423]
# Feature request
Add an "active" or "active_skill_level" key to the skills returned by the skills endpoint to determine if a player can actually use said skill.

### Route
`/characters/{character_id}/skills/`

### Authentication
Yes, character same scope as right now.

### Use case
Currently we can't tell if a certain character is able to use certain ships due to the fact that an alpha character will still have omega skills in this endpoint this means they can't actually fly the doctrine.

I use skill checking (and as such doctrine checking) quite extensively for recruitment purposes and to allow FCs to determine if a new doctrine or fit is feasible.

This option was described as a solution by HakShak in November 2016 here: https://github.com/ccpgames/esi-issues/issues/95#issuecomment-263623670 but was never given a separate ticket.

### Example returns
`{
  "application/json": {
    "skills": [
      {
        "current_skill_level": 5,
        "active_skill_level": 0,
        "skill_id": 1,
        "skillpoints_in_skill": 10000
      }
    ],
    "total_sp": 10000
  }
}`

### Previous XML or CREST route
None.

**Comment by a-tal** [comment]
this is live in dev/v4
