### ISSUE TITLE
/characters/{character_id}/assets/ should return asset names

### ISSUE THREAD

**Issue by skyride** [ccpgames/esi-issues#429]
# Feature request

### Route
/characters/{character_id}/assets/

### Use case
Various assets, mainly ships, can have names set by the player. It'd be great if we could have this added to ESI. XML returned this info and it was quite useful.

### Proposed Output
```
[{"location_flag": "Hangar", "type_id": 17738, "name": "Yeahh boiii", "is_singleton": true, "item_id": 1022661991638, "location_id": 1021167234609, "location_type": "other"}]
```

**Comment by gitAskur** [comment]
That's not going to happen. A whole lot of assets do not have names, just a type, and adding the overhead of fetching names for everything just to service those few is something I am not willing to do.

The characters current ship name is however tracked, and can be provided as a part of the ship endpoint, but we will not be returning any asset names with generic asset calls.
