### ISSUE TITLE
Mailing list endpoint only returns IDs

### ISSUE THREAD

**Issue by GunfighterJ** [ccpgames/esi-issues#43]
https://esi.tech.ccp.is/latest/#!/Mail/get_characters_character_id_mail_lists only returns the mailing list ID. The model example shows a name field, the actual response is missing this.

**Comment by a-tal** [comment]
fix inc

**Comment by a-tal** [comment]
fixed with https://github.com/ccpgames/esi-mail/commit/af9fe418aef08e8d74624231147cdd5f39f425d7

thanks!
