### ISSUE TITLE
Conditional request support for remaining static data

### ISSUE THREAD

**Issue by Shirrath** [ccpgames/esi-issues#430]
This is a followup to #364.
Please add ETag/Last-Modified conditional request support to the following endpoints:

- [x] /markets/groups/
- [x] /markets/groups/{market_group_id}/

Other static data endpoints (that I don't use myself) which would benefit from conditional requests:

- [x] /corporations/npccorps/
- [x] /loyalty/stores/{corporation_id}/offers/
- [x] /dogma/attributes/
- [x] /dogma/attributes/{attribute_id}/
- [x] /dogma/effects/
- [x] /dogma/effects/{effect_id}/
- [x] /opportunities/groups/
- [x] /opportunities/groups/{group_id}/
- [x] /opportunities/tasks/
- [x] /opportunities/tasks/{task_id}/

**Comment by a-tal** [comment]
thanks!
