### ISSUE TITLE
get_universe_structures_structure_id returns 403 Forbidden during downtime even though I have docking access - indistinguishable from not having docking access

### ISSUE THREAD

**Issue by wtfrank** [ccpgames/esi-issues#431]
# Bug

During downtime I called get_universe_structures_structure_id() on structure 1022873465431 

The API returned 403 forbidden, with a json response of {u'error': u'Forbidden'} (which is exactly the same response that I get if I call the endpoint on a structure where I do not have docking access). 

After downtime the request succeeded with a 200 code.

The issue is that I was never disallowed docking access - and this downtime response is indistinguishable from the case where I am genuinely disallowed docking access. If I want to find out whether I have docking access I'm given incorrect information during downtime.

I know you guys have said in the past you've had trouble with downtime, I really feel like there should be a different code for "I can't find out whether you have docking access or not" and it should not be the same as "you do not have docking access".

### Request
get_universe_structures_structure_id
### Response
403  {u'error': u'Forbidden'} 
### Expected
502 {u'error': u'Cluster unavailable'} or something like that

**Comment by a-tal** [comment]
this behaviour has been modified. checks for docking access will raise a 502 if a result can't be determined
