### ISSUE TITLE
/characters{character_id}/assets Does not include active ship if undocked.

### ISSUE THREAD

**Issue by GeorgeDietrich** [ccpgames/esi-issues#433]
# Bug
The assets endpoint does not include the active ship if you are undocked.

### Request
Include the character's active ship in the asset list if undocked.

**Comment by ddouglas493** [comment]
Correct me if I am wrong, but does the ship show in assets when ur undocked? I wouldn't think so since it is in space.

**Comment by Blacksmoke16** [comment]
It does not.  However it should still should still show up in the endpoint as it is something you own.

**Comment by SpeedProg** [comment]
Don't think it should show up there.
I'd really like to give keys over my assets without allowing them to see what ship/fit I am currently in.

**Comment by Scrin** [comment]
I don't think it should show up there either. Assets don't include *everything* you own anyway, only items that are in an "idle"-ish state, ie. "not in use", such as sitting in some random hangar, but not items that are, for example, listed up for sale (in market or contracts, you still *own* the item as long as it haven't been sold) or items being used in industry currently, and an undocked ship is more in this category than "idling in a hangar", at least in my opinion

**Comment by Blacksmoke16** [comment]
Fair enough.  Maybe factor this into the /location/ship endpoint then?  

Basicly, I have a tracker that will update daily on my total wealth.  If i have a carrier or a jump freighter undocked there should be at least some way to get the ship and fit to include into the total wealth.  Active ship shouldn't just be some void of no information.

**Comment by Scrin** [comment]
That would be nice and useful also for fleet related utilities as you could then get info about the fit as well and get all kinds of cool things, fleet total DPS and stuff

**Comment by skyride** [comment]
The XML API has worked like this forever, and it has some genuinely useful applications. For example PL and NC both have an audit tool in their alliance services that automatically checks if someone has all the refits they are supposed to have when applying to the super/titan groups.

I could see the arguments against it if this were new, but the XML API has worked like this literally since it was added to the game and a lot of useful tools have been built on it.

**Comment by Blacksmoke16** [comment]
Yea, the XML API includes the active ship in its asset listing.  So either ESI needs to reflect that to reach parity, or moved to a different endpoint.  As of now, active ship is just a void of no information (besides the hull you are flying).

**Comment by tsuthers-ccpgames** [comment]
Active ship you are flying is definitely something that should be under a different endpoint and scope, it's much more sensitive information than your assets list. I'm tending towards adding the fittings and cargo to the /characters/{character_id}/ship/ endpoint, although I'm open to arguments for putting it on a different endpoint again if people feel that's worth doing.

Reviewing exactly how the assets endpoint handled your current ship is something that's been on my to-do list for a while, so I'm gonna say this is not so much a bug as an unintentional feature.

**Comment by Blacksmoke16** [comment]
@tsuthers-ccpgames Would there be a way to handle the situation where "I'm docked so it shows up on the assets endpoint and it is my active ship so it shows up in the ship endpoint"  i.e. Having the same ship/fit show up on both endpoints when docked.  

Would have to do some thinking on how to handle this, other wise values of things would get counted twice.

**Comment by skyride** [comment]
As long as the item id of the ship is provided in the new endpoint it'd be trivial to check that.

**Comment by Blacksmoke16** [comment]
Ah yea, just exclude the stuff that has the location_id of the active ship.  Smart.

**Comment by tsuthers-ccpgames** [comment]
You can currently use the item ID returned from the ship endpoint to determine the current ship contents if docked, and could certainly use that to de-dupe.

It's an interesting question. My initial thought would be "don't show the active ship in assets ever - simple", but that's maybe not so great for use cases where you're trying to tally assets. It does have the benefit of consistency though, the current system could see your net worth fluctuating a lot depending on whether you're docked or not. Strong opinions?

**Comment by CarbonAlabel** [comment]
I don't see a perfect solution here, as all the options allow for varying degrees of information leakage, so I'd go with consistency and never showing the active ship in the assets list.

My preference would be to have the contents of my active ship available over a separate endpoint, `/characters/{character_id}/ship/contents/`, either requiring a new scope or both of the current `read_ship_type` and `read_assets` scopes.

**Comment by skyride** [comment]
I can't really think of a situation in which you'd want to hide information about a ship you have in your hangar just because you happen to be sitting in it.

It also introduces a situation in which a ship could temporarily be invisible because it would be cached as hidden on assets, and not shown on an active ship endpoint with a shorter cache time.

If it's in your hangar in a station/structure, it should be in your assets.

**Comment by jowrjowr** [comment]
Could this please be decided one way or another?

Right now the _ship itself_ does not show up in assets, but everything inside the ship does. Which is kinda funky.

**Comment by GoldenGnu** [comment]
I want to voice my support for this issue.
All ships you own should always be considered assets, no matter if the ship is active or not, in space or not.
If you own it, it's an assets, I think it should be that simple.

**Comment by a-tal** [comment]
closing in favor of: https://github.com/ccpgames/esi-issues/issues/683

**Comment by warlof** [comment]
Bumping this issue since getting current ship into character asset response would help to keep asset tree consistent.

We actually have access to asset from active ship in response but not the ship itself which is the base location.

Could it be possible to queuing back that issue ?
