### ISSUE TITLE
[Feature Request]  /incursions/ should return infested system types

### ISSUE THREAD

**Issue by musicmage4114** [ccpgames/esi-issues#434]
Currently, the /incursions/ endpoint returns an array of infested system ids, as well as the id of the staging system. It would be useful for the `infested_solar_systems` field to instead return an array of arrays containing information about an incursion's layout.

Each sub-array can contain a `system_id` as currently returned, as well as an `infestation_type`, which can be one of: `staging` (or `scout`), `vanguard`, `assault`, or `headquarters`.

While the layout of incursions in a given constellation appears to be consistent across repeat invasions, users should not need to archive this information themselves.

Adding this information may also allow for the removal of the current `staging_solar_system_id` field, as that information would instead be conveyed in `infested_solar_systems`.

**Comment by a-tal** [comment]
to clarify, this is a request to change the array of ints `infested_solar_systems` into an array of objects with `solar_system_id` and `infestation_type` keys.

is `infestation_type` available in any other API currently?

**Comment by musicmage4114** [comment]
Currently, the only available information on the `infestation_type` (the name of which I just made up as an illustration, to be clear) is the `staging_solar_system_id`, which denotes the Incursion system that spawns scout sites.

**Comment by a-tal** [comment]
ok. this will need game design feedback then, there could be a reason why this is not exposed via API currently.

**Comment by musicmage4114** [comment]
I will add that the general pattern of Incursion [constellation layouts](https://wiki.eveuniversity.org/Constellation_layouts_for_Incursions) is fairly common knowledge, and as I mentioned before, the layout for a given constellation appears to be static between different incursion instances.

Thank you so much for the consideration!

**Comment by HakShak** [comment]
While we appreciate the thoroughness of the players, this information is for discovery. It is learned through experience and is very similar to the archives of EVE-Survival.org.

In the same way we won't add all mission information to the API, we won't be adding incursion site information.
