### ISSUE TITLE
Oauth flow for non browser app is unclear

### ISSUE THREAD

**Issue by Zyles** [ccpgames/esi-issues#435]
Unclear instructions:

http://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/nonbrowserapps.html

What is the flow for non browser apps, or browser based client side apps **without a client secret**.

1. Go to /oauth/authorize and get code
2. ???
3. Go to /oauth/token and get token

Since you should not store client secret in a desktop app I want to know what endpoint to hit with a POST or GET and which parameters to get the access token.

**Comment by fuzzysteve** [comment]
For when you aren't distributing the secret, you're using the oauth implicit flow. you do not recieve a refresh token for this. Right now, this limits you to 20 minutes of authenticated access.

https://www.fuzzwork.co.uk/market/viewer2/ has an example of how to use it.

**Comment by Robbilie** [comment]
apparently the name of this repo is unclear /s :D

implicit auth has the access_token as a parameter after the # in the url :)

**Comment by Zyles** [comment]
Thank you Steve that makes it a lot easier.

**Comment by Zyles** [comment]
Oh btw, you need to reauthenticate every 20 mins, or can you refresh it automatically without user input? Seems like a hassle for them otherwise.

**Comment by Zyles** [comment]
Ah sorry I see you need a refresh token to refresh.

That is pretty horrible if you play 5 hours and you need to login at the wrong moments constantly...
