### ISSUE TITLE
Increase oauth implicit flow expiration time

### ISSUE THREAD

**Issue by Zyles** [ccpgames/esi-issues#436]
# Feature request

Asking the user to login every 20 minutes with SSO is not a good user experience when they are playing.

I can see people stop using my app if they need to do this.

Minimum should be an hour. Possibly longer, or customizable.

Or I need to distribute the client secret in the app which is not desireable.

**Comment by SpeedProg** [comment]
taken from https://github.com/ccpgames/esi-issues/issues/435
>  Robbilie commented an hour ago
apparently the name of this repo is unclear /s :D

ESI and SSO are different things

**Comment by a-tal** [comment]
out of scope

**Comment by Zyles** [comment]
What github repo is in scope then?

**Comment by Robbilie** [comment]
as suggested by the repos name, esi.

**Comment by Zyles** [comment]
> as suggested by the repos name, esi.

Let me ask that again.

What Github repo is in scope for SSO? Where is the SSO repo? Where do I ask questions about SSO? Where do I submit feature requests and ask about problems regarding SSO?

**Comment by SpeedProg** [comment]
How about the eve forums? Maybe not every team has a feature request github repo for everything?

**Comment by rohimma** [comment]
slack -> devfleet

**Comment by Robbilie** [comment]
My comment wasn't sent before yours I guess, fugging mobile internet.

My comment was referring to the "out of scope" by snowy.

There is no repo for SSO issues, feel free to submit bug reports on the official site or try to find someone from the SSO team to talk to (hint: even though talking in #devfleet might increase the chance that your issue reaches the SSO team, there still is noone of that team anywhere to reach)
