### ISSUE TITLE
Remove the "response type indication" from Example Value in Swagger UI

### ISSUE THREAD

**Issue by Scrin** [ccpgames/esi-issues#438]
Currently the `Example Value` on the ESI page wraps the example response in a `{ "application/json": value }` to indicate that this is the example response for JSON content type. Since ESI only speaks JSON, this is kind of redundant. 

For example the https://esi.tech.ccp.is/latest/#!/Universe/get_universe_races Example Value is as follows:

```
{
  "application/json": [
    {
      "alliance_id": 500001,
      "description": "Founded on the tenets of patriotism and hard work...",
      "name": "Caldari",
      "race_id": 1
    }
  ]
}
```

This could be replaced with the following:

```
[
  {
    "alliance_id": 500001,
    "description": "Founded on the tenets of patriotism and hard work...",
    "name": "Caldari",
    "race_id": 1
  }
]
```

**Comment by a-tal** [comment]
will take a look at this when I update the swagger-ui

**Comment by a-tal** [comment]
took a look at upstream swagger-ui v3 again today. they need to fix https://github.com/swagger-api/swagger-ui/issues/2884 (ideally in a backwards compatible way) before we can consider updating.

**Comment by a-tal** [comment]
this is better handled in the v3 ui, which was just made the default
