### ISSUE TITLE
No Route from item type, to the market group containing it.

### ISSUE THREAD

**Issue by fuzzysteve** [ccpgames/esi-issues#440]
# Feature request

While the /universe/types/{type_id}/ endpoint returns the inventory group id, it doesn't return the market group id. This leads to the only way to find a market group for an item to be querying all of them until you find a match.

### Route

update for /universe/types/{type_id}/

### Authentication

Unauthenticated.

### Use case

Expanding a item list to include the other items within the market group. For example, from an item search, to market data.

**Comment by aquarhead** [comment]
The `/dev` or `/v3` version has this: https://esi.tech.ccp.is/dev/?datasource=tranquility#!/Universe/get_universe_types_type_id
