### ISSUE TITLE
Clarify description on jump and kill statistics

### ISSUE THREAD

**Issue by marekr** [ccpgames/esi-issues#444]
GET /universe/system_jumps/
>Get the number of ship, pod and NPC kills per solar system within the last hour, excluding wormhole space. Only systems with kills will be listed

Should be clarified as

>Get the number of ship, pod and NPC kills per solar system within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with kills will be listed

GET /universe/system_kills/
>Get the number of jumps in solar systems within the last hour, excluding wormhole space. Only systems with jumps will be listed

Should be clarified as

>Get the number of jumps in solar systems within the last hour ending at the timestamp of the Last-Modified header, excluding wormhole space. Only systems with jumps will be listed

Otherwise its funny. Last hour meaning what? Fixed points in time, 22:00-23:00. Last hour when you request? So adding that the cache be determined by Last-Modified clarifies the "last hour".

**Comment by a-tal** [comment]
thanks, updated

**Comment by aquarhead** [comment]
It is not statistic data "ending at the timestamp of the Last-Modified header". Actually, the monolith cache these statistics every few minutes. This endpoint just gathers all these data points "within last hour" (when you request it) and return an aggregation.

Changing it like this is simply wrong and misleading, it is not as "up to date" as the cache timer may suggest.

**Comment by marekr** [comment]
>It is not statistic data "ending at the timestamp of the Last-Modified header". Actually, the monolith cache these statistics every few minutes. This endpoint just gathers all these data points "within last hour" (when you request it) and return an aggregation.



So what you are saying is the endpoint should be providing the actual last hour start and end points from the monolith :P
