### ISSUE TITLE
GET /universe/system_kills/ counting npc_kills in ship_kills

### ISSUE THREAD

**Issue by marekr** [ccpgames/esi-issues#445]
# Bug
 /universe/system_kills/ is counting npc_kills towards ship_kills. Evident by seeing all the many systems where the numbers are all the same.

### Request
curl -i --compressed -X GET --header 'Accept: application/json' 'https://esi.tech.ccp.is/latest/universe/system_kills/?datasource=tranquility'

### Response

  {
    "system_id": 30000153,
    "ship_kills": 110,
    "npc_kills": 110,
    "pod_kills": 0
  },

### Expected

  {
    "system_id": 30000153,
    "ship_kills": 0,
    "npc_kills": 110,
    "pod_kills": 0
  },

**Comment by a-tal** [comment]
updated the description of v1 to reflect this.

created a v2 (under dev) that properly splits npc and ship kills
