### ISSUE TITLE
503 "Market access denied" over downtime to market that I have access to

### ISSUE THREAD

**Issue by wtfrank** [ccpgames/esi-issues#448]
# Bug

Over downtime, a call to get_markets_structures_structure_id() returned 503 Market access denied to ~10 structures that I was on the ACL for e.g. 1023286064533

The cluster not being available over downtime is not the same error as not having permissions to access a market, however the error message returned is identical.

Possibly related issue #399 

### Request
https://esi.tech.ccp.is/latest/#!/Market/get_markets_structures_structure_id

### Response
503 Market access denied

### Expected
an error like "cluster not available" (i.e. different to the error i get if i am not on the acl to access the market)

**Comment by aquarhead** [comment]
Merge into #399
