### ISSUE TITLE
Feature Request: Pilot titles

### ISSUE THREAD

**Issue by crazyjoery** [ccpgames/esi-issues#459]
# Feature request

Endpoint that returns character titles to allow titles to be used for specific access rights in corp managment tools.

### Route

GET /characters/{character_id}/titles/

### Authentication

OAuth2.0 using the SSO
potential scope : esi-characters.read_titles (just building on the current character endpoints)

### Use case

Pilot has title of srp-agent ingame, website grants access to srp management tool
Pilot has pos-fueler title, website grants access to pos statistics tool

### Example returns
~~~
{
  "application/json": [
    "Pos-fueler",
    "SRP-agent"
  ]
}
~~~

**Comment by crazyjoery** [comment]
correct yes

**Comment by a-tal** [comment]
per character:
https://esi.tech.ccp.is/ui/#/Character/get_characters_character_id_titles

or per corporation:
https://esi.tech.ccp.is/ui/#/Corporation/get_corporations_corporation_id_members_titles
