### ISSUE TITLE
/characters/{char_id}/contracts cache timer

### ISSUE THREAD

**Issue by Blacksmoke16** [ccpgames/esi-issues#462]
# Feature request

### Route
/characters/{char_id}/contracts

### Authentication
esi-contracts.read_character_contracts.v1

### Use case
Using this endpoint for a tool to monitor courier contracts that I have outstanding for a JS service i run.  The XML version of it has a cache timer of 15min, whereas this one is 60.  Is it doable to reduce cache timer for this ESI endpoint to at least 15min to match the old XML API?

**Comment by aquarhead** [comment]
Currently in ESI we usually have cache timers of 5 sec, 5 min or 1 hour. This would need some input from @gitAskur @a-tal and @tsuthers-ccpgames

**Comment by gitAskur** [comment]
The db doesn't mind if it gets request from the monolith or the XML API - no need to have a different cache timer between them from my perspective.

**Comment by Blacksmoke16** [comment]
I'd be okay with a 5min timer ;)

**Comment by gitAskur** [comment]
Now I begin my new life as a one armed programmer :(

**Comment by a-tal** [comment]
5m should be fine here

**Comment by gitAskur** [comment]
Eeeh, might not be as cool as you think over in monolith land. But we can try it.

**Comment by aquarhead** [comment]
Reduced to 5min
