### ISSUE TITLE
/search/ bug with dots

### ISSUE THREAD

**Issue by JakeChely** [ccpgames/esi-issues#464]
# Bug
There seem to be a bug with the /search/ request when doing a strict search for a name with a dot.
### Request
https://esi.tech.ccp.is/latest/search/?categories=corporation&datasource=tranquility&language=en-us&search=The%20Red.&strict=true
### Response
Way too many corporations having "red" in their names and no dot just after.
### Expected
{
  "corporation": [
    98422779
 ]
}
The only corporation named  "The Red."

**Comment by mullinger** [comment]
This is actually a duplicate of #211, and a general problem with the "strict" search

**Comment by aquarhead** [comment]
As @mullinger mentioned, merge to #211
