### ISSUE TITLE
Wallet Journey Providing failed to coerce value into type integer

### ISSUE THREAD

**Issue by SpareWheat** [ccpgames/esi-issues#466]
# Bug

### Request
	https://esi.tech.ccp.is/latest/characters/2112385200/wallets/journal/?datasource=tranquility

### Response
	{
	  "error": "Invalid 200 response: failed to coerce value '4641205018' into type integer (format: int32), failed to coerce value '4641123445' into type integer (format: int32), failed to coerce value '4641103872' into type integer (format: int32), failed to coerce value '4641101571' into type integer (format: int32), failed to coerce value '4641096785' into type integer (format: int32), failed to coerce value '4641069657' into type integer (format: int32), failed to coerce value '4641067285' into type integer (format: int32), failed to coerce value '4641066612' into type integer (format: int32), failed to coerce value '4641066482' into type integer (format: int32), failed to coerce value '4633324219' into type integer (format: int32), failed to coerce value '4633288562' into type integer (format: int32), failed to coerce value '4633287903' into type integer (format: int32), failed to coerce value '4628685809' into type integer (format: int32), failed to coerce value '4628617425' into type integer (format: int32), failed to coerce value '4628240197' into type integer (format: int32), failed to coerce value '4627850189' into type integer (format: int32), failed to coerce value '4627144111' into type integer (format: int32), failed to coerce value '4627144101' into type integer (format: int32), failed to coerce value '4626643764' into type integer (format: int32), failed to coerce value '4626643205' into type integer (format: int32), failed to coerce value '4626350347' into type integer (format: int32), failed to coerce value '4626287181' into type integer (format: int32), failed to coerce value '4626286273' into type integer (format: int32), failed to coerce value '4626284730' into type integer (format: int32), failed to coerce value '4626274592' into type integer (format: int32), failed to coerce value '4626261909' into type integer (format: int32), failed to coerce value '4626260552' into type integer (format: int32), failed to coerce value '4626259625' into type integer (format: int32), failed to coerce value '4626259586' into type integer (format: int32), failed to coerce value '4626248087' into type integer (format: int32), failed to coerce value '4626245787' into type integer (format: int32), failed to coerce value '4626245456' into type integer (format: int32), failed to coerce value '4626243218' into type integer (format: int32), failed to coerce value '4626242834' into type integer (format: int32), failed to coerce value '4626241483' into type integer (format: int32), failed to coerce value '4626239569' into type integer (format: int32), failed to coerce value '4626235418' into type integer (format: int32), failed to coerce value '4626233334' into type integer (format: int32), failed to coerce value '4626233070' into type integer (format: int32), failed to coerce value '4626232455' into type integer (format: int32), failed to coerce value '4626226815' into type integer (format: int32), failed to coerce value '4626225437' into type integer (format: int32), failed to coerce value '4626225329' into type integer (format: int32), failed to coerce value '4626225245' into type integer (format: int32), failed to coerce value '4626223761' into type integer (format: int32), failed to coerce value '4626223633' into type integer (format: int32), failed to coerce value '4625633936' into type integer (format: int32), failed to coerce value '4625559358' into type integer (format: int32), failed to coerce value '4625118522' into type integer (format: int32), failed to coerce value '4625035960' into type integer (format: int32), failed to coerce value '4625025126' into type integer (format: int32), failed to coerce value '4624996132' into type integer (format: int32), failed to coerce value '4624973643' into type integer (format: int32), failed to coerce value '4624968256' into type integer (format: int32), failed to coerce value '4624955979' into type integer (format: int32), failed to coerce value '4624948671' into type integer (format: int32), failed to coerce value '4624938243' into type integer (format: int32), failed to coerce value '4624937851' into type integer (format: int32), failed to coerce value '4624937321' into type integer (format: int32), failed to coerce value '4624931480' into type integer (format: int32), failed to coerce value '4624922471' into type integer (format: int32), failed to coerce value '4624910180' into type integer (format: int32), failed to coerce value '4624905401' into type integer (format: int32), failed to coerce value '4624902476' into type integer (format: int32), failed to coerce value '4624897232' into type integer (format: int32), failed to coerce value '4624890787' into type integer (format: int32), failed to coerce value '4624890566' into type integer (format: int32), failed to coerce value '4624890388' into type integer (format: int32), failed to coerce value '4624890204' into type integer (format: int32), failed to coerce value '4624890020' into type integer (format: int32), failed to coerce value '4624889329' into type integer (format: int32), failed to coerce value '4624878138' into type integer (format: int32), failed to coerce value '4624878137' into type integer (format: int32), failed to coerce value '4624877626' into type integer (format: int32), failed to coerce value '4624877400' into type integer (format: int32), failed to coerce value '4624877399' into type integer (format: int32), failed to coerce value '4624877397' into type integer (format: int32), failed to coerce value '4624876821' into type integer (format: int32), failed to coerce value '4624872943' into type integer (format: int32), failed to coerce value '4624872521' into type integer (format: int32), failed to coerce value '4624872401' into type integer (format: int32), failed to coerce value '4624871903' into type integer (format: int32), failed to coerce value '4624871629' into type integer (format: int32), failed to coerce value '4624871490' into type integer (format: int32), failed to coerce value '4624870891' into type integer (format: int32), failed to coerce value '4624870437' into type integer (format: int32), failed to coerce value '4624858561' into type integer (format: int32), failed to coerce value '4624858147' into type integer (format: int32), failed to coerce value '4624857642' into type integer (format: int32), failed to coerce value '4624857008' into type integer (format: int32), failed to coerce value '4624856664' into type integer (format: int32), failed to coerce value '4624856663' into type integer (format: int32), failed to coerce value '4624856090' into type integer (format: int32), failed to coerce value '4624323744' into type integer (format: int32), failed to coerce value '4622444181' into type integer (format: int32), failed to coerce value '4619798273' into type integer (format: int32)",

	"response": [
		{
	    	... (correct wallet Journal entry)
		}
	]

### Expected
	Wallet Journal with no errors in the response

**Comment by CarbonAlabel** [comment]
For reference, it is the `ref_id` property that's overflowing the defined int32 format. (I've already reported this error privately.)

**Comment by aquarhead** [comment]
We'll push out a better spec later, which will also fix this

**Comment by aquarhead** [comment]
This is fixed and we also made one with a better spec at https://esi.tech.ccp.is/latest/#!/Wallet/get_characters_character_id_wallet_journal, the `/wallets/` one will be deprecated soon
