### ISSUE TITLE
/characters/{character_id}/ not updated properly

### ISSUE THREAD

**Issue by prusya** [ccpgames/esi-issues#470]
# Bug
`alliance_id` takes hours to appear in Public information after character changed alliance.

### Request
https://esi.tech.ccp.is/latest/characters/92604044/?datasource=tranquility

### Response
{
  "corporation_id": 275493539,
  "birthday": "2012-11-10T21:38:40Z",
  "name": "Arnold Olympus",
  "gender": "male",
  "race_id": 1,
  "bloodline_id": 2,
  "description": "",
  "ancestry_id": 9,
  "security_status": 0.39473296156443005
}

### Expected
{
  "corporation_id": 275493539,
  "birthday": "2012-11-10T21:38:40Z",
  "name": "Arnold Olympus",
  "gender": "male",
  "race_id": 1,
  "bloodline_id": 2,
  "description": "",
  "ancestry_id": 9,
  "security_status": 0.39473296156443005,
  #### `"alliance_id": 99005518,`
}

**Comment by aquarhead** [comment]
ping @gitAskur

**Comment by gitAskur** [comment]
Character info just needs to not talk to the shitty config service character info cache for up to date affiliation info. I can't promise I'll get to this before vacation next week as the error rate limiting is much more important for live service health.

**Comment by gitAskur** [comment]
Nope, this is totally lost on some Backlog state. I'll at least put it somewhere I wont miss it and try and get it done today.

**Comment by gitAskur** [comment]
This should be going out during today's downtime - given that ESI is talking to the most recent version of the action.

@tsuthers-ccpgames @aquarhead Can either of you check what version of get_character_info is being used. V4 is the only one with properly up to date alliance and corporation info.

**Comment by aquarhead** [comment]
`/latest` is using v4 action so all good

**Comment by gitAskur** [comment]
Radical. I'll close this then after DT.

**Comment by gitAskur** [comment]
Deployed so errything should be peachy when TQ comes back online.
