### ISSUE TITLE
/markets/{region_id}/orders/ endpoint is ignoring order_type parameter

### ISSUE THREAD

**Issue by ivoronin** [ccpgames/esi-issues#475]
# Bug
/markets/{region_id}/orders/ endpoint is ignoring order_type parameter and always returns all orders

### Request
https://esi.tech.ccp.is/latest/markets/10000002/orders/?datasource=tranquility&order_type=buy&page=1

### Response
```json
[
  {
    "order_id": 911203054,
    "type_id": 967,
    "location_id": 60000274,
    "volume_total": 1,
    "volume_remain": 1,
    "min_volume": 1,
    "price": 50000,
    "is_buy_order": false,
    "duration": 365,
    "issued": "2017-06-06T11:05:50Z",
    "range": "region"
  },
...
]
```
### Expected
Only orders with "is_buy_order: True" to be present.

**Comment by aquarhead** [comment]
ping @a-tal

**Comment by a-tal** [comment]
the order_type parameter is defined as:

```json
{
  "default": "all",
  "description": "Filter buy/sell orders, return all orders by default. If you query without type_id, we always return both buy and sell orders.",
  "enum": [
    "buy",
    "sell",
    "all"
  ],
  "in": "query",
  "name": "order_type",
  "required": true,
  "type": "string"
},
```

this is working as intended

**Comment by aquarhead** [comment]
To make it more clear:

> If you query without `type_id`, we always return both buy and sell orders.

We combined several different endpoints in CREST to just this one mainly to avoid duplicating response schema in multiple endpoints, but maybe it's better to separate type_id specific buy/sell orders out, so we can make type_id a required parameter to avoid confusion.
