### ISSUE TITLE
Wallet Journal timing out

### ISSUE THREAD

**Issue by kftang** [ccpgames/esi-issues#476]
# Bug

### Request
    https://esi.tech.ccp.is/latest/characters/96919329/wallets/journal/?datasource=tranquility
### Response
    {
        "error": "No reply within 10 seconds"
    }
### Expected
Wallet Journal

**Comment by aquarhead** [comment]
Currently, there's a bug when handling bounty reward entries, will be fixed tomorrow, there will also be big refactors to wallet endpoints very soon, just keep your eyes on updates.

**Comment by aquarhead** [comment]
Merge into #493
