### ISSUE TITLE
Spec insonsistent for GET /characters/{character_id}/corporationhistory/

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#477]
# Inconsistency
Unliked the GET /corporations/{corporation_id}/alliancehistory/ endpoint, corporationhistory does not have the is_deleted field set to required.

### Routes
GET /characters/{character_id}/corporationhistory/

### Description
required is missing the is_deleted field

### Resolution
add "is_deleted" to the required array for said endpoint to be consistent with the other endpoint.

**Comment by a-tal** [comment]
these endpoints are consistent in /dev/.

we need to schedule a time to move them into /latest/ (and move current /latest/ into /legacy/), but this is already fixed.
