### ISSUE TITLE
Endpoint Request: /corporation/{corp_id}/assets/

### ISSUE THREAD

**Issue by airbone95** [ccpgames/esi-issues#478]
# Feature request
An Endpoint for Corporation-Assets

### Route
/corporation/{corp_id}/assets/

### Use case
Automated stocktaking of corporation property

### Example returns
similar to /characters/{character_id}/assets/
just for the Stuff in the Corporation Hangars

### Previous XML or CREST route
https://api.eveonline.com/corp/AssetList.xml.aspx

**Comment by gitAskur** [comment]
Please see https://github.com/ccpgames/esi-issues/issues/26
