### ISSUE TITLE
Automated login to ESI for dedicated donation character 

### ISSUE THREAD

**Issue by pennyarcade** [ccpgames/esi-issues#479]
# Feature request

### Route 
N/A

### Authentication
Anything that is completely automated 
e.g. OAuth, API Token etc.

### Use case
I plan to collect ISK donations towards offsetting development time and cost on my own eve app. To that end I have set up a dedicated alt character to recieve donations.
I want to now poll the api completely automatically in a cron job to fetch wallet transactions of that character once every few hours. This data is to be displayed in the app for transparency and encouragement. I plan Kickstarter style goals to encourage donations.
This requires a completely automated authentication for that character. At the moment this is possible via the old XML API and API token. I'd love to see any automatable authentication process for the new ESI. I would be ok with any process that does not involve human interaction such as oauth, api key or similar.

I'd like to avoid scripting the current SSO process.

### Example returns
n/a

### Previous XML or CREST route
API token authentication

**Comment by pennyarcade** [comment]
Loosely related to Issue #169

**Comment by pennyarcade** [comment]
Possibly related Issue #303

**Comment by fuzzysteve** [comment]
Once you've logged in with a scope once, you have a refresh token (given to you at the same time as the access token)

That refresh token can be used to get access tokens at will, thus automating the login.

**Comment by fuzzysteve** [comment]
https://github.com/fuzzysteve/FuzzMarket/blob/master/scripts/citadelgetter.py is an example

**Comment by pennyarcade** [comment]
Thanks @fuzzysteve,

that helped to get started. I'll try it and report back.
Sadly your code is very hard to read and doesn't follow the common coding standards. Writing better structured and readable code make your scripts easier to maintain and understand for others and for yourself. That may not matter with such small scripts but is a good practice anyway. :-)

**Comment by Robbilie** [comment]
> creates issue for something that is already possible the way it should be done with oauth2
> gets help
> complains about coding style

**Comment by pennyarcade** [comment]
Sorry for maybe getting the wrong tone of voice. I am very grateful for the help. In return I'm just trying to help @fuzzysteve to be a better coder. I will include my own example in the issue to help others with the same question.

I would suggest to CCP to add a short paragraph to the SSO section of the documentation along the lines of "If you are coding a recurring automated task please use the refresh token mechanism. Do the OAuth dance once by hand and you can use this indefinately." .
That would have prevented me posing this issue in the first place.

**Comment by Robbilie** [comment]
http://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/implicitflow.html#server-side-applications

**Comment by fuzzysteve** [comment]
eh, it was a cheap and nasty script to do something :D 

tbh, it was probably a bad example, as it doesn't do the oauth handling itself, but does it in a library.

https://github.com/fuzzysteve/FuzzMarket/blob/master/scripts/aggloader-esi.py is a little better for that. At around line 200 you have the code which handles the refresh token. It's using requests, but that's just to make the http code nicer.

To get a refresh token, without writing an app take a look at https://www.fuzzwork.co.uk/2017/03/14/using-esi-google-sheets/

**Comment by pennyarcade** [comment]
thanks again... @fuzzysteve thats great coding in the second example. :-) 
I couldn't get the Oauth2Session lib refresh to work. Will test the requests refresh now to update the token and start the OAuth session again with the token already in place.

**Comment by pennyarcade** [comment]
This issue can be closed now I think. Thanks for all the help again.

**Comment by pennyarcade** [comment]
Here is my working solution based on @fuzzysteve's example for future reference. 
It is much shorter and just refreshes the token, does a single ESI request and dumps the result to stdout.

https://gist.github.com/pennyarcade/bf032d940268a81183aa7d5b5d241325
