### ISSUE TITLE
esi-corporations: date_founded similar to the one alliances have

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#48]
apparently not in the XML corporationsheet, not even talking about the CREST corp endpoint but would probably be handy to show on an information sheet about a corporation

**Comment by gitAskur** [comment]
Corporation create date was a bit wonky on the eve side as it only existed for corps created after a certain date. The data has been fixed up and the value provided in the get_corporation_info-v1 (minor 0).

**Comment by Regner** [comment]
Is that the monolith handler @gitAskur ? So ESI work still to be done?

**Comment by gitAskur** [comment]
Yup yup @Regner , my default setting is "monolith handler". I try to specify it all the time but "trying" only goes so far!

**Comment by ccpStuart** [comment]
Deployed with corp info v3
