### ISSUE TITLE
[Feature] Shorter Scope Names 

### ISSUE THREAD

**Issue by mglinski** [ccpgames/esi-issues#483]
There is a tendency to use very verbose scope names for ESI routes. There is room for saving some characters in scope names while still being 100% obvious to their intent.

For example, scopes like:

```
esi-assets.read_assets.v1
esi-bookmarks.read_character_bookmarks.v1
```

Can easily be shortened while still maintaining their descriptive nature:

```
esi-assets.read.v1
esi-bookmarks.read_character.v1
```

With the URI length limits enforced by ISS, keeping scope names short but accurate will likely be more and more important as more discrete scopes are created.

This also brings up that the ESI scope names seem to be a concatenation of multiple domains of thought and organization.

Why are there `character` scopes in the `esi-bookmarks.*` namespace while also having various scopes with a `esi-character.*` namespace?

**Comment by a-tal** [comment]
won't fix.

changing this would break every app in existence. there is no way to document `or` scopes in swagger.

we're looking into unfucking IIS here, to bring it up to current year standards in regards to url limits. currently that work is in staging, but I can't comment as to when it will make it to TQ... Soon™
