### ISSUE TITLE
Incomplete implementation of /latest/status

### ISSUE THREAD

**Issue by BaldvinTh** [ccpgames/esi-issues#488]
# Bug

The server status endpoint is incomplete, and is missing the status of the service itself. As in:

- Online
- Offline
- VIP

## Crest equivalent

https://crest-tq.eveonline.com/
 - "serviceStatus": "online"

### Request
GET https://esi.tech.ccp.is/latest/status/?datasource=tranquility

### Response
```
{
  "start_time": "2017-07-10T11:03:26Z",
  "players": 123456,
  "server_version": "123456"
}
```

### Expected
```
{
  "start_time": "2017-07-10T11:03:26Z",
  "players": 123456,
  "server_version": "123456",
  "status": "online"
}
```

**Comment by a-tal** [comment]
You can tell if the server is in VIP if the optional boolean `vip` is sent. You'll receive a 502 if the datasource was unable to respond, hence why there isn't an "online/offline" boolean or whatnot.

the `"serviceStatus": "online"` return by CREST was/is redundant information, ESI tries to avoid redundancy where possible.
