### ISSUE TITLE
Limit transactions amount

### ISSUE THREAD

**Issue by Ionaru** [ccpgames/esi-issues#489]
# Feature request

https://esi.tech.ccp.is/v1/characters/{character_id}/wallet/transactions/

The transactions API currently returns as many records as it can, sometimes being in the thousands.
It would be nice to have an optional limit added to the parameters.

**Comment by aquarhead** [comment]
There is an upper limit of 2500 transactions it can return if you look at the spec.

For now, we don't provide ways to vary page size.

**Comment by Ionaru** [comment]
I don't see that mentioned anywhere on https://esi.tech.ccp.is/latest/#!/Wallet/get_characters_character_id_wallet_transactions, it's only mentioned in the [swagger.json](https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility) source. Maybe something to look into?

But besides that: 2500 records would be almost 100kb in transaction data, which I think is a lot of data to request unless absolutely necessary. Especially when developing for mobile, you'd want to paginate and get more data only if the user chooses to.

**Comment by polarina** [comment]
@Ionaru allowing arbitrary page sizes makes it trivial to bypass any HTTP caching going on in ESI.
