### ISSUE TITLE
GET /characters/{character_id}/online/ endpoint request

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#49]
should return the online state of a character, out of game online lists or for ceos to see how many players are logged in this would be a nice thing

**Comment by Regner** [comment]
Generally speaking it will probably help CCP greatly when requesting endpoints if you can include a sample of how it should look and a use case for the endpoint. Helps them make sure they understand exactly what you want and balance priorities.

**Comment by Robbilie** [comment]
maybe a good idea although i think the endpoints should be quite self-explaining :3

**Comment by Regner** [comment]
"out of game online lists or for ceos to see how many players are logged in this would be a nice thing"

Maybe it would just be better to have a corporation API then that returns all online members?

**Comment by Robbilie** [comment]
yes that would be the next thing to ask for :D
i was mostly pointing out this endpoint because i thought CREST had the location endpoint return an empty response when not logged in, so basically feature parity.
the online endpoint could also get a higher cache time than the location one so you would poll the online one until online and then use the location one

**Comment by polarina** [comment]
I totally forgot to write this endpoint while I was still at CCP while doing the backend work for the current ship and location. :(

The needed backend work is done, so for CCP: you can use the `get_character_ship-v1` monolith handler as a template, and change the call to `GetCharacterShip` to `IsCharacterOnline` on the `characterSurveillance` service moniker. Adjust return data in the handler accordingly.

**Comment by w9jds** [comment]
A list would be nice, but the single user would also be helpful for tools like Wormhole mappers. Currently when you get location, if the user is offline you get an empty object, so instead of that it would be good to be able to check if the user is online before going and using their location/ship info.

**Comment by tsuthers-ccpgames** [comment]
So there are two online status cases:
Up to the (5) second accuracy online status will have to be a per-user endpoint that requires a specific auth from the user.

There is also the corporation online status, which would be equivalent to what's currently exposed to line members in the corporation membership window in game. That'll be on a longer time, probably 5-10 minutes, and would need an auth from someone in the corp you are querying.

**Comment by sankage** [comment]
Any update on this one? This is kinda a key feature needed for mapping software.

**Comment by PrometheusSatyen** [comment]
Any updates? Really important feature for the TVP incursion community.

**Comment by SpeedProg** [comment]
I generally don't think exposing this to an api is good idea. Sine it will allow making very accurate behavior profiles of players, especially if you combine it with the location endpoint.
So Idk about this. As nice as it would be for some circumstances, I am pretty sure people would be able to live without it.
But there is no way for a player to notice that a 3rd party app is tracking at what times they play and (and eventually where they go) out of scope of their usage.

Now people could say, well there is the corp last online data and stuff but that is by fare not this accurate.
Because MemberTracking api was first of only request able by corporation and 2nd it had like what 5h cache time? And then it showed only the last login and logoff.

**Comment by fuzzysteve** [comment]
Thing is, if you have the location endpoint, then you kind of need this one. So you're not tracking the position of an offline person, 24 hours a day.

**Comment by SpeedProg** [comment]
> It is one people have to approve. They don't need to give it to anything.
Thing is, that is easier said then done.

- Big alliances are probably gonna request you to give it for all your toons or leave.
- Things like the tvp waitlist are probably gonna force you to give it or not join their fleets

Technically you could go to the support page and revoke the token every time after leaving stuff like that
This is taking way to long, so nearly no one is ever gonna do it

An at least decent solution would be to the later would be, having a selection on the grant screen to make "refresh" tokens that have an expire of e.g. 1-72h or sth. like that.
This wouldn't solve the alliance thing through which is think is just stupid.

Sure this endpoint would make some problems easier.

But your example:

> Thing is, if you have the location endpoint, then you kind of need this one. So you're not tracking the position of an offline person, 24 hours a day.

Could instead be solved by only tracking them as long as they have your website open and your website just sends a ping back to your server every 10min or so telling it, that the person is still there.
Well some people keep sites just open for no reason and that would hinder this solution a bit.

**Comment by sankage** [comment]
This functionality was part of the [CREST API's location endpoint](https://eveonline-third-party-documentation.readthedocs.io/en/latest/crest/character/char_location.html). We are just looking for feature parity.

**Comment by w9jds** [comment]
haha you are making a huge deal about this existing, when it already does... Currently when you hit the CREST API location endpoint, if the user isn't online then it returns an empty object `{}` So your whole argument of 'this will be abused' is kind of moot.

If the user gives their Scope access then it is a valid way to get information. Shortening a refresh tokens life doesn't do anything, the client can just go and request a new refresh token until the user removes access to the application... This is how oAuth works, for everything.

Doing client side isn't even a solution...

**Comment by Robbilie** [comment]
I want the online endpoint but @w9jds you messed something up there. The thing the user removes is the refresh_token, you are thinking of access_tokens which the application can request over and over again when it has a refresh_token.

**Comment by w9jds** [comment]
@Robbilie Should be able to re-verify with the API since you already have consent from the user for another refresh token, unless the verification code expires. Which unless I'm mistaken does.

**Comment by Robbilie** [comment]
I have no idea what you are talking about but per user consent the application can get 0 or 1 refresh_tokens depending on scopes, ever. An application can only get a new refresh_token if the user logs into the app again. And yes, the code should expire.

**Comment by a-tal** [comment]
v1 of GET /characters/{character_id}/online/ is now available, v2 will be coming Soon™ which will change the return from a simple boolean to an object also including datetimes for last login and logout.

see #424 for v2
