### ISSUE TITLE
Better scope titles in authorization window

### ISSUE THREAD

**Issue by Ionaru** [ccpgames/esi-issues#490]
![screenshot_20170711_154502](https://user-images.githubusercontent.com/3472373/28071433-3211ceda-6650-11e7-9b18-e4612b908951.png)

Scopes are currently listed with_underscore_syntax, but it would be much neater and cleared for the user if they were listed as short normal sentences (ignoring the XML scopes):

- Read character location
- Read character ship type
- Read character wallet balance
- Read character market orders
- Read character skills
- Read character skill queue

**Comment by Robbilie** [comment]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

**Comment by Ionaru** [comment]
They are ESI scopes, are they not?

**Comment by SpeedProg** [comment]
they are oauth scopes, esi just uses them I'd say. Also the representation on the SSO login window is 100% oauth.

**Comment by Robbilie** [comment]
as speedprog said, they are oauth2 scopes which is solely related to sso
according to the spec, spaces are not allowed in the scopes and therefore displaying them with spaces would also only be done on the sso end
https://tools.ietf.org/html/rfc6749#page-72

**Comment by aquarhead** [comment]
This is part of the SSO OAuth flow, so not something we control, and no point in discussing here as the SSO team is not involved anyway.

To make things easier you can report issues of anything under https://esi.tech.ccp.is/ and generally nothing more than it.

The scopes are "created" (or rather named) and used by us, but nothing beyond that: not managed by us, not "stored" with ESI etc..

**Comment by Ionaru** [comment]
Any idea where I should be communicating this instead of here? https://community.eveonline.com/support/submit-bug-report maybe?

**Comment by a-tal** [comment]
if you had a bug with sso, yeah that'd be the place. this however is not a bug, and will not be fixed (scopes are space separated already, hence disallowed in names)

also any attempted fix would break every app in existence

**Comment by Ionaru** [comment]
I'm not saying the scopes should have a different name internally, just the way they are presented on the authorization page.
