### ISSUE TITLE
Wallet journal/transactions

### ISSUE THREAD

**Issue by Ekzilit** [ccpgames/esi-issues#493]
For example i want to get my journal records from today. But i have a problem i don't know "transaction_id" from today. Not first, not last, i don't know any of  "transaction_id". Only i know that it is int type. If i don't place "transaction_id" then i have got 
{
  "error": "No reply within 10 seconds"
}
May be i something missed? Where i should get "transaction_id"?
Logically it is look like that use dates of transaction is best. I send one date and get some limit records to this date. Or i send two dates and get records between this two days, and not more than limit of records for one response.

**Comment by SpeedProg** [comment]
Not 100% sure what you are talking about, especially since I can't find a parameter "transaction_id" in /characters/{character_id}/wallet/transactions/  or /characters/{character_id}/wallet/journal/
But /characters/{character_id}/wallet/transactions/ if you don't send a "from_id" you get the latest transactions, then you can crawl backwards by providing the id of the oldest transaction you got with your last call as "from_id". Till you got all that you want, or there are none anymore.
And that error probably just means that the api is funky

**Comment by deadlybulb** [comment]
This error happens from time to time when the ESI is overloaded.  I see it all the time on the market data endpoints.  It's not specific to any particular endpoint as far as I know.

**Comment by Ekzilit** [comment]
I mixed up "transaction_id" with "ref_id" that i should put into "from_id", but this does not matter, because i have got this error for three different characters. 
And i picked up "from_id" with what i get success result,  but transaction was from the middle of all transactions, and when i  crawl up by increasing id, and at one of them, and at all bigger than that one i have got again this error. Because of that i think that data is too big to calculate it in 10 sec. 
sorry for my english... i hope you understood what i mean

**Comment by GoldenGnu** [comment]
I have not been able to get journals since it was released, translations works though. Issue #476 state that there is a bug in the journal endpoint. It shoud have been fixed 15 days ago, but, the issue is still open and I'm still getting the error.

**Comment by Ekzilit** [comment]
Yes, transaction works for me too, error appears only at journal

**Comment by aquarhead** [comment]
There is a fix for the issue I mentioned in #476, but after that the 2 endpoints still fail "randomly" and we're not entirely sure why atm, will update here if we figure it out and fix it.

**Comment by GoldenGnu** [comment]
I'm not 100% sure what you mean by "randomly "...

So, I will clarify...
It does not fail randomly for me, it literately never works for me.
I have not been able to make a single successful request to the endpoint with any of my chars, yet.

**Comment by kftang** [comment]
I have had the same experience as @GoldenGnu

**Comment by porowns** [comment]
For some characters, /characters/character_id/wallet/journal works for me, but for others I get either a NoneType returned, or if I'm lucky, {'error': 'Unhandled internal error encountered!'}.

**Comment by krojew** [comment]
I can confirm both journal and transactions still have this "10 seconds" problem.

**Comment by gitAskur** [comment]
Looking at this first thing tomorrow morning.

**Comment by gitAskur** [comment]
Easy fix, expect it out on Thursday.

**Comment by gitAskur** [comment]
Also fixed for character transactions after @aquarhead pointed out that this was a two sided issue!
