### ISSUE TITLE
Inconsistent Header for /markets/{region_id}/orders

### ISSUE THREAD

**Issue by clstb** [ccpgames/esi-issues#495]
# Inconsistency

### Routes
/markets/{region_id}/orders

didnt test any other routes yet

### Description
When using non standard regions for ex. wormhole ones

{
  "region_id": 11000026,
  "name": "E-R00026",
  "constellations": [
    21000256,
    21000257,
    21000258,
    21000259,
    21000260,
    21000261,
    21000262,
    21000263,
    21000264
  ]
}

the response header is inconsistent.

Im not an expert but shouldnt the header be consistent regardless of what parameters are passed? Here are two response headers as example.

/markets/11000026/orders
{
  "date": "Fri, 21 Jul 2017 18:46:28 GMT",
  "via": "1.1 google",
  "status": "200",
  "strict-transport-security": "max-age=31536000",
  "alt-svc": "clear",
  "content-length": "2",
  "last-modified": "Fri, 21 Jul 2017 18:43:58 GMT",
  "access-control-max-age": "600",
  "access-control-allow-methods": "GET,OPTIONS",
  "content-type": "application/json",
  "access-control-allow-origin": "*",
  "access-control-expose-headers": "Content-Type,Warning",
  "cache-control": "public",
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Content-Type,Authorization,X-User-Agent",
  "expires": "Fri, 21 Jul 2017 18:48:58 GMT"
}

/markets/10000002/orders
{
  "date": "Fri, 21 Jul 2017 18:45:53 GMT",
  "content-encoding": "gzip",
  "status": "200",
  "access-control-max-age": "600",
  "strict-transport-security": "max-age=31536000",
  "alt-svc": "clear",
  "via": "1.1 google",
  "last-modified": "Fri, 21 Jul 2017 18:40:39 GMT",
  "x-pages": "26",
  "vary": "Accept-Encoding",
  "access-control-allow-methods": "GET,OPTIONS",
  "content-type": "application/json",
  "access-control-allow-origin": "*",
  "access-control-expose-headers": "Content-Type,Warning",
  "cache-control": "public",
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Content-Type,Authorization,X-User-Agent",
  "expires": "Fri, 21 Jul 2017 18:45:39 GMT"
}

### Resolution
Add missing fields??

Edit:
I noticed the problem as my app threw an error because "x-pages" was not defined at all.

**Comment by a-tal** [comment]
`"content-length": "2"` explains why `vary` and `content-encoding` are absent..

`x-pages` likely isn't returned because there was no data (length 2 is probably `[]`) and thus no pages

this needs a monolith patch to properly fix

**Comment by clstb** [comment]
That makes sense. I dont know if it is worth the effort but its something to look into I think.

**Comment by a-tal** [comment]
pushed a patch to esi-lib to enforce a minimum pages of 1. monolith was returning pages "0" with no results, which was causing the header to not be sent.

currently going through CI, staging soon

**Comment by aquarhead** [comment]
please leave this open until it's also fixed on monolith side

**Comment by a-tal** [comment]
this is resolved in ESI now:

```bash
$ curl -i 'https://esi.tech.ccp.is/latest/markets/11000026/orders/'
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,X-User-Agent
Access-Control-Allow-Methods: GET,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type,Warning
Access-Control-Max-Age: 600
Cache-Control: public
Content-Length: 2
Content-Type: application/json
Date: Fri, 04 Aug 2017 16:26:24 GMT
Expires: Fri, 04 Aug 2017 16:27:46 GMT
Last-Modified: Fri, 04 Aug 2017 16:22:46 GMT
Strict-Transport-Security: max-age=31536000
X-Pages: 1
Via: 1.1 google
Alt-Svc: clear

[]
```
