### ISSUE TITLE
/characters/{character_id}/orders/ cache timer

### ISSUE THREAD

**Issue by Blacksmoke16** [ccpgames/esi-issues#497]
# Feature request

### Route
/characters/{character_id}/orders/

### Authentication
esi-markets.read_character_orders.v1

### Use case
Could we get the cache timer for this endpoint lowered to 5min to match the /markets/structures/{structure_id}/ endpoint?  Having up to date, near real time information about your market orders could be useful.

**Comment by aquarhead** [comment]
Duplicate of #468
