### ISSUE TITLE
Add itemName data to assets lookup

### ISSUE THREAD

**Issue by nicebits** [ccpgames/esi-issues#498]
# Feature request

### Route
/characters/{character_id}/assets/
### Authentication
SSO
### Use case
Add ability to look up itemName data similarly to how it's given by the /char/Locations.xml.aspx endpoint in the XML API.
### Example returns
get_characters_character_id_assets_200_ok {
is_singleton (boolean): is_singleton boolean ,
item_id (integer): item_id integer ,
**item_name (string): item_name string**,
location_flag (string): location_flag string = ['AutoFit', ... (trimmed) ... , 'Wardrobe'],
location_id (integer): location_id integer ,
location_type (string): location_type string = ['station', 'solar_system', 'other'],
quantity (integer, optional): quantity integer ,
type_id (integer): type_id integer
}

**Comment by aquarhead** [comment]
Merge into #213 as an option, check comments there
