### ISSUE TITLE
/markets/groups/{group_id}/ Types array always empty

### ISSUE THREAD

**Issue by Blacksmoke16** [ccpgames/esi-issues#499]
# Bug

### Request
/markets/groups/{group_id}/
### Response
>{
"market_group_id": 157,
"name": "Drones",
"description": "Drones are semi-autonomous robotic devices used for military and industrial purposes throughout space.",
"types": []
}

### Expected
>{
"market_group_id": 157,
"name": "Drones",
"description": "Drones are semi-autonomous robotic devices used for military and industrial purposes throughout space.",
"types": `Array of typeIDs in this group`
}

**Comment by aquarhead** [comment]
The endpoint only lists immediate child types, [example](https://esi.tech.ccp.is/latest/markets/groups/1676/?datasource=tranquility&language=en-us)

Also by using `parent_group_id` you can build a hierarchy of market groups the same as in game client's Regional Market window.
