### ISSUE TITLE
Odd response when using /v1/characters/{character_id}/mail/, labels required or not?

### ISSUE THREAD

**Issue by binarygod** [ccpgames/esi-issues#506]
# Bug
At 01:46 Eve Time I attempted to use the "/v1/characters/{character_id}/mail/" endpoint where CharacterID is 95914159.  ESI UI only shows that 'character_id' is required, if no 'labels' are provided then the response is as listed below.

A successful response is returned when I add a 'labels' value of 0 for my Inbox.

### Request
https://esi.tech.ccp.is/latest/characters/95914159/mail/?datasource=tranquility

### Response
Response Code: 400
Response Body: {"error": "Owner type not found!"}

### Expected
List of Mail headers

**Comment by aquarhead** [comment]
Might be because of some character/corp/alliance etc.. is deleted, tagging @gitAskur for now

**Comment by gitAskur** [comment]
get_character_inbox-v2 does not require label to be supplied, in the case of None it sjpiæ return all mails despite labels.

**Comment by gitAskur** [comment]
Should work fine with just supplying a characterID and no label or mailID for pagination.

**Comment by gitAskur** [comment]
Something is setting invalid ownerIDs (ID 0) in corp/alliance ID key, which in turn resolves to owner system which is not an owner that should be sending any emails to anybody. Probably ESI sent mail that is causing issues for ESI inbox fetches.

**Comment by gitAskur** [comment]
Validation of owners is unsafe and only checks that ownerID if it is any value other than None or 0... so 0 escapes checks. Adding check although I do not know how these values are being supplied and might very well start throwing 520s back to ESI if it is allowing these calls through.

**Comment by gitAskur** [comment]
@aquarhead @a-tal @tsuthers-ccpgames @ccp-zoetrope - This fix might percolate the issue up to the ESI layer. See comment above.

**Comment by gitAskur** [comment]
Deployment requested tomorrows downtime, 29th of August 2017.

**Comment by gitAskur** [comment]
This is not being deployed today as I just forgot to integrate it to release and thus this was not a part of the build deployed.

Sorry, vacation brain.
