### ISSUE TITLE
/universe/names endpoint broken and not in spec

### ISSUE THREAD

**Issue by Ionaru** [ccpgames/esi-issues#511]
The '/universe/names' endpoint does not show up in the spec and the endpoint does not function anymore.

**Comment by rohimma** [comment]
there was a message about it on tweetfleet:

![image](https://user-images.githubusercontent.com/2255417/29411343-bdd4b164-8354-11e7-9a6f-9439de9f82f9.png)

**Comment by tsuthers-ccpgames** [comment]
Yup. We're working on a permanent solution, but no news yet. Discussion on these sorts of things works best in slack rather than on github tickets, so I'm gonna close this. Ping me on tweetfleet slack if you've got questions.

**Comment by Ionaru** [comment]
I thought the point of this repository was to track ESI issues, '/universe/names' not working is a pretty big issue, why do you not want to track that here, @tsuthers-ccpgames?
