### ISSUE TITLE
Feature Request: Notifications Route

### ISSUE THREAD

**Issue by Makeshift** [ccpgames/esi-issues#512]
# Feature request
Similar to the original XML route, `/char/Notifications.xml.aspx` and `/char/NotificationTexts.xml.aspx`, it would be incredibly useful to have access to similar routes via ESI.

### Route
`/characters/notifications/`
I don't see the need in having separate notifications from notification texts in this instance. The notifications route can simply be made pageable.
### Authentication
Would require SSO auth token (Character ID not neccessary as auth token is tied to characters)

### Use case
These are essential for attack warning systems for Citadels and (currently) POS's, as well as sovereignty structures. Current systems include bots on Jabber, Slack and Discord that check for attack notifications.

### Example returns
```
{
  "application/json": [
    {
      "from": 90000001,
      "is_read": true,
      "message":
        {
          "type": 187,
          "aggressorAllianceID": 44481237,
          "aggressorCorpID": 129876123
          "aggressorID": 1239876,
          "armorValue": 1.0,
          "hullValue": 1.0,
          "shieldValue": 0.995
          "structureID": 1239867,
          "solarSystemID": 1239876,
          "typeID": 35833
        }
      "timestamp": "2015-09-30T16:07:00Z"
    }
  ]
}
```

### Previous XML or CREST route
`/char/Notifications.xml.aspx`
`/char/NotificationTexts.xml.aspx`

**Comment by tsuthers-ccpgames** [comment]
I'm open to merging these two routes, and the work for this will be happening soon. I'd be curious if you have any data on how many notification entries you'd expect to see for an average user, to give me a feel for how many pages we might be talking?

In regard to the character ID in route, that's a concession to caching. It's easiest to cache on a per-url basis, so encoding the character ID in the URL makes it easier to cache your characters response.

**Comment by Makeshift** [comment]
As a line member in a large alliance with no specific roles I would say I get somewhere between 5-15 notifications per day. For my characters in smaller corporations they barely get 1-2. I daresay the number would be drastically different for a person with roles in a large alliance though - Specifically war declarations, ihub/infrastructure node attacks, wars/allies, and structure damage. Even in a small corporation if you run several citadels in lowsec they can probably generate 10-15 notifications a day by themselves. 

Were you thinking of limiting it to a certain number per page and then a certain number of pages (say, 10 pages of 10), or would you rather do the last 7/14/30 days? I can't see a use case for needing to go too far into a characters notification history really, as most notifications are pretty time sensitive.

In terms of character route - That's a good point, I didn't think of that.

**Comment by jowrjowr** [comment]
The notification amount he's getting is in line with mine. ~10/day is the rough order of magnitude. Certainly not more than 100/day except in extreme cases.

(if you are getting 100/day there will very soon be a time where you stop getting any notifications)

**Comment by tsuthers-ccpgames** [comment]
This has been deployed today. After consideration I've merged the two routes into one, which simply gives you your 200 most recent notifications as of now.

The XML API handled notifications in a pretty weird way with a whole bunch of strange timers, but I don't /think/ I've removed any functionality by unifying them this way. If anyone has lost functionality through this merge, please drop by the #esi channel and let me know.

**Comment by NomadThanatos** [comment]
Can you reduce the cache time from 30 mins to 1 min?
Since Upwell structure will be reinforced around 20 mins at max DPS and sov structure will be reinforced from 10 to 60 mins.

I got 30 - 35 different chars api key to achieve above goal and hope we can make those code easy and useful in esi system.

**Comment by jowrjowr** [comment]
+1 to reducing the cache timer.
