### ISSUE TITLE
GET request to "/characters/{character_id}/location" returns "HTTP Error 404: Not Found"

### ISSUE THREAD

**Issue by crickert1234** [ccpgames/esi-issues#515]
# Bug

### Request
A GET request to 

> https://esi.tech.ccp.is/latest/characters/{character_id}/location/?datasource=tranquility

fails with the
### Response

> HTTP Error 404: Not Found

### Expected

I can't find a way to get my character's current location. In the "Requested Scopes List" the scope I am looking for is described as 

>  characterLocationRead: Allows an application to read your characters real time location in EVE.

**Comment by samuelgrant** [comment]
Probably doesn't need to be stated but might as well mention it anyway:
`https://esi.tech.ccp.is/latest/characters/{character_id}/online/?datasource=tranquility`

Is also returning an HTTP 404

**Comment by jowrjowr** [comment]
ccp removed that endpoint because it was decided that location tracking is too powerful. sorry.

**Comment by tsuthers-ccpgames** [comment]
Please don't troll jowr.

The locations and wallets endpoint are not stable at the moment. We have offlined them and are investigating, they will be brought back online once we have resolved the issue. Please join the #esi channel in the tweetfleet slack for more details.

**Comment by crickert1234** [comment]
Thank you!

**Comment by ccp-zoetrope** [comment]
Relevant blog: https://developers.eveonline.com/blog/article/2017-08-18-esi-outage-1

**Comment by crickert1234** [comment]
I'll keep my fingers crossed for you investigations. 👍
