### ISSUE TITLE
Provide fuel expire time among with expire date for structures endpoint.

### ISSUE THREAD

**Issue by EvilKot** [ccpgames/esi-issues#516]
# Inconsistency

### Routes
/corporations/{corporation_id}/structures/
### Description
Field "fuel_expires" contains date in "YYYY-MM-DD" while in CREST same field "fuelExpires" comes with  "YYYY-MM-DDThh-mm" format.

Without time it is impossible to determine if structure is gone offline or not during the last day.

**Comment by CarbonAlabel** [comment]
Same is true for `state_timer_start`, `state_timer_end`, and `unanchors_at`. I'm assuming this to just be a mistake in the endpoint's spec, and it's pretty annoying.

**Comment by ccp-zoetrope** [comment]
Staged for release soon™.

**Comment by ccp-zoetrope** [comment]
This is out now and you will see it fixed in the v1 endpoint.

**Comment by eve-n0rman** [comment]
Shouldn't a change in the spec bump the version?  I was following the spec, used underscore routes to freeze the route versions, and suddenly I'm getting times instead of dates.

**Comment by ccp-zoetrope** [comment]
Yes you are correct, I made the decision that this was small enough to not need a version bump but in retrospect it was not. Sorry if any of your stuff broke 😬

**Comment by eve-n0rman** [comment]
It was an easy enough fix on my end, just wanted to make sure my assumption that this sort of thing should not impact a versioned endpoint was correct.  Thanks.
