### ISSUE TITLE
Inconsistent data type in /wallet/

### ISSUE THREAD

**Issue by Ionaru** [ccpgames/esi-issues#518]
# Inconsistency

### Routes
v1/characters/{character}/wallet

### Description
Return data is not a consistent type on success and on error. If it were consistent is would be easier to handle errors.

### Resolution
Wrap the return data in an object, for example 
```json
{
  "application/json": {
    "balance": 99999.99
  }
}
```

**Comment by aquarhead** [comment]
Sorry clicked the wrong button

**Comment by Ionaru** [comment]
@aquarhead Wanna press the correct button and add a tag then? ;)

**Comment by a-tal** [comment]
this isn't an issue, many routes have a 200 response that isn't an object. that's why we have swagger specs
