### ISSUE TITLE
Difference between the scopes app settings/ auth url

### ISSUE THREAD

**Issue by Pseudocode99** [ccpgames/esi-issues#520]
What is the difference between the scopes in application settings (https://developers.eveonline.com/applications)
and the scopes i must send with the https://login.eveonline.com/oauth/authorize url?

Why there are two places to set the scopes?

Don´t find anything in the documentation.

**Comment by Kyria** [comment]
Scope in application settings is all scope you application __can__ request.
Scopes you give in `oauth/authorize` are the actual scope you want for a given token (and there you may ask for none, some or all scope you defined in application settings)

**Comment by ddouglas493** [comment]
This is not an issue with the ESI API and should not been posted here. For assistance with the ESI API or the SSO please jump on the Tweetfleet Slack and join the #esi channel.

To answer your question though. As a developer, you need the Client ID and Secret to make authorized calls to the API. This client and secret are acquired via the site you linked. When you setup your application on the Developers Site you are informing CCP what scopes you intend for your application to utilize.

When you make a call to the API and send you user to the SSO login, those are the scopes that are valid for the token that is being generated and that you will actually use to make the call and retreive the data. The scopes that you send with this call must have of been selected when you created the application on the developers site.

**Comment by Pseudocode99** [comment]
Thanks for the explanation!
