### ISSUE TITLE
Routes sometimes return in reverse order

### ISSUE THREAD

**Issue by w9jds** [ccpgames/esi-issues#522]
/route/{origin}/{destination}/ sometimes returns in the reverse order.

If you are supplying the origin and the destination. You would expect it to start at the origin and end at the destination. 

However, sometimes the destination is listed first and the origin last.

**Comment by a-tal** [comment]
can you supply an example?

sometimes being some combinations or some frequency of requests?

**Comment by w9jds** [comment]
As in just randomly, I had to resort to just checking, and reversing the array if they weren't in the right order. I'll see if I can find a reproducable one for you.

**Comment by aquarhead** [comment]
I added a [property test](http://hypothesis.works/articles/what-is-property-based-testing/) regarding this, I'm closing this because it didn't find a falsifying example after 20k attempts.

You're welcomed to play with it, if there's a problem, please reopen this with a falsifying example.

```
◊ PYTHONPATH=./ TEST_PBT=1 pytest --hypothesis-show-statistics
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.6.2, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/aquarhead/Projects/esi-routes, inifile:
plugins: teamcity-messages-1.21, ordering-0.5, flask-0.10.0, cov-2.5.1, hypothesis-3.30.0
collected 1 item

tests/test_dijkstra.py
=========================================================================================================== Hypothesis Statistics ===========================================================================================================

tests/test_dijkstra.py::TestDijkstra::test_origin_destination_order:

  - 20000 passing examples, 0 failing examples, 0 invalid examples
  - Typical runtimes: 3-458 ms
  - Stopped because settings.max_examples=20000

======================================================================================================== 1 passed in 3456.22 seconds ========================================================================================================

```
