### ISSUE TITLE
Feature Request : Return the current route as part of the add way point

### ISSUE THREAD

**Issue by Slazanger** [ccpgames/esi-issues#524]
### Route
/ui/autopilot/waypoint/

### Authentication
SSO

### Use case
Add/Set a new Waypoint and allow the current route to be returned from the autopilot

### Example returns

204 | Open window request received |  { "active_route":  [30002771,   "30002770,    30002769,    30002772  ]  "|
403 | Forbidden |  Value{   "error": "string",   "sso_status": 0 } |

**Comment by aquarhead** [comment]
All the "remote UI" functionalities are not guaranteed to run, nor are they supposed to return any thing.

**Comment by Slazanger** [comment]
is it possible to get the current route at all then ?

**Comment by w9jds** [comment]
Also wanted to point out. 204 specifically means success, no content. So it wouldn't make sense to return anything with a 204.

**Comment by aquarhead** [comment]
@Slazanger there's an existing issue for it: #366 

Extension on @w9jds 's point, for all "remote UI" requests, a 204 response only means the server has received your request, whether it succeeds in notifying the client to take action is not guaranteed.
