### ISSUE TITLE
is broken flag for broken endpoints, rather than removing from swagger.json

### ISSUE THREAD

**Issue by fuzzysteve** [ccpgames/esi-issues#525]
# Feature request

When a route is broken, it drops from the list. Which means any libraries built off that drop the endpoint, even if you're not actively devving that bit.

Flagging it as broken, rather than removing would help there.

**Comment by a-tal** [comment]
```
HTTP/1.1 501 Not Implemented
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,X-User-Agent
Access-Control-Allow-Methods: GET,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type,Warning
Access-Control-Max-Age: 600
Connection: close
Content-Length: 60
Content-Type: application/json
Date: Wed, 23 Aug 2017 18:18:15 GMT

{"error": "The requested endpoint is temporarily disabled."}
```

open to feedback

**Comment by fuzzysteve** [comment]
As a response, that works fine for me :)

It's mostly to stop them dropping from the spec file when you turn them off.

**Comment by a-tal** [comment]
fixed in `esi-lib`.

to ESI devs, there are two new kwargs to the endpoint wrap, `hidden_in` and `broken_in`. each of which can be a list of environments. more details in the linked esi-lib commit.

**Comment by a-tal** [comment]
thanks for the suggestion :)
