### ISSUE TITLE
Go-Swagger Validator fails ESI

### ISSUE THREAD

**Issue by tankbusta** [ccpgames/esi-issues#53]
Using the latest version of [go-swagger](https://github.com/go-swagger/go-swagger) generates the following errors when attempting to validate.

     PS > swagger validate https://esi.tech.ccp.is/latest/swagger.json
    The swagger spec at "https://esi.tech.ccp.is/latest/swagger.json" is invalid against swagger specification 2.0. see errors :
    - /corporations/{corporation_id}/wallets/{wallet_id}/journal/ in body must be of type string: "array"
    - /corporations/{corporation_id}/wallets/{wallet_id}/transactions/ in body must be of type string: "array"

If you remove these 2 dummy routes, it passes the validation.

    PS > swagger validate .\prettyswag.json
    The swagger spec at ".\\prettyswag.json" is valid against swagger specification 2.0

Since these are dummy/test routes from the looks of it, might it be a wise idea to remove them from prod/latest documentation?

**Comment by a-tal** [comment]
fixed with https://github.com/ccpgames/esi-wallet/commit/fa19fb49c8e5d88d5ca5826a9e7501ce04f41761 - changed dummy returns to 204s

thanks!
