### ISSUE TITLE
error 502 ignoring content-type

### ISSUE THREAD

**Issue by jowrjowr** [ccpgames/esi-issues#530]
this url gave an error 502: https://esi.tech.ccp.is/v4/characters/93573761/?datasource=tranquility

no big deal, except the result is straight html which isn't what is expected.

specifically:
```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

should i be forcing the issue with a different header?

**Comment by aquarhead** [comment]
I think this is something wrong with Google CDN (public cache), otherwise we'd never return plain HTML

BTW it works for me

**Comment by a-tal** [comment]
this error is from the google CDN. we can't customize it unfortunately
