### ISSUE TITLE
additional refinery api information request

### ISSUE THREAD

**Issue by jowrjowr** [ccpgames/esi-issues#534]
There's a few pieces of information that would be really nice to have exposed via ESI that don't quite fit in with what will be exposed via calendar.

* Complete chunk history

When you launch a chunk you get WHEN it was launched, WHEN it arrives, and WHEN it will automatically explode. Currently only arrival date is exposed in the calendar, and only if you remember to check a box. 

Having those 3 dates, along with who launched the chunk, available for use in the API would be quite helpful for planning purposes.

* Chunk composition

The planetcracked chunk information is shown completely to the gunner, but after that we don't (currently) get to see it again. It would be great for planning to be able to get this information in case the gunner doesn't copy it down. I consider this information something akin to what we had before with say silo contents or running corporation jobs. Since currently the upper bound for an event is _two months_, this would be really nice.

_will show to fozzie and such for feedback_

**Comment by aquarhead** [comment]
> I don’t know if we have any plans right now to expose this or not. Its likely not something we’ll have to time to do for release anyway... But sounds like an interesting thing to look at for follow-up work once things stabilize.

-- from related feature team

**Comment by tsuthers-ccpgames** [comment]
A new endpoint will pop up on singularity within the next hour, giving the extraction start and finish time as well as the natural decay time for all chunks currently under extraction by a corporation.

With regards to who started it and the expected composition, that's unlikely to be in a dedicated endpoint in time for launch day, but all that information shows up in the notification that is sent to all station managers in a corporation when an extraction is started. I'll be prodding the notifications endpoint in a bit to make sure it has all the new structure notifications in it's enum, and you can pull it from there for the moment.
