### ISSUE TITLE
Inconsistency: characters/{character_id}/wallet/journal/ ->ref_type

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#535]
# Inconsistency

### Routes
Inconsistency:
https://esi.tech.ccp.is/latest/#!/Wallet/get_characters_character_id_wallet_journal

Compared to:
https://esi.tech.ccp.is/latest/#!/Wallet/get_corporations_corporation_id_wallets_division_journal

### Description

The Characters Journal field ``ref_type`` values does not match Corporation Journal (or the XML API).
The Corporation Journal almost exactly matches the XML API, making it easy to go from the XML API to ESI.
But, The Characters Journal have a lot of _strange_ values. Making it unnecessary hard to work with.

**Example 1:**
Characters Journal have:
```contract```

Corporation journal (and XML API) have:

```
contract_auction_bid,
contract_auction_bid_refund
contract_collateral
contract_reward_refund
contract_auction_sold
contract_reward
contract_collateral_refund
contract_collateral_payout
contract_price
contract_brokers_fee
contract_sales_tax
...
```

**Example 2:**
Characters Journal have:
```
bounty_prize_historical
mission_reward_bonus
```
There is nothing like it in the corporation journal or XML API.

### Resolution
Use the ref_type values from the corporation endpoint in the character endpoint.

**Comment by aquarhead** [comment]
Yeah, you should use `v2` of character wallet journal, that's the same with the corporation one.

It will be promoted to `latest` soon!
