### ISSUE TITLE
Support X-Pages in paginated endpoints

### ISSUE THREAD

**Issue by Blacksmoke16** [ccpgames/esi-issues#536]
(changed by @aquarhead to reduce noise, see below for todo list)

**Comment by aquarhead** [comment]
Changed title to combine all related endpoints:

- [ ] https://esi.tech.ccp.is/latest/#!/Contacts/get_characters_character_id_contacts
- [ ] https://esi.tech.ccp.is/latest/#!/Corporation/get_corporations_corporation_id_structures
- [ ] https://esi.tech.ccp.is/latest/#!/Market/get_markets_structures_structure_id
- [ ] https://esi.tech.ccp.is/latest/#!/Universe/get_universe_groups
- [ ] https://esi.tech.ccp.is/latest/#!/Universe/get_universe_types
- [ ] https://esi.tech.ccp.is/latest/#!/Wars/get_wars_war_id_killmails

**Comment by aquarhead** [comment]
- [ ] https://esi.tech.ccp.is/latest/#!/Market/get_markets_region_id_orders (for specific type's orders)

**Comment by a-tal** [comment]
all linked issues are closed

**Comment by copyliu** [comment]
also missing  /universe/groups/
