### ISSUE TITLE
Incorrect Endpoint Summary on ESI Website

### ISSUE THREAD

**Issue by ddouglas493** [ccpgames/esi-issues#538]
This isn't a bug, nor a feature request, nor a consistency issue. Just wanted to let you know that for the following endpoint on the ESI site:

GET /corporations/{corporation_id}/wallets/{division}/journal/          Get **character** wallet journal

It says character for the corporation wallet journal endpoint

**Comment by aquarhead** [comment]
My bad, already fixed :)

Thanks for the report!
