### ISSUE TITLE
Bug: /markets/groups/{market_group_id}/  gives empty name and description !

### ISSUE THREAD

**Issue by mullinger** [ccpgames/esi-issues#541]
https://esi.tech.ccp.is/latest/markets/groups/402/?datasource=tranquility&language=en-us

{
  "market_group_id": 402,
  "name": "",
  "description": "",
  "types": [
    11200,
    11202
  ],
  "parent_group_id": 399
}

This is new. This is bad. It worked a few days ago.

**Comment by aquarhead** [comment]
it's good now

**Comment by synullinger** [comment]
Yeah, just noticed.

Thank you!
