### ISSUE TITLE
POST /fleets/{fleet_id}/members/ returns error code 500 / "Unhandled internal error encountered!"

### ISSUE THREAD

**Issue by AndreyYarovoy** [ccpgames/esi-issues#544]
Tested via https://esi.tech.ccp.is/

curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer wHsJG0C7nfifSJxnyB7e6l5qaVDKsHC9DZhpUN6zUnOcvKCWxUn-n_e0sUlQ4pcgz_DhcjnBf89WR7c0nSq4kQ2' -d '{ \ 
   "character_id": 95410894, \ 
   "role": "squad_member", \ 
   "squad_id": 3217611363963, \ 
   "wing_id": 2110411363963 \ 
 }' 'https://esi.tech.ccp.is/latest/fleets/1085211363963/members/?datasource=tranquility'

Response Body
{
  "error": "Unhandled internal error encountered!"
}
Response Code
500
Response Headers
{
  "date": "Fri, 08 Sep 2017 01:56:05 GMT",
  "via": "1.1 google",
  "x-esi-error-limit-remain": "100",
  "alt-svc": "clear",
  "access-control-allow-origin": "*",
  "x-esi-error-limit-reset": "55",
  "access-control-max-age": "600",
  "access-control-allow-methods": "GET,POST,OPTIONS",
  "content-type": "application/json",
  "status": "500",
  "access-control-expose-headers": "Content-Type,Warning",
  "access-control-allow-credentials": "true",
  "strict-transport-security": "max-age=31536000",
  "access-control-allow-headers": "Content-Type,Authorization,X-User-Agent",
  "content-length": "50"
}

// fleet members for this fleet to show that squad & wing ids are valid

curl -i --compressed -X GET --header 'Accept: application/json' --header 'Authorization: Bearer wHsJG0C7nfifSJxnyB7e6l5qaVDKsHC9DZhpUN6zUnOcvKCWxUn-n_e0sUlQ4pcgz_DhcjnBf89WR7c0nSq4kQ2' 'https://esi.tech.ccp.is/latest/fleets/1085211363963/members/?datasource=tranquility&language=en-us'

Response Body
[
  {
    "character_id": 94772763,
    "ship_type_id": 22440,
    "wing_id": 2110411363963,
    "squad_id": 3217611363963,
    "role": "squad_member",
    "role_name": "Squad Member (Boss)",
    "join_time": "2017-09-08T01:21:02Z",
    "takes_fleet_warp": true,
    "solar_system_id": 30000075
  }
]
Response Code
200
Response Headers
{
  "date": "Fri, 08 Sep 2017 01:53:32 GMT",
  "via": "1.1 google",
  "status": "200",
  "strict-transport-security": "max-age=31536000",
  "alt-svc": "clear",
  "content-length": "256",
  "x-esi-error-limit-remain": "100",
  "last-modified": "Fri, 08 Sep 2017 01:53:32 GMT",
  "x-esi-error-limit-reset": "28",
  "access-control-max-age": "600",
  "access-control-allow-methods": "GET,POST,OPTIONS",
  "content-language": "en-us",
  "access-control-allow-origin": "*",
  "access-control-expose-headers": "Content-Type,Warning",
  "cache-control": "private",
  "access-control-allow-credentials": "true",
  "content-type": "application/json",
  "access-control-allow-headers": "Content-Type,Authorization,X-User-Agent",
  "expires": "Fri, 08 Sep 2017 01:53:37 GMT"
}

**Comment by aquarhead** [comment]
Unfortunately, this will be straight-up broken until we push out the fix with EVE's deployment (hopefully sometime next week)
