### ISSUE TITLE
Storage contents showing wrong data

### ISSUE THREAD

**Issue by DavidEdwards** [ccpgames/esi-issues#547]
# Bug

The launchpad and storage facilities are showing the wrong data. 

### Request

https://esi.tech.ccp.is/latest/characters/1880441064/planets/40298263/?datasource=tranquility

### Response

Launchpad JSON
```
{
  "pin_id": 1023468930016,
  "type_id": 2544,
  "latitude": 1.68405841235,
  "longitude": 0.973914974368,
  "contents": [
	{
	  "type_id": 3689,
	  "amount": 130
	}
  ]
}
```

Storage Facility JSON
```
{
  "pin_id": 1023468930018,
  "type_id": 2541,
  "latitude": 1.69292010901,
  "longitude": 0.98237290496,
  "contents": [
	{
	  "type_id": 2270,
	  "amount": 32466
	},
	{
	  "type_id": 2399,
	  "amount": 1060
	}
  ],
  "last_cycle_start": "2017-02-12T21:02:08Z"
}
```

Here is that data represented in my UI.

The launch pad contains the wrong number of mechanical parts.

The storage contains the wrong number and type of items. 

![app_result](https://user-images.githubusercontent.com/1585923/30221684-85d7f218-94c4-11e7-8a57-90fd460aed39.png)

### Expected

Here you can see what the launchpad should have.
![launchpad](https://user-images.githubusercontent.com/1585923/30221676-7fba322e-94c4-11e7-8146-a1bac3f8704a.png)

Likewise, for the storage facility.
![storage_facility](https://user-images.githubusercontent.com/1585923/30221683-83927dfc-94c4-11e7-9928-c801acbfa1c3.png)

**Comment by aquarhead** [comment]
> Note: Planetary information
            is only recalculated when the colony is viewed through the client.
            Information will not update until this criteria is met.

from its ESI spec

**Comment by DavidEdwards** [comment]
Yeah, I knew that. Standard PI practice.

The numbers are starting to "fix" themselves now. I guess that was the issue. A mixture of planetary caching (on visit) and ESI caching causing me to see wrong results.

I'll close this. I think you are probably right with your assessment.
