### ISSUE TITLE
BUG: FW system stats not updating

### ISSUE THREAD

**Issue by garemoko** [ccpgames/esi-issues#548]
# Bug
Since yesterday, FW system stats are not updating in ESI. For example, if you look at Kamela (system id 30003069) on Dotlan which still uses the old xml API, it shows Kamela at 96.67% whereas evewarfare.com, which has updated, is stuck at 94.67% like a schmuck. 

### Request

https://esi.tech.ccp.is/latest/fw/systems/?datasource=tranquility
```
...
{"solar_system_id": 30003069, "occupier_faction_id": 500003, "owner_faction_id": 500003, "victory_points": 2840, "victory_points_threshold": 3000, "contested": true}
...
```

http://games.chruker.dk/eve_online/test_eve_api.php?action=lookup&function=faction_warfare_occupancy&myeve_key_id=

```
...
<row solarSystemID="30003069" solarSystemName="Kamela" occupyingFactionID="0" owningFactionID="500003" occupyingFactionName="" owningFactionName="Amarr Empire" contested="True" victoryPoints="2900" victoryPointThreshold="3000" />
...
```

### Expected
I would expect these values to be the same, or the ESI values to be more up to date.

**Comment by garemoko** [comment]
The stats are updating every downtime and not changing after that.

**Comment by ccp-zoetrope** [comment]
The fix for this will be out after downtime on 9/13/2017.
