### ISSUE TITLE
Contract Completions displaying as unknown in Wallet/Journals vs. XML Output

### ISSUE THREAD

**Issue by ddouglas493** [ccpgames/esi-issues#550]
# Bug

### Request

`https://esi.tech.ccp.is/latest/characters/94941977/wallet/journal/?datasource=tranquility&accessToken={accessToken}`

### Response

```
{
    "date": "2017-09-02T22:02:42Z",
    "ref_id": 14523050008,
    "ref_type": "unknown",
    "amount": 20000000,
    "balance": 2904923972.6217,
    "extra_info": {}
},
```
XML Output
```
<row 
    date="2017-09-02 22:02:42"
    refID="14523050008"
    refTypeID="68"
    ownerName1="Secure Commerce Commission"
    ownerID1="1000132"
    ownerName2="Slifa Baddanold"
    ownerID2="94941977"
    argName1="122307050"
    argID1="0"
    amount="20000000.00"
    balance="2904923972.62"
    reason=""
    taxReceiverID=""
    taxAmount=""
    owner1TypeID="2"
    owner2TypeID="1380"
/>
```

### Expected
```
{
    "date": "2017-09-02T05:03:25Z",
    "ref_id": 14520021375,
    "ref_type": "contract_reward",
    "first_party_id": 1000132,
    "first_party_type": "corporation",
    "second_party_id": 94941977,
    "second_party_type": "character",
    "amount": 30000000,
    "balance": 2884923972.6217,
    "extra_info": {
        'contract_id': 122307050
    }
},
```

**Comment by aquarhead** [comment]
Can you try the `/v2` or `/dev` one?

**Comment by ddouglas493** [comment]
That is no V2 for that endpoint. Only V1 at this time that i am aware of. Will try /dev in a moment. Something came up at work

**Comment by aquarhead** [comment]
eh........... what?

![image](https://user-images.githubusercontent.com/222272/30279739-8fb3dc9e-96fd-11e7-8608-8c7dd94ecbc3.png)

**Comment by ddouglas493** [comment]
That alternate route is only displayed under Dev. It is not displayed under Latest. My apologies. I did query it and it is returning the correct ref_type.

![](https://i.imgur.com/08KKwPa.png)


`https://esi.tech.ccp.is/v2/characters/94941977/wallet/journal/?token={token}`

```
    {
        "date": "2017-09-02T22:02:42Z",
        "ref_id": 14523050008,
        "ref_type": "contract_reward",
        "amount": 20000000,
        "balance": 2904923972.6217,
        "extra_info": {}
    },
```

**Comment by ddouglas493** [comment]
Any chance we can get first and second party ids/types and the contract id under extra info?

**Comment by aquarhead** [comment]
I'm adding the `contract_id` now, first and second party I'd say if we don't have it already then we don't have it unfortunately :(

**Comment by ddouglas493** [comment]
I can work with the Contract ID and query my contract table for the involved parties. Thanks a bunch.

**Comment by ddouglas493** [comment]
Can V2 be used for Prod now?

**Comment by aquarhead** [comment]
@ddouglas493 strictly speaking not really, you should wait for it to be under `/latest` we consider endpoints that are only under `/dev` subject to change at any time - meaning mainly spec breaking changes - but in this case, I'm thinking about promoting `/v2` to `/latest`, so it's ready to use already, and also it resolves a bunch more `ref_type` than `/v1`.

**Comment by ddouglas493** [comment]
Thanka much sir. I will wait for it to show up on `/latest`

**Comment by aquarhead** [comment]
Just deployed, should be in effect after the current cache expires. If not, please re-open.
