### ISSUE TITLE
Character Wallet Journal Outputting Invalid Location ID for industry_facility_tax journal entries

### ISSUE THREAD

**Issue by ddouglas493** [ccpgames/esi-issues#551]
# Bug

### Request

https://esi.tech.ccp.is/latest/characters/96447585/wallet/journal/?datasource=tranquility&token={access_token}

Search for any entry with type industry_facility_tax and in the extra info array, the location id is included and the value is the ID of the Manufacturing Job that the character was performing rather that then the location ID of where the job was processed at. The issue here is that the field is mislabeled and the location parameter is missing if it is necessary. 

### Response

```
    {
        "date": "2017-08-21T00:12:00Z",
        "ref_id": 14476028930,
        "ref_type": "industry_facility_tax",
        "first_party_id": 96447585,
        "first_party_type": "character",
        "second_party_id": 1000035,
        "second_party_type": "corporation",
        "amount": -77985,
        "balance": 3176116297.8468,
        "extra_info": {
            "location_id": 337255578
        }
    },
```

### Expected

```
    {
        "date": "2017-08-21T00:12:00Z",
        "ref_id": 14476028930,
        "ref_type": "industry_facility_tax",
        "first_party_id": 96447585,
        "first_party_type": "character",
        "second_party_id": 1000035,
        "second_party_type": "corporation",
        "amount": -77985,
        "balance": 3176116297.8468,
        "extra_info": {
            "job_id": 337255578
        }
    },
```

**Comment by ddouglas493** [comment]
I forgot to mention that i have confirmed this across three different chars.

**Comment by aquarhead** [comment]
Just deployed, should be in effect after the current cache expires. If not, please re-open.
