### ISSUE TITLE
Wallet Journal HTTP 500 Unhandled Exception

### ISSUE THREAD

**Issue by ddouglas493** [ccpgames/esi-issues#552]
# Bug

### Request

[2017-09-11 05:11:05] local.INFO: Failed ESI Call GET /v1/characters/917907859/wallet/journal/ HTTP/1.1

Been getting them all night on this one character

### Response

Error: Unhandled internal error encountered!

### Expected

Character Wallet Journal Details

**Comment by ddouglas493** [comment]
@aquarhead When is this next deployment out of curiosity? I am going to write a command if to stop calls for dudeman journal until the fix is implemented. He is the only character that I am having that issue with.

**Comment by aquarhead** [comment]
Today

**Comment by GoldenGnu** [comment]
I was in doubt if this was the same issue or not, but, here we go:

### Request
https://esi.tech.ccp.is/latest/corporations/1020386980/wallets/1/transactions/?datasource=tranquility

### Response

Response Body
```
{
  "error": "Unhandled internal error encountered!"
}
```
Response Code
```
500
```
### Expected
Corporation Wallet Transactions

**Comment by aquarhead** [comment]
#564 did you see this after today's deployment?

**Comment by GoldenGnu** [comment]
I'm getting it right now. Not sure when it started, sorry
``date": "Mon, 25 Sep 2017 11:49:31 GMT``

**Comment by noenedrops** [comment]
Despite of this issue being closed, I am getting the same results for character Darshana Fi-Nai and her corp. If I specify the wallet division she can access, server returns 500 `{"error"=>"uncaught exception"}`, however, for the wallets that the character doesn't have access to, the response is `[]`. Master wallet (division = 1) works fine.

**Comment by GoldenGnu** [comment]
I have duplicate too: https://github.com/ccpgames/esi-issues/issues/631

**Comment by ccp-zoetrope** [comment]
@GoldenGnu @noenedrops you should not be seeing this error anymore as the missing ref_type's have been added to ESI now.
