### ISSUE TITLE
GET /corporations/{corporation_id}/wallets/{division}/journal/

### ISSUE THREAD

**Issue by MrGrapeDrink** [ccpgames/esi-issues#554]
# Bug

Unhandled Internal Error when trying to pull division 1 of corp wallet transactions. 2-7 work as expected. 1-7 work when trying with a different corporation

### Request

https://esi.tech.ccp.is/latest/corporations/98475638/wallets/1/journal/?datasource=tranquility

### Response

{
  "error": "Unhandled internal error encountered!"
}

### Expected

Division 1 wallet transactions.

**Comment by aquarhead** [comment]
Same issue with #550 will fix with next EVE deployment, please track the progress in that issue instead

**Comment by aquarhead** [comment]
Sorry I meant #552
