### ISSUE TITLE
Feature Request: Open a pay a person window

### ISSUE THREAD

**Issue by Dusty-Meg** [ccpgames/esi-issues#555]

**Comment by Dusty-Meg** [comment]
Because I fail at waffle.
Ability to open a pay this person with pre-filled amount and description.
Being able to use a corp wallet if you have the roles would also be great ability.

**Comment by SpeedProg** [comment]
kind like this: #190

**Comment by Dusty-Meg** [comment]
Exactly like that,

**Comment by Blacksmoke16** [comment]
Duplicate of https://github.com/esi/esi-issues/issues/190
