### ISSUE TITLE
Support X-Pages header in /markets/structures/{structure_id}/

### ISSUE THREAD

**Issue by ETristram** [ccpgames/esi-issues#556]
# Bug

### Request
https://esi.tech.ccp.is/latest/markets/structures/1023164547009/?datasource=tranquility&page=3

### Response
{
  "access-control-allow-credentials": "true",
  "access-control-allow-headers": "Content-Type,Authorization,X-User-Agent",
  "access-control-allow-methods": "GET,OPTIONS",
  "access-control-allow-origin": "*",
  "access-control-expose-headers": "Content-Type,Warning",
  "access-control-max-age": "600",
  "content-type": "application/json",
  "strict-transport-security": "max-age=31536000",
  "x-esi-error-limit-remain": "100",
  "x-esi-error-limit-reset": "56",
  "alt-svc": "clear",
  "expires": "Tue, 12 Sep 2017 13:49:05 GMT",
  "last-modified": "Tue, 12 Sep 2017 13:44:05 GMT"
}
### Expected
X-Pages header to be present

**Comment by aquarhead** [comment]
Maybe it's better to unify this and #536 together with all other endpoints that should support `X-Pages`

**Comment by aquarhead** [comment]
Merge into #536
