### ISSUE TITLE
esi-corporations: Invalid 200 response

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#557]
# Bug

### Request
https://esi.tech.ccp.is/v4/characters/90006401/?datasource=tranquility

### Response
```{"error": "Invalid 200 response: 'corporation_id' is required", "response": {"name": "Jenlura Taron", "ancestry_id": 24, "gender": "female", "bloodline_id": 4, "security_status": 10.0, "birthday": "2010-11-04T12:35:00Z", "race_id": 2, "description": ""}}```

### Expected
```{"corporation_id": 1000051, "name": "Jenlura Taron", "ancestry_id": 24, "gender": "female", "bloodline_id": 4, "security_status": 10.0, "birthday": "2010-11-04T12:35:00Z", "race_id": 2, "description": ""}```

### Additional Notes:
According to @polarina the birthday attribute is broken. According to that chars corporationhistory it joined Republic Fleet in 2001, 9 years before being born. This is a character that was once used for lore so probably CCP created.

**Comment by gitAskur** [comment]
That's the result of someone here at CCP deciding to hack together a lore npc by breaking all the rules for creating npcs.

Effectively this is an NPC, but you have no way of knowing that. Currently we are not "tracking" NPCs because there are no values to track - they do not change. However, the tracker service has no way of knowing this is an NPC so it attempts to track it. That creates problems.

At any rate, we're just going to have to bite the bullet and support npcs and deleted chars.

**Comment by cvweiss** [comment]
> At any rate, we're just going to have to bite the bullet and support npcs and deleted chars.

Will this mean that 404s/410s won't be returned anymore?

**Comment by gitAskur** [comment]
404s will still be returned if you are querying random IDs that do not resolve to anything, and they will count towards any sort of error response based throttling. But at the very least deleted characters will return the data they have.

I'm not quite set on the NPC part.. on one hand they are static and should perhaps be serviced from a different endpoint. On the other hand some brilliant ray of sunshine created the NPC-BUT-NOT-REALLY character that is creating this issue.. and that is only an issue if there's some difference between NPCs and PCs when it comes to getting character info.

But 410s will definately never be meaningful at this point. They are not working right now and I'm not gonna fix that seeing as that would all be undone by not being a dick with deleted data.
