### ISSUE TITLE
Request: JSON does not properly support sending of mail formatting

### ISSUE THREAD

**Issue by Erelaszun** [ccpgames/esi-issues#558]
# Feature request

change send mail where body can be a base64 encoded string of the mail body.

As I started working with mail sending, I used mail get to get a weekly e-mail I send my corp
(with colors, font sizes, etc, etc), using php's json_encode, I put that same mail body I got from 
get /chars/charID/mail/mailID, but it would just error out stating it needed "body", "subject", etc etc.

After doing a ton of regex to strip most of the formatting, I was able to get the mail to send.

This could be corrected, by simply allowing us to encode "body" in base64
(maybe even change get body to base64, to make it consistent)

**Comment by SpeedProg** [comment]
Would you have any example of a mail that breaks it? :/ I have been sending pretty big mails with formatting in the past :(. As in ~6k character, font size/color, urls, ingame char links.

**Comment by Erelaszun** [comment]
After doing a lot of testing, and escaping lol, I was able to get it to work. However, I will still stand by a base64 encode request, as it would make it much easier, and would not need escaping.

**Comment by jowrjowr** [comment]
so when you write the json correctly, it works.

good to know.
