### ISSUE TITLE
Loyalty Store Offers endpoint returns 500 for NPC corporations that don't have a loyalty store

### ISSUE THREAD

**Issue by BuumEdzott** [ccpgames/esi-issues#559]
# Bug

### Request
https://esi.tech.ccp.is/v1/loyalty/stores/1000261/offers/

### Response
{
  "error": "Unhandled internal error encountered!"
}

### Expected
This should probably either return a 404 or a 200 with an empty list as the body.

Additionally, as far as I can tell, there is no way to know a priori whether a particular NPC corp (of those returned by the /corporations/npccorps/ endpoint) has a loyalty store and will trigger this error.

**Comment by BuumEdzott** [comment]
All corporations which trigger this:

```
1000001 Doomheim
1000173 Polaris Corporation
1000174 Polaris Bug Hunters
1000175 Polaris Events
1000176 Pann's Peeps
1000193 Arkombine
1000198 Imperial Guard
1000261 State Peacekeepers
1000262 Federal Marines
1000263 Republic Command
1000282 Directive Intelligence Agency
```

**Comment by CarbonAlabel** [comment]
Fun fact: the same thing happened when the loyalty store offers endpoint was first introduced to CREST, and was soon fixed to return an empty list for such corporations.

**Comment by Aidansavage** [comment]
-Doomheim is the PC graveyard, thus does not provide missions
-Polaris Corporation is the GM corporation (ceo GM Loki)
-Polaris Bug Hunters and Events, Pann's Peeps are closed
-Arkombine is a Clone Soldier corp
-Imperial Guard, State Peacekeepers, Federal Marines, Republic Command, and Directive Intelligence Agency are all corps that also do not have agents


Would it be worth adding an additional return for npc corps that state whether the corp has a LP store as a t/f value?

**Comment by Blacksmoke16** [comment]
Probably easier to just return an empty array, as if it's not empty it would be assumed they do.
