### ISSUE TITLE
/v1/markets/structures/ doesn't contain X-Pages header

### ISSUE THREAD

**Issue by krojew** [ccpgames/esi-issues#561]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

# Bug

### Request

/v1/markets/structures/{structure_id}/

### Response

Stuff without X-Pages header.

### Expected

Stuff with X-Pages header.

**Comment by Blacksmoke16** [comment]
This is handled in #536.

**Comment by aquarhead** [comment]
Duplicate of #536
