### ISSUE TITLE
Feature Request: Add division in /corporation/{corporation_id}/assets

### ISSUE THREAD

**Issue by frankysaken** [ccpgames/esi-issues#562]
### Request
`GET /corporations/{corporation_id}/assets/`

### Response
```
{
  "application/json": [
    {
      "is_singleton": true,
      "item_id": 1000000016835,
      "location_flag": "Hangar",
      "location_id": 60002959,
      "location_type": "station",
      "type_id": 3516
    }
  ]
}
```

### Expected
```
{
  "application/json": [
    {
      "is_singleton": true,
      "item_id": 1000000016835,
      "location_flag": "Hangar",
      "location_id": 60002959,
      "location_type": "station",
      "type_id": 3516,
      "division": 1
    }
  ]
}
```

# Feature request
It would be nice to see which division hangar specifically corporate assets are stored in. The division can then be looked up from: `GET /corporations/{corporation_id}/divisions/` to get its name.

# Possibly related
https://github.com/ccpgames/esi-issues/issues/213
https://github.com/ccpgames/esi-issues/issues/498

**Comment by GoldenGnu** [comment]
Corp hangars are found via the flag valve: CorpSAG1-CorpSAG7
And you can find the names of the hangars here: https://esi.tech.ccp.is/latest/#!/Corporation/get_corporations_corporation_id_divisions 

If Hangar is returned by stuff in a corp hangar it's a bug!

**Comment by aquarhead** [comment]
I think @GoldenGnu is correct, in my test I also see items in corp hangar divisions marked as `CorpSAG1` etc.. (though maybe we should improve the naming there)

If you think you see some weird response can you report with an example `corp_id` and `item_id`? You can also talk to me directly in Slack if you don't want to publicly expose these information.

**Comment by GoldenGnu** [comment]
My opinion: Don't change the names, it's compatible with XML (it will be less important in a year, but, for now compatibility is important as most of us are supporting both ESI and XML)

**Comment by tsuthers-ccpgames** [comment]
Corporation hangar divisions do indeed show up as CorpSAG1-CorpSAG7. I'm not sure why you're seeing corporation assets showing up under Hangar, it may or may not be a bug.

The item ID in the OP doesn't exist any more, between that and no further information from @frankysaken I'm going to assume this was a transient issue. If you're still seeing this franky, please contact me on slack with some item ID's and we'll go take a peek to see if this is a problem with ESI or a problem with the characters inventory 😄
