### ISSUE TITLE
Bug ESI corp wallet journal API - response code 500

### ISSUE THREAD

**Issue by ancosmin** [ccpgames/esi-issues#564]
# Bug

No longer being able to access the corp journal data through the ESI api call.
I can reproduce the issue with both my code and on the Swagger page.
Corp ID: 98150953
Wallet division : 1
Please note that i can access the data for all other wallet divisions.
Issue noticed after Eve server downtime Sunday 17th September.
### Request

GET /corporations/{corporation_id}/wallets/{division}/journal/

### Response
Response code 500

"error": "Unhandled internal error encountered!"

### Expected

Master wallet journal Data.

**Comment by aquarhead** [comment]
Same issue as #552 , just fixed, will be deployed soon
