### ISSUE TITLE
Reduce cache timer on /characters/notifications route

### ISSUE THREAD

**Issue by Makeshift** [ccpgames/esi-issues#565]
Referencing [this comment](https://github.com/ccpgames/esi-issues/issues/512#issuecomment-329343631), it would be very nice if we could reduce the cache on the notifications endpoint.

Currently, the primary use case for notifications is to know outside of game when a structure is being attacked. With the 30 minute timer, that structure is going to be dead before you know about it.

I propose reducing it down to 1 minute, or perhaps 5 if this is too low.

**Comment by tsuthers-ccpgames** [comment]
It's definitely not going to drop below 5 minutes. It's an old component and a surprisingly expensive operation, so we need to protect the DB from people's enthusiasm. I'm going to drop it to 10 for now and monitor performance. Provided that goes smoothly I'll look into dropping it to 5. Changes happening Imminently™

**Comment by NomadThanatos** [comment]
Upwell structure or IHUB TCU under attack will notify the whole corporation or alliance.
So we just need several chars' token polled in that corp or alliance to reduce that latency(in this case we would query the same amount queries no matter the cache time, just make the code and maintenance much harder).
If notification endpoint should not be used like this, can we have some endpoint easy to relay?

**Comment by Makeshift** [comment]
I'd like to reopen this to evaluate performance on the drop to 10 minutes to see if 5 minutes is feasible. With Citadel 2.0 it's become even more important to have timely attack notifications at any time of day and it would be really nice to have more than (worst case) ~4 minutes to get a fleet to defend stuff.
