### ISSUE TITLE
Invalid 200 response in wallet transactions

### ISSUE THREAD

**Issue by krojew** [ccpgames/esi-issues#566]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

# Bug

### Request

 /v1/characters/<character id>/wallet/transactions/

### Response

 Invalid 200 response: failed to coerce value 'None' into type integer (format: int64)

### Expected

wallet transactions

**Comment by aquarhead** [comment]
Sorry, I think I saw an error report in our tools yesterday night, but for some reason I cannot find it anymore now... Can you provide a character id that is experiencing this issue?

If you don't want to publicly expose char id you can DM me (ccp_aquarhead) on tweetfleet.slack.com

**Comment by krojew** [comment]
The user which submitted this bug to me (https://bitbucket.org/krojew/evernus/issues/321/failed-to-import-wallet-transactions-since) hasn't responded yet, unfortunately.

**Comment by krojew** [comment]
Got the id: 95867007
