### ISSUE TITLE
X-Pages Header doesn't get sent for  get /markets/{region_id}/orders/ 

### ISSUE THREAD

**Issue by drkthunder02** [ccpgames/esi-issues#567]
When pulling the headers from /markets/{region_id}/orders/ end point from the latest ESI revision through the ESI Swagger Interface page by CCP and in my own library, the X-Pages header item does not get transmitted in the headers of the cURL request.

**Comment by ccp-zoetrope** [comment]
I'm not able to reproduce this, which region ID are you using?

**Comment by aquarhead** [comment]
Be ware pagination only works if `order_type=all` (which is the default) (for now)

![image](https://user-images.githubusercontent.com/222272/30804335-9a48c554-a1dc-11e7-8e1a-6b429aaaa2f8.png)

**Comment by aquarhead** [comment]
Sorry, pagination only works if you don't pass in a `type_id`

**Comment by drkthunder02** [comment]
10000002

Steps to reproduce error.

Go to https://esi.tech.ccp.is
Enter region id of 10000002
Type id of 34
Click Try It Out button
Scroll down to headers portion and no x-pages is found.

**Comment by aquarhead** [comment]
Yes, you set `type_id` to 34, which disables `X-Pages`. (for now)

Currently, if you give it a `type_id` it just (tries) to list all orders for that type in that region (in 1 page).

Added more things in #536 to track this.
