### ISSUE TITLE
Request - Crest fleet end point

### ISSUE THREAD

**Issue by Dusty-Meg** [ccpgames/esi-issues#57]
Request for the crest fleet endpoint to get moved over to ESI.
As a side note would it be possible to have a nearest celestial added to the fleet member call?

**Comment by aquarhead** [comment]
> As a side note would it be possible to have a nearest celestial added to the fleet member call?

Can you expand this request with an example?

**Comment by erittainvarma** [comment]
If the fleet endpoint is going to be implemented same way it's on CREST, nearest celestial info is pretty useless as CREST fleet endpoint is too slow for even system info to have real value for FC.

Nearest celestial would be great addition to character location though.

**Comment by Regner** [comment]
That would require having the location nodes include that information in their updates to the fleet node and the fleet node storing the information.

**Comment by polarina** [comment]
I would suggest getting the list of celestials from the SDE and compute the nearest one based on the X, Y, and Z coordinates in the application that needs this information.

**Comment by Dusty-Meg** [comment]
An example would have been:

**Comment by Dusty-Meg** [comment]
An example would be:
"solarSystem": {
        "id_str": "30003729",
        "href": "https://crest-tq.eveonline.com/solarsystems/30003729/",
        "id": 30003729,
	"nearest_celestial": KBP7-G III,
        "name": "KBP7-G"
      },
However as polarina said just having the X,Y,Z Coordinates would work just as well.
If this is not possible then I will attempt to come up with a different way of doing it but the backstory of the request comes from.
https://forums.eveonline.com/default.aspx?g=posts&m=6678731

**Comment by StephenSwat** [comment]
In addition to this, something that I felt was missing in the CREST API was the ability to add a fleet member to the watchlist automatically.

**Comment by aquarhead** [comment]
@StephenSwat Currently the fleet endpoint only allow the fleet boss to operate, so the watchlist thing won't really help much?
