### ISSUE TITLE
Document the /verify endpoint

### ISSUE THREAD

**Issue by ddouglas493** [ccpgames/esi-issues#571]
# Feature request

When I have been lurking in #esi, i keep seeing references to a /verify endpoint. I am not sure what it is used for (Verifying Access Tokens/ Auth Codes?) and I cannot find any documentation on it in the Swagger Spec nor in the issues. Please document this endpoint some where so everybody can use it.

*Edit: Grammer

**Comment by Dusty-Meg** [comment]
https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/obtaincharacterid.html

**Comment by itshouldntdothis** [comment]
https://esi.tech.ccp.is/swagger.json is the ESI meta info spec.

**Comment by fuzzysteve** [comment]
/verify is the same as the endpoint in https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/obtaincharacterid.html

But actually works with CORS headers. :D

**Comment by ddouglas493** [comment]
Thanks Steve.
