### ISSUE TITLE
Asset Endpoint returns Negative Quantity for Plastic Wrap

### ISSUE THREAD

**Issue by ddavaham** [ccpgames/esi-issues#580]
# Bug

### Request

/v1/characters/{character_d}/assets/

### Response

```
    {
        "type_id": 3468,
        "location_id": 60003760,
        "location_type": "station",
        "item_id": 1025601457889,
        "location_flag": "Hangar",
        "is_singleton": false,
        "quantity": -1500000
    },
    {
        "type_id": 601,
        "location_id": 1025601457889,
        "location_type": "other",
        "item_id": 1024292122448,
        "location_flag": "AutoFit",
        "is_singleton": true
    },
```

### Expected

The quantity of items in the package, quantity = 1, no quantity, I honestly do not know.

¯\_(ツ)_/¯

**Comment by tsuthers-ccpgames** [comment]
Hrm, I'm looking into this now as part of resolving https://github.com/ccpgames/esi-issues/issues/792 but I can't reproduce it. I've tested with both single and double-wrapped courier contracts.

Can you confirm this is still an issue?

**Comment by ddavaham** [comment]
I'll check this morning.

**Comment by ddavaham** [comment]
Not seeing the issue anymore. It was a stupid basic courier, I am not sure what went wrong. I remember I asked Snowy about it and he told me to create this. Closing now as unable to reproduce. Thanks for Pinging me.
