### ISSUE TITLE
Unable to fetch structure orders

### ISSUE THREAD

**Issue by krojew** [ccpgames/esi-issues#581]
# Bug

Something has changed to the /v1/markets/structures/{structure_id}/ endpoint. Previously it returned a "Market access denied" error in case a citadel wasn't open to particular person. Now, there's a TON of such errors, and it gets worse - future requests get terminated with:

"You have exceeded the error limit for ESI. Please make a greater effort in the future to receive valid responses. For tips on how, come have a chat with us in #esi on tweetfleet slack. If you're not on tweetfleet slack yet, you can get an invite here -> https://www.fuzzwork.co.uk/tweetfleet-slack-invites/"

If valid requests are terminated like this, because earlier requests were denied - there's a logical problem, because the app doesn't know which citadels are available before asking. If that fails, asking proper citadels also fails, therefore there's effectively no way to fetch orders from citadels.

### Request

/v1/markets/structures/{structure_id}/ 

### Response

A ton of:

"Market access denied"

followed by:

"You have exceeded the error limit for ESI. Please make a greater effort in the future to receive valid responses. For tips on how, come have a chat with us in #esi on tweetfleet slack. If you're not on tweetfleet slack yet, you can get an invite here -> https://www.fuzzwork.co.uk/tweetfleet-slack-invites/"

### Expected

"Market access denied" for unavailable citadels and proper order list for open ones.

**Comment by ETristram** [comment]
Highlighted that issue in #560, no CCP response so far...

**Comment by jowrjowr** [comment]
you are hitting error rate limits.

**Comment by ccp-zoetrope** [comment]
The error limiting @jowrjowr is referring to was talked about in [this blog](https://developers.eveonline.com/blog/article/esi-error-limits-go-live) and is explained in more details in [this blog](https://developers.eveonline.com/blog/article/error-limiting-imminent). The TLDR is that if you generate more than 100 errors (an error is in the 4xx and 5xx range) within a 60 second window your software will be error limited with a 420 response until that 60 second window has elapsed. 

Until we can make an endpoint that does something similar to what was suggested in #560 then you will have to make sure your app spreads its requests over time a bit more. You could do this by caching info like who has access to which citadel.

**Comment by krojew** [comment]
I know I'm hitting the limit, but the issue is not about that, but the logical problem it introduces. The only way to know which citadels are available is to actually make a request. I also cannot rate limit and cache such info, because this will make the import practically synchronous, since every request depends on potential error of previous ones.

**Comment by cvweiss** [comment]
I'm curious, how often are you getting new citadel IDs? Yes, you'll need to check, but once you get an error, you won't need to check again at all, or for a few days if you want to see if access has opened up. You should be able to easily limit this down to <100 errors per minute.

**Comment by krojew** [comment]
That's not practical for few reasons:

- In theory this data might change at any time. It might be acceptable to have it stale for some time, but that can introduce problems if someone is in a hurry.
- The bigger problem is the limit itself - Evernus makes thousands of requests per second and it's absolutely impractical to having it wait a full minute after each 100 requests. In a minute you can easily import whole regions of data. With e.g. 100k requests guess how much time will be wasted for initial import (or every, in case of no caching). This is unacceptable for the users.
- Given the first point, you can hit 100 limit even with caching (when permissions change). This implies every import should check the results of previous requests, which in effect makes everything synchronous. Otherwise you'll hit the limit wall and have to wait to repeat everything again. Totally impractical for the users.

**Comment by krojew** [comment]
Until we get a proper way to get a list of available citadels, could error limiting be disabled for this particular use case?
