### ISSUE TITLE
characters/{id}/notifications/ issue

### ISSUE THREAD

**Issue by Jimmy062006** [ccpgames/esi-issues#583]
If you request 
```
https://esi.tech.ccp.is/latest/characters/804998826/notifications/
```

with a token I get.

```
Response Body
{
  "error": "Unhandled internal error encountered!"
}

Response Code
500
```

Was told to report it here for CCP SnowedIn

**Comment by antihax** [comment]
Have same issue right now apparently. Many many characters.

**Comment by aquarhead** [comment]
We have identified the issue. However this would need a monolith deployment to fix, so expect it after some DT.

**Comment by gitAskur** [comment]
I'll live fix this after DT once I've gotten the code to the proper places.

**Comment by gitAskur** [comment]
Temporary fix 'deployed' for this server run.

**Comment by Jimmy062006** [comment]
This still yields an error 500 but with results is this intended ?

```{
  "error": "Invalid 200 response: 'Unknown' is not valid, 'Unknown' is not valid, 'Unknown' is not valid, 'Unknown' is not valid, 'Unknown' is not valid, 'Unknown' is not valid, 'Unknown' is not valid, 'Unknown' is not valid, 'Unknown' is not valid, 'Unknown' is not valid",
  "response": [
    {```

```Response Code
500```

**Comment by gitAskur** [comment]
We also need to figure out what that unknown owner type is and fix the interface to supply whatever valid type that is.

**Comment by Jimmy062006** [comment]
I'm guessing this is the culprit

```    {
      "notification_id": 673338042,
      "type": "BillOutOfMoneyMsg",
      "sender_id": 2,
      "sender_type": "Unknown",
      "timestamp": "2017-09-26T11:07:00Z",
      "is_read": true,
      "text": "billTypeID: 2\ndueDate: 131510658600000000\n"
    }```

This notification type BillOutOfMoneyMsg appears 10 times all with sender_type Unknown

**Comment by gitAskur** [comment]
```
typeID    typeName
     2    Corporation
```

Pretty sure that's a typeID rather than ownerID in that senderID field. Not sure why right now, makes little sense to me and could easily just be the itemID of the corporation sending this notification and thus keep with the basic paradigm of EVE. But we can't have nice things all the time.

**Comment by gitAskur** [comment]
Nope, this is itemID 2. Item name EVE Central Bank, of typeID 0 - SYSTEM.

Would be better if this was itemID 1000132, Secure Commerce Commission, but sometthingsomethingsomething nice things and having them.

owner type "System" will have to be supported by ESI backend.

**Comment by gitAskur** [comment]
Salty Sailor-Jesus! We have to also support name lookups for SYSTEM typed 'owners' because of this.

**Comment by aquarhead** [comment]
@tsuthers-ccpgames let's discuss whether we should change the spec when you're back.

**Comment by Jimmy062006** [comment]
Guess I'll put my port to ESI on hold then 🗡

**Comment by a-tal** [comment]
added `other` to the sender_type enum to fix this for now

**Comment by aquarhead** [comment]
^ is already deployed
