### ISSUE TITLE
Failed to fetch access data on /markets/structures/{structure_id}

### ISSUE THREAD

**Issue by joshuataylor** [ccpgames/esi-issues#585]
# Bug
Failed to fetch access data

### Request
```
https://esi.tech.ccp.is/latest/markets/structures/60004588?datasource=tranquility
```
### Response
{"error":"Failed to fetch access data"}

### Expected
A list of station (structure) orders.

**Comment by krojew** [comment]
Got the same few minutes ago.

**Comment by joshuataylor** [comment]
You can't query NPC stations, not sure if you are doing that.

**Comment by krojew** [comment]
Nope, fetching citadels.
