### ISSUE TITLE
500 response due not matching the schema

### ISSUE THREAD

**Issue by curzonj** [ccpgames/esi-issues#588]
# Bug

### Request

`/v1/characters/{character_id}/wallet/journal/` where `character_id=92453716`

### Response

Status code 500

```
{
  "error": "Invalid 200 response: 'Unknown' is not valid",
  "response": [
.....
    {
      "balance": 1.0,
      "second_party_id": 92453716,
      "first_party_id": 2,
      "amount": 0.18,
      "date": "2017-09-24T23:08:51Z",
      "first_party_type": "Unknown",
      "ref_id": 14606574270,
      "second_party_type": "character",
      "ref_type": "corporation_dividend_payment",
      "extra_info": {
        "argument_value": 98189435
      }
    },
....
  ]
}
```

(Balance redacted)

### Expected

A 200 status code

```
first_party_type (string, optional): first_party_type string = ['character', 'corporation', 'alliance', 'faction'],
```

**Comment by itshouldntdothis** [comment]
This issue appears to have been resolved in the proceeding endpoint versions currently v4.

**Comment by tsuthers-ccpgames** [comment]
Yeah, there were quite a few issues with the v3 of this endpoint, but @ccp-zoetrope put in some frankly heroic work to improve it. I'm expecting this to be gone in v4, comment if you're still seeing it and I'll re-open it.
