### ISSUE TITLE
Wallet transactions schema incorrect

### ISSUE THREAD

**Issue by curzonj** [ccpgames/esi-issues#589]
# Bug

The `GET /characters/{character_id}/wallet/transactions/` swagger schema says:

* `"unit_price":{"description":"Amount paid per unit","format":"float","title":"get_characters_character_id_wallet_transactions_unit_price","type":"integer"}`

but the `integer` type contradicts the `float` format and causes clients to generate incorrectly.

The `GET /characters/{character_id}/wallet/journal/` swagger schema is the correct style with a `number` type:

* `"amount":{"description":"Transaction amount. Positive when value transferred to the first party. Negative otherwise","format":"float","title":"get_characters_character_id_wallet_journal_amount","type":"number"}`

**Comment by aquarhead** [comment]
Thanks for the report! I have no idea why our Swagger Codegen test shows no errors and the swagger validator claims it's valid.

I've fixed the `type` and seems [a spec diff tool](https://github.com/civisanalytics/swagger-diff) shows no conflict to current TQ spec, so I'll just push the changes to prod now.
