### ISSUE TITLE
Incorrect basePath in underscore json spec

### ISSUE THREAD

**Issue by lukasni** [ccpgames/esi-issues#590]
# Bug

Underscore swagger specs (`_latest`, `_dev`) incorrecly supply a `basePath` field of `/`, which leads to URLs like this being generated when running Swagger 2.0 codegen: `https://esi.tech.ccp.is//v2/search/`.

According to the OpenAPI 2.0 spec, the `basePath` field should be omitted to serve the API directly under the host.

### Request
- `https://esi.tech.ccp.is/_dev/swagger.json?datasource=tranquility`
- `https://esi.tech.ccp.is/_latest/swagger.json?datasource=tranquility`
- `https://esi.tech.ccp.is/_legacy/swagger.json?datasource=tranquility`
### Response
```json
{
"basePath": "/",
"definitions": {...},
"host": "esi.tech.ccp.is",
[...]
}
```

### Expected
```json
{
"definitions": {...},
"host": "esi.tech.ccp.is",
[...]
}
```

**Comment by a-tal** [comment]
this is fixed now. thanks
