### ISSUE TITLE
Unhandled internal error encountered

### ISSUE THREAD

**Issue by krojew** [ccpgames/esi-issues#592]
# Bug

### Request

/v1/markets/10000002/history/

type_id: 666

### Response

500 - "error": "Unhandled internal error encountered!"

### Expected

not 500

**Comment by aquarhead** [comment]
![image](https://user-images.githubusercontent.com/222272/31495353-d55f206c-af46-11e7-8f07-ecceb2daf14e.png)

Please request a valid type.

**Comment by krojew** [comment]
Shouldn't market history also return 422 "Type not found" , instead of 500 "Unhandled internal error encountered!"?
