### ISSUE TITLE
/characters/$character_id/ gives 500 for NPC character_ids

### ISSUE THREAD

**Issue by kriberg** [ccpgames/esi-issues#596]
# Bug

Looking up NPC characters in the /characters/$character_id/ endpoint gives internal server error.

If you pull Aliastra from the /corporations/$corporation_id/
`curl -i --compressed -X GET --header 'Accept: application/json' 'https://esi.tech.ccp.is/latest/corporations/1000111/?datasource=tranquility'
`

You will get 3004229 as ceo_id:
```javascript
{
  "corporation_name": "Aliastra",
  "ticker": "A",
  "member_count": 123894,
  "ceo_id": 3004229,
  "corporation_description": "A well-run retail company that has a broad inter-stellar scope, with operations in all the empires. Aliastra has not been able to compete domestically with FedMart, but has seen moderate success in other empires.",
  "tax_rate": 0.11,
  "creator_id": 1,
  "url": "None"
}
```

If you try to look up that character_id through /characters/names/, it will resolve to:
```javascript
[{
    "character_id": 3004229,
    "character_name": "Etaurtetel Ruyt"
}]
```

### Request
`curl -i --compressed -X GET --header 'Accept: application/json' 'https://esi.tech.ccp.is/latest/characters/3004229/?datasource=tranquility'`

### Response
```javascript
{
  "error": "Unhandled internal error encountered!"
}
```
### Expected

Either is should give 404, if it doesn't serve NPC characters or it should return the public info ala
```javascript
{
    "character_id": 3004229,
    "character_name": "Etaurtetel Ruyt"
  }
```

**Comment by aquarhead** [comment]
Same issue reported by another player:

> GET https://esi.tech.ccp.is/latest/characters/3000001/?datasource=tranquility resulted in a 500 Internal Server Error response: {"error":"Unhandled internal error encountered!"}

Whereas v3 endpoint works:

https://esi.tech.ccp.is/v3/characters/3000001/

**Comment by gitAskur** [comment]
Fix should be out in the wild now.
