### ISSUE TITLE
Bug: getCharacterContacts is returning data on pages that should be empty.

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#598]
Since around noon CST today, ESI started returning data on contact pages that should be empty resulting in some of my code running infinite loops over getCharacterContacts. It used to return an empty array on the last page.

Send help.

### Request
`GET https://esi.tech.ccp.is/v1/characters/95099207/contacts/?page=34`
### Response
```
Access-Control-Expose-Headers: Content-Type,Warning
Access-Control-Max-Age: 600
Alt-Svc: clear
Cache-Control: private
Content-Type: application/json
Date: Fri, 13 Oct 2017 01:21:08 GMT
Expires: Fri, 13 Oct 2017 01:25:04 GMT
Last-Modified: Fri, 13 Oct 2017 01:20:04 GMT
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
Via: 1.1 google
X-Esi-Error-Limit-Remain: 100
X-Esi-Error-Limit-Reset: 52
X-Pages: 1
[
{"standing":0.0,"contact_type":"character","contact_id":dfgdfghdfghdgh,"is_watched":true},
... names withdrawn to protect the soon to be dead people ...
]
```
### Expected
`[]`

**Comment by aquarhead** [comment]
You should really use the `X-Pages` header to determine how far you go, but we'll look into what happened

**Comment by antihax** [comment]
X-pages is not documented for this endpoint.

**Comment by aquarhead** [comment]
This should be fixed now, I will also address a few other endpoints to prevent this from happening in the future.

Thanks for the report :)
