### ISSUE TITLE
Setting autopilot way point disables autopilot in game

### ISSUE THREAD

**Issue by ReeseWang** [ccpgames/esi-issues#599]
# Bug

### Request

/ui/autopilot/waypoint/

### Result

The autopilot in the game is disabled if my ship is autopiloting.

### Expected

 Autopilot won't be disabled, instead, the autopilot will execute the new route afterward. This is the behavior when I'm setting a destination in the game UI.

**Comment by CarbonAlabel** [comment]
This was brought up before, and the reply we got from CCP was that it is intentional behaviour meant to prevent malicious apps from changing their users' autopilot destination without their consent.

**Comment by tsuthers-ccpgames** [comment]
This is not a bug, the feature was designed this way both for the reason Carbon gives above and also to prevent it from being used to directly automate gameplay.
