### ISSUE TITLE
Inconsistency - char/corp killmail endpoint cache timers

### ISSUE THREAD

**Issue by cvweiss** [ccpgames/esi-issues#606]
# Inconsistency

### Routes

    GET /characters/{character_id}/killmails/recent/
> This route is cached for up to 120 seconds

    GET /corporations/{corporation_id}/killmails/recent/
> This route is cached for up to 3600 seconds

### Description

These two endpoints should have similar cache timers, or at least much closer together. Taking into account that corporations can have many more killmails, I'd like to see corporation with a 10 or 15 minute cache timer.

Also, keep in mind that there is the potential for API verified characters to have more killmails than many corporations.

### Resolution

Bring the cache timers to be equal at 120 seconds, or at least reduce the corporation cache time to 600 - 900 seconds (10 - 15 minutes).

**Comment by aquarhead** [comment]
@gitAskur gives the green light, so I think we can at least reduce the corp endpoint to 5min or sth, maybe even bring the 2 endpoints to the same cache timer.

**Comment by ccp-zoetrope** [comment]
The cache time for this will be changed to 5 minutes after downtime tomorrow.

**Comment by cvweiss** [comment]
Awesome! Thanks!

**Comment by ccp-zoetrope** [comment]
Due to circumstances outside of my control the fix for this won't be deployed until Thursday.

**Comment by ccp-zoetrope** [comment]
Unfortunately I must burst your bubble once more and deliver the bad news that this will not be going out today. This has been downgraded to soon™ so I don't make anymore promises I can't keep :).

**Comment by cvweiss** [comment]
Well it is in the works, I can be happy with that :)

**Comment by ccp-zoetrope** [comment]
This has gone into effect as of now.
