### ISSUE TITLE
Bug in Character Assets: Trained skills and location_flag

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#608]
# Bug
Skill you have trained are included with the assets list
They used to have `"location_flag": "Skill"` now they have `"location_flag": "Module"`
It's important to be able to identify them as trained skill, so you can filter them out, if it's not info you want to include.

Until this get fixed, it would be super useful to know what else `"location_flag": "Module"` is used for, to know if it's safe to filter it out, like it is with `"location_flag": "Skill"`

### Request

https://esi.tech.ccp.is/latest/characters/987623974/assets/?datasource=tranquility&page=1

### Response
```
  {
    "type_id": 3300,
    "location_id": 987623974,
    "location_type": "other",
    "item_id": 987623975,
    "location_flag": "Module",
    "is_singleton": false,
    "quantity": 1
  },
```

### Expected
```
  {
    "type_id": 3300,
    "location_id": 987623974,
    "location_type": "other",
    "item_id": 987623975,
    "location_flag": "Skill",
    "is_singleton": false,
    "quantity": 1
  },
```

**Comment by ccp-zoetrope** [comment]
So "Module" should have always been "Skill" and has been changed in the v2 version of the characters assets endpoint. It will be promoted to latest in two weeks: https://esi.tech.ccp.is/dev/#!/Assets/get_characters_character_id_assets

**Comment by Blacksmoke16** [comment]
Does it make sense for skills to even BE in this endpoint at all?  What benefit is there vs using the /skills/ endpoint?
