### ISSUE TITLE
Bug in Assets: is_singleton is always false

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#610]
# Bug

Looks like `is_singleton` is always `false`, I don't have a single item that have `"is_singleton": true`
The example bellow is a Station Container, that contains assets...

### Request

https://esi.tech.ccp.is/latest/characters/987623974/assets/?datasource=tranquility&page=1

https://esi.tech.ccp.is/latest/corporations/1020386980/assets/?datasource=tranquility&page=1

### Response
```
  {
    "type_id": 17366,
    "location_id": 160882969,
    "location_type": "other",
    "item_id": 1004588290148,
    "location_flag": "CorpSAG2",
    "is_singleton": false,
    "quantity": 1
  },
```

### Expected
```
  {
    "type_id": 17366,
    "location_id": 160882969,
    "location_type": "other",
    "item_id": 1004588290148,
    "location_flag": "CorpSAG2",
    "is_singleton": true,
    "quantity": 1
  },
```

**Comment by kriberg** [comment]
Getting the same behaviour. Even items which have flags indicating they're fitted have is_singleton==false.

**Comment by ccp-zoetrope** [comment]
So the examples above, by the XML API's logic, would not be marked as is_singleton. The rules for "is_singleton" is if quantity < 0. Not sure why exactly, am still looking into what this is supposed to signify.

**Comment by polarina** [comment]
@ccp-zoetrope Singletons are non-stackable items.

**Comment by fuzzysteve** [comment]
Quantity below 0 is used for things like blueprints. -2 for copies, -1 for researched blueprints. for example. on the xml api you also had 'raw quantity'. iirc (I might have the copy/original the wrong way round)

**Comment by GoldenGnu** [comment]
Singleton: True is unpacked (not stackable), False is packed (stackable)
The only relation to quantity is if it’s above 1 or bellow 0 it should always be Singleton = True. But, it’s most useful for when quantity is 1

**Comment by ccp-zoetrope** [comment]
This fix is released and present in /v3/characters/{character_id}/assets/ and /v2/corporations/{corporation_id}/assets/

**Comment by CarbonAlabel** [comment]
@ccp-zoetrope I've noticed that these new versions have had their page sizes reduced from 5000 down to 1000 items. Why was this done?

**Comment by ccp-zoetrope** [comment]
@CarbonAlabel  The default and most performant pagination size for ESI has been determined to be 1000. If an endpoint is still passing around large sets of data then we usually bring them down to this default size unless there is a very good reason not to.
