### ISSUE TITLE
Corp/Char Market Orders: Parity

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#612]
# Parity

The ESI Market Orders endpoints for corporations and characters are missing data compared to the XML API.

The ESI endpoints only include active orders.

The XmlApi returned:
 - Orders that was completed immediately (there is no way to get those types of orders with ESI)
 - Active orders (this is what ESI returns)

The XmlApi also allowed you to get the order details of a single order by providing the OrderID.
That allowed you to get the order details for completed orders, not included in the default return.

### Route
https://esi.tech.ccp.is/latest/#!/Market/get_characters_character_id_orders
https://esi.tech.ccp.is/latest/#!/Market/get_corporations_corporation_id_o

### Use case

If you keep history of Market Orders, you need to know why and how each order was closed.
This is no longer possible with ESI, but, was possible with the XmlApi
Additional, orders that was completed immediately, are never included in ESI, leaving gaps in the history, this was also included in the XmlApi

### Previous XML route
http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/character/char_marketorders.html
http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/corporation/corp_marketorders.html

**Comment by ccp-zoetrope** [comment]
Just released https://esi.tech.ccp.is/ui/?version=latest#/Market/get_characters_character_id_orders_history and https://esi.tech.ccp.is/ui/?version=latest#/Market/get_corporations_corporation_id_orders_history allowing you to see a corporation's or character's cancelled or expired orders going 90 days back.

Also bumped https://esi.tech.ccp.is/ui/?version=dev#/Market/get_characters_character_id_orders and https://esi.tech.ccp.is/ui/?version=dev#/Market/get_corporations_corporation_id_orders to v2 which are now dedicated to only open orders with a cache timer of 20 minutes.
