### ISSUE TITLE
Missing scopes in SISI SSO

### ISSUE THREAD

**Issue by matthewpennell** [ccpgames/esi-issues#614]
The `/corporations/{corporation_id}/wallets/` and its sub-endpoints have a minor typo in the scope requirements. The Swagger spec states that it requires scope `esi-wallet.read_corporation_wallets.v1`, whereas the scope listed in the developers applications list is `esi-wallet.read_corporation_wallet.v1` (note singular "wallet", not "wallets").

As far as I can tell, the latter is correct, and therefore the Swagger spec is incorrect and needs to be updated.

**Comment by polarina** [comment]
The former is correct. Corporations have multiple wallets.

**Comment by matthewpennell** [comment]
Okay, but there is still an issue with the mismatched scope. When I try to sign in via SSO, passing the following scopes:

```php
'esi-industry.read_corporation_mining.v1',
'esi-wallet.read_corporation_wallets.v1',
'esi-mail.send_mail.v1',
'esi-universe.read_structures.v1',
```

I get the following error:

```json
{"error":"invalid_scope","error_description":"The requested scopes either don't exist, or are not valid for this client"}
```

My application has the exact same scopes set, apart from the typo mentioned above ("wallet" instead of "wallets"). I am therefore unable to authorise access to my application when passing the correct scope name.

**Comment by aquarhead** [comment]
You can edit your application's scopes:

![image](https://user-images.githubusercontent.com/222272/31856341-f0e2737a-b6ad-11e7-9d66-af1bfec1c2a7.png)

Also in the description I already explicitly said it's a legacy scope (`esi-wallet.read_corporation_wallets.v1`)

![image](https://user-images.githubusercontent.com/222272/31856337-d745458c-b6ad-11e7-80ad-ec8f64c457d0.png)

**Comment by matthewpennell** [comment]
Doesn't say that on the sisi developer side:

![image](https://user-images.githubusercontent.com/48792/31860164-06a1e4ec-b70e-11e7-93ab-c971fec4d4e3.png)

and the `read_corporation_wallets` doesn't exist in the list on developers.testeveonline.com.

**Comment by aquarhead** [comment]
Added all the missing scopes on Sisi as of now
