### ISSUE TITLE
Service Unavailable when fetching structure markets

### ISSUE THREAD

**Issue by krojew** [ccpgames/esi-issues#618]
# Bug

### Request

 https://esi.tech.ccp.is/v1/markets/structures/1022690772186/?page=1&datasource=tranquility

char id: 2112979466

### Response

Service Unavailable

### Expected

market orders

**Comment by ccp-zoetrope** [comment]
Here are more examples of structure IDs throwing the same error, putting it here before the slack gods delete them:
1022918594607
1021765226143
1022809618797
1022735802869
1022589338590
1022898422755
1022911899478
1022776127487

**Comment by rossos** [comment]
Another one giving the same error:

1021570510123

**Comment by ccp-zoetrope** [comment]
The fix for this should be out with the next deployment.

The fix that is being deployed will make these structures and structures like them return "Market Access Denied" instead of Service Unavailable. 

This is because of an edge case in our auth system.

**Comment by ccp-zoetrope** [comment]
Due to circumstances outside of my control the fix for this won't be deployed until Thursday.

**Comment by ccp-zoetrope** [comment]
Unfortunately I must burst your bubble once more and deliver the bad news that this will not be going out today. This has been downgraded to soon™ so I don't make anymore promises I can't keep :).

![I did my best](https://j.gifs.com/kRZ6PX.gif)

**Comment by ccp-zoetrope** [comment]
The fix for this has been deployed, your users should now be seeing a 403 with "market access denied" instead of a 503.

**Comment by warlof** [comment]
@ccp-zoetrope why should we get a 403 by attempting to retrieve data from public market ? ie : jita stations.

Is the endpoint covering citadels structures only ?

**Comment by tsuthers-ccpgames** [comment]
Structure endpoints only cover structures, yes. Public station market data can be queried on a regional basis from the /markets/{region_id}/orders/ endpoint.
