### ISSUE TITLE
Inconsistency: In the example data; structure market locationID is an NPC station and not a structureID from structures endpoint.

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#619]
# Inconsistency
The Structure Market example references an NPC station ` "location_id": 60005599,` and not one of the structures in the structure example `1000000017013`.

Could the example be changed to reference the locationID of `1000000017013` instead?

This affects my mock server used for testing.

**Comment by ccp-zoetrope** [comment]
Changed it do 1020988381992
