### ISSUE TITLE
Skills endpoint

### ISSUE THREAD

**Issue by dilutedsauce** [ccpgames/esi-issues#620]
# Feature request
Endpoints listing skills and their prerequisites

### Route
```/universe/skills/```
```/universe/skills/{skill_id}```

### Authentication
No authentication required, this is all universe information

### Use case

Creating skill trees 

### Example returns

```/universe/skills/```
would yield something like
```
{
  "application/json": [
    3373,
    11584,
    37796,
    37797,
    37798,
    37799,
    ...
  ]
}
```
then ```/universe/skills/37796/``` 
would yield something like 
```
{
  "application/json": {
    "group_id": 1545,
    "name": "Structure Missile Systems",
    "published": true,
    "omega_only":true,
    "requirements": [
      {
          "type_id":1544,
          "level":4
      }
    ]
  }
}

```
### Previous XML or CREST route
I've been told there is some xml skilltree endpoint which is comparable to this.

**Comment by dilutedsauce** [comment]
Oh I guess it should have attributes as well

**Comment by fuzzysteve** [comment]
right now you can get the requirements from the main universe types endpoint.

They're just attributes.

182,183,184,1285,1289,1290 for the required skillid
277,278,279,1286,1287,1288 for the required level

**Comment by dilutedsauce** [comment]
That is a truly remarkable way of storing that information. Still, for ease of converting preexisting apps from the xml api to esi it would be nice if there were a straightforward switch from one end point to another.

**Comment by fuzzysteve** [comment]
It's a space efficient way to store it :) And it fits everything else.

Things are either attributes, or effects. They show up one way or another.

**Comment by ccp-zoetrope** [comment]
The endpoints you need for this already exist and you can see which ones you need to use by looking at [https://ccpgames.github.io/esi-issues/XML_to_ESI#skilltree](https://ccpgames.github.io/esi-issues/XML_to_ESI#skilltree) 😄 However if you notice something that you need missing from these endpoints please make a new issue about that, but I think you should be covered by the existing endpoints.
