### ISSUE TITLE
Sometimes does not search in category solarsystem

### ISSUE THREAD

**Issue by hiveliberty** [ccpgames/esi-issues#621]
# Bug

### Request
https://esi.tech.ccp.is/latest/search/?categories=solarsystem&datasource=tranquility&language=en-us&search=XX9-WV&strict=false

### Response
"No reply within 10 seconds"
![evescreen001](https://user-images.githubusercontent.com/16673541/32104989-dfce0dd6-bb37-11e7-8dba-048de1b4969b.png)

### Expected
solarsystem id

**Comment by ccp-zoetrope** [comment]
It seems to be working now and looks to have been a performance problem around that time, sorry about that :)
