### ISSUE TITLE
Message ID in mail header is a long, but message ID argument in mail body request expects an int

### ISSUE THREAD

**Issue by deadlybulb** [ccpgames/esi-issues#622]
# Inconsistency

### Routes

GET /characters/{character_id}/mail/ - mail header request
GET /characters/{character_id}/mail/{mail_id}/ - mail body request

### Description

GET /characters/{character_id}/mail/ - mail header request

has this model for mail_id:

mail_id: {
description: "mail_id integer",
format: "int64",
title: "get_characters_character_id_mail_mail_id",
type: "integer"
}

while GET /characters/{character_id}/mail/{mail_id}/ - retrieve mail body

has this model for the mail_id argument:

{
description: "An EVE mail ID",
format: "int32",
in: "path",
name: "mail_id",
required: true,
type: "integer"
}

### Resolution

Determine whether long or int is correct, and change the two route models to match.

**Comment by deadlybulb** [comment]
It looks like many other endpoints have the same inconsistency with character ID which are listed as int32 in the parameters argument, but are int64 in many return types.

**Comment by a-tal** [comment]
all mail_ids should be int64 now. if i've missed any feel free to open another issue

thanks
