### ISSUE TITLE
Typo in wallet endpoints models

### ISSUE THREAD

**Issue by irwiss** [ccpgames/esi-issues#628]
/v1/corporations/{corporation_id}/wallets/{division}/journal/
/v2/characters/{character_id}/wallet/journal/
(may be elsewhere too)

tax_reciever_id -> tax_receiver_id 

Not a critical bug I suppose

**Comment by aquarhead** [comment]
:fail:

**Comment by a-tal** [comment]
thanks for the bug report. fixed in:

* /v2/corporations/{corporation_id}/wallets/{division}/journal/
* /v3/characters/{character_id}/wallet/journal/

didn't see this particular misspelling in any other endpoints with my grep-fu
