### ISSUE TITLE
Feature Request: Add support for HEAD verb in paginated endpoints

### ISSUE THREAD

**Issue by lukasni** [ccpgames/esi-issues#629]
# Feature request

Add support for the `HEAD` HTTP verb for paginated endpoints to streamline fetching data from those routes. This is currently supported by the CDN but not ESI itself, leading to somewhat unpredictable results (Status 200 if cached on CDN, 405 otherwise).

### Route

All paginated routes. At the time of this writing those are the following (going off `/_latest/swagger.json`)

```
/v1/alliances/{alliance_id}/contacts/
/v1/characters/{character_id}/assets/
/v1/characters/{character_id}/contacts/
/v1/characters/{character_id}/mining/
/v1/corporation/{corporation_id}/mining/observers/
/v1/corporation/{corporation_id}/mining/observers/{observer_id}/
/v1/corporations/{corporation_id}/assets/
/v1/corporations/{corporation_id}/blueprints/
/v1/corporations/{corporation_id}/bookmarks/
/v1/corporations/{corporation_id}/bookmarks/folders/
/v1/corporations/{corporation_id}/contacts/
/v1/corporations/{corporation_id}/containers/logs/
/v1/corporations/{corporation_id}/contracts/{contract_id}/bids/
/v1/corporations/{corporation_id}/customs_offices/
/v1/corporations/{corporation_id}/industry/jobs/
/v1/corporations/{corporation_id}/medals/
/v1/corporations/{corporation_id}/medals/issued/
/v1/corporations/{corporation_id}/orders/
/v1/corporations/{corporation_id}/roles/history/
/v1/corporations/{corporation_id}/shareholders/
/v1/corporations/{corporation_id}/standings/
/v1/corporations/{corporation_id}/starbases/
/v1/corporations/{corporation_id}/starbases/{starbase_id}/
/v1/corporations/{corporation_id}/structures/
/v1/markets/structures/{structure_id}/
/v1/markets/{region_id}/orders/
/v1/markets/{region_id}/types/
/v1/universe/groups/
/v1/universe/types/
/v1/wars/{war_id}/killmails/
/v2/characters/{character_id}/blueprints/
```

### Authentication

Same as GET request to the respective routes.

### Use case

Mainly useful for streamlining code when fetching a full list of all records from a paginated endpoint. Currently it's necessary to either first request Page 1, then iterate over the remaining pages or to set the loop end condition after fetching the first page. 

### Example returns

`curl --head "https://esi.tech.ccp.is/v1/markets/10000002/orders/?datasource=tranquility&page=1" -H "accept: application/json"`
```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,X-User-Agent
Access-Control-Allow-Methods: GET,HEAD,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type,Warning
Access-Control-Max-Age: 600
Content-Length: 2165355
Content-Type: application/json
Date: Wed, 01 Nov 2017 10:02:58 GMT
Expires: Wed, 01 Nov 2017 10:05:27 GMT
Last-Modified: Wed, 01 Nov 2017 10:00:27 GMT
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Esi-Error-Limit-Remain: 100
X-Esi-Error-Limit-Reset: 3
X-Pages: 29
Via: 1.1 google
Cache-Control: public
Age: 7
Alt-Svc: clear
```

### Previous XML or CREST route
N/A

**Comment by lukasni** [comment]
Summarizing a slack conversation with @aquarhead, this is of very limited usefulness, as it tends to only add on additional requests. Only use-case where it would marginally reduce bandwidth would be `X-Pages: 0`, where it would avoid sending the truly earth-shattering body of `[]`.

**Comment by a-tal** [comment]
done
