### ISSUE TITLE
Bug: Character Journal uncaught exception

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#631]
# Bug
I have a user that report error on the character journal endpoint

### Request
https://esi.tech.ccp.is/latest/#!/Wallet/get_characters_character_id_wallet_journal
Reproduce with the character `Synodos Lunastice`
### Response
```
500
```
```
 {"error":"uncaught exception"}
```

### Expected
Journals...

### Extra Info
My guess is that the endpoint needs to be updated with the latest `ref_type` (more stuff was added with the latest release, but, this endpoint was not updated to reflect that - Xml was, though)

**Comment by ccp-zoetrope** [comment]
The missing ref types have been added so you should not be seeing this error anymore.
