### ISSUE TITLE
Bulk item data endpoint

### ISSUE THREAD

**Issue by krojew** [ccpgames/esi-issues#633]
# Feature request

### Route

/universe/whatever

### Authentication

none

### Use case

Currently there are inconsistencies in ESI vs SDE. It would be great to be able to get SDE-like bulk type information about existing types. Essentially - the same thing which returns info about a specific type, but in bulk for everything.

**Comment by a-tal** [comment]
this issue is too vague as written. if there's something specifically that you'd like to discuss, data in the SDE that you'd like exposed through ESI, etc, please open an issue detailing that.
