### ISSUE TITLE
Starbases endpoints: No strontium appearing under fuel

### ISSUE THREAD

**Issue by irwiss** [ccpgames/esi-issues#642]
## Bug: No strontium is appearing under `/corporations/{corporation_id}/starbases/{starbase_id}/` under fuels

The strontium exists in-game and the xml api correctly returns the strontium amounts.

Snippet from the output (same occurs on ~12 POSes in different systems):
```
{
  "fuel_bay_view": "starbase_fuel_technician_role",
  "fuel_bay_take": "config_starbase_equipment_role",
  "anchor": "config_starbase_equipment_role",
  "unanchor": "config_starbase_equipment_role",
  "online": "config_starbase_equipment_role",
  "offline": "config_starbase_equipment_role",
  "allow_corporation_members": true,
  "allow_alliance_members": true,
  "use_alliance_standings": false,
  "attack_if_other_security_status_dropping": false,
  "attack_if_at_war": true,
  "attack_standing_threshold": 0.1,
  "fuels": [
    {
      "type_id": 4312,
      "quantity": 5260
    }
  ]
}
```

Let me know if you need more details

**Comment by ccp-zoetrope** [comment]
The fix for this has been integrated into our internal processes and will be out soon™.

**Comment by ccp-zoetrope** [comment]
The fix for this has been deployed and you should be seeing strontium now in the returned fuels.

**Comment by ccp-zoetrope** [comment]
Psych! But seriously I mistakenly thought this was out but it's not yet. Sorry for that!

**Comment by ccp-zoetrope** [comment]
This is now out for realsies so you should be seeing strontium show up now.
