### ISSUE TITLE
Resolve location_id from corporations/{corporation_id}/assets/ to citadel name

### ISSUE THREAD

**Issue by heggi** [ccpgames/esi-issues#643]
Endpoint /corporations/{corporation_id}/assets/ return array of items, where location_id is some number.
How to get citadel/station name where item is located, if location_flag is CorpSAGx?

Endpoint /universe/structures/{structure_id}/ return error 403

**Comment by Aidansavage** [comment]
https://esi.tech.ccp.is/latest/#!/Assets/post_corporations_corporation_id_assets_locations for corp assets.

**Comment by heggi** [comment]
This not work.
For example I have 
https://esi.tech.ccp.is/latest/corporations/xxx/assets/?datasource=tranquility&page=1
```
{
    "type_id": 34,
    "location_id": 1024956763219,
    "location_type": "other",
    "item_id": 1025842514958,
    "location_flag": "CorpSAG4",
    "is_singleton": false,
    "quantity": 94902299
  }
```

Try 
`curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer xxxxx' -d '[1024956763219]' 'https://esi.tech.ccp.is/latest/corporations/xxxxx/assets/locations/?datasource=tranquility'`
Response: error 404, 
```
{
  "error": "Invalid IDs in the request"
}
```

P.S. corporations/{corporation_id}/assets/names/ beautiful work for ship's names

**Comment by Aidansavage** [comment]
Use the right itemID perhaps? If it's telling you that using the loc_id is wrong, did you try using item_id? https://esi.tech.ccp.is/latest/#!/Assets/post_corporations_corporation_id_assets_locations says to use an array of item ids under parameters, not location ids.

**Comment by heggi** [comment]
I found solution
`https://esi.tech.ccp.is/latest/corporations/xxx/assets/?datasource=tranquility&page=1`
return 
```
...
{
    "type_id": 34,
    "location_id": 1024956763219,
    "location_type": "other",
    "item_id": 1025842514958,
    "location_flag": "CorpSAG4",
    "is_singleton": false,
    "quantity": 94902299
},
...
{
    "type_id": 27,
    "location_id": 1023447625143,
    "location_type": "other",
    "item_id": 1024956763219,
    "location_flag": "OfficeFolder",
    "is_singleton": false,
    "quantity": 1
  },
...
```
Founding location_id 1024956763219 has array item with item_id=1024956763219 which is "OfficeFolder" and location_id of this OfficeFolder is a structure_id 

```
curl -i --compressed -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer xxx' -d '[1023447625143]' 'https://esi.tech.ccp.is/latest/corporations/xxx/assets/names/?datasource=tranquility'
[
  {
    "item_id": 1023447625143,
    "name": "My citadel"
  }
]
```

**Comment by ccp-zoetrope** [comment]
Closing because it looks like you found a solution.
