### ISSUE TITLE
EVE Swagger interface site endpoint indicators (lights) not working

### ISSUE THREAD

**Issue by matthewpennell** [ccpgames/esi-issues#647]
The endpoint status 'lights' are not working - every endpoint currently reports grey, despite requests working as expected.

![image](https://user-images.githubusercontent.com/48792/32601854-f5eb719a-c53b-11e7-82ef-00ac2362b496.png)

**Comment by ccp-zoetrope** [comment]
/status.json is also not working for the same reason as the lights aren't working.

**Comment by a-tal** [comment]
this is fixed, thanks @matthewpennell
