### ISSUE TITLE
Feature Request: wallet/journal does not return refTypeID, instead it returns a string

### ISSUE THREAD

**Issue by kilgarth** [ccpgames/esi-issues#650]
The XML API has always returned an integer refTypeID for entries. The ESI wallet journal endpoint is returning a string ref_type instead of the integer, and there is no way to get the integers to even perform any kind of mapping. The result of this is that there is no way to translate the string type to the integer type which means it is very difficult to implement anything that uses the ESI wallet endpoints to insert data into anything that was designed for the XML API. 

There should either be an endpoint that gives us a list of string -> int types or the wallet journal output should include the int refTypeID.

**Comment by CarbonAlabel** [comment]
https://gist.github.com/CarbonAlabel/321334fe78f41ff28786fe7c4719ae8b

**Comment by ccp-zoetrope** [comment]
We're not going to make an endpoint specifically for the purpose of translating a ref_type string to int, however we can make the string->int mapping public so you do not have to guess anymore. I put the mapping in this gist: [https://gist.github.com/ccp-zoetrope/c03db66d90c2148724c06171bc52e0ec](https://gist.github.com/ccp-zoetrope/c03db66d90c2148724c06171bc52e0ec). I have also updated the documentation for ref_type in the wallet journal endpoints to have a note about this.

**Comment by antihax** [comment]
So what happens when new ref_types are added?

**Comment by ccp-zoetrope** [comment]
This is only a temporary measure. There have been talks about possibly open sourcing the repo we use for consts like this which would be a more permanent fix, but that is still TBD.

**Comment by Blacksmoke16** [comment]
Wouldn't a better solution be to just include this kind of stuff in the SDE export as another YAML file or something?

**Comment by tsuthers-ccpgames** [comment]
People should only need these refTypeID magic numbers to assist them in the transition from ESI. There are multiple reasons for wanting to abstract these numbers away from third party devs, one of them being that we might want to remap them one day without breaking all your stuff.

Putting them in the SDE would a) be heavyweight b) make the SDE an important part of the documentation when we're actively attempting to sideline the SDE into an "advanced users only" position c) imply that using the magic numbers is somehow good practice.

I want to show people the mappings to assist devs with transitioning XML API applications to ESI, but everyone should definitely be working to remove or abstract these numbers from their own code. If you want to internally cast the strings back to an enum of some kind that's up to you of course, but directly piping our internal const values to you is an inappropriately leaky abstraction layer.

@antihax When new reftypes crop up we get automated alerts and can append them to the existing endpoints without needing to bump the endpoint version. We've done this several times already on several different endpoints.

**Comment by GoldenGnu** [comment]
Some of the IDs that are now String/Enum are actually in the SDE:
Assets Flags are in the SDE, and that is useful, because, you get the exciact in-game name of the flags (in return of the flag ID), instead of some string constant that may or may not match what is in-game.

Enum are just as good as IDs, but, we still need a way to convert the constant to the exact in-game name.

As, I have said before, this is a minor inconvenience for me and I really love working with ESI and appreciate all the effort put into it :)

**Comment by a-tal** [comment]
for anyone in the future: https://github.com/ccpgames/eve-glue/blob/master/eve_glue/wallet_journal_ref.py
