### ISSUE TITLE
ESI's CORS policy does not expose X-Pages or other custom ESI headers

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#656]
# Bug

### Description
The `Access-Control-Expose-Headers` header returned by ESI doesn't list the `X-Pages` or the ESI error limit headers, making it impossible to access their values in browser apps.

**Comment by Aidansavage** [comment]
This would depend on the app's framework I think. Even so, if you know the name of the header already, there should be ways to directly access it based on which language you use. X-Pages _is_ exposed as a header already, which should mean it shows up in a response and/or header object.

**Comment by fuzzysteve** [comment]
The issue is that CORS masks it from the javascript which is calling it in browser apps. This includes the error headers too.

**Comment by a-tal** [comment]
thanks, updated to:

`access-control-expose-headers: Content-Type,Warning,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset`
