### ISSUE TITLE
Loyalty Point store returns iskCost as float32/number when it should be integer. akCost is also missing.

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#659]
# Inconsistency
The loyalty point store endpoints return iskCost as float32/number when they are integer both in game, and in CREST (and even in the swagger model example).
akCost is also missing.

http://eveonline-third-party-documentation.readthedocs.io/en/latest/crest/eve/eve_loyaltystore.html
http://puu.sh/yp4Yc/455ff75bff.jpg

### Routes
https://esi.tech.ccp.is/latest/#!/Loyalty/get_loyalty_stores_corporation_id_offers

### Resolution
Change iskCost spec to integer and add akCost

**Comment by a-tal** [comment]
in staging. the new type is `integer/int64`
