### ISSUE TITLE
ability to list corp/alliance-owned structures

### ISSUE THREAD

**Issue by wtfrank** [ccpgames/esi-issues#66]
Currently its possible to retrieve a list of public structures.

Its also possible to retrieve info about any structure that you are able to dock at, if you know that structure's ID.

It would be useful to be able to retrieve a list of structures owned by the player's corporation/alliance. Or perhaps a list of any structure that the player is explicitly included in the ACL of.

**Comment by polarina** [comment]
Suggestion: These endpoints would return an array of structure IDs.

* `/characters/{character_id}/structures/`
* `/corporations/{corporation_id}/structures/`
* `/alliances/{alliance_id}/alliances/`

**Comment by ccpStuart** [comment]
Corporation done, wont do character or alliance
