### ISSUE TITLE
Timestamps on ESI-Contracts are prefilled with invalid data

### ISSUE THREAD

**Issue by ddavaham** [ccpgames/esi-issues#660]
# Bug

### Request

Any Contract

### Response

```
 +"type": "courier"
  +"status": "outstanding"
  +"for_corporation": false
  +"availability": "personal"
  +"date_issued": "2017-11-19T22:22:59Z" <<---
  +"date_expired": "2017-11-22T22:22:59Z" <<---
  +"start_location_id": redact
  +"end_location_id": redact
  +"title": "FEPL:FQH5YMF3MMAJFVD"
  +"date_accepted": "2017-11-19T22:22:59Z" <<---
  +"days_to_complete": 7
  +"date_completed": "2017-11-19T22:22:59Z" <<---
```

### Expected

Correct Date Timestamps and or null values or not included in the output if the event that generates that timestamp has not taken place i.e. accepting the contract and delivering a contract.

**Comment by GoldenGnu** [comment]
Workaround:
Check if `date_issued` equals `date_accepted`/`date_completed` to check if it's accepted/completed.

Fix:
Both `date_accepted` and `date_completed` should return null, it's not accepted/completed, yet (both are optional).  `date_issued` and `date_expired` return the correct value, as far as I know.

I need this fixed to...

**Comment by Blacksmoke16** [comment]
👍 A quick fix would be much appreciated :)

**Comment by a-tal** [comment]
PR submitted, in review

**Comment by a-tal** [comment]
resolved

**Comment by ddavaham** [comment]
\o/
