### ISSUE TITLE
500 error on /corporations/{corporation_id}/wallets/{division}/journal/

### ISSUE THREAD

**Issue by angel8878** [ccpgames/esi-issues#661]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

# Bug
got a 500 response code when submitting /corporations/{corporation_id}/wallets/{division}/journal/

"error": "Invalid 200 response: 'system' is not valid, 'system' is not valid, 'system' is not valid, 'system' is not valid",

### Request
/corporations/{corporation_id}/wallets/{division}/journal/

### Response
"error": "Invalid 200 response: 'system' is not valid, 'system' is not valid, 'system' is not valid, 'system' is not valid",

### Expected
should be return 200: OK

**Comment by ccp-zoetrope** [comment]
Can you paste the whole response including the data with things you want to stay secret removed? I would like to see the structure of the JSON returned to you.

**Comment by GoldenGnu** [comment]
@ccp-zoetrope 
Messaged you a result on slack.
I think the problem is: ```"second_party_type":"system",```

**Comment by ccp-zoetrope** [comment]
This has been fixed now and you should not be seeing this as a 500 anymore.
