### ISSUE TITLE
Asset name for corp container does not refresh via ESI when renamed in game using same character

### ISSUE THREAD

**Issue by ponderzgaming** [ccpgames/esi-issues#662]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

# Bug
Asset name for container does not refresh via ESI when renamed in game.
However, if i log out the same character and log back in, ESI will then return the correct names.

Steps
---
1- Game: Login with character in game. Use same character for ESI.
2- ESI: Fetch item_id for a container and fetch the name for that container.
3- Game: Rename that container.
4- ESI: Run asset names with item_id. Notice name is the same.
6- Game: Log off character.
7- ESI: Run asset names with item_id. Notice name is updated. If it is not, try logging in and try again.

### Request
/corporations/{corporation_id}/assets/names/

### Expected
Updated name

**Comment by DaneelTrevize** [comment]
`get /corporations/{corporation_id}/assets/ ` has a cache timer of 3600 seconds. Is this simply that /names/ doesn't list what its is? The reproduction steps don't seem to eliminate a simple short cache timer being in effect.

**Comment by ponderzgaming** [comment]
Hi,

The asset exists, however the name did not change.

Is the cache timer for the logged user only, or all users, and does it reset at some point ?

I ran the test many times for at least 10 minutes, with same result.
However, the moment i logged out of Eve client, ESI had the change available.

I will run my test again, and maybe I can post part of the output logs.

**Comment by ponderzgaming** [comment]
Ah, here is the path /corporations/{corporation_id}/assets/names/ i use.

I will get more info in a bit.

**Comment by ponderzgaming** [comment]
I actually do not need to logout for a 100% repro .

I data from ESI get once i undock, so it seems to be session related. It's the same annoying bug we always have when I change a name of a corp container in a station, and my other accounts still doe not see the new name.

I had to redock to get new name appear on other accounts.

So what I did this time is:
1- Move a packaged container into a corp hanger
2- Unpackage it, but not rename it yet.
  * At this point ESI does not see any assets in the Trade hanger yet.
3- Undock and dock back in Citadel.
4- Observe that ESI will now see the new asset.

2017-11-22 15:36:22,079: INFO: __main__->test_fetch_corp_asset_containers: location_path=['Trade'] item_id=[1026083891704] item_name=[] <<<<< This is correct after redock. However it woudl be cool if it displayed the default name "Giant Secure Container"

I will now test rename it from here.

**Comment by ponderzgaming** [comment]
Ok, I now understand better whats going on.

ESI; will not see any changes for at least 5-60 minutes for names, and 5-10 minutes for asset location. i.e. moved container to another location, regardless if i change sessions or relog into the game. 

EVE client; however, will not see the change on my other logged in accounts to the names of the containers **unless** I relog into the game again.

So, i guess not much to do but wait up to, but no more than 3600s?

**Comment by Blacksmoke16** [comment]
That's kinda the point of the cache timers.  If you make a request and see container name, the result wont change until the cache expires 3600s later.

**Comment by ponderzgaming** [comment]
So why is it that many times I see the changes within minutes. I never had to wait 1 hour to see changes in the game, only a few minutes.

**Comment by GoldenGnu** [comment]
Most likely the cache is per itemID, so, if the ItemID changes (repacking, unpacking will do that) you are able to get the new name instantly otherwise it won’t be updated until the cache expires. Moving does not change the itemID.

**Comment by Blacksmoke16** [comment]
Key word there _in the game_.  Of course you won't have to wait an hour in the game.  ESI however is not the game, it's an API.  Things are cached to make it more performant on CCP's end

**Comment by ponderzgaming** [comment]
@Blacksmoke16 I am aware of the differences, however I am saying changes are within minutes not 1 hour with ESI.

**Comment by ponderzgaming** [comment]
@GoldenGnu ok thanks, that would make sense. So by repacking it will release the item_id. One way around waiting for the cache to update.

**Comment by GoldenGnu** [comment]
Doing thinks to avoid the cache time may be against the developer license. I wrote that to help you understanding of why the cache time didn’t always apply, not to help you avoid the cache times. 🙂

**Comment by ponderzgaming** [comment]
Ah good point, I will do that too.

> ESI returns standard caching headers if the data is cached. Applications should notice and make use of these headers (expires and last-modified) on routes where they are provided.

Expires: Thu, 23 Nov 2017 12:11:36 GMT
Last-Modified: Thu, 23 Nov 2017 11:11:36 GMT
Date: Thu, 23 Nov 2017 16:33:30 GMT

What is this one for, should be using it ?
Access-Control-Max-Age: 600

I do cache a lot of that data, and use static download data where possible.

Thanks!

**Comment by ponderzgaming** [comment]
I read up a bit on HTTP caching, is:

Cache-Control: max-age=3600 => the same as => Access-Control-Max-Age: 600

I could not see any of the response having max-age=3600 in them.
All i get is Cache-Control: private or Cache-Control: public 

Should I be posting these questions somewhere else? :)

**Comment by antihax** [comment]
Best bet is here m8.
https://www.fuzzwork.co.uk/tweetfleet-slack-invites/ 
Channel #esi

**Comment by tsuthers-ccpgames** [comment]
You can see the cache timer in seconds on the ESI page, as here: https://esi-test.tech.ccp.is/ui/#/Assets/get_corporations_corporation_id_assets

"This route is cached for up to 3600 seconds"

The header you should be observing is "Expires", this tells you when the cache of the result you just got will expire. A quick skim of the code suggests that the cache is on the entire result, and we cache per route, which means if anyone who is authorized to call this endpoint calls it, the cache is primed for all other authorized users for the next hour. That means that even though you are correct that packaging and unpackaging the container will cause it to get a new item ID, I would not expect repackaging and unpackaging the container to refresh or bust the cache.

Just skimming the thread it sounds like there's no bug here, so I'm going to close the ticket.
