### ISSUE TITLE
Shorten Cache/Expire Cache on Jump Clone Activation on /characters/{character_id}/implants/ 

### ISSUE THREAD

**Issue by PrometheusSatyen** [ccpgames/esi-issues#663]
# Feature request

### Route
GET /characters/{character_id}/implants/ 

### Alteration
This route is currently cached for 3600 seconds (1 hour).

I would like this substantially shortened (60 seconds) or alternatively for the cache to be expired when a character activates a jump clone.

### Use case
I would like to use this endpoint to verify that the members of a fleet have an implant slotted. Data up to an hour old is really not sufficient for this in the age of instant jump cloning in citadels.

**Comment by Aidansavage** [comment]
Would it not be easier to just poll the /charid/clones/ endpoint instead? It lists each clone and what implants they have. 120 second cache.

**Comment by PrometheusSatyen** [comment]
@Aidansavage That endpoint lists your jump clones, it does not include any information on the current clone.

**Comment by tsuthers-ccpgames** [comment]
I have just lowered the cache timer on this to 5 minutes. I don't want to lower it further with everyone about to go on holiday, I'll check in after the new year and provided it's had no significant impact on performance we can talk about dropping it to two minutes, like clones.
