### ISSUE TITLE
Change list of object with ID into an array of the values

### ISSUE THREAD

**Issue by seraphx2** [ccpgames/esi-issues#666]
# Inconsistency

### Routes
/corporations/{corporation_id}/members/

### Description
In the rest of the API, when an array of IDs are being returned, they are sent back literally in an array. Instead, the route mentioned above is returning an object with a single property for the Id.

### Resolution
Make response consistent with the majority of other routes where a list of IDs is simply an array.

**Comment by a-tal** [comment]
this is already the case in dev
