### ISSUE TITLE
Location object created for consistency with other routes

### ISSUE THREAD

**Issue by seraphx2** [ccpgames/esi-issues#667]
# Inconsistency

### Routes
/characters/{character_id}/assets/locations/

### Description
In all other instances of position coordinates (x,y,z) they are returned as their own object.

### Resolution
Drop down the x,y,z properties into their own Position/Location object (property name is not consistent between endpoints either) and return it nested inside the main object.

**Comment by a-tal** [comment]
thanks, both the character and corporation asset location endpoints have an updated dev version now with a consistent position attribute

https://esi.tech.ccp.is/ui/?version=dev#/Assets/post_characters_character_id_assets_locations
https://esi.tech.ccp.is/ui/?version=dev#/Assets/post_corporations_corporation_id_assets_locations
