### ISSUE TITLE
Audit log containers' logs

### ISSUE THREAD

**Issue by polarina** [ccpgames/esi-issues#67]
Would love to have audit log containers' logs available via ESI. Would allow me to migrate my little tool over. :)

See https://api.eveonline.com/corp/ContainerLog.xml.aspx

Suggested route: `/corporations/{corporation_id}/assets/{item_id}/logs/`

**Comment by ccpStuart** [comment]
Remains on the backlog for xml api parity

**Comment by ccp-zoetrope** [comment]
@polarina Here is the link: https://esi.tech.ccp.is/latest/#!/Corporation/get_corporations_corporation_id_containers_logs. It works like the XML API endpoint did. This means it shows all audit logs for the previous 7 days in descending order. If you want a specific endpoint to put the {container_id} into and see only logs for a given container then please make a new feature request :)
