### ISSUE TITLE
[FEATURE REQUEST] Endpoint to determine if a structure is still anchor'd

### ISSUE THREAD

**Issue by ddavaham** [ccpgames/esi-issues#674]
# Feature request

### Route

`universe/structures/{structure_id}/anchored`

### Authentication

None

### Use case

Reduce hits against `universe/structures/{structure_id}` by allowing us to know if the structure is still anchored. 

**Example Case**
User joins corp. User logs into our site. User has asset in structure from last corp. User is no longer on the ACL for that structure, so our system is unable to resolve the name of the that structures id that we get from the Assets Endpoint. We have a schedule that routinely hits `universe/structures` with varying tokens attempting to resolve the id => name. We will never know if that structure even still anchor'd. Having this endpoint will allow for us to know if that ID still exists in the universe and if not, we dispose of the id.
 
### Example returns

[true, false]

### Previous XML or CREST route

None

**Comment by tsuthers-ccpgames** [comment]
Information that allows players to determine the existence of a structure is extremely sensitive. Even knowing that there is an increase in the rate of deployment can under some circumstances be strategically significant.

As such, we cannot create endpoints that confirm that a specific item ID is a structure without checking to see that the user is on the ACL for that structure. If you have characters that can access the structure then that's fair game, but if you've been locked out then we will respect the structure owners security decisions, and refuse to directly confirm the existence of the structure.

When it comes to assets in structures you can't see, when a structure is unanchored or destroyed, all assets inside are handled by the asset safety mechanic. Depending on where the structure is they might be dropped, destroyed, or safety wrapped and placed into the asset safety netherspace, but they should not remain in the structure (file a support ticket to get your inventory fixed if this is not true). Therefore if the assets endpoint says they are in the structure, you can derive that the structure is still in place.
