### ISSUE TITLE
ISK values in Float

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#679]
# Inconsistency
Using `Float` for ISK values, should be `Double`?
I'm not sure if they were left it out on purpose or not...
Note: Created new issue as requested in #356

### Routes
- [x] /characters/{character_id}/contracts/ 
- [x] /corporations/{corporation_id}/contracts/ 
- [x] /characters/{character_id}/orders/ 
- [x] /corporations/{corporation_id}/orders/ 
- [x] /characters/{character_id}/industry/jobs/ 
- [x] /corporations/{corporation_id}/industry/jobs/ 

### Description
The following still use `Float` for ISK values:
- character/corporation market orders `escrow`
- character/corporation industry jobs `cost`
- character/corporation contracts  `buyout`, `collateral`, `price`, `reward`

### Resolution
Change to `Double`

**Comment by a-tal** [comment]
this is fixed now. thanks for the descriptive and well-formatted issue
