### ISSUE TITLE
IP limits on applications

### ISSUE THREAD

**Issue by irwiss** [ccpgames/esi-issues#680]
# Feature request

I'd like to request an additional field in ESI application page for IP limits on which IPs api requests can originate from.

### Use case

Currently there's no way to see if your tokens are compromised, or even if you do know the only way to deal with it is nuking the entire app Id and starting from scratch.

I'd like to request a whitelist of ipv4/ipv6 that requests for particular application are allowed to come from, mostly for server apps - since they generally keep a fairly static ip.

### Example returns

Valid refresh / access token from ipv4/ipv6 and no whitelist specified -> no change

Valid refresh / access token from ipv4/ipv6 in whitelist -> no change

Valid refresh / access token from ipv4/ipv6 not in whitelist -> **deny access**

#### Optionally for the last case:
Allow specifying a backchannel url - to allow using the token revoke endpoint for compromised tokens, perhaps even not block at all but just notify that a token has been used outside of whitelisted IPs.

Example:
https://example.tld/esi-not-in-whitelist-alert/?token={token}&token_hint={access|refresh}&offending_ip={ip_that_failed}

**Comment by Aidansavage** [comment]
I think this is putting too much onus on CCP to manage security concerns for app devs that should be managed by the app devs.

That being said, even if a refresh token is compromised, the worst they can do would be revoke the token themselves on you. Anything else would require that they _also_ possess your client id/secret. If they DO possess those, ccp does have the ability to nuke and reset your application's client id/secret pair. Once those get changed, existing tokens for the old pair would no longer work. 

Access tokens? They'd be lucky to have the full 20 minutes of data access. And that's IF they're in the app's backend at the time of the refresh token being used to generate a new access token, which does mean the app dev's got pretty shitty security for their server side stuff.

**Comment by a-tal** [comment]
> ESI application page

there's no such thing, you have us confused with SSO.

https://github.com/ccpgames/sso-issues/issues
