### ISSUE TITLE
Feature request: Break end of year stats up

### ISSUE THREAD

**Issue by andimiller** [ccpgames/esi-issues#682]
# Feature request

### Route
/v1/characters/{character_id}/stats/

The 200 return type for this includes 290 fields, this is over the limit (of 255) on the JVM so I can't model this response as a class. If we could get things like combat, industry, market, mining, module, social and travel broken into subobjects this would stop blowing up my compiler, and make the endpoint a bit more friendly to use.

**Comment by a-tal** [comment]
lol java.

will take a look tho

**Comment by a-tal** [comment]
v2 breaks up the return:

https://esi.tech.ccp.is/ui/?version=dev#/Character/get_characters_character_id_stats
