### ISSUE TITLE
Characters Assets: strange location_id

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/esi-issues#684]
# Bug
Characters assets are returning some very strange values for `location_id`
Example: `9001359308000569359`

### Request
/characters/{character_id}/assets/ 
Reproduce with: `Neugeniko`
### Response
As It's not my own character, I can not produce a result via esi.tech.ccp.is.
The bellow are reconstructed via jEveAssets data and may not be 100% correct.
`location_id`, `item_id`, and `type_id` should be correct, though.
```
 {
    "type_id": 33077,
    "location_id": 9001359308000569359,
    "location_type": "other",
    "item_id": 1025271267554,
    "location_flag": "AutoFit",
    "is_singleton": true,
    "quantity": 1
  },
 {
    "type_id": 17931,
    "location_id": 9001352597000041864,
    "location_type": "other",
    "item_id": 1025056159281,
    "location_flag": "AutoFit",
    "is_singleton": true,
    "quantity": 1
  },
```

### Expected
No strange `location_id`

**Comment by tsuthers-ccpgames** [comment]
By the looks of it, your inventory is bugged. ESI is accurately reporting this item location as it is given in the DB, but obviously that value is not valid.

If this is your character, file a support ticket with the item ID's, and request a GM help you move them somewhere real.

**Comment by Neugeniko** [comment]
I've submitted support ticket #560452 to try get these items in a real location.

Cheers,
Neug

**Comment by GoldenGnu** [comment]
It’s a little unclear to me, if this have been fixed yet. If it’s not fixed, could you re-open the issue until it is fixed. Otherwise just confirming it’s fixed would be nice. 🙂

**Comment by ccp-zoetrope** [comment]
This has now definitely been fixed :)

**Comment by SpeedProg** [comment]
Is this fix in as they found out why some items are in strange locations or as in we just hide your bugged assets from you know and you will never get them back? :(

**Comment by GoldenGnu** [comment]
I can answer that:
It turned out that the first reply by tsuthers-ccpgames was not correct.
The true nature of the 9e18 assets, are that they're an artifact from a eve-online bug.
All the stuff you didn't manage to get from each exploration end up as 9e18 assets.
So, the correct thing is simply to hide them, as they don't exist in-game.

zoetrope may be able to explain it better, but, that is how I understand it
