### ISSUE TITLE
Feature Request: Change Corporate Mining Ledger Endpoint to Jr. Accountant , and pass dates as parameters

### ISSUE THREAD

**Issue by warriorsoul15** [ccpgames/esi-issues#688]
# Feature request

CCP Below is the corporate mining ledger endpoint, can I make 2 suggestions. First, this endpoint requires accountant. There are no bills to pay, can we change the requirement to Junior Accountant please?

Second, can we pass a time/date range in the request so we can request this information in a particular window of time?

GET
/corporation/{corporation_id}/mining/observers/{observer_id}/
Observed corporation mining

Paginated record of all mining seen by an observer

Alternate route: /dev/corporation/{corporation_id}/mining/observers/{observer_id}/

Alternate route: /legacy/corporation/{corporation_id}/mining/observers/{observer_id}/

Alternate route: /v1/corporation/{corporation_id}/mining/observers/{observer_id}/

This route is cached for up to 3600 seconds

Requires one of the following EVE corporation role(s): Accountant

**Comment by ddavaham** [comment]
I believe this issue came up once in conversation in #esi on Slack. Permissions for Endpoint MUST match what is in game. If you the client requires accountant to view the data in game, then ESI will require it as well. I don't know since i do not look at this data, even in game.

None of the endpoint accept time and date parameters to be passed to narrow the results being fed back and it is not likely they ever will since those parameters can be used to bust the cache.

**Comment by tsuthers-ccpgames** [comment]
@ddavaham is on point here, I've got nothing further to add :)

**Comment by warriorsoul15** [comment]
So change the in game role.

**Comment by ddavaham** [comment]
Are you being serious right now? 

You have posted the same question in both the forums and here on the issue board and have been told the same thing by two different third party devs, which has then been confirmed by an ESI API Developer @tsuthers-ccpgames 

This is not the place to request an change to in game mechanics. This repo is for issues and feature requests to the ESI API. Not to the game itself. If you want the in game role changed, then please submit a ticket using the [EVE Online Support Portal](https://support.eveonline.com/hc/en-us). If the in game role requirement is changed, then the change will filter down to ESI.

**Comment by Aidansavage** [comment]
@warriorsoul15 game design changes belong in the PF&I section of the forums, not github. As per your original request, Game Design and tsuthers have spoken and said 'no.' Any change MUST BE FACILITATED BYTHE GAME DESIGN TEAM in order for ESI to change, much like I told you in the first place last week when you first made this suggestion in PFI. This GitHub is not associated with the GD team, so changing your request to "well, change it in game" is exactly the same as asking your mail carrier to replace the engine in your car.

**Comment by warriorsoul15** [comment]
My original request was on the forums and I was told to post it here.....
 likewise if you want to be a dick this isnt the place for it.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by a-tal** [comment]
> if you want to be a dick this isnt the place for it

couldn't agree more. going to stop this drama train now.
