### ISSUE TITLE
Server start time (Server Status) inconsistent

### ISSUE THREAD

**Issue by deadlybulb** [ccpgames/esi-issues#691]
# Inconsistency

### Routes

/status/

### Description

GET /status/ can return slightly different server start times depending, I assume, on which front end you hit.

Two examples I found today (just hitting the endpoint regularly):

{
  "start_time": "2017-12-24T11:03:46Z",
  "players": 28373,
  "server_version": "1223575"
}

{
  "start_time": "2017-12-24T11:03:45Z",
  "players": 28295,
  "server_version": "1223575"
}

### Resolution

It's minor, just annoying if, like me, you track history of data by looking for differences.

**Comment by a-tal** [comment]
this is a product of the response coming from a random node on each cache cycle. not all nodes start on the same second

**Comment by Jimmy062006** [comment]
Whilst this might be a closed issue it is still an issue. What should really happen is when the ESI cluster see's a time that's greater then its time it should store this time and only reply with this result. It's not like this is going to change many time in between down time's.
