### ISSUE TITLE
Generated swagger client for Python: "SyntaxError: more than 255 arguments"

### ISSUE THREAD

**Issue by hiveliberty** [ccpgames/esi-issues#693]
# Bug

I'm using a swagger client for python, generated by docker (https://developers.eveonline.com/blog/article/swagger-codegen-update).
When I produce the import library, I get an exception "SyntaxError: more than 255 arguments" in get_characters_character_id_stats_200_ok.py
This happened after latest updates.

### Code
`from vendor import swagger_client`

### Exception
`File "/opt/BroadswordBot/lib/eve.py", line 22, in <module>
    from vendor import swagger_client
  File "/opt/BroadswordBot/vendor/swagger_client/__init__.py", line 102, in <module>
    from .models.get_characters_character_id_stats_200_ok import GetCharactersCharacterIdStats200Ok
  File "/opt/BroadswordBot/vendor/swagger_client/models/__init__.py", line 102, in <module>
    from .get_characters_character_id_stats_200_ok import GetCharactersCharacterIdStats200Ok
  File "/opt/BroadswordBot/vendor/swagger_client/models/get_characters_character_id_stats_200_ok.py", line 623
    travel_docks_null_sec=None, travel_jumps_stargate_high_sec=None, travel_jumps_stargate_low_sec=None, travel_jumps_stargate_null_sec=None, travel_jumps_wormhole=None, travel_warps_high_sec=None, travel_warps_low_sec=None, travel_warps_null_sec=None, travel_warps_to_bookmark=None, travel_warps_to_celestial=None, travel_warps_to_fleet_member=None, travel_warps_to_scan_result=None, travel_warps_wormhole=None):
                   ^
SyntaxError: more than 255 arguments`

### Expected
import without exceptions

**Comment by andimiller** [comment]
https://github.com/ccpgames/esi-issues/issues/682 I reported this here and it's being broken up in the v2

**Comment by ccp-zoetrope** [comment]
I'm closing this since it is fixed in the v2 endpoint which will be promoted to latest on January 26th. You can use https://esi.tech.ccp.is/_dev/swagger.json until then for generating a swagger client as this endpoint is literally the only endpoint that is currently different in dev at the moment.

**Comment by ccp-zoetrope** [comment]
So you don't actually have to use _dev anymore as this was promoted to latest just now. Just use https://esi.tech.ccp.is/_latest/swagger.json
