### ISSUE TITLE
Cannot get data older than 1 month when using /corporations/{corporation_id}/wallets/{division}/journal/

### ISSUE THREAD

**Issue by angel8878** [ccpgames/esi-issues#696]
# Feature request

### Route
/corporations/{corporation_id}/wallets/{division}/journal/

### Use case
Tried today and can only get data later than Dec.2 00:00 even with `from_id` specified.
Just want to know if this is by design or not and how can I get data older than 1 month if possible?

**Comment by Aidansavage** [comment]
Game Design limitation I believe, as the game itself does not keep transaction history for very long.

**Comment by ccp-zoetrope** [comment]
@Aidansavage is correct, the game client does not show data more than a month old and ESI follows the same convention.

**Comment by angel8878** [comment]
Got it, thanks @Aidansavage and @ccp-zoetrope  for answering.
