### ISSUE TITLE
contract items argument order is inconsistent with itself.

### ISSUE THREAD

**Issue by jennej** [ccpgames/esi-issues#699]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

# Inconsistency

### Routes
/corporations/{corporation_id}/contracts/{contract_id}/items/
/characters/{character_id}/contracts/{contract_id}/items/

### Description

The order that the parameters to these two routes are declared in the swagger code is swapped.  
corps is contract_id then corporation_id
chars is character_id then contract_id

this means that any generated api code, is going to put those args in that order, which, since they are both id's, was a bit of a debugging mess.  It was easy enough to sort out, but it still makes me twitch a bit. 

### Resolution
Pick an order?

**Comment by a-tal** [comment]
parameters are alpha sorted by name
