### ISSUE TITLE
esi wars endpoints

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#70]
- [ ] GET /wars/
List of IDs of all currently active wars.

- [ ] GET /wars/{war_id}/
Get details on a war.

- [ ] GET /corporations/{corporation_id}/wars/
List of all wars this corporation is or was involved in.

- [ ] GET /alliances/{alliance_id}/wars/
List of all wars this alliance is or was involved in.

**Comment by aquarhead** [comment]
For anyone interested, the latter 2 endpoints will be tracked at #305
