### ISSUE TITLE
Enable or Modify Google CDN query string blacklist

### ISSUE THREAD

**Issue by itshouldntdothis** [ccpgames/esi-issues#700]
# Feature request
Setup or add the query string `user_agent` to the [Google CDN query string blacklist](https://cloud.google.com/cdn/docs/caching#cache-keys) used for cache key generation.
### Use case
This change should stop cache misses caused by using the `user_agent` query string parameter on all ESI resources that use it by not including it in the cache key on the CDN.

**Comment by a-tal** [comment]
closed via commit, cheers
