### ISSUE TITLE
Medals Endpoint Internal Server Error Response

### ISSUE THREAD

**Issue by leonjza** [ccpgames/esi-issues#702]
# Bug
Requests to the `/characters/{character_id}/medals/` endpoint results in a an HTTP 500 response. The endpoint currently shows as "yellow" within the Swagger UI.

![https://i.imgur.com/y15q7dp.png](https://i.imgur.com/y15q7dp.png)

### Request
https://esi.tech.ccp.is/v1/characters/1477919642/medals/?datasource=tranquility

### Response
HTTP 500 response with `{"error":"Unhandled internal error encountered!"}` as body.

### Expected
Medals model for the character.

**Comment by ccp-zoetrope** [comment]
This was fixed with today's deployment.
