### ISSUE TITLE
Get the current players in your current Solar System

### ISSUE THREAD

**Issue by CerebralThrombosis** [ccpgames/esi-issues#705]
I looked at the ESI doc, and I couldn't find a feature that grabbed the current players that are in the solar system your character is in returning all of their names. Assuming you're not in a WH.

Is this feature available?

If not please add it.

**Comment by DianaOlympos** [comment]
Knowing that the only way to do that programmatically right now is to run OCR on a client, which is against the EULA, i would argue that any decision on that would come from Game Design. And that do not seems to be the direction CCP is going.

**Comment by a-tal** [comment]
denied by game design
