### ISSUE TITLE
X-Pages Missing from character wallet journal

### ISSUE THREAD

**Issue by adgriff2** [ccpgames/esi-issues#709]

**Comment by Aidansavage** [comment]
```
Name | Description
-- | --
character_id *integer(path) | An EVE character ID
datasourcestring(query) | The server name you would like data from
>>>>>>from_idinteger(query) | Only show journal entries happened before the transaction referenced by this id<<<<<<
tokenstring(query) | Access token to use if unable to set a header
user_agentstring(query) | Client identifier, takes pedence over headers
X-User-Agentstring(header) | Client identifier, takes precedence over User-Agent
```
That's how you walk backwards in the wallet endpoints. You dont need an `x-pages` header for an endpoint where you arent getting pages to begin with.

(and try to have more than just the title next time please, a little bit of information to go with the request can go a long way)

**Comment by ccp-zoetrope** [comment]
@Aidansavage is correct, pagination works slightly different with this endpoint, using the from_id as a query parameter and feeding it an order id to see orders that happened before that particular ID: https://esi.tech.ccp.is/ui/#/Wallet/get_characters_character_id_wallet_journal.
