### ISSUE TITLE
esi-universe : Space Object generic information

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/esi-issues#71]
For any static space object accessible from the `esi-universe` endpoint I'd like to have access to the following generic information (And anything else shared between all objects that I've forgotten)

Generic Data:
===
- **name** { string } - The name of the object
- **type** { string } - The object's type
- **category** { string } - The object's category
- **item_id** { number} - The object's id
- **type_id** { number } - The object's type id
- **graphic_id** { number } - The object's graphic id
- **category_id** { number} - The object's category id
- **system_id** { number } - The system the object resides in
- **resource** { string } - the resource file (legacy models) used to create the object
- **position** { vec3 } - The object's position in space relative to its system's center 
- **rotation** { vec3 } - The object's rotation in space
- **description** { [string] } - The object's description if it has one
- **mass** { number } - The object's mass
- **height** { number } - The object's height as is recorded in game ( not its model's dimensions )
- **length** { number } - The object's length as is recorded in game ( not its model's dimensions )
- **width** { number } - The object's width as is recorded in game ( not its model's dimensions )

Additional data for objects built with the SOF:
===
- **resource** { String } - DNA string to create the object
- **sof_hull** { [string] } - object's SOF hull
- **sof_faction** { [string] } - object's SOF faction
- **sof_race** { [string] } - object's SOF race

_I assume this data will be available in the graphic_id route_

**Comment by ccpStuart** [comment]
This has some gameplay implications, please provide a specific use-case(s)

**Comment by Robbilie** [comment]
Building scenes from actual solar systems using ccpwgl, thats why he also wanted rotation data for citadels and ships i think :)
not sure what gameplay implications this would have since at least for the esi-universe stuff this is just static data which you could reverse engineer by looking at the items (rotation) and position is in the sde anyways afaik

**Comment by cppctamber** [comment]
Ah it was poorly written sorry @ccpStuart , most of this has now been covered.
I will update the post.
