### ISSUE TITLE
Industry job locations have different property names for job location_ids

### ISSUE THREAD

**Issue by leonjza** [ccpgames/esi-issues#727]
# Inconsistency
Response model for `/corporations/{corporation_id}/industry/jobs/` and `/characters/{character_id}/industry/jobs/` have different field names for the location of the job. One is `location_id` and another is `station_id`.

### Routes
`/corporations/{corporation_id}/industry/jobs/`  
`/characters/{character_id}/industry/jobs/`

### Resolution
Choose one.

**Comment by GoldenGnu** [comment]
https://github.com/ccpgames/esi-issues/issues/604
