### ISSUE TITLE
path GET : characters/name uses long ids instead of int (64b instead of 32b)

### ISSUE THREAD

**Issue by guiguilechat** [ccpgames/esi-issues#730]
# Bug
The path in the spec is /paths/characters.names .
The method GET uses character ids in both the parameter and the response. They are specified with format "int64"

However there is already a parameter defined in /parameters/ with name character_id and format "int32"

easy fix :
remove the specification of parameter name and instead use the ref like other methods using the ids.

**Comment by lukasni** [comment]
Looks like a duplicate of #710

**Comment by guiguilechat** [comment]
indeed.
