### ISSUE TITLE
alliances/affiliations

### ISSUE THREAD

**Issue by whinis** [ccpgames/esi-issues#734]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

# Feature request

### Route
alliances/affiliations

### Use case
Getting the faction of alliances in bulk 

### Example returns
```
[
 {
    "alliance_id": 434243723,
    "faction_id":5
  }
]
```
### Previous XML or CREST route
After talk in slack #esi it may have at one point functioned at but does not currently
https://api.eveonline.com/eve/CharacterAffiliation.xml.aspx

**Comment by a-tal** [comment]
this use case is made redundant by your other issue (#733)

**Comment by lukasni** [comment]
How does `/corporations/affiliations/` make this redundant? This would be used to resolve the `faction_id` of a bunch of `alliance_ids` in bulk, which the other route wouldn't be able to do.
