### ISSUE TITLE
Add support for all celestials and factions to /universe/names/ and /universe/ids/

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/esi-issues#736]
# Inconsistency

### Routes
https://esi.tech.ccp.is/ui/?version=dev#/Universe/post_universe_ids
https://esi.tech.ccp.is/ui/?version=dev#/Universe/post_universe_names

### Description
The two endpoints do not support many types of celestials (stations seem to be the only ones supported at the moment) that their XML API predecessors supported.
These are: stars, planets, moons, asteroid belts, stargates.
In addition to those celestial types, the endpoints don't support resolving faction IDs/names either.

### Resolution
Add support for those celestial types to the endpoints.

\#parity

**Comment by ccp-zoetrope** [comment]
Confirmed these are possible to retrieve in the XML endpoint, tagged as parity.

**Comment by ccp-zoetrope** [comment]
We do not want `/universe/ids/` and `/universe/names/` to become a dumping ground . Therefore, it makes more sense to have asteroid belts shown similarly to the rest of these celestial objects: in the `/universe/systems/{system_id}/` endpoint. I have made this issue to track that: https://github.com/ccpgames/esi-issues/issues/813
