### ISSUE TITLE
Feature request : merge /alliances/ and /alliances/alliance_id/corporations/ to match XML alliances endpoint

### ISSUE THREAD

**Issue by JakeChely** [ccpgames/esi-issues#744]

**Comment by ccp-zoetrope** [comment]
Sorry but ESI is purposely made as to not be redundant and mix different types of info in multiple endpoints like the XML API did. All the info in the AllianceList XML endpoint is present in ESI using the following three routes:
* https://esi.tech.ccp.is/ui/#/Alliance/get_alliances
* https://esi.tech.ccp.is/ui/#/Alliance/get_alliances_alliance_id
* https://esi.tech.ccp.is/ui/#/Alliance/get_alliances_alliance_id_corporations

**Comment by lukasni** [comment]
@JakeChely I highly recommend looking into async requests for these things, I'm fetching all alliances in about 14 seconds.

**Comment by JakeChely** [comment]
To fetch all alliances or to fetch all alliances AND their corporation members?

**Comment by lukasni** [comment]
Ah, you need full detail on the corps? Fair, that'll be a bit longer, but still not crazy.

**Comment by lukasni** [comment]
if you just need names you can do it much more quickly, but I'd say needing full details on every corp in the game isn't exactly a "once every few minutes" thing.

**Comment by JakeChely** [comment]
I don't need names, just the Ids of the corps in every alliance.

Let's compared that to [https://esi.tech.ccp.is/ui/#/Character/post_characters_affiliation](url)
but for corporations and not characters.

**Comment by lukasni** [comment]
If you need only IDs we're back down to about 15s or less with concurrent requests. 
`/alliances/` to get all alliances, single request, pretty much negligible.
`/alliances/{alliance_id}/corporations/` 3007 requests at the time of this writing, takes me about 13s with 100 workers.

**Comment by JakeChely** [comment]
What do you use to make these calls ?

**Comment by lukasni** [comment]
In this specific case I used python requests_futures, but pretty much any language out there will have some form of concurrent requests package available. You could also check out the ESI blog on the subject:

https://developers.eveonline.com/blog/article/esi-concurrent-programming-and-pagination

**Comment by JakeChely** [comment]
Thanks. I'll look into it.

**Comment by lukasni** [comment]
No worries. ESI Definitely takes some getting used to coming from XML API, but it's got a lot of great features that make it worth the bother, imo.

**Comment by JakeChely** [comment]
What I already have is written in PHP.
I'll see if it can handle async requests.

**Comment by skiedude** [comment]
I use the guzzle client for my ESI requests and it comes with an easy async/concurrent request setup http://docs.guzzlephp.org/en/stable/quickstart.html#concurrent-requests
