### ISSUE TITLE
Bug- Search endpoint not able to find some corps

### ISSUE THREAD

**Issue by Aidansavage** [ccpgames/esi-issues#745]
Posting here more for posterity and tracking. Not sure how esi-related it is, but as of earlier today, the search endpoint (as well as search within the game itself) is failing to search and return some corporations. One example is `Red Frog Freight` which the endpoint only returns an empty list for, and ingame fails to find entirely:

`https://esi.tech.ccp.is/latest/search/?categories=corporation&datasource=tranquility&search=Red%20Frog%20Freight&strict=true`
res: `{}`

edit: corp ID for RFF is 1495741119

**Comment by tsuthers-ccpgames** [comment]
Looking into it, thanks.
