### ISSUE TITLE
Fitting is optional when creating fitting.

### ISSUE THREAD

**Issue by p-groarke** [ccpgames/esi-issues#748]
# Bug

### Request

At POST /characters/{character_id}/fittings/, the fitting is optional. It seems to be a bug. What would be a reasonable outcome of creating a fitting with an empty fitting?

### Response

{"error":"'description' is required, 'ship_type_id' is required, 'name' is required, 'items' is required"}

### Expected

Fitting is required.

**Comment by a-tal** [comment]
fixed, thanks

**Comment by p-groarke** [comment]
No problem, you can see my new issue for more details on how to identify these (there may be more). Good day o7

**Comment by a-tal** [comment]
yeah no worries. I added a standards test to check for this as well (there was another endpoint - post mail labels). no endpoint should be able to build in the future if it violates this convention.

**Comment by p-groarke** [comment]
Awesome! :)
