### ISSUE TITLE
Invalid 200 response: too many items for 'response' for structures endpoint

### ISSUE THREAD

**Issue by Y00sh00** [ccpgames/esi-issues#758]
# Bug
Similiar to https://github.com/ccpgames/esi-issues/issues/671 we are getting this message for the endpoint: https://esi.tech.ccp.is/latest/corporation/[corporation_id]/structures/ if you need a corp to test with take Pandemic Horde. 

Started happening today, I do not think it's the patch but instead, we probably hit a magic number of citadels in-game atm. The array cuts off at item 415 which seems an odd number to put a limit on.

### Response
{
  "error": "Invalid 200 response: too many items for 'response'",
  "response": [
    {
      "type_id": 35832,
      "profile_id": XXXX,
      "corporation_id": 98388312,
      "reinforce_weekday": X,
      "state": "shield_vulnerable",
      "system_id": XXXXXXXX,
      "reinforce_hour": XX,
      "structure_id": XXXXXXXXX
    },
    {
      "type_id": 35825,
      "profile_id": XXXX,
      "corporation_id": 98388312,
      "reinforce_weekday": X,
      "state": "shield_vulnerable",
      "system_id": XXXXXX,
      "reinforce_hour": XX,
      "structure_id": XXXXXXXXX
    },
    ...
  ]
}
### Expected
A temporary workaround for bumping the response limit would be appreciated and ultimately paging.

**Comment by ccp-zoetrope** [comment]
This is a result of the release of the v2 version of this endpoint today, it is already paginated and returns 1000 per page but I had mistakenly forgotten to bump the maxItems of the spec to the same thing. I have fixed this and you should not be receiving this error anymore.
