### ISSUE TITLE
Inconsistenc notification type for moonmining

### ISSUE THREAD

**Issue by Fundaris** [ccpgames/esi-issues#759]
# Inconsistency

### Routes
get /characters/{character_id}/notifications

### Description
All Moonming types are as follows:
MoonminingExtractionFinished
MoonminingLaserFired
MoonminingAutomaticFracture

Ecept this one. It jumps out of format:
notificationTypeMoonminingExtractionStarted

### Resolution
notificationTypeMoonminingExtractionStarted should be MoonminingExtractionStarted

**Comment by ccp-zoetrope** [comment]
This has been fixed in the [v2 version](https://esi.tech.ccp.is/ui/?version=dev#/Character/get_characters_character_id_notifications) of this endpoint released today
