### ISSUE TITLE
esi-universe: /universe/factions/{faction_id}/

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#76]
additionally to the npcs route a route to retrieve basic information about the existing factions ingame would be nifty, even though this endpoint would mostly return "static" data unless you integrate faction warfare into it in which case a whole endpoint for it might be an option

- [ ] GET /universe/factions/{faction_id}/
      return basic information about a faction

returning all factions_ids on GET /universe/factions/ might be an option too

**Comment by Salvoxia** [comment]
I'd like to chime in on this, with special regard to the faction IDs returned by the killmail endpoint.
For Sleepers as attackers, the killmail endpoint will return faction ID 500021, which was translated to "Unknown" by the CREST killmail endpoint, but is not contained in the SDE.
So if a factions endpoint is ever a thing, I hope it would know about the "Unknown" faction (pun intended).

Best Regards,
Salvoxia
