### ISSUE TITLE
[SDE] release 20180214 missing typeIDs.yaml entry 47374

### ISSUE THREAD

**Issue by guiguilechat** [ccpgames/esi-issues#762]
release 20180214 missing entry 47374

```
grep 47374 bsd/dgmTypeAttributes.yaml 
    typeID: 47374
grep 47374 fsd/typeIDs.yaml 
(nothing)

```

**Comment by guiguilechat** [comment]
https://esi.tech.ccp.is/latest/universe/types/1230/
returns correct data for veldspar

https://esi.tech.ccp.is/latest/universe/types/47374/
returns incorrect type.

**Comment by tsuthers-ccpgames** [comment]
As far as I can tell, there is no type of ID 47374.

What do you expect it to be?

**Comment by guiguilechat** [comment]
I don't  know, it is present in the bsd/dgmTypeAttributes.yaml , as my grep showed.
There is an attribute entry that refers to this typeid.
It can as well be an error in the bsd/dgmTypeAttributes.yaml, I can't tell what is the error.

**Comment by guiguilechat** [comment]
I noticed that when compiling against the SDE, my compiler crashed. I inspected the reason of this crash and posted the result.

**Comment by tsuthers-ccpgames** [comment]
Yep, it's a result of a few crossed wires in our workflow. Said bacon will exist (and be renamed prior to release) at some point in the future, but a reference to it appears to have slipped out early.

There's not much I can do about it unfortunately. It will go away once the item is actually released, not 100% sure what the ETA on that is. In the mean time I would suggest modifying the compilation process to be a bit more robust to cases like these.

**Comment by guiguilechat** [comment]
Modifications were done on my side prior to posting this bug, basically skipping null entries and logging them with warnings.

However you may add checks to ensure such a thing can't get through .
It takes my java program less than a minute, on a ~1600-threads computer, to load all the required yaml files and create internally the representation (java classes), translate the sde files into created classes and export this in-memory database to local files.
Such an automated test (prior to deployment) should not take longer.
