### ISSUE TITLE
Inconsistent property name between similar endpoints and objects

### ISSUE THREAD

**Issue by seraphx2** [ccpgames/esi-issues#763]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

# Inconsistency

### Routes
1. "/characters/{character_id}/orders/"
2. "/characters/{character_id}/orders/history/"

### Description
Endpoint 1 returns is_corp in its object.
Endpoint 2 returns is_corporation in its object.

### Resolution
Rename the property in Endpoint 1 to match Endpoint 2.

**Comment by GoldenGnu** [comment]
Looks like it’s already fixed in v2, that is in dev now and is getting promoted to latest on the 2018-03-08

**Comment by ccp-zoetrope** [comment]
@GoldenGnu [is correct](https://esi.tech.ccp.is/ui/?version=dev#/Market/get_characters_character_id_orders), closing this issue because it has already been fixed in v2.
