### ISSUE TITLE
Character Notification returns 500 for some Characters

### ISSUE THREAD

**Issue by Fundaris** [ccpgames/esi-issues#764]
# Bug
I'm getting for a few characters a 500 error when trying to read their notifications
This started happening around tuesday. Can't tell if before patch or not.
Didn't had the response to file it earlier. I'm 100% sure that the character has notifications.

### Request
get /latest/characters/{character_id}/notifications/ 
"request_header": "GET \/latest\/characters\/{the character}\/notifications\/ HTTP\/1.1\r\nUser-Agent: EVE-Noti\r\nHost: esi.tech.ccp.is\r\nAccept: *\/*\r\nAuthorization: Bearer {some token}\r\n\r\n"

### Response
{error: uncaught exception}

### Expected
Getting list of notifactions of this character

**Comment by ccp-zoetrope** [comment]
This has been fixed now.
