### ISSUE TITLE
Feature Request: Channels ESI

### ISSUE THREAD

**Issue by alexbaileyuk** [ccpgames/esi-issues#768]
# Feature request

### Route
/Channels/

### Use case
Get Characters known/saved chat channels and return their ID's. This could be useful for example when changing the fleet MOTD via the ESI if you wanted to link a channel for example or when sending a mail and wanting to link a channel.

### Example returns
[

{
   "channelID": "123456",
   "channelName": "The Channel Name",
   "owner": "[characterID]"
},...

]

### Previous XML or CREST route

**Comment by lunedis** [comment]
https://esi.tech.ccp.is/ui/#/Character/get_characters_character_id_chat_channels

"Return chat channels that a character is the owner or operator of"

**Comment by alexbaileyuk** [comment]
Already there!
