### ISSUE TITLE
When does skill queue renumber positions?

### ISSUE THREAD

**Issue by deadlybulb** [ccpgames/esi-issues#770]
# Inconsistency
More likely just a question

### Routes
/characters/{character\_id}/skillqueue/

### Description
In a longish skill queue which hasn't been updated in a while, I noticed that queue position doesn't start at 0.  In my particular case, it starts at 15 (and there are two skills, so queue positions 15 and 16).  There were many earlier skills which have since completed.

When will queue positions be updated to start at 0 again?

### Resolution

¯\_(ツ)_/¯

**Comment by Aidansavage** [comment]
IIRC, skill queue API stuff only gets updated when you log into the character.

**Comment by ddavaham** [comment]
Furthermore, the queue position number only updates when the character modifies or restart his/her queue

**Comment by ddavaham** [comment]
@ccp-zoetrope How is this an inconsistency?

**Comment by Aidansavage** [comment]
Less an inconsistency issue and more an API behavior I think. There's other things that don't update on ESI until you log a character in as well. 

That being said, if you are training an omega skill and lapse to alpha, ESI is not notified of the queue pause/drop until after you have logged in that character.

**Comment by a-tal** [comment]
it updates on character login. the historical skills in this list are their recently completed skills
