### ISSUE TITLE
Add SP/hr to the skill queue

### ISSUE THREAD

**Issue by Malchia7** [ccpgames/esi-issues#787]
# Feature request
Add SP/hr to the skill queue (if too difficult for the entire queue, just the first entry would be enough)

### Route
/characters/{character_id}/skillqueue/

### Authentication
OAuth

### Use case
SP/hr can be used to determine alpha vs omega in a character specific way (affected by implants/boosters/etc). It also saves applications from calculating this themselves and guarantees we're calculating the same way CCP is.

### Example returns
[
  {
    "skill_id": 1,
    "finish_date": "2016-06-29T10:47:00Z",
    "start_date": "2016-06-29T10:46:00Z",
    "finished_level": 3,
    "queue_position": 0,
    "skill_points_per_hour": 2390
  },
  {
    "skill_id": 1,
    "finish_date": "2016-07-15T10:47:00Z",
    "start_date": "2016-06-29T10:47:00Z",
    "finished_level": 4,
    "queue_position": 1,
    "skill_points_per_hour": 2390
  },
  {
    "skill_id": 2,
    "finish_date": "2016-08-30T10:47:00Z",
    "start_date": "2016-07-15T10:47:00Z",
    "finished_level": 2,
    "queue_position": 2,
    "skill_points_per_hour": 1890
  }
]

**Comment by tsuthers-ccpgames** [comment]
All of the information required to do this is in the skillqueue endpoint already. Use the data from the skill with the lowest skill position.

The formula is:
(level_end_sp - training_start_sp) / ((finish_date - start_date) * {hours factor})

Where hours factor is whatever value your software environment needs to convert its internal representation of the timestamps into a count of hours. We prefer not to centralize the processing of stuff that can be handled by the client, if we did it for every possible usecase across the whole API it would increase our costs considerably :)
