### ISSUE TITLE
All pages of ESI are empty in Microsoft Edge

### ISSUE THREAD

**Issue by nardieu** [ccpgames/esi-issues#794]
# Bug
All pages of https://esi.tech.ccp.is/ shows only menu in Microsoft Edge because JS code has exception

![image](https://user-images.githubusercontent.com/3143121/37453980-64a904dc-284a-11e8-9f79-c18e1194f81d.png)

According to documentation of [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) it's not supported by Internet Explorer and Edge.
I added following userscript to extension Tampermonkey and it helped:
```js
// ==UserScript==
// @name         EVE ESI Fix
// @namespace    https://esi.tech.ccp.is/
// @version      0.1
// @author       You
// @match        https://esi.tech.ccp.is/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    console.log("URLSearchParams added");
    var URLSearchParams = class URLSearchParams {
        constructor(search) {
        }
        get(term) {
            return "";
        }
    };
    var global = window || global;
    global.URLSearchParams = URLSearchParams;
})();
```

Please fix script on page.

**Comment by ccp-zoetrope** [comment]
I moved this to the relevant Github project for this particular problem: https://github.com/ccpgames/esi-swagger-ui/issues/17
