### ISSUE TITLE
ESI SSO Scopes

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/esi-issues#80]
- [ ] read_character_bookmarks is missing its complete description
- [ ] several scopes have their description cutoff because of misusing the jquery-ui accordion
      FIX: add the heightStyle option in Line 56 (https://login.eveonline.com/oauth/authorize)
```
$("#accordion").accordion({
    heightStyle: "content"
});
```

**Comment by a-tal** [comment]
@Robbilie can you add a screenshot?

**Comment by Robbilie** [comment]
http://imgur.com/a/Ya4pn

the fix fixes it :D

**Comment by a-tal** [comment]
ah, ok. this is an issue with the SSO site then, not ESI.

can you please open an issue here -> https://support.eveonline.com/hc/en-us/requests/new

(feel free to reference this thread there)
