### ISSUE TITLE
/v2/corporations/{corporation_id}/wallets/{division}/journal/ return no information for incursions

### ISSUE THREAD

**Issue by Swantu** [ccpgames/esi-issues#802]
Hello everyone
# Bug
When pulling the corporation wallet journal, the ref_type "corporate_reward_payout" does not contain information on the involved players:
### Request
/v2/corporations/{corporation_id}/wallets/{division}/journal/
### Example returns
 {
    "date": "2018-03-15T23:16:07Z",
    "ref_id": 15300148357,
    "ref_type": "corporate_reward_payout",
    "amount": 4500000,
    "balance": 653461262.1606,
    "reason": "",
    "tax_receiver_id": 0,
    "tax": 0
  }
### Expected
"reason" with content [the eve client shows a reason]
"first_party_id"
"first_party_type"
"second_party_id"
"second_party_type"

### Resolution
Fill reason with content and ad the other fields to the ESI response (?)

**Comment by ccp-zoetrope** [comment]
[v3 of this endpoint](https://esi.tech.ccp.is/ui/?version=dev#/Wallet/get_corporations_corporation_id_wallets_division_journal) was recently released. It includes the description you see in the client for each wallet journal transaction. Try the v3 endpoint and if still does not have the info you need re-open this issue and let us know :).

**Comment by Blacksmoke16** [comment]
Do you know when v3 will be released to latest?  I do not see it on the changelog. @ccp-zoetrope

**Comment by ccp-zoetrope** [comment]
@Blacksmoke16 adding that slipped through the cracks when we moved to [changelog.md](https://github.com/ccpgames/esi-issues/blob/master/changelog.md), thanks for the poke! The date for this to be promoted to latest will be April 26th, 2018.

**Comment by Blacksmoke16** [comment]
Sounds good, thanks.

**Comment by Swantu** [comment]
@ccp-zoetrope 
Thanks for the update. I've played with v3 now a bit and still believe the core-issue has not changed. In v3, the example above looks now as follows:

### Example returns
```
  {
    "date": "2018-03-15T23:16:07Z",
    "id": 15300148357,
    "ref_type": "corporate_reward_payout",
    "description": "CONCORD rewarded Rakutsch Fera for services performed.",
    "amount": 4500000,
    "reason": "",
    "balance": 653461262.1606
  },
```

### Expected
however, there are still no parties involved:

    "first_party_id":1000125,  // =concord
    "second_party_id": xxxxx,  // =player_id

afaik, corporate_reward_refund is the only journal-entry that does not have a first_ & second_party_id.

cheers
Swantu
P.S: Thanks for the description field - it makes it easier to understand things sometimes :)
