### ISSUE TITLE
Not the exact value of the number "cost_index".

### ISSUE THREAD

**Issue by asvpdev** [ccpgames/esi-issues#807]
# Bug

Not the exact value of the number "cost_index".

### Request

https://esi.tech.ccp.is/latest/industry/systems/

### Response

[
  {
    "solar_system_id": 30020141,
    "cost_indices": [
      {
        "activity": "manufacturing",
        "cost_index": 0.0343
      },
      {
        "activity": "researching_time_efficiency",
        "cost_index": 0.0209
      },
      {
        "activity": "researching_material_efficiency",
        "cost_index": 0.0274
      },
      {
        "activity": "copying",
        "cost_index": 0.0123
      },
      {
        "activity": "invention",
        "cost_index": 0.0502
      },
      {
        "activity": "reaction",
        "cost_index": 0.001
      }
    ]
  },

....
]

### Expected

[
  {
    "solar_system_id": 30020141,
    "cost_indices": [
      {
        "activity": "manufacturing",
        "cost_index": 0.03439368825622633
      },
      {
        "activity": "researching_time_efficiency",
        "cost_index": 0.02094838710201359
      },
      {
        "activity": "researching_material_efficiency",
        "cost_index": 0.02745641420927296
      },
      {
        "activity": "copying",
        "cost_index": 0.012341278349091296
      },
      {
        "activity": "invention",
        "cost_index": 0.05032760912884897
      },
      {
        "activity": "reaction",
        "cost_index": 0.001
      }
    ]
  },

....
]

See https://crest-tq.eveonline.com/industry/systems/

{
            "systemCostIndices":  [
                {
                    "costIndex":  0.03439368825622633,
                     "activityID":  1,
                     "activityID_str":  "1",
                     "activityName":  "\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u043e"
                },
                 {
                    "costIndex":  0.02094838710201359,
                     "activityID":  3,
                     "activityID_str":  "3",
                     "activityName":  "\u041f\u043e\u0432\u044b\u0448\u0435\u043d\u0438\u0435 \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0430"
                },
                 {
                    "costIndex":  0.02745641420927296,
                     "activityID":  4,
                     "activityID_str":  "4",
                     "activityName":  "\u041f\u043e\u0432\u044b\u0448\u0435\u043d\u0438\u0435 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u043e\u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u0438 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0430"
                },
                 {
                    "costIndex":  0.012341278349091296,
                     "activityID":  5,
                     "activityID_str":  "5",
                     "activityName":  "K\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435"
                },
                 {
                    "costIndex":  0.05032760912884897,
                     "activityID":  8,
                     "activityID_str":  "8",
                     "activityName":  "\u0418\u0437\u043e\u0431\u0440\u0435\u0442\u0435\u043d\u0438\u0435"
                }
            ],
             "solarSystem":  {
                "id_str":  "30020141",
                 "href":  "https://crest-tq.eveonline.com/solarsystems/30020141/",
                 "id":  30020141,
                 "name":  "Senda"
            }

**Comment by a-tal** [comment]
game design has dictated 4 digit precision for this going forward

CCP'ers see jira [TTC-951]

**Comment by asvpdev** [comment]
Insufficient accuracy for calculations.
The formulas give strong errors.
