### ISSUE TITLE
Inconsistencies in Base Item Cost Calculation for Reactions

### ISSUE THREAD

**Issue by mullinger** [ccpgames/esi-issues#816]
Help!

My information on a lot of internet research is that base item cost is based on the adjusted prices of the input materials of the markets/prices/ endpoint.

Checking the ingame client versus the prices from the gives a pretty substantial difference:

200* (38) Nocxium @294.12
100* (30372) Fullerite-C70@334.01
100* (30374) Fullerite-C84 @1081.6
~= 200385.0

while the ingame client reports ~253k base item cost.

Could you please clarify if
a) The formular for base item cost for reactions is different
b) The adjusted prices in ESI of the markets/prices/ endpoint for reaction components are wrong
c) ...???

Its driving me pretty crazy.

![screenshot 2018-03-26 17 14 48](https://user-images.githubusercontent.com/645185/37915898-cb9f0dca-311a-11e8-89d9-45db74376a08.png)

**Comment by fuzzysteve** [comment]
Lanthanum Metallofullerene?

are you including the fuel block cost? 5 blocks at 10532.81

**Comment by mullinger** [comment]
Oh sh*t, guess I am not.

Somehow, on the way from loading the reactions from the SDE to doing the calculations in my backend the fuel blocks seem to get lost...somewhere.

That explains it of course. Thanks a ton.

**Comment by mullinger** [comment]
https://esi.tech.ccp.is/latest/universe/types/30348/
-> {
  "type_id": 30348,
  "name": "Lanthanum Metallofullerene Reaction",

https://cdn1.eveonline.com/data/sde/tranquility/sde-20180323-TRANQUILITY.zip
File sde/bsd/invTypeReactions.yaml

sde/bsd$ grep 30348 invTypeReactions.yaml | wc -l
4


Search for 30348
4 matches

-   input: true
    quantity: 200
    reactionTypeID: 30348
    typeID: 38
-   input: true
    quantity: 100
    reactionTypeID: 30348
    typeID: 30372
-   input: true
    quantity: 100
    reactionTypeID: 30348
    typeID: 30374
-   input: false
    quantity: 120
    reactionTypeID: 30348
    typeID: 30307

No more matches in the file..

It seems the fuel blocks are missing in the sde export :-1:

**Comment by mullinger** [comment]
@SpeedProg I wasn't sure where the error was in the beginning. Now I do. Feel free to contribute and let me know me where to report SDE errors instead of complaining and playing admin.
If they are no responsible, I hope the ESI folks can at least let the right people know about this error.

**Comment by fuzzysteve** [comment]
To confirm: invTypeReactions is a defunct file. It's not used for anything any more. you want blueprints.yaml, with an activity id of 11. (If you're using my conversion, it's in industryActivityMaterials and industryActivityProducts

**Comment by mullinger** [comment]
Thanks, @fuzzysteve  That is really helpful and will let me fix these issues.
The fsd/blueprints.yaml does not contain activityIds, but reactions do contain a block:
activities:
        reaction:

That is enough to filter for reactions.
