### ISSUE TITLE
/v3/universe/types/{typeid}/ returns gibberish content with X-Esi-Ab-Test:1

### ISSUE THREAD

**Issue by Shirrath** [ccpgames/esi-issues#820]
{
    Content: "\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000��WM��8\u0014�+W^�\"l���;��f3�ʹ�\u001c�\t�\u0003��M���\u001fA��&�œ^r\u000f���a��ۀ\u0007Ր=e)-\u0012�e�dO>��x�$!\r�ڪ�+�ɞ�q:a��\u0005�\u001bԦ?*��\u0019|��\u001c���`�h��@i��Q�7��U�v�5xB��\u0005���<�Ny�n·(/7��ɱ�P�Q9�.���Ǟ\u0019��\u000f\u0000(\u0007R��\u0017ٍ��!ȦQ3�\u001b��\u0006�]�^�\u0016N�֘�9=\u0018\u0018������g8�\u0016g\u001eFw7p�\u001a\u001c�gy\u0003�����\u000e�(g��,8)�\u001a8�F+��\tH�M3v\b�V�-�\u0016�G\u0007r�I�J\u000f��``����L\u0000�-Z�L\u0006x8\u001bt;������>�\u0005;3���?꫒�#p��\u0010`\u0011�\u001b�G\u0018�s����3z�<4���ݑ��x�Zj8��\u001d�ݢ� mof�\u001d�F7�\u0015�h\u0004��ܓ\u001f\r�͝�\u001b\u0007���)'v�K����3{h�m@��Mij+��\u001d�u�ڌv�W9h\f:�Q�����Jߢ\u0005י�|�\u0003�\u0003gz���\b�ꕟX�\u001c�v3\u0012;��5Z�\u000e���=L\"\t\u0019�c�\\�\r�{;bB�֌�<'e�'���\u001d�a���\u0005M���\u001a\u001d�S��҄\\L7N�Di���7����\u0019��3���L�P+#���3�؉����\u0013n:�M�\u0005K\u001fϜ�\u001cZU�\u0004�Ld\ti̹�\u0007�U�ѣ#�����;0!Ӥ ٧��{�k8���~GU\u000b��#(ϋ'�E\u0011�\u0019/��i\u0016�/TE��k��܈\u0007\"cqF_?�\u0005�)�\"\u0016\u0006s�Gp��D�x��$��\"��D�X�d<\u000eY��2��\u0014t1�2\u0011�S�\u0001\u0015N#\u0007�<@\u0014<�B,e_c�\u0019];��Ase\u0011-�Fui�T&*��lA�+��aiD\u0011˒n\"�&\"�\u001aE\u001e\u0014�Ź�,�\u0010���Q\u0014�J�S����J'�|�q&6*��\u0006]��)w4÷4�]��\u0017]���\t��5\u0015�l��\rb�`���Y�f�+�ņV�6���͂)ZÔ,�\u001cY�\u0012墉�\"��ۘm�{��:X\u001a�2J��\u001b���4�Q���`t\u0019Ƭ�W&)��\u0015��5�j!\u0002�4�q[\u0019\u000f\u0015\u0017\"\u0006\u0011�����\u0005���*�:P�����=\u0014��t�R\u0016Y8B�\n�|�D\"؆+����)L�3�b���,ڰ?ݗ\"��2�\bKCY4G�S\"�!+B��\u0018`�\u0019Y�E��`\u0007�_Ah\u0019\\�o,��\u0015L�[\u0015m����7K��s\u001e�}\u001e�y��g\u001e�����G��z�\"��y��^��x������%����퇊�(wh�4��&���\u001cN�\u0003P�O���ʫ���\u0007P�C�\u000f�ʫ��F� \u0017�x4ח��\u0007\u0000\u0000��\"\u0003\u001b��\u0010\u0000\u0000",
    Expires: "2018-03-28T11:05:00.0000000Z",
    Headers: {
        Access-Control-Allow-Credentials: "true",
        Access-Control-Allow-Headers: "Content-Type,Authorization,X-User-Agent",
        Access-Control-Allow-Methods: "GET,OPTIONS",
        Access-Control-Allow-Origin: "*",
        Access-Control-Expose-Headers: "Content-Type,Warning,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset",
        Access-Control-Max-Age: "600",
        Cache-Control: "public",
        Date: "Wed, 28 Mar 2018 06:06:24 GMT",
        Etag: "W/\"8cd8c6f9e1488046588e88bcc5f565beb138beb3b0c8befe14e0ef12\"",
        Strict-Transport-Security: "max-age=31536000",
        Vary: "Accept-Encoding",
        X-Esi-Ab-Test: "1",
        X-Esi-Error-Limit-Remain: "100",
        X-Esi-Error-Limit-Reset: "36",
        Via: "1.1 google",
        Alt-Svc: "clear",
        Content-Language: "en-us",
        Content-Type: "application/json",
        Expires: "Wed, 28 Mar 2018 11:05:00 GMT",
        Last-Modified: "Tue, 27 Mar 2018 11:09:13 GMT"
    },
    ProtocolVersion: "1.1",
    StatusCode: "OK",
    StatusDescription: "OK",
    _typeTag: "Message"
}

**Comment by fuzzysteve** [comment]
I think it's not gibberish. as such. I _think_ it's gzipped, but without notification that it's encoded that way.

I've been seeing it with the market data.

**Comment by Shirrath** [comment]
If it's gzipped, it should have a Content-Encoding: gzip header to let the client know how to decompress it. Either that header is never sent, or a load balancer/reverse proxy/whatever strips it.

**Comment by fuzzysteve** [comment]
Yep.

It's a side effect of their A/B testing, I suspect. I've waved it at them.

**Comment by a-tal** [comment]
this should be fixed now, thanks for the report

**Comment by a-tal** [comment]
patch rolled back, investigating

**Comment by a-tal** [comment]
rollback was due to an unrelated patch, fixed and pushing this to prod again
