### ISSUE TITLE
MoonminingExtractionStarted notification type is incorrect.

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#821]
# Bug

The type for MoonminingExtractionStarted is incorrect.
`notificationTypeMoonminingExtractionStarted` should be `MoonminingExtractionStarted`

**Comment by ccp-zoetrope** [comment]
I assume you're talking about `/characters/{character_id}/notifications/`. This has been fixed in the v2 endpoint which will be promoted to latest today.
