### ISSUE TITLE
Get Blueprints returns location flag name, not ID - request change to flagID

### ISSUE THREAD

**Issue by Zifrian** [ccpgames/esi-issues#822]
# Inconsistency

The output of the blueprints data is somewhat inconsistent with other data available in that it returns the flag name of the location instead of the flag code. Since the codes are in the SDE, request returning the "location_flag" to "location_flag_id" that returns an integer to link to the invFlags table. 

{
  "application/json": [
    {
      "item_id": 1000000010495,
      "type_id": 691,
      "location_id": 60014719,
      **"location_flag": "Hangar",** <- change to flagID
      "quantity": 1,
      "time_efficiency": 0,
      "material_efficiency": 0,
      "runs": -1
    }
  ]
}

**Comment by CarbonAlabel** [comment]
ESI is moving away from using IDs to represent properties such as location flags. If you're looking for a way to convert location flags returned by ESI to their respective IDs, see https://github.com/ccpgames/eve-glue/blob/master/eve_glue/location_flag.py.
![the-future-is-now](https://user-images.githubusercontent.com/17382986/38168591-ffd1bec8-3550-11e8-8445-fb7353989736.jpg)

**Comment by Zifrian** [comment]
Weird. I guess if they want to move off of the SDE then that makes sense but I thought the goal was to move away from translating everything, which is what they did in most of the others. Almost all the names are gone from those. 

I can convert using the tables for the codes if needed, which isn't really a big deal.

**Comment by ccp-zoetrope** [comment]
@CarbonAlabel is correct and we are only going with string representations now but have the string -> ID conversion in https://github.com/ccpgames/eve-glue.
