### ISSUE TITLE
Naming inconsistency in industry jobs between corporation and character data

### ISSUE THREAD

**Issue by Zifrian** [ccpgames/esi-issues#823]
# Inconsistency
The naming convention for industry/jobs in both character and corporation should be the same.  Currently, the characters returns a "station_id" field, while they could install a job outside of a station. In corporations, the same field is there but it's called "location_id"

**/characters/.../industry/jobs**
{
  "application/json": [
    {
      "job_id": 229136101,
      "installer_id": 498338451,
      "facility_id": 60006382,
      **"station_id": 60006382,**
      "activity_id": 1,
      "blueprint_id": 1015116533326,
      "blueprint_type_id": 2047,
      "blueprint_location_id": 60006382,
      "output_location_id": 60006382,
      "runs": 1,
      "cost": 118.01,
      "licensed_runs": 200,
      "status": "active",
      "duration": 548,
      "start_date": "2014-07-19T15:47:06Z",
      "end_date": "2014-07-19T15:56:14Z"
    }
  ]
}

**/corporations/.../industry/jobs**
{
  "application/json": [
    {
      "job_id": 229136101,
      "installer_id": 498338451,
      "facility_id": 60006382,
      **"location_id": 60006382,**
      "activity_id": 1,
      "blueprint_id": 1015116533326,
      "blueprint_type_id": 2047,
      "blueprint_location_id": 60006382,
      "output_location_id": 60006382,
      "runs": 1,
      "cost": 118.01,
      "licensed_runs": 200,
      "status": "active",
      "duration": 548,
      "start_date": "2014-07-19T15:47:06Z",
      "end_date": "2014-07-19T15:56:14Z"
    }
  ]
}
#Request 
Rename the "station_id" field in the characters/.../industry/jobs to "location_id" to be consistent with corporations/.../industry/jobs

**Comment by itshouldntdothis** [comment]
Appears to be a dupe of #604.

**Comment by Zifrian** [comment]
Yes, it is. Thanks for finding it. I tried to search for it!
