### ISSUE TITLE
oauth2 access token expiry errors not documented in swagger spec

### ISSUE THREAD

**Issue by wtfrank** [ccpgames/esi-issues#83]
bravado.exception.HTTPBadRequest: 400 BAD REQUEST: Response specification matching http status_code 400 not found for operation Operation(get_universe_structures_structure_id). Either add a response specification for the status_code or use a `default` response.

At least... I assume the above error is due to oauth2 access token expiry, but its conceivable that something else causes it.

**Comment by a-tal** [comment]
yeah, currently we pass all errors from SSO as is, with their return code.

I'll change this to include the upstream status code in the error message, and hide everything under a 403

**Comment by wtfrank** [comment]
FYI on /universe/structures/{structure_id}/, it is documented that you may return 403.

If you are using 403 to mean both "you don't have an ACL for this structure" and "you have an expired access token" then we will need precise specifications of what the error string will be in each case. (Currently...this is documented as error: "string"...i.e. not really specified!)

Alternatively that structure endpoint could return something other than 403 for structures without an appropriate ACL.

**Comment by a-tal** [comment]
all SSO errors will be returned as a 403 now. all routes that use auth should have the 403 response defined already. errors from SSO will mention specifically that they are from SSO in the message, should be able to differentiate a SSO error vs a permission issue with that.
