### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by wvdvegt** [ccpgames/esi-issues#834]
Can anyone explain me the difference between

characterResearchRead and esi-characters.read_agents_research.v1?

If I add the first one everything seems ok, the 2nd one results in 400 errors.

**Comment by antihax** [comment]
the former is for crest, the latter for esi. Join us on #esi and #sso on slack for these types of questions. :)

https://www.fuzzwork.co.uk/tweetfleet-slack-invites/

**Comment by a-tal** [comment]
thanks @antihax
