### ISSUE TITLE
Missing from_type on mail list

### ISSUE THREAD

**Issue by warlof** [ccpgames/esi-issues#837]
# Inconsistency

### Routes
`/characters/{character_id}/mail/`
`/characters/{character_id}/mail/{mail_id}/`

### Description
On detail mail, you provide the recipient_type attached to the recipient_id; therefore; we know if we're able to resolve it to a name.

On mail list, you only provide the ID from which entity the mail is coming. So, when we're attempting to make resolve; we may be bounced by the search endpoint.

### Resolution
Add an enum property `from_type` which can contain `alliance, character, corporation, mailing_list, system?` to the mail list endpoint.

**Comment by ddavaham** [comment]
Duplicate of https://github.com/ccpgames/esi-issues/issues/312

Hint. It will only ever be a character id or mailing_list_id

**Comment by warlof** [comment]
true, didn't catch it with my keywords.

Having choice between `character` and `mailing_list` is an extra choice which can lead to a bad request :p
