### ISSUE TITLE
Performance and server errors

### ISSUE THREAD

**Issue by evrial** [ccpgames/esi-issues#84]
Error rate is too high in comparison to CREST, about 3% requests fail most frequently with 500 or 502, or drop connection. Even on low request rate about 20/s, 10 concurrent workers.
Performance could be better too, with CREST client limit 150 QPS, ESI peaks 100 without limiting client.

**Comment by Regner** [comment]
Can you provide some examples of requests that are failing?

**Comment by wtfrank** [comment]
my experience is that on thurs/fri/sat/sun there were a fair number of 502s, but today i've seen close to 0 when I fetch from the structure info endpoint. A VM image restarted today perhaps?

**Comment by evrial** [comment]
Sure. https://www.dropbox.com/s/gr407xrxeac1077/gethistory.log?dl=1

**Comment by HakShak** [comment]
Yeah, we haven't really done a focused optimization path for capacity. We will spin up more resources as ESI grows in adopters.

What we would like to see is metrics over a week (preferably around a weekend) of what your application is experiencing per endpoint. Then we could prioritize based on that info.

**Comment by aquarhead** [comment]
@evrial are you working on markets endpoints? There used to be some problems with markets endpoints that should have been solved a few weeks back, are you still seeing a lot of errors?

**Comment by antihax** [comment]
I am seeing some on occasion. Starts as 500 and progresses to 502. I will try to start logging them.

**Comment by evrial** [comment]
@aquarhead yea, as we speak still present some 500s. Look at my log above | tail.

**Comment by aquarhead** [comment]
@evrial got 404 visiting the dropbox link

**Comment by evrial** [comment]
Sorry. https://www.dropbox.com/s/fp9tmngk7a2c83v/gethistory.log?dl=0
Currently 132 errors in Forge region.

**Comment by a-tal** [comment]
closing this as of `esi-lib 0.4.1`, which dropped ESI's error rate significantly (0.047% today, also includes downtime)
