### ISSUE TITLE
qt5cpp-client broken?

### ISSUE THREAD

**Issue by 3vi1** [ccpgames/esi-issues#844]
The problem:  The qt5cpp-client code generated both via swagger.io or via docker seems very broken and incomplete.

Some examples:  

*  SWGGet_characters_character_id_roles_ok makes reference to RolesEnum, Roles_at_hqEnum, etc...  But there are no declarations for these enums.

*  There's at least one place in the code trying to call QDate().isSet()... which isn't a thing.

*  There are a lot of places in the generated client doing this:

`    foreach(QJsonValue obj, jsonArray) {
        qint32* o = new qint32();
        QJsonObject jv = obj.toObject();
        QJsonObject * ptr = (QJsonObject*)&jv;
        o->fromJsonObject(*ptr);
        output->append(o);
    }
`

   which isn't valid because qint32.fromJsonObject also isn't a thing.  It looks like it should have been doing this?:

`    foreach(QJsonValue obj, jsonArray) {
        output->append(obj.toInt());
    }
`

There are probably many other things wrong, but I quit looking when I ran into the missing enums.

So, my request is:  Can someone tell me if I've been taking crazy pills or if the generated code really doesn't work for anyone else?  I'm not at all experienced with Swagger, so I might just be missing a large piece of the puzzle here.

If this is really broken, is there any hope a resolution?  I'll be happy to assist as well as I can.

**Comment by antihax** [comment]
The swagger codegen tends to be incomplete for complex specs and languages like cpp. Take the template as a base and tweak to your needs.

**Comment by 3vi1** [comment]
Hmmm...  It seems like that defeats the purpose/benefits.  

If you have to rewrite a bunch of missing components or manually patch specific functions every time the API changes, rather than just generate a new client wrapper... you might as well write your own minimal client that handles just the functions you need - since it's less to maintain.  :\

**Comment by Aidansavage** [comment]
Some languages people do just that. perl as an example has built in functions to handle making the GET/POST/DELETE calls and can even fetch the initial auth code snippet with a lightweight http server. 

As far as modifying the templates, it's most likely an issue with swagger itself (it's had several over the last year that made some templates or online editors worthless) that's causing the problems, not an ESI issue.

**Comment by 3vi1** [comment]
Yeah, I agree.  I'll go ahead and close this out.  Seems like rolling my own is really the only way to go if I want to keep the project pure C++.  Thanks for the insight guys.
