### ISSUE TITLE
Journal - Individual market transactions and associated taxes and fees

### ISSUE THREAD

**Issue by thecraigstone** [ccpgames/esi-issues#85]
**[[Edited to redact previous request. Rewrote as actionable request.]]**

**Ask:** ESI Pull which draws last 1000 transaction records from (corporate/character) wallet journal & transactions. Needs to specifically include transaction data from structures, and ancillary data.

- Market transaction type (auction, sale)
- item sold
- item qty
- item price
- % corp tax (amount)
- % tax (amount)
- escrow amt
- seller
- seller corp
- seller alliance
- buyer
- buyer corp
- buyer alliance
- Location (structure, station)
- Ownership (state/outpost/structure)

**Rationale:** Futhers/facilitates ability for corps/alliances and individual industrialists to produce monthly, quarterly, annual reports and market data dashboards. (Provided they take care of history/pulls themselves.) E.g. Identification of peak buyers, peak buy periods, primary markets, strongest growth areas, etc.

Will also allow deeper visibility into revenue sources in corporate wallet. E.g. breakout by top individual producers, top sellers, primary markets, which structures are performing best, etc. Right now this visibility is missing/difficult to tabulate.

**Comment by aquarhead** [comment]
Just deployed https://esi.tech.ccp.is/latest/#!/Wallet/get_corporations_corporation_id_wallets_division_transactions
