### ISSUE TITLE
Feature Request: Type of sender in mail header

### ISSUE THREAD

**Issue by Headwuend** [ccpgames/esi-issues#853]
### Route
/characters/{character_id}/mail/

### Use case
This would make it easier to identify the sender of a mail as a mailing list.

For now I have to resort to tossing out any IDs that begin with '14' from a list I gather to eventually resolve all names via /universe/names/.

### Example returns
```
{
    'mail_id': 123456789,
    'subject': 'pew pew pew'
    'from_type': 'mailing_list',
    'from': 141414141,
    'timestamp': '2018-04-05T16:37:00Z',
    'labels': [],
    'recipients': [{
        'recipient_type': 'mailing_list',
        'recipient_id': 141414141
    }],
    'is_read': True
}
```

**Comment by ddavaham** [comment]
Duplicate of #312

Hint. It will only ever be a character id or mailing_list_id

**Comment by Headwuend** [comment]
Closed as duplicate.
