### ISSUE TITLE
/characters/{character_id}/chat_channels/ timing out since DT

### ISSUE THREAD

**Issue by DaneelTrevize** [ccpgames/esi-issues#855]
# Bug

### Request
https://esi.tech.ccp.is/v1/characters/1416844877/chat_channels/
`curl -X GET "https://esi.tech.ccp.is/latest/characters/1416844877/chat_channels/" -H  "accept: application/json" -H  "authorization: Bearer ..."`

### Response
`502: Error: Bad Gateway`
`{
  "error": "Timeout contacting tranquility",
  "timeout": 10
}`

### Expected
*List of character's chat channels for which they're owner/operator of*

I know the data was stale stuff from the 20th March, but it was more convenient for the API endpoint to still be responding.  
I first tried it right about downtime today, not sure when it before between then and yesterday evening.

**Comment by a-tal** [comment]
ESI is currently down, due to pubsub issues -> https://status.cloud.google.com/incident/cloud-pubsub/18002

please follow the discussion in #esi on tweetfleet slack or twitter for further updates
