### ISSUE TITLE
mail_id are int64 but requesting a last_mail_id of 2,147,483,648 causes 500 error

### ISSUE THREAD

**Issue by antihax** [ccpgames/esi-issues#856]
# Bug
It appears that last_mail_id are actually int32 and not int64 a sending 2,147,483,647 as a last_mail_id works, but 2,147,483,648 fails. Also if possible, could this be made uint32? 

### Request
```
curl -X GET "https://esi.tech.ccp.is/latest/characters/1331768660/mail/?last_mail_id=2147483648" -H "accept: application/json" -H "authorization: Bearer validtokenhere"
```
### Response
500 Internal Server Error 
```
{
  "error": "Unhandled internal error encountered!"
}
```
### Expected
Mails

**Comment by a-tal** [comment]
https://github.com/ccpgames/esi-mail/pull/10

**Comment by a-tal** [comment]
thanks, deployed. for future reference, mail and label ids are both int32, the specs have been updated to reflect this.

technically this is a breaking change, but since it was causing errors in the monolith (and no int64 values should of been handed out ever) there was not a version bump.
