### ISSUE TITLE
Map jump/kill statistics in ESI

### ISSUE THREAD

**Issue by andimiller** [ccpgames/esi-issues#86]
The endpoints in the XML API which power map statistics would be great to have available via ESI:

http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/map/map_kills.html
http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/map/map_jumps.html

**Comment by ETristram** [comment]
Since yesterday my XML importer for Kills/Jumps throws occasional errors after running flawless for months. Thus I second this request to bring this information to ESI.
