### ISSUE TITLE
/characters/{character_id}/wallet/ does not return json

### ISSUE THREAD

**Issue by wvdvegt** [ccpgames/esi-issues#860]
# ATTENTION: DON'T SUBMIT SSO/CREST/XML RELATED ISSUES

# Bug
/characters/{character_id}/wallet/ does not return json, it returns a plain text body. This breaks swagger codegen as one expects all calls to return json.

### Request
/latest/characters/{character_id}/wallet/ 

### Response
1234.23

### Expected
{
"balance": 1234.23
}

**Comment by CarbonAlabel** [comment]
A bare value is valid JSON, this would be the codegen for your language of choice assuming otherwise.

**Comment by deadlybulb** [comment]
Are you using swagger codegen?  Or did you write your own?  Swagger codegen works for me (in Java anyway).

**Comment by a-tal** [comment]
this return is documented, valid json

**Comment by wvdvegt** [comment]
Would be nice if anyone could explain how i can see this kind of plain return values in swagger.

**Comment by antihax** [comment]
https://github.com/antihax/goesi/blob/master/esi/api_wallet.go#L132

Please join us on slack for help. Channel #esi 
https://www.fuzzwork.co.uk/tweetfleet-slack-invites/

**Comment by wvdvegt** [comment]
Thx but not what i need (I know how to parse json). 

What i need is how i can tell in the swagger definition so i can adjust my own code generator.

**Comment by SpeedProg** [comment]
you can tell by reading it and it saying number or what ever and not object or array?

**Comment by itshouldntdothis** [comment]
The swagger schema for the personal wallets 200 success currently is
> {
> "type":"number",
> "format":"double",
> "description":"Wallet balance",
> "title":"get_characters_character_id_wallet_ok"
> }
which should be enough info to parse the response.

**Comment by wvdvegt** [comment]
Thx,  so the thing to look for would be the "type": "number" line where most other calls have "type": "object" or "type": "array" in their return definition.

As i do not generate model classes i skipped most of the interpreting of these object definitions, I clearly missed this one.

**Comment by wvdvegt** [comment]
The C# code I wrote just uses simpleJSON to parse all json into a easy to adres data structure (so no endless model classes). Works like charm. So not need for throwing exceptions on that. 

It's just that this lib won't parse plain data values. I should be able to adjust my codegenerator a bit to cope with it.
