### ISSUE TITLE
Universe/Stations endpoint does not drop cache (only after downtime)

### ISSUE THREAD

**Issue by dhoffend** [ccpgames/esi-issues#865]
# Bug

Serverside caching of stations endpoint seems to wrong. it only really updates after downtime. This applies to all stations

### Request

    /v2/universe/stations/61000577/

### Response

```
{
  "station_id": 61000577,
  "name": "H23-B5 V - inPanic 1",
  "type_id": 21644,
  "position": {
    "x": 1345809653760,
    "y": 74536181760,
    "z": 2496256942080
  },
  "system_id": 30004178,
  "reprocessing_efficiency": 0.5,
  "reprocessing_stations_take": 0,
  "max_dockable_ship_volume": 50000000,
  "office_rental_cost": 50000000,
  "services": [
    "bounty-missions",
    "courier-missions",
    "reprocessing-plant",
    "cloning",
    "repair-facilities",
    "factory",
    "labratory",
    "fitting",
    "news",
    "insurance",
    "docking",
    "office-rental",
    "navy-offices"
  ],
  "owner": 98416918, <<<<<<<<<<<<<<<<<<
  "race_id": 4
}
```

### Expected

Here is the example result of the xml api endpoint (see a different owner)

    <row stationID="61000577" 
         stationName="H23-B5 V - inPanic 1"
         stationTypeID="21644"
         solarSystemID="30004178"
         corporationID="1000132" <<<<<<<<<<<<<<<<
         corporationName="Secure Commerce Commission"
         x="1345809653760"
         y="74536181760"rsult 
         z="2496256942080"/>

**Comment by ccp-zoetrope** [comment]
You are correct about the cache in the monolith for this only being updated at downtime. A fix theoretically is possible but requires a lot of work and considering that outposts will be changing in June then I don't see a lot of benefit in trying to get this updated at any time but downtime at the moment. However, I have updated the route's cache to be correct.
