### ISSUE TITLE
Cache for contested flag has invalid state (likely updated only during downtime)

### ISSUE THREAD

**Issue by dhoffend** [ccpgames/esi-issues#868]
# Bug

When tracking the fw systems endpoint, the contested flag only seems to get updated right after downtime. Changes to the contested flag during the day are not shown (likely system cache from downtime).

victory points are updates correctly. The xml endpoint shows the correct contested flag value

### Request

    /v1/fw/systems/

### Response

    {
      "solar_system_id": 30002098,
      "occupier_faction_id": 500003,
      "owner_faction_id": 500002,
      "victory_points": 60,
      "victory_points_threshold": 3000,
      "contested": false <<<<<<<<<<<<<<<<<<
    },

### Expected

    <row solarSystemID="30002098"
         solarSystemName="Orfrold"
         occupyingFactionID="500003"
         owningFactionID="500002"
         occupyingFactionName="Amarr Empire"
         owningFactionName="Minmatar Republic"
         contested="True" <<<<<<<<<<<<<<<<
         victoryPoints="60"
         victoryPointThreshold="3000"/>

**Comment by ccp-zoetrope** [comment]
the `contested` flag has been turned into an [enum](https://github.com/ccpgames/eve-glue/blob/master/eve_glue/faction_warfare.py) and is updated correctly now (not just at downtime) on the new v2 version of /fw/systems/.

**Comment by dhoffend** [comment]
Okay cool. So the cache issue was solved Ausstellung i guess

I just have to find out what what the difference between the values are now ... what vulnerable vs uncontested or so means
