### ISSUE TITLE
Getting 'X-Esi-Ab-Test' in the HTTP header

### ISSUE THREAD

**Issue by asvpdev** [ccpgames/esi-issues#871]
### Request 1
https://esi.tech.ccp.is/latest/characters/******/roles/?token=********

#### Body
{"roles":["Factory_Manager","Account_Take_1","Account_Take_2","Rent_Factory_Facility","Rent_Research_Facility","Trader"],"roles_at_hq":["Hangar_Take_1","Hangar_Take_2","Hangar_Take_3","Hangar_Query_1","Hangar_Query_2","Hangar_Query_3","Container_Take_1"],"roles_at_base":["Hangar_Take_1","Hangar_Take_2","Hangar_Take_3","Hangar_Query_1","Hangar_Query_2","Hangar_Query_3","Container_Take_1"],"roles_at_other":["Hangar_Take_1","Hangar_Take_2","Hangar_Take_3","Hangar_Query_1","Hangar_Query_2","Hangar_Query_3","Container_Take_1"]}

#### HTTP Header
HTTP/1.1 200 OK
Cache-Control: private
Date: Tue, 24 Apr 2018 13:20:53 GMT
Via: 1.1 google
Allow: GET,HEAD,OPTIONS
Content-Length: 528
Content-Type: application/json; charset=UTF-8
Expires: Tue, 24 Apr 2018 13:39:16 GMT
Last-Modified: Tue, 24 Apr 2018 12:39:16 GMT
ETag: ec25989ea3e253dc9fa0f8355c7ab691bd6d5e84da2dcf111312b585
Vary: Accept-Encoding
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,X-User-Agent
Access-Control-Allow-Methods: GET,HEAD,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type,Warning,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
Access-Control-Max-Age: 600
Strict-Transport-Security: max-age=31536000
X-Esi-Error-Limit-Remain: 100
X-Esi-Error-Limit-Reset: 7
X-Esi-Request-Id: 8dd04a7b-bf5f-4f67-b209-507df845a55b
Alt-Svc: clear

### Repeated request
https://esi.tech.ccp.is/latest/characters/******/roles/?token=********

Exactly the same as in Response 1
#### Body
{"roles":["Factory_Manager","Account_Take_1","Account_Take_2","Rent_Factory_Facility","Rent_Research_Facility","Trader"],"roles_at_hq":["Hangar_Take_1","Hangar_Take_2","Hangar_Take_3","Hangar_Query_1","Hangar_Query_2","Hangar_Query_3","Container_Take_1"],"roles_at_base":["Hangar_Take_1","Hangar_Take_2","Hangar_Take_3","Hangar_Query_1","Hangar_Query_2","Hangar_Query_3","Container_Take_1"],"roles_at_other":["Hangar_Take_1","Hangar_Take_2","Hangar_Take_3","Hangar_Query_1","Hangar_Query_2","Hangar_Query_3","Container_Take_1"]}

#### HTTP Header
HTTP/1.1 200 OK
Cache-Control: private
Date: Tue, 24 Apr 2018 13:20:58 GMT
Via: 1.1 google
Allow: GET,HEAD,OPTIONS
Content-Length: 528
Content-Type: application/json; charset=UTF-8
Expires: Tue, 24 Apr 2018 14:13:51 GMT
Last-Modified: Tue, 24 Apr 2018 13:13:51 GMT
ETag: ec25989ea3e253dc9fa0f8355c7ab691bd6d5e84da2dcf111312b585
Vary: Accept-Encoding
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type,Authorization,X-User-Agent
Access-Control-Allow-Methods: GET,HEAD,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type,Warning,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
Access-Control-Max-Age: 600
Strict-Transport-Security: max-age=31536000
**X-Esi-Ab-Test: 1**
X-Esi-Error-Limit-Remain: 100
X-Esi-Error-Limit-Reset: 2
X-Esi-Request-Id: f1e9e469-d74f-4630-b9d3-19ff061712fa
Alt-Svc: clear

**Comment by Dusty-Meg** [comment]
See https://developers.eveonline.com/blog/article/esi-march-news

**Comment by ccp-zoetrope** [comment]
Yeah this header shows up if your request went to our AWS infrastructure since we're routing a percentage of ESI requests there for AB testing. The only time it is relevant is when reporting a bug :)
