### ISSUE TITLE
/route/{origin}/{destination}/ fails for new abyssal systems

### ISSUE THREAD

**Issue by Chnkr** [ccpgames/esi-issues#873]
# Bug

### Request

`https://esi.tech.ccp.is/latest/route/32000001/30002771/?datasource=singularity&flag=shortest`

### Response

```
{
  "error": "System not found"
}
```

### Expected

```
{
  "error": "No route found"
}
```

**Comment by ficti0n1** [comment]
Not the best medium to troll CCP.
