### ISSUE TITLE
Endpoint with server status

### ISSUE THREAD

**Issue by Regner** [ccpgames/esi-issues#88]
Similar to what CREST provides:
- Is the server online, offline, or in VIP
- player count
- server version

**Comment by aquarhead** [comment]
How does CREST show the server is offline?

**Comment by Regner** [comment]
By returning 503 :P

Also I it shows as offline while in any state other than "accepting connections" or "VIP" I think. The server can be in "I am turning on, please wait" mode but CREST just returns "offline" status. I think...

**Comment by Robbilie** [comment]
it would be so cool if we could get a response when the server is offline like XML does, it made me really sad that CREST didnt have that…
had to laugh a bit about aquarheads comment ^^

but such an endpoint would be really good, maybe the offline state could be displayed by the Ingress with a static JSON file `{ "status": "offline", "player_count": 0 }`

**Comment by deadlybulb** [comment]
Somewhat off-topic, but what is VIP anyway?  (yes I know what VIP stands for, just curious how it's used)

**Comment by aquarhead** [comment]
CREST is bundled with EVE itself, so you can relitavily be sure when CREST is offline that EVE is also offline. But ESI is not, when ESI cannot access EVE, it does not necessary mean EVE is offline.

**Comment by Regner** [comment]
@aquarhead I am sure you creative bunch can come up with something. :P The XML API goes straight to the DB for the funzies. There is also a server shutdown broadcast sent out. So maybe listening for that?

@deadlybulb VIP mode is when only accounts with the VIP role can log in. Usually used to do some final testing after a big patch, or to ensure a test server can be accessed externally but only by authorized people, etc.

**Comment by aquarhead** [comment]
@Regner We sometimes experience that EVE servers would temporarily disconnect from ESI (aka. Google) but yeah we're researching how to approach downtime handling atm.

I'd imagine XML goes to DB directly, now you've confirmed it. However ESI would now have that luxury :(

**Comment by a-tal** [comment]
this endpoint is scheduled to be released tomorrow at downtime. spec is:

```
  /status/:
    get:
      description: 'EVE Server status


        ---


        Alternate route: `/v1/status/`


        Alternate route: `/legacy/status/`


        Alternate route: `/latest/status/`



        ---


        This route is cached for up to 30 seconds'
      operationId: get_status
      parameters:
      - default: tranquility
        description: The server name you would like data from
        enum:
        - tranquility
        - singularity
        in: query
        name: datasource
        type: string
      - description: Client identifier, takes precedence over headers
        in: query
        name: user_agent
        type: string
      - description: Client identifier, takes precedence over User-Agent
        in: header
        name: X-User-Agent
        type: string
      responses:
        '200':
          description: Server status
          examples:
            application/json:
              players: 12345
              server_version: 1132976
              start_time: '2017-01-02T12:34:56Z'
          headers:
            Cache-Control:
              description: The caching mechanism used
              type: string
            Expires:
              description: RFC7231 formatted datetime string
              type: string
            Last-Modified:
              description: RFC7231 formatted datetime string
              type: string
          schema:
            description: 200 ok object
            properties:
              players:
                description: Current online player count
                title: get_status_players
                type: integer
              server_version:
                description: Running version as string
                title: get_status_server_version
                type: string
              start_time:
                description: Server start timestamp
                format: date-time
                title: get_status_start_time
                type: string
              vip:
                description: If the server is in VIP mode
                title: get_status_vip
                type: boolean
            required:
            - start_time
            - players
            - server_version
            title: get_status_ok
            type: object
        '500':
          description: Internal server error
          examples:
            application/json:
              error: 'uncaught exception: IOError(''out of memory'')'
          schema:
            description: Internal server error
            properties:
              error:
                description: Internal server error message
                title: get_status_500_internal_server_error
                type: string
            title: get_status_internal_server_error
            type: object
      summary: Retrieve the uptime and player counts
      tags:
      - Status
      x-alternate-versions:
      - latest
      - legacy
      - v1
      x-cached-seconds: 30
```

**Comment by deadlybulb** [comment]
What is the expected response during downtime?  Returns 404?  Player count is 0?

**Comment by a-tal** [comment]
you'll get a 500 with a timeout error if the server is offline

**Comment by a-tal** [comment]
this is live now
