### ISSUE TITLE
500 Error Failed to read request body on Ab-Test: 1 while posting to universe/names

### ISSUE THREAD

**Issue by Dusty-Meg** [ccpgames/esi-issues#886]
Sending a post request to the https://esi.tech.ccp.is/v2/universe/names/ endpoint is occasionally returning a 500 Error Failed to read request body.

With the following headers
Access-Control-Allow-Credentials: true | Access-Control-Allow-Headers: Content-Type,Authorization,If-None-Match,X-User-Agent | Access-Control-Allow-Methods: POST,OPTIONS | Access-Control-Allow-Origin: * | Access-Control-Expose-Headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset | Access-Control-Max-Age: 600 | Strict-Transport-Security: max-age=31536000 | X-Esi-Ab-Test: 1 | X-Esi-Error-Limit-Remain: 100 | X-Esi-Error-Limit-Reset: 18 | Alt-Svc: clear | Content-Length: 40 | Content-Type: application/json | Date: Sat, 28 Apr 2018 09:41:42 GMT | Via: 1.1 google |

Whenever I see this error the Ab-Test header is always present

I am sending the following headers so 100% including the content type
```
[HttpRequestHeader.Accept] = "application/json",
[HttpRequestHeader.ContentType] = "application/json"
```

I have only been using this Post endpoint so cannot see any others.

**Comment by Dusty-Meg** [comment]
As an update I am also getting the same issue with the /characters/affiliation/ endpoint.

**Comment by a-tal** [comment]
thanks for the report. I've made an internal reference to this to investigate further, if we plan on ab testing again
