### ISSUE TITLE
Request: Rename certain groups or certain skills

### ISSUE THREAD

**Issue by rumpfc** [ccpgames/esi-issues#888]
# About the project:
I'm about to finish automization for getting external recources from ESI. It is for getting all available ores, minerals and skills needed for reprocessing calculations where you enter the number of minerals needed and calculates optimal amount of ores needed to mine and refine depending on skill levels.

# Procedure:
1. Map infos from file "invTypeMaterials.yaml"
2. Get all groups from categorie "Asteroids" (ID: 25)
3. If group is published: Use group name to find Skill ID (i.e. Group "Arkonor" -> Skill "Arkonor Processing")
4. Get all asteroids from each group
5. If asteroid is published: Get name, portion_size and volume
6. Filter map from step 1 to only get material informations from asteroids
7. Download all PNGs for each item
8. Safe all basic informations in an external resource file (with last update timestamp)

# The Problem
In step 3 I use i.e. `https://esi.tech.ccp.is/latest/search/?categories=inventory_type&search=Arkonor%20Processing&strict=true` to look for the processing skill of each group. I just combine "group name" + " Processing" (with whitespace)

The newly added Moon ores cause some problem
Group "Common Moon Asteroids" -> "Common Moon Ore Processing"
Group "Ubiquitous Moon Asteroids" -> "Ubiquitous Moon Ore Processing"
etc.

As you can see the step "group name" + " Processing" won't work there, resulting in getting the correct skill ID or Skill name. I need a workaround to transform "Asteroids" into "Ore".

For the 5 moon ore groups, is it possible to rename the group names or the reprocessing skill names? I don't like workarounds.

LG

**Comment by alexbaileyuk** [comment]
This sounds very much like "can you change the game so it's simpler to program".

I understand the logic to your request but developing is very rarely straight forward. Why not just check for either group name + processing OR the other syntax?

**Comment by cvweiss** [comment]
This is more of a game design issue than an esi issue.

**Comment by jameson2011** [comment]
Renaming skills to assist data reference matching is not going to be robust. I'm not a manufacturing expert in any way but I imagine the correlation of skills to things has been addressed in other applications. Why not join devfleet and ask around?

**Comment by rumpfc** [comment]
Just got help from devfleet, I found the info I need in a Dogma attribute called "reprocessingSkillType" (ID 790). So neither renaming nor workarounds are necessary anymore.
