### ISSUE TITLE
New type icons are missing

### ISSUE THREAD

**Issue by evrial** [ccpgames/esi-issues#89]
All new items (engineering structures and services) blueprints and ship skins missing icons from http://imageserver.eveonline.com/
Another examples:
> 'Excavator' Ice Harvesting Drone
> Azbel
> Sotiyo

Also market group icons aren't uploaded to the server.

**Comment by a-tal** [comment]
please only a ticket here -> https://support.eveonline.com/hc/en-us/sections/200455699-Graphics
