### ISSUE TITLE
read/write character notes

### ISSUE THREAD

**Issue by NathenSample** [ccpgames/esi-issues#892]
# Feature request

### Route
POST/PUT/GET `/characters/{character_id}/notes/`

### Authentication
Authenticated endpoint

### Use case
It is currently possible to manually enter notes about a character on their show-info page, it is impossible to mechanically read, or edit this information

## Note 
Some system, or alternative endpoint that would allow a wildcard return of all users you have stored notes about would also be incredibly useful should this be implemented.

**Comment by CarbonAlabel** [comment]
Duplicate of #238.

**Comment by NathenSample** [comment]
ty @CarbonAlabel
