### ISSUE TITLE
Last-Modified header from /universe/system_kills/ route alternates

### ISSUE THREAD

**Issue by pathead** [ccpgames/esi-issues#895]
# Bug

I've noticed that sending repeated requests for the system kills sometimes results in a different Last-Modified header being returned as well as different stat values.  

My most recent testing had it switching between Wed, 02 May 2018 20:32:15 GMT and Wed, 02 May 2018 20:46:40 GMT.

The reason I noticed was because I am trying to make sure I have the most recent statistics as soon as they are updated but the frequency of updates does not seem to be consistent.  Sometimes there is 45 minutes between updates, sometimes it is an hour and 15 minutes... 

### Request
`https://esi.tech.ccp.is/latest/universe/system_kills/`

**Comment by a-tal** [comment]
likely due to the transition from gcloud to aws, which should be complete tomorrow.

feel free to use https://esi.evetech.net (the new url) in the meantime.
