### ISSUE TITLE
Assets page=0 does not return an error.

### ISSUE THREAD

**Issue by wvdvegt** [ccpgames/esi-issues#904]
- Bug

Using get_characters_character_id_assetsAsync with page=0 returns some strange (and invalid) items besides (civilian bpo's) correct ones. Expected would be an (parameter) error.

I know page=0 is an illegal value but there does not seem to be a check on invalid values for this parameter.

- Request

Version 0.8.0

- Response

A json array with items of which some are invalid (civilian bpo's mostly with an invalid location).

- Status Code

200

- Expected

Expected would be an (parameter) error.

**Comment by a-tal** [comment]
this is resolved now, thanks
