### ISSUE TITLE
[Bug] /route/ connections parameter is not working

### ISSUE THREAD

**Issue by DaneelTrevize** [ccpgames/esi-issues#907]
# Bug

This endpoint returns a route that does not seem to consider any supplied connections pairs that would cause a shorter alternative route. In the following example, an Amarr to Jita route is request, with a shortcut connection supplied, between Sarum Prime and Perimeter. The regular ~10 gates route is still returned, rather than the 4 named systems hypothetical option.

## Request

`GET /latest/route/30002187/30000142/?connections[0]=[30003522,30000144]`

### Status Code

`200`

### Headers

```
HTTP/2.0 200 OK
date: Thu, 10 May 2018 09:49:06 GMT
content-type: application/json; charset=UTF-8
content-length: 91
access-control-allow-credentials: true
access-control-allow-headers: Content-Type,Authorization,If-None-Match,X-User-Agent
access-control-allow-methods: GET,HEAD,OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Content-Type,Warning,ETag,X-Pages,X-ESI-Error-Limit-Remain,X-ESI-Error-Limit-Reset
access-control-max-age: 600
allow: GET,HEAD,OPTIONS
cache-control: public
etag: "e74c016dcf01085693f03b8c041773005b7062c565c655fcc48680c0"
expires: Thu, 10 May 2018 18:47:16 GMT
last-modified: Wed, 09 May 2018 18:47:16 GMT
strict-transport-security: max-age=31536000
vary: Accept-Encoding
x-esi-error-limit-remain: 100
x-esi-error-limit-reset: 54
x-esi-request-id: 7327c457-4b26-45ea-9938-93689e2180cd
X-Firefox-Spdy: h2
```

### Body

Please provide the response body, feel free to scrub any opsec details you wish. E.g.:

```[30002187,30003491,30003503,30003504,30002789,30002788,30002791,30000139,30000144,30000142]```

## Expected

```[30002187,30003522,30000144,30000142]```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [x] Response headers are provided
- [x] Response body is provided
- [x] Expected response is provided

**Comment by a-tal** [comment]
you're missing qsarg formatting. (a swagger client would do this for you)

https://esi.evetech.net/latest/route/30002187/30000142/?connections=30003522%7C30000144&datasource=tranquility&flag=shortest

**Comment by DaneelTrevize** [comment]
Hey, I was just [trying to help someone else out](https://www.reddit.com/r/evetech/comments/8idb57/esi_route_connections_parameter/).

Seems there's not a HTTP standard for GET request array encoding, even if Swagger has one somewhere. Good to know ESI sounds like it's following that.
