### ISSUE TITLE
Remote UI

### ISSUE THREAD

**Issue by georgwacker** [ccpgames/esi-issues#91]
Add remote UI functionality, especially for market details and waypoints.

**Comment by wtfrank** [comment]
And opening specific blueprints in manufacturing window!

**Comment by a-tal** [comment]
blueprints specifically mentioned in https://github.com/ccpgames/esi-issues/issues/59

**Comment by a-tal** [comment]
waypoints specifically mentioned in https://github.com/ccpgames/esi-issues/issues/118

**Comment by a-tal** [comment]
market details mentioned in https://github.com/ccpgames/esi-issues/issues/54

**Comment by a-tal** [comment]
going to close this as a dupe now, if there is something that you'd like to add to the specific linked issues go for it, or if you feel this has been closed in error feel free to open a new issue with more details
