### ISSUE TITLE
Feature Request: Mutated attributes for Dynamic Items in Asset List.

### ISSUE THREAD

**Issue by Neugeniko** [ccpgames/esi-issues#910]
# Feature Request

This feature would return modified attributes and their values for dynamic items in the assets
list.

/characters/{character_id}/assets/dynamic_item_details

## Use case

Anyone wishing to see the details of dynamic items in their asset list in order to
- evaluate the items price
- fit the item in a fitting program without manually having to set attributes
- search with advanced filters for mutated items in their asset list

## Authentication

Yes

## Example return

```
item_id
         attribute_id
         value
         ......more attibute/value pairs
.... 999 more items
```

# Checklist

Check all boxes that apply to this issue:

- [x] Feature request description is provided
- [x] Use case exists
- [x] Feature requires a new route
- [ ] Feature adds data to existing route
- [ ] Feature requires new auth scope
- [x] Feature can reuse existing scope
- [ ] Feature does not require auth
- [ ] Meta feature, applies to all routes

**Comment by a-tal** [comment]
am going to close this as a dupe to #847 (even though they're slightly different)

this is most likely going to be rolled out as a separate endpoint that you can feed an item id into and get the mutated properties in return. we're working with the feature team at this point to finalize how this is going to be presented via ESI.
