### ISSUE TITLE
/characters/{character_id}/assets/ returns implants/skills/wardrobe items for some characters

### ISSUE THREAD

**Issue by wvdvegt** [ccpgames/esi-issues#911]
# Bug

the v1 endpoint:

**/characters/{character_id}/assets/** 

returns implants/skills and/or wardrobe items for some characters as part of the inventory. 
This without specifying that implants can be queried (so no scope for it). 

The character returned by this as a container (but not for all pilots and not with all item types). So I have 3 pilots with skills+implants+wardrobe) , one with only implants an and one that does not have his character returned as a asset container.

## Request

I used:
/characters/{character_id}/assets/ 
esi-assets.read_assets.v1

I read all pages until less than a 1000 where returned.

## Response

For some characters not only assets in stations are returned, but also the character itself containing items like implants, learned skills and/or wardrobe items. 

### Status Code

200

### Body

One item returned is:

```json
  {
    "is_singleton" : true,
    "item_id" : 165495902,
    "location_flag" : "Skill",
    "location_id" : 148948054,
    "location_type" : "other",
    "quantity" : 1,
    "type_id" : 3303
  }
```

## Expected

As there are other endpoints covering these (at least the skills/implants) I would expect them not to be present in this endpoint (especially as implants requires a separate scope not present in my app).

`200`

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Response status code is provided
- [ ] Response headers are provided
- [x] Response body is provided
- [ ] Expected response is provided

**Comment by a-tal** [comment]
thanks for this. the only items you should see now where location_id == character_id are wardrobe items, because there's no other route for retrieving that information.

**Comment by CarbonAlabel** [comment]
@a-tal what about those who can't see our clothes in the assets list?

**Comment by a-tal** [comment]
@CarbonAlabel I'd have to look into why it's only returned sometimes. it wouldn't surprise me if "characters who haven't changed clothes for a long time" played into it somehow though.

feel free to make a separate issue for that, will require some monolith investigation

**Comment by GoldenGnu** [comment]
I don't know if you already excluded them, but, at one points, active boosters was also return.
Maybe you already excluded them, in that case, sorry to waste time...

**Comment by wvdvegt** [comment]
I do not see any characters anymore, even the one that had the wardrobe item.
