### ISSUE TITLE
Number of items returned nog stable over pages

### ISSUE THREAD

**Issue by wvdvegt** [ccpgames/esi-issues#914]
# Bug

The endpoint:
**/characters/{character_id}/assets/ (scope esi-assets.read_assets.v1)**
returns a varying number of items on each page. I've seen 999, 998 478, 1000 and finally 0 when requesting a series of pages.

## Request

**/characters/{character_id}/assets/**

with a page parameter that is incremented by 1 for each subsequent request.

## Response

A varying number smaller or equal to the documented maximum of 1000.
So code that tests on less than 1000 returned items to stop requesting new pages will fail.

You need to do the rather un-logical request pages until one has 0 items.

## Expected

Each page to return exact 1000 items (the max) and the last page less then 1000 items.

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [x] Request path is provided
- [x] Expected response is provided

**Comment by deadlybulb** [comment]
I'm guessing this happens because of additional filtering on the ESI side, which can be hard to fix without introducing more buffers, etc.  How critical is this?  What if the spec said at most 1000 results?

**Comment by Aidansavage** [comment]
The fact that it's saying `maxItems: 1000` doesnt mean you're always going to get a thousand items per page (post monolith filtering perhaps), just that 1000 is _the_ maximum per page. 

And tbf, coding on the assumption that `<1000 items equals last page` is the more illogical thing :smile: _Especially_ when assets is a paginated endpoint that returns the first page on a fresh request and also gives you a `X-Pages: N` header along with it. Thus after the first request (giving you page 1), you then just have to request pages 2 through N.

**Comment by wvdvegt** [comment]
Normally when you request chunks of data, it's from a database and you get exact numbers. As stated before you probably filter out some stuff after the query (like the invalid items). In that case it's understandable. 

Checking on zero returned items btw also means I always have to make another request that does not return a thing, so another hit on the server.

As for X-Pages header, nice but not very helpful for me, as it's at http level that in my app is handled without knowledge of what is retrieved (it just returns Json and no headers). I only process the error count headers to log then during the request.

I just hope filtering will not remove all objects on a page ;-)

**Comment by a-tal** [comment]
this is due to ESI (post-monolith) filtering. once the monolith updates to not send the items that ESI is currently filtering, the page sizes will be consistent again.

you should always be using `x-pages` to know what the last page is, not `len(results) < max_page_size`
