### ISSUE TITLE
tokenUrl in securityDefinition

### ISSUE THREAD

**Issue by Kyria** [ccpgames/esi-issues#92]
Currently in the swagger.json we only have the `authorizationUrl` for the OAuth2. 
As the token is part of the login process in OAuth2 can we have the `tokenUrl` added in the securityDefinition ? 

This will allow us to only have to know the `swagger.json` url, without having to write constants in our code for the auth urls. 

Thanks !

**Comment by a-tal** [comment]
`tokenUrl` is not valid with `implicit` auth flow

**Comment by CarbonAlabel** [comment]
@a-tal couldn't another security definition describing the authorization code flow be added?
