### ISSUE TITLE
Character -> Clone State "Alpha/Omega"

### ISSUE THREAD

**Issue by Legedric** [ccpgames/esi-issues#95]
It is absolutely critical for skill training calculations to know if a character is an Alpha or Omega clone. Unfortunatelythere isn't any information about this in ESI on the character or clone endpoints.

An extension of the character's public information (or a new non-public endpoint similar to XML CharacterSheet) like below would be great.

`{
  "ancestry_id": 19,
  "birthday": "2015-03-24T11:37:00Z",
  "bloodline_id": 3,
  "corporation_id": 109299958,
  "description": "",
  "gender": "male",
  "name": "CCP Bartender",
  "race_id": 2,
  "clone_state": "Alpha"
}`

**Comment by HakShak** [comment]
By no means will we be exposing account specific information on the character level. This was a large discussion with the CSM.

What will be happening for the skills endpoint is the addition of "active skill level". This should solve the skill training calculation problems. This may also need to include a "potential skill level" as well. That would be a more important discussion to have on another issue.

For now I will be closing this, but if there is more functionality around clone state that cannot be achieved, I would like to target the problem instead directly in another issue.

**Comment by markrwilkins** [comment]
Hey folks:

(Note to non-CCPers, I'm not on Team Tech Co, so I'm asking from the
standpoint of an API user.)

It sounds to me like the functionality that's being requested is having
some way to access one of (1) base character training rate (before
implants/attributes), (2) current character training rate (after
implants/attributes), or (3) completion time of skills in the queue rather
than a direct query of account "alpha" vs. "omega" status.  Maybe if a
follow-up issue requested access to one or more of those, it might more
directly address the issue and avoid questions of querying account data as
such.

(Nick's willingness to consider adding "active" vs. "potential" skill level
indicates that it isn't necessarily a problem to be able to infer that
account-level information, the question is whether it's exposed directly.)

**Comment by Kupuyc** [comment]
It's not a problem of skill training speed only. For example I want to know clone status for sure that character should be kicked from teamspeak.

**Comment by polarina** [comment]
> I want to know clone status for sure that character should be kicked from teamspeak.

Why would you want to kick Alpha players from Teamspeak?

**Comment by Kupuyc** [comment]
Why not? Spies for free, alliance politics, etc. Kick - just example. On the other hand it's good idea to set them TS group - to prevent join some channels or see that they are alpha players. A lot of examples.

**Comment by Legedric** [comment]
It is not only about training times but also about what the character is able to train. As the list of trainable skills is quite limited for an Alpha state clone we definitely need some kind of information about the clone state of a character to list the trainable skills for example.

**Comment by markrwilkins** [comment]
But, you do not need to know the clone state (which is a property of the account, not the skill), only whether the skills in question are trainable for the character (or any active limits.)

- Mark

**Comment by Legedric** [comment]
It doesn't matter what "label" CCP puts onto this but one way or another you have to know the clone state for a character. It doesn't matter if you provide something like a "trainable skills" list for each character, provide some kind of base training time multiplier (that determines the training speed) or just put a simple flag "clone state" on the character endpoint.

Whatever will get to the ESI at the end it will and it has to enable us 3rd party developers to "read" the clone state of a character from it, no matter how you call it. I understand that you do not want to expose it directly but exactly this (a simple flag on a character) would be a) sufficient and b) the simpliest solution.

I do understand you don't want to expose it directly but at the end of the day we (as 3rd party developers) will be able to read the clone state from a character so making the ESI part about this topic complex just to hide this status somewhere but with the same result (being still able to read it somewhere in some way) is somewhat inefficient from a development perspective.

For me personally it is still possible to let the user just flag a character as Alpha on my site, that's ok for me but that's not what a user may expect to do but expects to come from the API instead :)

**Comment by markrwilkins** [comment]
My understanding (and note that I am not on the team working on the API, but I have spoken with them about this) is that the concern is not preventing you from inferring the clone state, but avoiding querying account state directly in the API, since "clone grade" is account-level information, not character-level information.

Of course, if you infer the state of that single account flag from one query and assume other unqueried properties from it, that will likely break should additions or changes be made to the clone state concept later on.

- Mark

**Comment by markrwilkins** [comment]
To put this another way, querying or inferring that single clone state attribute would then put the onus on you to track any and all changes to what that flag means.  I argue this is not viable.  For example, what if there were (hypothetically) an A/B test conducted such that the attribute meant different things for different characters?  This would be impossible for you to even know in advance, and would just reveal itself when your users complained that your site were inexplicably not working.

**Comment by Legedric** [comment]
You are correct but if that's an argument within the CCP API team the API would only provide "result" values for us 3rd party developers as there are several of things within the API that we 3rd party devs "know" the current the function of that may change in the future.
Like the character raceId, which mainly only defines the base skill set, but who knows what else in the future?

This is just an example of the top of my head :)

But let's assume the "complex" way is the way to go for clone states, what does that mean for CCP to provide through the API?
They would have to provide a trainable skill list for each character. For Alpha clones it is quite limited (but still individual for each character's race) but for Omega clones it would result in providing EVE's entire set of skills for each Omega character through an API endpoint. Pretty redundant and unnecessary overhead if you ask me!?

In addition they would have to provide some kind of training time multiplier. A simple 1 for Omega clones and 2 for Alpha would be the most basic approach but it comes pretty much close to just flagging a character's clone state directly.
Another approach would be the provision of some kind of base training rate per character. But as the training rate is nothing coming from a character but from a skill and its primary and secondary attributes it will be (at least from my perspective as a non-CCPer) impossible to define something like this on a general character-wide basis without taking their attributes and active implants into account. And skill training tools need this "flat" base character training rate (without attributes and implants) to simulate attribute remaps or implant switches for example.
At least at the moment I cannot think of a simple solution for the "training time problem" without exposing the clone state too directly on one hand and not making the ESI a complete mess for skill training on the other hand...

**Comment by Ebag333** [comment]
>It is not only about training times but also about what the character is able to train. As the list of trainable skills is quite limited for an Alpha state clone we definitely need some kind of information about the clone state of a character to list the trainable skills for example.

#133 would cover this.

**Comment by markrwilkins** [comment]
Here's what you should do:

Make a list of all the information you would infer from clone state if you had it.  Base training rate, skill caps, skill completion times, whatever.  Ask for those things on a per-character basis.

If you have all that, you don't need to know or care what the clone state is, or even whether clone states exist or what they mean.

The exception might be if you're planning to let an alpha model their character as an omega for planning purposes, or vice versa.  In that case you can infer what you need, at the cost of having to chase any changes to clone states in the future in your implementation.  Also, it sounds like there may be some openness to providing generalized information about that too.

- Mark

markrwilkins@gmail.com

**Comment by frankysaken** [comment]
Hey, I'm sad to see this as a **wontfix**. Here are some things I'd like to do with the clone state/subscription time left (and if not clone state something else).

Remember that adding any of these will disclose clone state in a roundabout way in any case and if the intent is to never disclose clone state then the features below won't be possible without people manually finding out when their accounts have expired and manually setting those characters to alpha in your application.

These two are for skill planning tools.
* Calculate the time for a skillqueue to complete for a character.
* Know if a character can add a certain skill to their skillqueue.

These are for fitting applications but also for authentication systems and HR applications where people would like to know if a new recruit can fly certain doctrine fits and what the doctrine readiness of your corp/alliance is. Since some modules are gated behind being an Omega I can't infer this from their skills (a character can have, for example, Cloaking IV but might have turned Alpha so can't actually use a Covert Ops Cloaking Device).
* Know if a character can use a certain module.
* Know if a character can fly a certain ship.

These are more generic administration, I personally have a lot of accounts and sometimes some lapse when they are logged off for extended periods of time. It really sucks when you login and every module is offline.
* Subscription time left so I know when to PLEX my accounts or to go for some subscription deal.
